### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by Brand0n1** [GC-spigot/AdvancedEnchantments#1040]
**Describe the bug**
When I was loading up my server I saw an error in my console saying that what's shown in the link below: [https://pastebin.com/AJVUTP8k](https://pastebin.com/AJVUTP8k) 

The line in my enchants.yml is as follows:

```
masterinquisitive:
  display: '%group-color%Master Inquisitive'
  description: "Heroic Enchantment. Massively\nincreases EXP drops from mobs.\nRequires Inquisitive IV enchant\non item to apply."
  applies-to: 'Sword'
  type: 'KILL_MOB'
  group: 'HEROIC'
  settings:
    required-enchants:
      - 'inquisitive:4'
    removed-enchants:
      - 'inquisitive'
    removeable: false
  applies:
    - ALL_SWORD
  levels:
    1:
      chance: 20
      cooldown: 2
      effects:
        - 'EXP:<random number>6-11</random number> %victim%'
    2:
      chance: 40
      cooldown: 2
      effects:
        - 'EXP:<random number>7-12</random number> %victim%'
    3:
      chance: 60
      cooldown: 2
      effects:
        - 'EXP:<random number>8-13</random number> %victim%'
    4:
      chance: 80
      cooldown: 2
      effects:
        - 'EXP:<random number>9-15</random number> %victim%'
```

**To Reproduce**
Just load up the plugin that's what I did.

**Screenshots / Video**
N/A

**Server Information (please complete the following information):**
 - Minecraft Version [PaperSpigot 1.15.2]
- Plugin Version [7.1.9]
