### ISSUE TITLE
[Issue] Multiple Rewards for same mob not working

### ISSUE THREAD

**Issue by rocky143** [GC-spigot/AdvancedEnchantments#1068]
**Describe the bug**
Trying to set chances for the mob drop to drop different items and it wouldn't work.
Only the last item on the list would spawn. In my case, its the Heroic secret dust.
I can also confirm that this is happening with all rewards not just secret dust.
For example, I used the following configuration:
```
  ZOMBIE:
    chance: 5
    items:
      - 'secret:1:simple'
  ZOMBIE:
    chance: 4
    items:
      - 'secret:1:unique'
  ZOMBIE:
    chance: 3
    items:
      - 'secret:1:elite'
  ZOMBIE:
    chance: 2
    items:
      - 'secret:1:ultimate'
  ZOMBIE:
    chance: 1
    items:
      - 'secret:1:legendary'
  ZOMBIE:
    chance: 1
    items:
      - 'secret:1:heroic'
```
but only the last item on the list is being dropped as a reward ignoring all the above items.

**To Reproduce**
Use the above config and you will be able to reproduce the issue.

**Screenshots / Video**
None

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.15.2]
- Plugin Version [e.g. 7.5.0-Pre40]
