### ISSUE TITLE
[Issue] Autosmelt | Crashes / Spams Console

### ISSUE THREAD

**Issue by Redgames0** [GC-spigot/AdvancedEnchantments#1135]
**Describe the bug**
When autosmelt is on a pickaxe and you mine a ore block with it it spams the console with errors or sometimes crashes the server.

My Autosmelt config:
```
autosmelt:
  display: '%group-color%Auto Smelt'
  description: "Ores are automatically smelted\nwhen mined."
  applies-to: 'Pickaxes'
  type: 'MINING'
  group: 'COMMON'
  applies:
  - ALL_PICKAXE
  levels:
    1:
      chance: 50
      effects:
      - 'SMELT'
    2:
      chance: 70
      effects:
      - 'SMELT'
    3:
      chance: 100
      effects:
      - 'SMELT'
```

**To Reproduce**
Use the newest version of the plugin and add autosmelt to a pickaxe (I alsso believe it works in older versions)

**Screenshots / Video**

**Server Information (please complete the following information):**
 - Minecraft Version: Paper 1.15.2
- Plugin Version 7.7.1
