### ISSUE TITLE
"applies-to"

### ISSUE THREAD

**Issue by Eur0x** [GC-spigot/AdvancedEnchantments#1171]
Hi,
it's possible to hide attribute of "applies-to", for example:

```
jellylegs:
  display: '%group-color%Jelly Legs'
  description: "Chance to negate fall damage."
  applies-to: 'Boots' # # # <--------
  type: 'FALL_DAMAGE'
  group: 'ULTIMATE'
  applies:
    - ALL_BOOTS
  levels:
    1:
      chance: 40
      effects:
        - 'STOP_ATTACK'
        - 'MESSAGE:&b&l*** &f&lNegated Fall Damage &b&l***'
```
I just want to translate it to other language so it's possible to hide it? then I can add this to lore
description.

https://prnt.sc/t38a9i
