### ISSUE TITLE
translation [Issue]

### ISSUE THREAD

**Issue by Eur0x** [GC-spigot/AdvancedEnchantments#1217]
```
inventory:
  # set to 'none' to disable
  open-sound: 'BLOCK_CHEST_OPEN'
  name: "You                   Tinkerer"

items:
    agree:
      type: STAINED_GLASS_PANE
      id: 14
      name: '&eClick to ACCEPT trade'

    confirm-agree:
      enable: false
      type: STAINED_GLASS_PANE
      id: 5
      name: '&aClick to confirm the transaction'
```
      
```
name: '&eClick to ACCEPT trade'
   
name: '&aClick to confirm the transaction'

name: "You                   Tinkerer"
```

**Can you enable translation? bcs, when I want to translate it - the GUI is broken and the buttons don't work**

(tinkerer.yml)
