### ISSUE TITLE
[Issue] ADD_DURABILITY_CURRENT_ITEM does not work when used with repeating effect on armor

### ISSUE THREAD

**Issue by NightFuryStrike** [GC-spigot/AdvancedEnchantments#1256]
**Describe the bug**
I was attempting to create an enchantment that slowly repairs the item over time with a repeating effect. In my example, I applied the enchantment to a damaged diamond chestplate and then equipped the item. The repeating message I added for testing works properly, but the armor piece does not gain 5 durability every 5 seconds like it's supposed to.

**To Reproduce**

**Step 1:** Add the following enchantment shown below.
```
repairing:
  display: '%group-color%Repairing'
  description: "Slowly repairs the item over time while equipped or held."
  applies-to: 'Armor'
  type: 'REPEATING'
  time: 5
  group: 'SIMPLE'
  applies:
    - 'ALL_ARMOR'
  levels:
    1:
      chance: 100
      cooldown: 1
      effects:
        - 'ADD_DURABILITY_CURRENT_ITEM:-5'
        - 'MESSAGE:&eRepaired &65 &e/Durability!'
```
**Step 2:** Use the following command to give yourself a damaged diamond chestplate.
```
/give @s minecraft:diamond_chestplate{Damage:200} 1
```
**Step 3:** Add the enchantment to the diamond chestplate.
**Step 4:** Equip the diamond chestplate.
**Step 5:** Ensure you have "advanced tooltips" enabled to see the durability of the diamond chestplate. (F3 + H)
**Step 6:** Observe the durability on the diamond chestplate not rising by 5 points every 5 seconds, however the message is still printed in chat, showing that the repeating effect works, but the add_durability_current_item effect is not working.

**Server Information (please complete the following information):**
- Minecraft Version: Paper-79 (1.16.1)
- Plugin Version 7.9.30
