### ISSUE TITLE
[Issue] Using ADD_DURABILITY_CURRENT_ITEM on an armor piece and getting hit by a mob causes the effect to ignore the mob's durability damage

### ISSUE THREAD

**Issue by NightFuryStrike** [GC-spigot/AdvancedEnchantments#1299]
**Describe the bug**
I created an enchantment that slowly repairs the item over time with a repeating effect. In my example, I applied the enchantment to a diamond chestplate and then equipped the item.

When a mob does durability damage to the chestplate, it will cause the next repairing proc to ignore the mob's durability damage and repair it to what it was before the mob did damage, plus whatever the enchant itself repairs.

Example: Chestplate at 200 durability, repairing proc should restore 1 durability. Mob does damage to the armor, bringing the durability down to 198, but when the durability proc goes off, it repairs the armor to 201 instead of the expected 199.

**To Reproduce**
Step 1: Add the following enchantment shown below.
```
repairing:
  display: '%group-color%Repairing'
  description: "Slowly repairs the item over time while equipped or held."
  applies-to: 'Armor'
  type: 'REPEATING'
  time: 3
  group: 'SIMPLE'
  applies:
    - 'ALL_ARMOR'
  levels:
    1:
      chance: 100
      cooldown: 1
      effects:
        - 'ADD_DURABILITY_CURRENT_ITEM:-1'
        - 'MESSAGE:&eRepaired &61 &e/Durability!'
```
Step 2: Give yourself a diamond chestplate with full durability.
Step 3: Add the enchantment to the diamond chestplate and equip it.
Step 4: Ensure you have "advanced tooltips" enabled to see the durability of the diamond chestplate. (F3 + H)
Step 5: Summon a mob and allow it to hit you, observe the durability damage the mob does to the chestplate. Then observe when the enchantment procs, instead of restoring 1 durability, it restores the diamond chestplate back to full.

**Server Information** (please complete the following information):
Minecraft Version: Paper-93 (1.16.1)
Plugin Version 7.11.5
