### ISSUE TITLE
[Issue] Mining Trigger Issue

### ISSUE THREAD

**Issue by EarthAgar** [GC-spigot/AdvancedEnchantments#1322]
**Describe the bug**
My enchants that utilizes the `mining` trigger, is triggering up to 6 times per block when I break a block.

**To Reproduce**
Use my enchant bellow:
```
gemfinder:
  display: '%group-color%Gem Finder'
  description: '&fIncreases the odds of finding &dCrystals ♦ &fwhile Mining'
  applies-to: 'Pickaxes'
  group: 'LEGENDARY'
  type: 'MINING'
  applies:
    - 'ALL_PICKAXE'
  settings:
    removeable: false
  levels:
    '1':
      chance: 100
      effects:
        - 'CONSOLE_COMMAND:crystals add <random number>1-5</random number> %attacker%'
        - 'MESSAGE:&fYou found &d%random% &d♦ &fwhile mining! %attacker%'
        - 'PLAY_SOUND:BLOCK_END_PORTAL_FRAME_FILL:3:1 %attacker%'
```

**Screenshots / Video**
Here is proof of the spamming trigger.
![image](https://user-images.githubusercontent.com/27425322/88991635-093ad780-d296-11ea-89ab-e6067d7a3d1e.png)

**Server Information (please complete the following information):**
 - Minecraft Version: Paper
![image](https://user-images.githubusercontent.com/27425322/88991745-57e87180-d296-11ea-8506-92a78e2252b5.png)

- Plugin Version: 7.12.6
