### ISSUE TITLE
[Issue] "%damaged from behind% : %allow%" has the opposite effect of what it's supposed to

### ISSUE THREAD

**Issue by johnyuki** [GC-spigot/AdvancedEnchantments#1383]
**Describe the bug**
When using the %damaged from behind% condition along with %allow%, it's saying that "if the victim is damaged from behind, allow the effect to happen". However, this isn't the case. For to make the effect work, you need to use %stop%. 

**To Reproduce**
Add the following enchantment:
```
hind:
  display: "%group-color%Hind"
  description: "Take 50% less damage when being hit from behind. "
  applies-to: "Chestplate + Leggings"
  group: "ELITE"
  type: "DEFENSE"
  applies:
    - "ALL_CHESTPLATE"
    - "ALL_LEGGINGS"
  levels:
    1:
      chance: 100
      condition: 
        - '%damaged from behind% : %allow%'
      effects:
        - 'DECREASE_DAMAGE:50 %victim%'
        - 'MESSAGE:&e&l--- You took 50% less damage due to Hind ---'
```
You'll see that this enchantment doesn't work. 
Now change `'%damaged from behind% : %allow%'` to `'%damaged from behind% : %stop%'`. You'll now notice that the enchantment works, and the damage is halved and you receive the chat message.

EDIT:

This seems to be the case with %is under water%, so I would imagine it will be the same with all true/false conditions.

**Server Information (please complete the following information):**
 - Minecraft Version [Tuinity 1.15.2 (git ver. 5794d12)]
- Plugin Version [8.0.0 pre12]
