### ISSUE TITLE
[Issue] TRENCH:3 only breaks 2 deep

### ISSUE THREAD

**Issue by johnyuki** [GC-spigot/AdvancedEnchantments#1386]
**Describe the bug**
`TRENCH:3` effect applies correctly for X and Y, but when applying it for Z it only breaking 2 deep.

**To Reproduce**
Use the following enchant and apply it on a pickaxe, then go and mine.
```
detonate:
  display: '%group-color%Detonate'
  description: "Chance to break in 3x3 area."
  applies-to: 'Pickaxes'
  type: 'MINING'
  group: 'ULTIMATE'
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
  levels:
    1:
      chance: 100
      effects:
        - 'TRENCH:3'
```

**Screenshots / Video**
https://streamable.com/cbvv71

**Server Information (please complete the following information):**
 - Minecraft Version [Tuinity 1.15.2]
- Plugin Version [8.0.0-pre12]
