### ISSUE TITLE
Pull_closer effect fails to parse [Issue]

### ISSUE THREAD

**Issue by PeterDorvay** [GC-spigot/AdvancedEnchantments#1388]
**Describe the bug**
The PULL_CLOSER effect does not work. It says that it failed to parse. Here is a pastebin with the error. I'm using the bidirectional enchantment on a bow. https://pastebin.com/KdnqfngN

When using 'PULL_CLOSER %victim%' it gives the error. By default, the value was set to 'PULL_CLOSER:5 %victim%'. They both give the same error.

```
    3:
      chance: 32
      cooldown: 5
      effects:
        - 'PULL_CLOSER %victim%'
    4:
      chance: 100
      cooldown: 5
      effects:
        - 'PULL_CLOSER:5 %victim%'
```

**To Reproduce**
Use the same version and shoot a player with a bow using the Bidirectional Teleportation enchantment. Copy and paste the code above into enchantments.yml under the bidirectional teleportation section. It will give the failed to parse error.

**Screenshots / Video**

**Server Information (please complete the following information):**
 - Spigot 1.16.1
- Advanced Enchantments 8.0.0pre9
