### ISSUE TITLE
[question] What is the wait effect function?

### ISSUE THREAD

**Issue by EndlessLegends** [GC-spigot/AdvancedEnchantments#1510]
```
timber:
  display: '%group-color%timber'
  description: "timber"
  applies-to: 'Axes&7(Wooden &cX&7)'
  group: 'NORMAL'
  type: 'MINING'
  applies:
    - 'STONE_AXE'
    - 'IRON_AXE'
    - 'GOLDEN_AXE'
    - 'DIAMOND_AXE'
    - 'NETHERITE_AXE'
  levels:
    '1':
      chance: 100
      condition: 
        - '%block type% = oak_log or %block type% = spruce_log or %block type% = birch_log or %block type% = jungle_log or %block type% = acacia_log or %block type% = dark_oak_log or %block type% = oak_wood or %block type% = spruce_wood or %block type% = birch_wood or %block type% = jungle_wood or %block type% = acacia_wood or %block type% = dark_oak_wood : %allow%'
        - '%can break% = true : %allow%'
      cooldown: 8
      effects:
        - 'BREAK_TREE'
        - 'ACTIONBAR:You have 8 seconds to cool down : timber I'
        - 'WAIT:20'
        - 'ACTIONBAR:You have 7 seconds to cool down : timber I'
        - 'WAIT:20'
        - 'ACTIONBAR:You have 6 seconds to cool down : timber I'
        - 'WAIT:20'
        - 'ACTIONBAR:You have 5 seconds to cool down : timber I'
        - 'WAIT:20'
        - 'ACTIONBAR:You have 4 seconds to cool down : timber I'
        - 'WAIT:20'
        - 'ACTIONBAR:You have 3 seconds to cool down : timber I'
        - 'WAIT:20'
        - 'ACTIONBAR:You have 2 seconds to cool down : timber I'
        - 'WAIT:20'
        - 'ACTIONBAR:You have 1 seconds to cool down : timber I'
        - 'WAIT:20'
        - 'ACTIONBAR:Done! : timber I'
    '2':
      chance: 100
      condition: 
        - '%block type% = oak_log or %block type% = spruce_log or %block type% = birch_log or %block type% = jungle_log or %block type% = acacia_log or %block type% = dark_oak_log or %block type% = oak_wood or %block type% = spruce_wood or %block type% = birch_wood or %block type% = jungle_wood or %block type% = acacia_wood or %block type% = dark_oak_wood : %allow%'
        - '%can break% = true : %allow%'
      cooldown: 4
      effects:
        - 'BREAK_TREE'
        - 'ACTIONBAR:You have 4 seconds to cool down : timber II'
        - 'WAIT:20'
        - 'ACTIONBAR:You have 3 seconds to cool down : timber II'
        - 'WAIT:20'
        - 'ACTIONBAR:You have 2 seconds to cool down : timber II'
        - 'WAIT:20'
        - 'ACTIONBAR:You have 1 seconds to cool down : timber II'
        - 'WAIT:20'
        - 'ACTIONBAR:Done! : timber II'
    '3':
      chance: 100
      condition: 
        - '%block type% = oak_log or %block type% = spruce_log or %block type% = birch_log or %block type% = jungle_log or %block type% = acacia_log or %block type% = dark_oak_log or %block type% = oak_wood or %block type% = spruce_wood or %block type% = birch_wood or %block type% = jungle_wood or %block type% = acacia_wood or %block type% = dark_oak_wood : %allow%'
        - '%can break% = true : %allow%'
      cooldown: 2
      effects:
        - 'BREAK_TREE'
        - 'ACTIONBAR:You have 2 seconds to cool down : timber III'
        - 'WAIT:20'
        - 'ACTIONBAR:You have 1 seconds to cool down : timber III'
        - 'WAIT:20'
        - 'ACTIONBAR:Done! : timber III'
        
    '4':
      chance: 100
      condition: 
        - '%block type% = oak_log or %block type% = spruce_log or %block type% = birch_log or %block type% = jungle_log or %block type% = acacia_log or %block type% = dark_oak_log or %block type% = oak_wood or %block type% = spruce_wood or %block type% = birch_wood or %block type% = jungle_wood or %block type% = acacia_wood or %block type% = dark_oak_wood : %allow%'
        - '%can break% = true : %allow%'
      cooldown: 1
      effects:
        - 'BREAK_TREE'
        - 'ACTIONBAR:You have 1 seconds to cool down : timber IV'
        - 'WAIT:20'
        - 'ACTIONBAR:Done! : timber IV'
        
    '5':
      chance: 100
      condition: 
        - '%block type% = oak_log or %block type% = spruce_log or %block type% = birch_log or %block type% = jungle_log or %block type% = acacia_log or %block type% = dark_oak_log or %block type% = oak_wood or %block type% = spruce_wood or %block type% = birch_wood or %block type% = jungle_wood or %block type% = acacia_wood or %block type% = dark_oak_wood : %allow%'
        - '%can break% = true : %allow%'
      cooldown: 0.05
      effects:
        - 'BREAK_TREE'
        - 'ACTIONBAR:Done! : timber V'
```

In the above configuration, wait does not trigger break_tree. What exactly does wait do? Is there a way to display the cooldown in a different way than this? The vanilla enchantments.yml file example, or the information and examples on the github wiki page are lacking. It is also difficult to understand. Because I speak a different language than you.

Can I turn the function on/off with the RIGHT_CLICK type? When using the ADD or REMOVE effect, NBTs are created endlessly, do not work, or items are duplicated. I have a lot of questions, but I guess I will stop because I guess there will be a lot of your hard work(tired).
