### ISSUE TITLE
[Issue] Error with the halloweenify enchant

### ISSUE THREAD

**Issue by Sikatsu** [GC-spigot/AdvancedEnchantments#1529]
**Describe the bug**

https://pastebin.com/ffruxpre

![image](https://user-images.githubusercontent.com/5664135/97573180-a74f5280-19e9-11eb-95f0-0336205053bd.png)

**To Reproduce**
Use a sword with the halloweenify enchant on it.

```
halloweenify:
  display: '%group-color%Halloweenify'
  description: 'Verander de helm van de tegenstander \ntijdelijk naar een pompoen.'
  applies-to: 'Weapons'
  type: 'ATTACK_MOB'
  group: 'MASTERY'
  applies:
    - ALL_SWORD
    - ALL_AXE
  levels:
    1:
      chance: 10
      cooldown: 20
      effects:
        - 'PUMPKIN:40 %victim%'
        - 'PLAY_SOUND_OUTLOUD:ANVIL_DROP'
    2:
      chance: 20
      cooldown: 20
      effects:
        - 'PUMPKIN:40 %victim%'
        - 'PLAY_SOUND_OUTLOUD:ANVIL_DROP'
    3:
      chance: 30
      cooldown: 20
      effects:
        - 'PUMPKIN:60 %victim%'
        - 'PLAY_SOUND_OUTLOUD:ANVIL_DROP'
    4:
      chance: 40
      cooldown: 20
      effects:
        - 'PUMPKIN:60 %victim%'
        - 'PLAY_SOUND_OUTLOUD:ANVIL_DROP'
    5:
      chance: 50
      cooldown: 20
      effects:
        - 'PUMPKIN:80 %victim%'
        - 'PLAY_SOUND_OUTLOUD:ANVIL_DROP'
```

git-Tuinity-"5df4a4f" (MC: 1.16.3)
8.0.0-11.3 pre
