### ISSUE TITLE
[Issue] SHIFT event in armor sets

### ISSUE THREAD

**Issue by ludgart** [GC-spigot/AdvancedEnchantments#1544]
Hello,

im using the plugin version AdvancedEnchantments-8.0.0-Pre12.3 and I tried to setup an custom armor set with the event "shift" without success.
Here a part of the file:

```
events:
  SHIFT:
    effects:
      - 'BOOST:6'
      - 'MESSAGE:super mega jump'
```

Can you please fix it?

Server version: 1.16.3 - paper-244

Regards
ludgart
