### ISSUE TITLE
[Issue] Damage calculation

### ISSUE THREAD

**Issue by ludgart** [GC-spigot/AdvancedEnchantments#1545]
Hello,

im using the plugin version AdvancedEnchantments-8.0.0-Pre12.3 and I tried to add a damage increase effect on one of my sets, but it seemed to have no effect. I also tested the default yeti set, but same thing, dmg unaffected.
When I changed the damage modifier to 1000% instead of 10% it worked as intended.

```
events:
  ATTACK_MOB: 
    effects:
      - 'INCREASE_DAMAGE:10'
      - 'MESSAGE:test'

```

Server version: 1.16.3 - paper-244

Regards
ludgart
