### ISSUE TITLE
[Issue] Issue with Events & CustomWeapons

### ISSUE THREAD

**Issue by OGreenC** [GC-spigot/AdvancedEnchantments#1582]
I tried reaching out on Discord, but without luck, So I'll try through here :-)

**Describe the bug**
I can't for the life of me get events to work for custom weapons :i

I'm trying to give an permission, when the player hold an item, I've done this this way: 
```
events:
  HELD:
    chance: 100
    effects:
      - 'PERMISSION:test'
```

but the player does not get the permission test, when the player holds the weapon.
Any idea as to what I am doing wrong?

Yes, I have the armorset on, and have also tried with no required armor set, for the events to work, still no result.

The permission event-thingy works fine for armor - When I equip the full set, I get the desired permission, which I defined in the config

I Tried changing the event to the following, for testing purposes:
```
events:
  MINING:
    chance: 100
    effects:
      - 'MESSAGE:test'
```

This *kinda* works, but not really as intended.. When I right click with the weapon in the hand, it only white the message in the chat __The first time__ after a reload.
After this, nothing happens, when I right click.

If I do */ae reload*, and right click with the item again, the message "test" is once again shown in the chat, but only the first time, until the next reload, and so on.

See the gyazo I linked below - it only sends the message once, which for me indicates, something weird is going on.

**To Reproduce**
Create a customWeapon, and give it the Event:

```
events:
  HELD:
    chance: 100
    effects:
      - 'PERMISSION:test'
```

**Screenshots / Video**
https://gyazo.com/37b4efce4212a30a9114d67582e8d883

**Server Information (please complete the following information):**
- Server Version: [e.g. PaperSpigot-653 1.13.2
- Plugin Version: AdvancedEnchantments-8.0.0-Pre15.7.jar
