### ISSUE TITLE
'DOUBLE_DAMAGE' Effect is broken.

### ISSUE THREAD

**Issue by KasearMC** [GC-spigot/AdvancedEnchantments#1597]
Minecraft: 1.16.4
Paper
AE: 8.0.0 PRE - 17.0

The 'DOUBLE_DAMAGE' effect for enchantments is broken. Enchants running this effect simply do not work.
The last enchant code I tested with will be posted below. I also tried copy pasting the Insanity enchant from the default enchants.yml with the same effect and it still didn't work. Also didn't work using the enchantment creator website syntax.

```
damageboost:
  display: '%group-color%Damage Boost'
  description: 'Testing double damage.'
  applies-to: 'Weapons'
  group: 'TEST'
  type: 'ATTACK;ATTACK_MOB'
  applies:
    - ALL_SWORD
    - ALL_AXE
    - BOW
  levels:
    1:
      chance: 50
      cooldown: 2
      effects:
        - 'DOUBLE_DAMAGE %attacker%'
```
