### ISSUE TITLE
[Issue] Nightwalker enchantment text issue

### ISSUE THREAD

**Issue by Starkenz** [GC-spigot/AdvancedEnchantments#1765]
**Describe the bug**
When i hit mob with nightwalker custom enchant this[Screenshot] message appears.

**To Reproduce**
Hitting mob

**Screenshots / Video**
![7d503153-59ca-4476-bdfc-00d069927f07](https://user-images.githubusercontent.com/21794143/110494655-c5af2280-812e-11eb-939c-9f233109b066.png)

**Server Information (please complete the following information):**
- Server Version: [PaperSpigot-123 1.8.8]
- Plugin Version: [8.0.0-Pre20.5]

**Comment by Insprill** [comment]
seems like you have a configuration error. This is the default Nightwalker configuration: 
```yaml
nightwalker:
  display: '%group-color%Nightwalker'
  description: "Freeze mobs at night."
  applies-to: 'Swords'
  type: 'ATTACK_MOB'
  group: 'ELITE'
  applies:
    - ALL_SWORD
  levels:
    1:
      chance: 40
      condition: '%time% < 12300 or %time% >= 23850 : %allow%'
      effects:
        - 'POTION:SLOW:10:400'
    2:
      chance: 70
      condition: '%time% < 12300 or %time% >= 23850 : %allow%'
      effects:
        - 'POTION:SLOW:10:400'
    3:
      chance: 100
      condition: '%time% < 12300 or %time% >= 23850 : %allow%'
      effects:
        - 'POTION:SLOW:10:400'
```
If you need further help, you can join our [Discord Server](https://discord.gg/GzdQdMw), verify yourself in #verification, then create a ticket in #tickets and one of us will help you.
