### ISSUE TITLE
[Request] Custom applies groups

### ISSUE THREAD

**Issue by Insprill** [GC-spigot/AdvancedEnchantments#1794]
**Describe the Request**
Make a config section where server owners can create custom applies groups. This would make it much easier to say add carved pumpkins to all helmets without having to define it per enchant.  
Example:
```yaml
applies-groups:
    NETHERITE_ARMOR:
        - NETHERITE_HELMET
        - NETHERITE_CHESTPLATE
        - NETHERITE_LEGGINGS
        - NETHERITE_BOOTS
    DIAMOND_TOOLS:
        - DIAMOND_PICKAXE
        - DIAMOND_AXE
        - DIAMOND_SHOVEL
```
