### ISSUE TITLE
Issue with cooldowns on REPEATING enchantments

### ISSUE THREAD

**Issue by justaureus** [GC-spigot/AdvancedEnchantments#1869]
## Details

**Describe the bug**
When using a REPEATING enchantment with a cooldown, it appears the cooldown is "serverwide".  What I mean by that is if a player uses a REPEATING enchantment that has a cooldown, the entire server will have to wait until the cooldown has expired based on when that player used the item.  Shouldn't this cooldown be per player?

**To Reproduce**
This is the exact enchantment with the issue:
```
oceanforgedleggings:
  display: '%group-color%'
  description: "Enchant for Ocean Forged Leggings"
  applies-to: 'Ocean Forged Leggings'
  group: 'SIMPLE'
  type: 'REPEATING'
  time: 1
  applies:
    - 'ALL_LEGGINGS'
  settings:
    removeable: false
  levels:
    '1':
      cooldown: 5
      condition:
        - '%attacker is under water% = true : %allow%'
      effects:
        - 'POTION:DOLPHINS_GRACE:5:140'
        - 'POTION:BLINDNESS:0:200'
```
**Screenshots / Video**
It is not easy to get a video of this and demonstrate what is happening.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/jivihixanu
- Server log: https://gist.github.com/justaureus/20fcf8a03c270a97427b83789780de69
