### ISSUE TITLE
EXP:integer doesn't work as documented

### ISSUE THREAD

**Issue by ProfessionalBoatDrifter** [GC-spigot/AdvancedEnchantments#1891]
"EXP:integer" does not work as described in the documentation. Rather than dropping the amount of orbs each worth 4 EXP, it drops an orb worth that amount.

```
experience: 
  display: "%group-color%Experience"
  description: "description"
  applies-to: "Tools"
  type: "MINING"
  group: "SIMPLE"
  settings:
    required-enchants:
      - 'transmutation'
  applies:
    - ALL_PICKAXE
  levels:
    1:
      chance: 100
      cooldown: 1
      condition:
        - "%block type% contains ORE : %allow%"
      effects:
        - "EXP:1"
```

The setting above drops one orb worth 1 EXP point, rather than 1 orb worth 4 EXP.
I have tested using integers 1 through 5 with each ore yielding that amount of EXP. Verified using essentials /xp each time.
The required-enchant is a slightly modified version of "smelting" and works as intended on its own. 

Personally I would prefer keep it this way and instead adjust the documentation (https://ae.advancedplugins.net/enchantments/creating-enchantments/effect-list).
If you do decide to correct it according to the current documentation, please re-implement the above behaviour at the same time.

Version: 8.0.0-Pre23.5
git-Paper-588 (MC: 1.16.5)
