### ISSUE TITLE
Run commands when equipping/ unequipping sets

### ISSUE THREAD

**Issue by UneVentouse2** [GC-spigot/AdvancedEnchantments#1943]
## Request

**Description**
This request is to be able to add our own commands to be executed when the player equips himself with an armor and when he removes it ! Example:
```
  helmet:
    name: 'Add Commands'
    lore :
      - test
    enchantments:
      - protection:4
    commands :
      equip:
        - say test
        - eco gives %player% 1
      unequip :
        - say test
        - eco gives %player% 1
```
And also be able to add a command when the complete armor is put on and taken off. Example:
```
parameters:
  equipped:
    commands:
      - 'eco gives %player% 5'
      - 'msg: &a&l(!) &aYou have activated the Yeti set!'
  unequipped:
    commands:
      - 'eco give %player% 5'
      - 'msg: &c&l(!) &cYou have disabled the Yeti set!'
```

**How the feature is useful**
This feature could be very useful when we want to use commands from other plugins to be executed when the player uses an armor in parallel with the customs.
