### ISSUE TITLE
MobTrak and White Scroll read wrong Custom Model Data

### ISSUE THREAD

**Issue by bakaschwarz** [GC-spigot/AdvancedEnchantments#1944]
## Details

**Describe the bug**

When you set custom model data for the MobTrak or the White Scroll, the custom model data that gets set when the item is spawned using the `/ae giveitem` command is wrong.

Yes, my resourcepack works as intended and when i spawn the items myself by setting all NBT data manually, it works and the correct models get loaded.

**To Reproduce**

1. Have a resource pack with custom model data for an item. In my case i use INK_SACK and have custom model data defined in `ink_sac.json`.
2. Set `custom-model-data` to your custom model data number in `config.yml` in field `items.mobtrak` (18 in my case):
```yml
  mobtrak:
    type: INK_SACK
    id: 0
    custom-model-data: 18
    name: '&3MobTrak Creator'
    lore:
    - '&7Track how many mob kills you have with a weapon'
    - '&7Drag ontop of another item to apply it'
    messages:
      success:
      - '&7You successfully applied &3MobTrak Creator'
    settings:
      lore-display: '&eMob Kills: &f%stats%'
```
3. Do the same for the White Scroll item:
```yml
white-scroll:
  delete: true
  lore-display: '&f&lPROTECTED'
  item:
    type: INK_SACK
    id: 0
    custom-model-data: 24
    force-glow: false
    name: '&fWhite Scroll'
    lore:
    - '&fPrevents an item from being destroyed'
    - '&fdue to a failed Enchantment Book.'
    - '&ePlace scroll on item to apply.'
  messages:
    applied:
    - '&a&l(!) &aWhite scroll has been applied to your item.'
    failed:
    - '&c&l(!) &cWhite scroll saved the item.'
  custom-model-data: 0
```
(The `custom-model-data: 0` gets added at the end no matter what i do, the generated `config.yml` file says to write the custom model data inside the `item` field though)
4. Now load up the server and give yourself both items using `/ae giveitem`. Now the mobtrak has the custom model data of the holy white scroll and the white scroll has no custom model data at all.
5. You can use `/data get entity <playername> SelectedItem` to see the NBT data of those items when you hold them and sure enough, the custom model data is not like specified inside the configuration file.

**Screenshots / Video**

This is my current configuration:

https://pastebin.com/SHPaaYz5

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/leticayiru
- Server log: https://gist.github.com/bakaschwarz/2a13cf68e6723faaf251894a536b6f4a
