### ISSUE TITLE
REVIVE doesn't work

### ISSUE THREAD

**Issue by RulerOfEternity** [GC-spigot/AdvancedEnchantments#1978]
## Details

**Describe the bug**
REVIVE doesn't work, I'm using PASSIVE_DEATH and DEATH as the types.

**To Reproduce**
Make an enchantment with REVIVE and a 100% success rate just to see that it doesn't work at all.

**Screenshots / Video**
https://youtu.be/FMlocSZAvd8

## Server Information
- "/ae plinfo" link:  https://paste.md-5.net/itulegacit
- Server log:  https://gist.github.com/RulerOfEternity/c16e80016d502b70073db70fd4396353

**Comment by Insprill** [comment]
Can you send the enchantment you used? It's working fine for me. tested with this 
```yaml
test:
  display: "%group-color%Testing"
  description: "Enchant used to test things."
  applies-to: "Armor"
  type: "DEATH;PASSIVE_DEATH"
  group: "ULTIMATE"
  applies:
    - ALL_CHESTPLATE
  levels:
    1:
      effects:
        - 'REVIVE'
```
