### ISSUE TITLE
Slaughter enchantment spams chat and console when used on players

### ISSUE THREAD

**Issue by PeterDorvay** [GC-spigot/AdvancedEnchantments#2045]
## Details

**Describe the bug**
Players can not be converted to a stacked entity and as such the slaughter enchant spams an error in chat every time it is used on a player.

**To Reproduce**
Paste the following into enchantment.yml
```
slaughter:
  display: '%group-color%Slaughter'
  description: 'A chance to kill any mob in a single swing'
  applies-to: 'Sword'
  type: 'ATTACK_MOB'
  group: 'SIMPLE'
  applies:
    - ALL_SWORD
  levels:
    1:
      chance: 12
      effects:
        - 'KILL_MOB'
    2:
      chance: 27
      effects:
        - 'KILL_MOB'
    3:
      chance: 42
      effects:
        - 'KILL_MOB'
```
       
Then go and kill a player with that enchantment on a sword. It will spam an error in chat.

**Screenshots / Video**
https://pastebin.com/L3u9x5pB This is the error that is spammed.

## Server Information
- "/ae plinfo" link:  https://paste.md-5.net/iviteriqiq
- Server log:  https://pastebin.com/L3u9x5pB

**Comment by Insprill** [comment]
can you restart your server to make sure the type is properly applied? in theory this shouldn't be able to happen

**Comment by PeterDorvay** [comment]
Thought I had fixed it but it looks like its still repeating after a restart as well as adding `KILL_MOB:1` to the enchant. Here is the error: https://pastebin.com/JN2T8VzP
And this is how the enchantment looks:
```
slaughter:
  display: '%group-color%Slaughter'
  description: 'A chance to kill any mob in a single swing'
  applies-to: 'Sword'
  type: 'ATTACK_MOB'
  group: 'SIMPLE'
  applies:
    - ALL_SWORD
  levels:
    1:
      chance: 12
      effects:
        - 'KILL_MOB:1'
    2:
      chance: 27
      effects:
        - 'KILL_MOB:1'
    3:
      chance: 42
      effects:
        - 'KILL_MOB:1'
```
