### ISSUE TITLE
Issue with replanter

### ISSUE THREAD

**Issue by iGabyTM** [GC-spigot/AdvancedEnchantments#2124]
## Details

**Describe the bug**
```yml
      condition:
        - "%is crop% = false : %stop%"
        - "%is fully grown% = false : %stop%"
        - "%offhand item% = %block drop type% : %allow%"
      effects:
        - "TAKE_AWAY:%block drop type%"
        - "SET_BLOCK:%block type%"
 ```
The conditions aren't working, the enchantment procs for each and every block and it doesn't even take items from your inventory, so you can farm unlimited items.

**To Reproduce**
Apply the enchantment and just use it

**Screenshots / Video**

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/asuzumemoz
- Server log: https://mcpaste.io/0b598b44377c07e8
