### ISSUE TITLE
duplicated enchantments and cant remove it | HEX COLOR PROBLEM ⚠

### ISSUE THREAD

**Issue by SNokerYT** [GC-spigot/AdvancedEnchantments#2225]
## Details

**Describe the bug**
When I Change the global-color: '&4' For Example to be | global-color: '{#ff7010}' the problem happened
just use this config file and you will get the same Error 

```
# Enchantment groups are used for enchanter, to sell specific type books. You can group them
# and give each group global color.
# YOU CAN DELETE THESE GROUPS AND CREATE YOUR OWN
settings:
  magic-dust:
    # Limit applying of Magic dust per group
    # If false, magic dust can be applied to different groups
    limit-applying-per-group: true
  randomization-scrolls:
    # Limit applying of Randomization scrolls per group
    # If false, Randomization scrolls can be applied to different groups
    limit-applying-per-group: true
  # If set group is invalid, what should be the fall-back group
  fallback-group: SIMPLE
groups:
  SIMPLE:
    global-color: '{#88b94b}'
    group-name: "Simple"
    # Use this to change the type of item per group
    right-click-book-material: FIREWORK_CHARGE
    right-click-book-damage: 0
    right-click-book-custom-model-data: 0
    # Use this to set firework charge's color only! Uses RGB
    # Find colors here: https://htmlcolorcodes.com/color-picker/
    firework-color: 200;200;200
    slot-increaser:
      # How many slots should slot increaser add when using this type increaser
      slots: 1
    magic-dust:
      # when right-clicked, it gives magic with success chance
      # How much success should the dust have? (e.g.: 5 would mean always 5, 5-10 would mean random number from 5 to 10)
      success: 1-15
      # Chance to give Magic dust instead of Mystery dust
      chance: 22
  UNIQUE:
    global-color: '{#f65c6d}'
    group-name: "Unique"
    right-click-book-material: FIREWORK_CHARGE
    # Use this to set firework charge's color only! Uses RGB
    # Find colors here: https://htmlcolorcodes.com/color-picker/
    firework-color: 122;255;80
    slot-increaser:
      # How many slots should slot increaser add when using this type increaser
      slots: 1
    magic-dust:
      # when right-clicked, it gives magic with success chance
      # How much success should the dust have? (e.g.: 5 would mean always 5, 5-10 would mean random number from 5 to 10)
      success: 1-15
      # Chance to give Magic dust instead of Mystery dust
      chance: 22
  ELITE:
    global-color: '{#8b5cf6}'
    group-name: "Elite"
    right-click-book-material: FIREWORK_CHARGE
    # Use this to set firework charge's color only! Uses RGB
    # Find colors here: https://htmlcolorcodes.com/color-picker/
    firework-color: 20;250;255
    slot-increaser:
      # How many slots should slot increaser add when using this type increaser
      slots: 1
    magic-dust:
      # when right-clicked, it gives magic with success chance
      # How much success should the dust have? (e.g.: 5 would mean always 5, 5-10 would mean random number from 5 to 10)
      success: 1-15
      # Chance to give Magic dust instead of Mystery dust
      chance: 22
  ULTIMATE:
    global-color: '{#f49e0b}'
    group-name: "Ultimate"
    right-click-book-material: FIREWORK_CHARGE
    # Use this to set firework charge's color only! Uses RGB
    # Find colors here: https://htmlcolorcodes.com/color-picker/
    firework-color: 250;255;0
    slot-increaser:
      # How many slots should slot increaser add when using this type increaser
      slots: 1
    magic-dust:
      # when right-clicked, it gives magic with success chance
      # How much success should the dust have? (e.g.: 5 would mean always 5, 5-10 would mean random number from 5 to 10)
      success: 1-15
      # Chance to give Magic dust instead of Mystery dust
      chance: 22
  LEGENDARY:
    global-color: '{#c51414}'
    group-name: "Legendary"
    right-click-book-material: FIREWORK_CHARGE
    # Use this to set firework charge's color only! Uses RGB
    # Find colors here: https://htmlcolorcodes.com/color-picker/
    firework-color: 255;182;0
    slot-increaser:
      # How many slots should slot increaser add when using this type increaser
      slots: 1
    magic-dust:
      # when right-clicked, it gives magic with success chance
      # How much success should the dust have? (e.g.: 5 would mean always 5, 5-10 would mean random number from 5 to 10)
      success: 1-15
      # Chance to give Magic dust instead of Mystery dust
      chance: 22
  FABLED:
    global-color: '{#ff7010}'
    group-name: "Fabled"
    right-click-book-material: FIREWORK_CHARGE
    # Use this to set firework charge's color only! Uses RGB
    # Find colors here: https://htmlcolorcodes.com/color-picker/
    firework-color: 133;50;168
    slot-increaser:
      # How many slots should slot increaser add when using this type increaser
      slots: 1
    magic-dust:
      # when right-clicked, it gives magic with success chance
      # How much success should the dust have? (e.g.: 5 would mean always 5, 5-10 would mean random number from 5 to 10)
      success: 1-15
      # Chance to give Magic dust instead of Mystery dust
      chance: 22

```

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/68678154/127825354-6e262e0c-0829-4031-b85a-abd558a67b19.png)

## Server Information
- https://paste.md-5.net/anogezeleh
- https://paste.md-5.net/yawoyakeca.md
