### ISSUE TITLE
HEX COLOR PROBLEM | not removing enchant lore

### ISSUE THREAD

**Issue by SNokerYT** [GC-spigot/AdvancedEnchantments#2259]
not removing the enchant lore
when you use a HEX color on a group | 

```
  ELITE:
    global-color: "{#5b0d82}"
    group-name: "Elite"
    item:

```
![image](https://user-images.githubusercontent.com/68678154/129168451-0a30f710-6b81-41d5-a32e-b17333fa5c20.png)

## Server Information
- /ae plinfo https://paste.md-5.net/lelopazise
