### ISSUE TITLE
Custom Group Name Not working on | enchantment-book |

### ISSUE THREAD

**Issue by SNokerYT** [GC-spigot/AdvancedEnchantments#2262]
Custom Group Name Not working on | enchantment-book |
For Example, If  i set a group name on groups.yml to be a Test it will not use it and will only get the group name SAMPLE not the custom one i put | this problem happened after last update you made  it's not working only with - enchantment-book on config.yml

![image](https://user-images.githubusercontent.com/68678154/129237366-862e3455-bed6-48df-8aa7-ddc55051ded3.png)

```
groups:
  SIMPLE:
    global-color: '{#88b94b}'
    group-name: 'TEST'
    slot-increaser:
      slots: 1
    magic-dust:
      success: 1-15
      chance: 22
    item:
      type: COMMAND_BLOCK
      id: 0
      rgb-color: 200;200;200
```

the code I'm using on config.yml

```
enchantment-book:
  item:
    type: LEGACY_KNOWLEDGE_BOOK
    force-glow: true
    id: 0
    custom-model-data: 0
  name: '%group-color%%enchant-no-color% %level% | &f%group-name%'
```

https://paste.md-5.net/minadomesi
