### ISSUE TITLE
TP_DROP with silktouch doesnt drop torches

### ISSUE THREAD

**Issue by xCloudiness** [GC-spigot/AdvancedEnchantments#2264]
## Details

**Describe the bug**
 When using a telepathy enchant or something that uses TP_DROP and mine a torch that is placed in a wall it wont drop any torches nor place any torches back to your inventory

**To Reproduce** 

Have a silk touch pick with an enchant that uses telepathy or something like this
  levels:
    1:
      effects:
        - 'POTION:FAST_DIGGING:0'
        - 'TP_DROPS'

and mine a torch in a wall and it will not drop any torches
**Screenshots / Video**

https://imgur.com/sfAN92W

## Server Information
- "/ae plinfo" link:  https://paste.md-5.net/enociluxap
- Server log:  https://mcpaste.io/be5043b6171e507a

**Comment by Insprill** [comment]
Can you send the full enchantment? Default telepathy works fine for me when breaking wall torches.

**Comment by xCloudiness** [comment]
okay
```yml
hasteshift:
  display: '%group-color%Haste Shift'
  description: "&7Gain haste and teleport drops \nto you while using tools."
  applies-to: 'Tools'
  type: 'HELD;MINING'
  settings:
    removable: false
  group: 'ADVANCE'
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
    - ALL_AXE
  levels:
    1:
      effects:
        - 'POTION:FAST_DIGGING:0'
        - 'TP_DROPS'
    2:
      effects:
        - 'POTION:FAST_DIGGING:1'
        - 'TP_DROPS'
 ```
 heres the entire enchantment

**Comment by Insprill** [comment]
Using that enchant on 8.6.3 copying exactly what you did in the video I still couldn't reproduce it. Can you try removing all your plugins and see if it's still an issue and if it isn't add them back still it comes back?

**Comment by xCloudiness** [comment]
Using 8.6.4 with a silk touch and it still doesnt work 
https://discord.com/channels/861277994462478346/861277994462478349/875817011857489982
this bug only applies to silk touch picks and not any other bugs
"/ae plinfo" link: https://paste.md-5.net/atujuqojul
Server log: https://mcpaste.io/2c7a1d4771e2d4fe

**Comment by xCloudiness** [comment]
I tried using the premade telepathy and it gives the same result

https://user-images.githubusercontent.com/63063098/129409083-080df93b-092d-4084-b2d1-c1f9781742c1.mp4
"/ae plinfo" link: https://paste.md-5.net/oyalegayug
Server log: https://mcpaste.io/e04fce49794e2e5c

**Comment by Insprill** [comment]
Do you have experimental-block-breaking enabled? If not try enabling it.

**Comment by xCloudiness** [comment]
I tried having experimental-block-breaking to true, i wonder if i did it correctly though. sorry for the late reply, there was something we had to attend to
```yml

telepathy:
  display: "%group-color%Telepathy"
  description: "Automatically places blocks broken\nby tools in your inventory."
  applies-to: "Tools"
  type: "MINING"
  group: "UNIQUE"
  experimental-block-breaking: TRUE
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
    - ALL_AXE
  levels:
    1:
      chance: 40
      effects:
        - "TP_DROPS"
    2:
      chance: 60
      effects:
        - "TP_DROPS"
    3:
      chance: 80
      effects:
        - "TP_DROPS"
    4:
      effects:
        - "TP_DROPS"
```
