### ISSUE TITLE
EFFECT_STATIC effects are not applied/removed when drag+dropping armour to equip

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#2288]
## Details

**Describe the bug**
When equipping a piece of armour with an EFFECT_STATIC enchantment, specifically one that applies potion effects, the effect is not applied/removed unless the player shift-clicks the armour onto themselves, or right-clicks it in their hotbar to equip it. When they drag and drop it into/out of their armour slot, the effects are not applied. This means that the item can be shift-clicked to get the effects, then unequipped by drag+dropping, and they keep the effects.

**To Reproduce** 
Have a piece of EFFECT_STATIC enchantment armour in your inventory.
Click on the item, then click on the armour slot to equip it.
You will not receive the effects from the enchantment. Or, if you're unequipping it, the effect will not be removed if you had it.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/yadisemepi

**Comment by Insprill** [comment]
Can you send an example enchantment? Using this enchant I can't reproduce this issue. Picking up the armor and putting in the armor slots and taking it out works perfectly fine.
```yaml
overload:
  display: "%group-color%Overload"
  description: "Unlocks additional hearts."
  applies-to: "Armor"
  type: "EFFECT_STATIC"
  group: "LEGENDARY"
  applies:
    - ALL_ARMOR
  levels:
    1:
      effects:
        - "POTION:HEALTH_BOOST:0"
    2:
      effects:
        - "POTION:HEALTH_BOOST:1"
    3:
      effects:
        - "POTION:HEALTH_BOOST:2"
```

**Comment by Dakotaa** [comment]
`speed:
  display: '&7Speed'
  description: 'Added speed when equipped.'
  applies-to: 'Armor'
  type: 'EFFECT_STATIC'
  group: 'LEGENDARY'
  applies:
    - ALL_ARMOR
  levels:
    1:
      effects:
        - 'POTION:SPEED:0'
    2:
      effects:
        - 'POTION:SPEED:1'
    3:
      effects:
        - 'POTION:SPEED:2'`

**Comment by Dakotaa** [comment]
```
speed:
  display: '&7Speed'
  description: 'Added speed when equipped.'
  applies-to: 'Armor'
  type: 'EFFECT_STATIC'
  group: 'LEGENDARY'
  applies:
    - ALL_ARMOR
  levels:
    1:
      effects:
        - 'POTION:SPEED:0'
    2:
      effects:
        - 'POTION:SPEED:1'
    3:
      effects:
        - 'POTION:SPEED:2'
```
