### ISSUE TITLE
mobs spawn from GUARD effect will attack the player

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#2306]
## Details

**Describe the bug**
Mobs spawned from GUARD effect will attack the player.

**To Reproduce** 
1. use this enchantments
2. get attacked by a monster
3. guards are spawned and they attack me ...
```
精靈衛士:
  display: "%group-color%精靈衛士"
  description: "有機率召喚保護你的烈焰使者"
  applies-to: "Armor"
  type: "DEFENSE;DEFENSE_MOB"
  group: "ULTIMATE"
  applies:
    - ALL_ARMOR
  levels:
    1:
      effects:
        - "GUARD:VINDICATOR:10:10:%victim%"
        - "MESSAGE:activitated"
```

**Screenshots / Video**
![2021-08-19_23 18 46](https://user-images.githubusercontent.com/61608872/130095315-bed01e82-2d29-487f-a315-a2be1801ef72.png)

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/zaduxoluba
