### ISSUE TITLE
MORE_DROPS dupe mob armor

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#2309]
## Details

**Describe the bug**
more drop can be used to dupe armors, mobs that have armor or swords equipped , no matter player give them to equip, or they are naturally spawned, killing them with more_drops can get alot of armors, and cause dupe

**To Reproduce** 
1. use this ae on sword
```
diploid:
  display: "%group-color%diploid"
  description: "drop more things."
  applies-to: "Swords"
  type: "KILL_MOB"
  group: "FABLED"
  applies:
    - ALL_SWORD
  levels:
    1:
      # chance: 30
      # cooldown: 4
      # souls: 5
      effects:
        - "MORE_DROPS:10"
        - "MESSAGE:&cactivated"
```
2. to enhance the problem be much visible, can add a looting to increase chance to drop armor(more drops does not work if vanilla is not dropping armor and things), then with more_drops, armors are duped.

**Screenshots / Video**

youtube video: https://youtu.be/6tg4YPVtJAc

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/erujiyonex
- Server log: https://mcpaste.io/f9f243bca004d01b
