### ISSUE TITLE
[bug] AE REPEATING duplication

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#2334]
## Details

**Describe the bug**
AE REPEATING type enchantment will got it's effect duped if an item with EFFECT_STATIC is wear and take off for multiple times.
This is very hard to explain, please watch the video

https://youtu.be/urbuec4TEyY
https://youtu.be/rZquj36NG_E

**To Reproduce** 
1. enchant 
```
extrahealth:
  display: "%group-color%extra health"
  description: "give static extra health"
  applies-to: "Armor"
  type: "EFFECT_STATIC"
  group: "LEGENDARY"
  applies:
    - ALL_ARMOR
  levels:
    1:
      effects:
        - "POTION:HEALTH_BOOST:10"
add_health:
  display: "%group-color%add_health"
  description: "add health to player after a few sec."
  applies-to: "Armor"
  type: "REPEATING"
  time: 2
  group: "LEGENDARY"
  applies:
    - ALL_ARMOR
  levels:
    1:
      chance: 100
      effects:
        - "ADD_HEALTH:2"
        - "MESSAGE:&ctriggered addhealth"
```
extrahealth to helmet, add_health to leggings. or any of the gear.
2. make an item or add max health to the user, so that the regen health problem is shown much better
3. wear and take off the extrahealth AE gear, for multiple times, the more times the item is took off and then wear, the effect is duped much stronger

**Screenshots / Video**
https://youtu.be/urbuec4TEyY
https://youtu.be/rZquj36NG_E

## Server Information
https://paste.md-5.net/qudenafaye
