### ISSUE TITLE
TP_DROPS doesn't drop items from the top half of two high blocks

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#2336]
## Details

**Describe the bug**
when breaking the top half of a block using AE enchantment TP_DROPS, the drops are not given.

**To Reproduce** 
1. enchant the enchantment to a tool, axe as example here
```
TPBLOCKS:
  display: "%group-color%TPBLOCKS"
  description: "TP mined blocks"
  applies-to: "Tools"
  type: "MINING"
  group: "UNIQUE"
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
    - ALL_AXE
    - ALL_HOE
  levels:
    1:
      effects:
        - "TP_DROPS"
        # - "MESSAGE:&cactivated"
```
2. place 2 doors, then walk to the block in very close distance, almost stick to the door.
3. break the block, the block that should be appear in inventory after breaking will occasionally disappear.
*plz be alert, you need to try this for a few times to reproduce it, in my case i reproduced after breaking 6th block* 

**Screenshots / Video**
https://youtu.be/Xn8JJ0olSmI

## Server Information
- https://paste.md-5.net/uqunanilex
