### ISSUE TITLE
Effect REPAIR does not work with TRENCH

### ISSUE THREAD

**Issue by ProfessionalBoatDrifter** [GC-spigot/AdvancedEnchantments#2337]
## Details
I've enchanted a Netherite Pick with 2 enchantments having the REPAIR effect and TRENCH effect respectively.
I broke a flat stone wall in front of me and from full durability (2031) went down to 2012. 18 Cobblestone out of the 18 blocks broken (2 deep, 3x3 wall) was sent to the inventory.
With REPAIR, the item shouldn't be damaged at all.

**Describe the bug**
REPAIR effect does not work with the TRENCH effect.

**To Reproduce** 
1. Enchant an item with a TRENCH effect.
2. Enchant the same item with a REPAIR effect.
3. Break any block.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/kefiqopivi
- Server log: No messages from or related to AE.

**Comment by Insprill** [comment]
Wasn't able to reproduce this. Can you try toggling experimental-block-breaking? I tested it on and off but it's worth a shot for you to try it. Can you also send the enchantments you were using to test? I tested with unbreakable and trench and it repaired the pickaxe fine.

**Comment by ProfessionalBoatDrifter** [comment]
I've tried it with both experimental turned on (initially) and now off.
I'll try it on a test server and see if it's any different.

I've tested it and it still happens regardless of `experimental-block-breaking` being true or false.
Here is the /ae plinfo of that instance: https://paste.md-5.net/ocudirekop

Vanilla Minecraft's Unbreakable seems to work fine.

Here are the enchantments:

```
drill:
  display: "%group-color%Drill"
  description: "\n\n&fMining breaks blocks in a 3x3 area."
  applies-to: "Pickaxes"
  type: "MINING"
  group: "BASIC"
  applies:
    - ALL_PICKAXE
  levels:
    1:
      condition:
        - "%world% = world_nether : %stop%"
      effects:
        - "TRENCH:3"
ascended:
  display: "%group-color%Ascended"
  description: "Cannot break!"
  applies-to: "Tools & Weapons"
  type: "MINING;ATTACK;ATTACK_MOB;BOW;BOW_MOB"
  group: "BASIC"
  settings:
    newVersionsOnly: true # Only load this enchantment if server version is 1.13 or higher
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
    - ALL_AXE
    - ALL_SWORD
    - ALL_BOW
    - CROSSBOW
    - TRIDENT
  levels:
    1:
      effects:
        - "REPAIR"
```
Renamed the groups to work on a default file
