### ISSUE TITLE
ALL_CHESTPLATE enchantment can be activated when holding in mainhand

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#2342]
## Details

Enchantments that configured to be only applies on chestplate is still activating it's enchantment skill when the item is holding in main hand

**To Reproduce** 
1. use this enchantment
```
revive:
  display: "%group-color%revive"
  description: "revive when die."
  applies-to: "Chestplates"
  type: "DEATH;PASSIVE_DEATH"
  group: "FABLED"
  applies:
    - ALL_CHESTPLATE
  levels:
    1:
      effects:
        - "REVIVE %victim%"
        - "MESSAGE:&crevive activated"
```
2. enchant this enchantment to chestplate
3. die by a mob

**Screenshots / Video**
https://youtu.be/iPoReV-vMbo

## Server Information
- "/ae plinfo" link:  https://paste.md-5.net/ranayubugo
