### ISSUE TITLE
8.6.14 KILL_MOB is not triggering

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#2374]
### Describe the bug

AE enchant with kill mob type is not working, kill mob does not trigger enchantments.

### How to reproduce

kill mob with the following enchant

```
soul:
  display: "%group-color%soul"
  description: "kill mob, and you can get soul"
  applies-to: "Swords"
  type: "KILL_MOB"
  group: "FABLED"
  applies:
    - ALL_SWORD
  levels:
    1:
      effects:
        - "ADD_SOULS:1"
        - "PARTICLE:HEART:1:0"
```

### Screenshots / Videos

https://youtu.be/2IbWreYTF34

### "/ae plinfo" link

https://paste.md-5.net/tejoqupepi
