### ISSUE TITLE
8.6.14 effect "ADD_SOULS" does not add souls 

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#2378]
### Describe the bug

ADD_SOULS in AE enchant does not add any soul when the enchantment is triggered , the item have soul tracker, the enchantment is working in 8.6.10, but updated to 8.6.14, is not working any more, no souls are given to the item.

### How to reproduce

```
soulminer:
  display: "%group-color%Soulminer"
  description: "Chance to get souls by mining."
  applies-to: "Pickaxe"
  type: "MINING"
  group: "FABLED"
  applies:
    - ALL_PICKAXE
  levels:
    1:
      chance: 5
      effects:
        - "ADD_SOULS:1"
        - "PARTICLE:HEART:1:0"
    2:
      chance: 10
      effects:
        - "ADD_SOULS:1"
        - "PARTICLE:HEART:1:0"
    3:
      # chance: 100
      effects:
        - "ADD_SOULS:1"
        - "PARTICLE:HEART:1:0"
```
The above enchantment is from default enchantments.yml

i modified the level 3 so is 100% activated.

1. add soul tracker to item
2. add this enchantment
3. mine block
4. particle is generated.
5. no soul added

### Screenshots / Videos

https://youtu.be/Qrb3dUSYY1w

### "/ae plinfo" link

https://paste.md-5.net/zurevowixi
