### ISSUE TITLE
8.6.14   Tried to parse "ADD_HARM" effect with invalid argument. Expected a number, got %1%

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#2379]
### Describe the bug

This happen to default enchantment, reflect
if
``- "ADD_HARM:%damage% %attacker%"``
is used
the error will show when a mob or player attack the player 
![image](https://user-images.githubusercontent.com/61608872/134767675-56924697-ccab-4676-aed8-3cb1ddc131c7.png)

this error does not occur in previous version

### How to reproduce

use this enchantment, from default enchantments.yml
```
reflect:
  display: "%group-color%Reflect"
  description: "Absorb enemy damage and\nreflect it back."
  applies-to: "Armor"
  type: "DEFENSE;DEFENSE_MOB"
  group: "UNIQUE"
  applies:
    - ALL_ARMOR
  levels:
    1:
      # chance: 7
      # cooldown: 5
      effects:
        - "STOP_ATTACK"
        - "ADD_HARM:%damage% %attacker%"
        - "CACTUS_BREAK %victim%"
``` 
* cropped lower level, 100% for debug

1. use this enchantments and put on chestplate
2. wait for mob to attack

### Screenshots / Videos

https://youtu.be/kAJ9wh5odig

### "/ae plinfo" link

https://paste.md-5.net/hisaxamanu 

### Server Log

https://paste.gg/p/anonymous/9206fe7e055a45009568884f989b2b53
