### ISSUE TITLE
The ATTACK enchantment type does not work as expected 

### ISSUE THREAD

**Issue by rmalca** [GC-spigot/AdvancedEnchantments#2394]
### Describe the bug

I have an enchantment that throws lightning at the opponent, it is set to work in both PvP and PvE. Currently it only works as it should in PvE (ATTACK_MOB).

The problem is that it apparently only throws a bolt and then it never fires again. This works "fine" until version 8.6.12. "Good" because in that version there is a bug that for some reason ignores the cooldown or so it seems.

Going back to version 8.6.16, here it only shoots lightning once for players and lightning every 5 seconds for mobs. It should work the same for both mobs and players. 

Enchantment:
```yml
rayos:
  display: '%group-color%Rayos'
  description: 'Probabilidad que a tu enemigo le caigan rayos.'
  applies-to: 'Swords,Bows'
  type: 'ATTACK;ATTACK_MOB;BOW;BOW_MOB'
  group: 'UNIQUE'
  applies:
    - ALL_SWORD
    - BOW
    - CROSSBOW
  levels:
    1:
      cooldown: 5
      effects:
        - 'LIGHTNING %victim%'
    2:
      cooldown: 5
      condition:
        - '%victim has potion effect POISON% = TRUE : %stop%'
        - '%victim has potion effect ABSORPTION% = TRUE : %chance%+5'
        - '%victim has potion effect DAMAGE_RESISTANCE% = TRUE : %chance%+5'
      effects:
        - 'LIGHTNING %victim%'
```

### How to reproduce

1) Enchant sword with "Rayos" enchantment.
2) Use sword with a player.

### Screenshots / Videos

https://vimeo.com/622541107
https://vimeo.com/622541351

### "/ae plinfo" link

https://paste.md-5.net/vupiyolije
