### ISSUE TITLE
AE MORE_DROPS affecting mythicmobs mobs to drop more than it should

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#2408]
### Describe the bug

MORE_DROPS enchant is causing mythicmobs rpg mobs with fixed drop item to drop more item than it should.

**Situation**

RPG mobs drop should be fixed because they are connected to quest and many thing else, a way to boost the mob drop will cause some unique things to drop more than once, such as, some very rare armor will drop when boss is killed, it 
should drop one.

with MORE_DROPS, in normal cases, i will allow more_Drops drop 1-3 more items, if it activate on boss rare drop, it can already break game balance.

In fact, my players have already used this bug so that i report here and temporary freeze the AE enchantment

### How to reproduce

1. download mythicmobs free version
2. make a mythicmobs with fixed drop
in video, i use this mobs, add this to ExampleMobs.yml in mythicmobs/mobs folder
```
example:
  Type: ZOMBIE
  Health: 10
  Drops:
  - diamond 1 1
  Options:
    PreventOtherDrops: true
```
3. make a MORE_DROPS AE enchantment 
in video, enchantment is (for debug, more_drops is in very high level)
```
moredrop:
  display: "%group-color%moredrop"
  description: "drop more loot"
  applies-to: "Swords"
  type: "KILL_MOB"
  group: "FABLED"
  applies:
    - ALL_SWORD
  levels:
    1:
      effects:
        - "MORE_DROPS:100"
        - "MESSAGE:&cmoredrop DEBUG activated"
```
4. make a sword with the AE enchantment
5. use /mm r , to reload mythicmobs plugin so that mobs are loaded and can be spawn
6. kill the example mythicmobs zombie with vanilla sword, it should drop 1 diamond
7. kill the example mythicmobs zombie with more_drop AE, it should drop a lot of diamond

### Screenshots / Videos

Video demonstration, codes above are included, showing console, showing video with fortune , AE combination test
https://youtu.be/0Y1js7rbQB4

### "/ae plinfo" link

https://paste.md-5.net/zupefefeco

### Server Log

https://paste.gg/p/anonymous/e8469cd6e1f14f0e98afd94e9f628656
