### ISSUE TITLE
2+ Repeating enchantments cannot run properly in same armor

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#2423]
### Describe the bug

having 2 or more repeating enchantments in the same armor will cause problem, only 1 of the enchantment will run , another will not activated.
Have confirmed and tested that repeating enchantment working properly if 1 armor have only 1 repeating enchantment. 

### How to reproduce

1. use the following enchantments
```
add_food:
  display: "%group-color%add food"
  description: "add some food."
  applies-to: "Helmets"
  type: "REPEATING"
  time: 1
  group: "LEGENDARY"
  applies:
    - ALL_HELMET
  levels:
    1:
      effects:
        - "ADD_FOOD:4"
        - "MESSAGE:&cadded food  %server_time_HH:mm:ss%"
add_health:
  display: "%group-color%add health"
  description: "add some health."
  applies-to: "Armor"
  type: "REPEATING"
  time: 1
  group: "LEGENDARY"
  applies:
    - ALL_ARMOR
  levels:
    1:
      effects:
        - "ADD_HEALTH:6"
        - "MESSAGE:&cadded health %server_time_HH:mm:ss%"
```
2. try to test both of them  one by one on different helmet, only 1 "REPEATING" type enchantment in 1 armor
3. now, add both of the enchantments on 1 helmet
4. can reproduce

### Screenshots / Videos

Video demonstration, full reproduce step for above
https://youtu.be/m-s_jRHS1p8

### "/ae plinfo" link

https://paste.md-5.net/sifozeculi

### Server Log

https://paste.gg/p/anonymous/80300bf840a141abb3d8177bca84f9c7
