### ISSUE TITLE
McMMO Swords skill causes AdvancedEnchantments to repeat effects

### ISSUE THREAD

**Issue by squintinel** [GC-spigot/AdvancedEnchantments#2452]
### Describe the bug

McMMO has a Swords skill that causes "Bleeding", an effect which repeatedly damages your target for a short period of time. AdvancedEnchantments seems to think that each time "Bleeding" causes damage, the user is actively attacking the target. This is an issue because the custom enchantment effects are fired in succession and cause a great deal of damage.

### How to reproduce

I was able to reproduce this bug using the following steps using two people:

**1.** Load the following enchantment onto AdvancedEnchantments:
```
test:
  display: "&7Test"
  description: "An test enchantment"
  applies-to: "Armor"
  type: "DEFENSE;DEFENSE_MOB"
  group: "SIMPLE"
  applies:
    - ALL_ARMOR
  levels:
    1:
      effects:
        - "PLAY_SOUND:BLOCK_LARGE_AMETHYST_BUD_BREAK"
```
**2.** Install McMMO from [here ](https://popicraft.net/jenkins/job/mcMMO/).

**3.** Set your Swords skill to 1,000 to allow "Bleeding" to occur more frequently using `/addlevels {user} swords 1000`.

**4.** Have another player wear a full set of armor with the test enchantments applied, and attack them with a sword until they get the "Bleeding" effect. The sound effect from the enchantment should play every time they take damage from "Bleeding".

### "/ae plinfo" link

https://paste.md-5.net/esubojofal
