### ISSUE TITLE
ADD_HARM:%damage% is not working

### ISSUE THREAD

**Issue by t347549** [GC-spigot/AdvancedEnchantments#2455]
### Describe the bug

I am using a DEFENSE enchant that harms the attacker, I used ADD_HARM:%damage% and it does nothing to the attacker but ADD_HARM:5 (without a variable) works fine.

### How to reproduce

Try this enchant
```
reflection:
  display: '&7Reflection'
  description: "Returns melee damage taken back to attacker"
  applies-to: 'Armor'
  type: 'DEFENSE'
  group: 'SIMPLE'
  applies:
    - ALL_ARMOR
  levels:
    1:
      effects:
        - 'ADD_HARM:%damage% %attacker%'
        - 'PLAY_SOUND:BLOCK_LARGE_AMETHYST_BUD_BREAK'
        ```
        the amethyst sound is a test sound to see if the enchant activated.

### "/ae plinfo" link

https://paste.md-5.net/dorebaqabu
