### ISSUE TITLE
Enchantments do not function on Turtle Shells

### ISSUE THREAD

**Issue by Complex1t** [GC-spigot/AdvancedEnchantments#2501]
### Describe the bug

Enchantments do not function on Turtle Shells, even after adding TURTLE_SHELL and TURTLE_HELMET under the applies option.

### How to reproduce

1. Obtain a Turtle Shell.
2. Apply any enchantments onto the Turtle Shell.
3. Wear the turtle shell. The enchantments will not function.

Reference Enchantment:
```
glowing:
  display: "%group-color%Glowing"
  description: "Gives permanent night vision."
  applies-to: "Helmet"
  type: "EFFECT_STATIC"
  group: "SIMPLE"
  applies:
    - ALL_HELMET
    - TURTLE_SHELL
    - TURTLE_HELMET
  levels:
    1:
      effects:
        - "POTION:NIGHT_VISION:0"
```

Note that the error in the logs are caused from my other bug report, #2500. It does not relate to this bug.

### Screenshots / Videos

https://i.imgur.com/4ChokVv.mp4

### "/ae plinfo" link

https://paste.md-5.net/picegudonu

### Server Log

https://bin.bloom.host/qimoxebawu.yaml
