### ISSUE TITLE
%has potion effect <effect>% Doesn't Work

### ISSUE THREAD

**Issue by MamboTND** [GC-spigot/AdvancedEnchantments#2504]
### Describe the bug

I believe that the condition **%has potion effect <effect>%** is bugged.

### How to reproduce

Using the following DOES NOT work:
 ```
  type: 'ATTACK;ATTACK_MOB'
...
      chance: 0
      condition: '%victim has potion effect POISON% = true : %chance%+100'
      effects:
        - 'EXTRA_DAMAGE:4'
```
and
```
      condition: '%victim has potion effect POISON% = true : %allow%'
      effects:
        - 'EXTRA_DAMAGE:4'
```

I've tested similar conditions to find out if it was bugged, the following DOES work:
```
      condition: '%victim is on fire% = true : %allow%' 
      effects:
        - 'EXTRA_DAMAGE:4'
```

### "/ae plinfo" link

https://paste.md-5.net/asoyaronez
