### ISSUE TITLE
VEIN_MINE not compatible with fortune

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#2511]
### Describe the bug

VEIN_MINE not compatible with fortune, using a pickaxe with vein_mine and fortune, the drop is like without fortune. 

notice that, vein mine enchant activate normally, the config should be worked normally, the whitelist have nether gold ore.

VEIN_MINE enchantment:
```
veinminer:
  display: "%group-color%veinmier"
  description: "mine ores near by."
  applies-to: "Pickaxes"
  group: "ULTIMATE"
  type: "MINING"
  applies:
    - "ALL_PICKAXE"
  levels:
    1:
      # chance: 15
      # cooldown: 4
      effects:
        - "VEIN_MINE"
        - "MESSAGE:&cveinminer debug , activated"
```

### How to reproduce

1. make sure config have NETHER_GOLD_ORE in vein_mine whitelist
2. ``fortune-works-on-iron-gold: true`` in config, so that the config is appear configured right
3. make 2 pickaxe, both have fortune 20, 1 have veinminer enchant
4. mine nether_gold_ore
5. the one with veinminer will drop so less like no fortune enchant on

### Screenshots / Videos

https://youtu.be/GLG7v16DqPI

### "/ae plinfo" link

https://paste.md-5.net/uworahupiz
