### ISSUE TITLE
DEFENSE type with CONSOLE_COMMAND %attacker name% + other DEFENSE types enchants

### ISSUE THREAD

**Issue by MamboTND** [GC-spigot/AdvancedEnchantments#2520]
### Describe the bug

CONSOLE_COMMAND bugs the %player name% when two or more DEFENSE type enchantments  are used in the same armor.

### How to reproduce

I used this when testing and works fine when the only enchant on the armor.
```
grounded:
  display: '&7Grounded%group-color% ❖'
  description: "&8Venguful spirit that inflicts &bFatigue\n&8and &e25% &8chance to harm the attacker!\n&8- Applies &bFatigue II&8 for &e4 &8seconds.\n&8- Inflicts §e0-3 §8damage per hit."
  applies-to: 'Chestplates'
  type: 'DEFENSE;DEFENSE_MOB'
  group: 'LAND'
  applies:
    - ALL_CHESTPLATE
  levels:
    1:
      effects:
        - 'POTION:BLINDNESS:3:80 %attacker%'
        - 'PARTICLE:FALLING_DUST:20:1 %attacker%'
        - 'PLAY_SOUND_OUTLOUD:ENTITY_WITHER_SPAWN:0.6:1'
        - "CONSOLE_COMMAND:execute as %attacker name% positioned as %attacker name% run tp %attacker name% ~ ~-5 ~"
        - 'WAIT:60'
        - 'PLAY_SOUND_OUTLOUD:ENTITY_WITHER_SPAWN:2:1'
        - "CONSOLE_COMMAND:execute as %attacker name% positioned as %attacker name% run tp %attacker name% ~ ~5 ~"
```

It some how swaps %attacker name% to %victim name% meaning is sends the owner into the ground instead of the enemy.

### "/ae plinfo" link

https://paste.md-5.net/asoyaronez
