### ISSUE TITLE
%block location% in CONSOLE_COMMAND

### ISSUE THREAD

**Issue by MamboTND** [GC-spigot/AdvancedEnchantments#2521]
### Describe the bug

When Im using the following effect:
` - "CONSOLE_COMMAND:loot spawn %block location% loot minecraft:chests/shipwreck_treasure"`
%block location% gives 212.5|44.5|304.5

The issue is that to be able to use %block locations% in commands it must separate as such: 212.5 44.5 304.5

### How to reproduce

```
treasurehunter:
  display: '&7Treasure Hunter%group-color% ❖'
  description: 'When mining has a chance to drop custom enchants'
  applies-to: 'Pickaxe'
  group: 'LAND'
  type: 'MINING'
  applies:
    - 'ALL_PICKAXE'
  levels:
    '1':
      chance: 100
      condition:
        - "%block type% contains ORE : %allow%"
        - "%block drop type% contains ORE : %stop%"
      effects:
        - "CONSOLE_COMMAND:loot spawn %block location% loot minecraft:chests/shipwreck_treasure"
```

Console chat should create the following:
07.12 01:48:05 [Server] INFO Incomplete (expected 3 coordinates)
07.12 01:48:05 [Server] INFO ...oot spawn 212.5|44.5|304.5 loot minecraft:chests/shipwreck_treasure<--[HERE]

### "/ae plinfo" link

https://paste.md-5.net/asoyaronez
