### ISSUE TITLE
Odd bug - Cooldown is per entity?

### ISSUE THREAD

**Issue by MamboTND** [GC-spigot/AdvancedEnchantments#2539]
### Describe the bug

Not sure if this can be replicated but each zombie gets the 12 second cooldown instead of of the enchant only proc'ing every 12 second. You can test with 3 zombies, get hit by Zombie 1, then get hit by the Zombie 1 again and it will work fine. BUT if you get hit by Zombie 1 then Zombie 2, the enchant procs like it had no cooldown.

### How to reproduce

Spawn multiple zombies and get hit by them in different order.
```
explosivecombustion:
  display: "&7Explosive Combustion%group-color% 🔥"
  description: "&8Spark an &6Explosion &8when hit, hurting anyone in the radius!\n&8- &6Explode&8 in a &e8 &8block radius.\n&8- Sets wearer on &6Fire&8 for &e6 &8seconds.\n&8- Cooldown of &e12 &8seconds."
  applies-to: "Chestplate"
  type: 'DEFENSE;DEFENSE_MOB;DEFENSE_BOW;DEFENSE_BOW_MOB'
  group: 'HEAT'
  applies:
    - ALL_CHESTPLATE
  levels:
    1:
      cooldown: 12
      effects:
        - 'EXPLODE:0.1:true:false <aoe> radius=8 target=mobs </aoe>'
        - 'EXPLODE:0.1:true:false <aoe> radius=8 target=damageable </aoe>'
        - 'PARTICLE:FLAME:20:3'
        - 'PARTICLE:FLAME:50:5'
        - 'FLAME:6 %victim%'
```

### "/ae plinfo" link

https://paste.md-5.net/asoyaronez
