### ISSUE TITLE
Anvil with AdvancedEnchantments will add random enchants to the armor or sword or any thing

### ISSUE THREAD

**Issue by SNokerYT** [GC-spigot/AdvancedEnchantments#2566]
### Describe the bug

when I use Anvil it adds a default enchant? 
![image](https://user-images.githubusercontent.com/68678154/147852519-6f070512-ad9c-4c4d-a16d-58d1061dd983.png)

### How to reproduce

1 - get a book of AdvancedEnchantments 
2 - use it on the Anvil it will add random default enchant to the item

### "/ae plinfo" link

#

### Server Log

#

**Comment by GC-spigot** [comment]
Weird, can you share your configuration? `/ae zip`

**Comment by SNokerYT** [comment]
I found where the problem comes from, IT'S THE ( COLORS ) and this problem connected to old problems again 🤯, 
Please find final solution for colors! **It destroy the entire plugin**
https://github.com/GC-spigot/AdvancedEnchantments/issues/2262
![custom-leafsss4](https://user-images.githubusercontent.com/68678154/152178918-8c5f854a-ff98-4a66-b99c-ebf758103ae4.gif)

https://github.com/GC-spigot/AdvancedEnchantments/issues/2259
https://github.com/GC-spigot/AdvancedEnchantments/issues/2293



if you use colors on enchantment-book lore problem will happen again
```
enchantment-book:
  item:
    type: LEGACY_KNOWLEDGE_BOOK
    force-glow: true
    id: 0
    custom-model-data: 0
  name: '%group-color%%enchant-no-color% %level% | &f%group-name%'
  lore:
  - ''
  - ''
  - '        {#d92625}Chance of Destruction:&7 %destroy%%'
  - '&f%applies%'
  drag-drop-application: true
  anvil-application: true
```

**Also, Chance of Destruction not working on anvil**
