### ISSUE TITLE
ADD_HARM not working

### ISSUE THREAD

**Issue by NeuTraLZero** [GC-spigot/AdvancedEnchantments#2584]
### Describe the bug

ADD_HARM is not working on any enchantment type after update 8.8.1, will only display the entity as damaged but will not actually damage the entity

### How to reproduce

Example enchantment
```
shards:
  display: "&7Shards"
  description: "Damaging with a throw also damage nearby mobs"
  applies-to: "Trident"
  type: "BOW;BOW_MOB"
  group: "SIMPLE"
  applies:
    - TRIDENT
  levels:
    1:
      effects:
        - "ADD_HARM:4 <aoe> radius=5 target=mobs </aoe> %victim%"
        - "PARTICLE:CRIT_MAGIC:50:3 %victim%"
```

### "/ae plinfo" link

https://paste.md-5.net/enasucebog

### Server Log

https://mcpaste.io/1e3d48c436e6b6fd
