### ISSUE TITLE
BOW_MOB type with INCREASE_DAMAGE effect doesn't work when activated from an armor piece

### ISSUE THREAD

**Issue by NeuTraLZero** [GC-spigot/AdvancedEnchantments#2600]
### Describe the bug

When using an armor piece enchanted with BOW_MOB type with INCREASE_DAMAGE effect the actual damage dealt to the mob is not changed

### How to reproduce

Example enchantment:
```
ranger:
  display: "&7Ranger"
  description: "Increase crossbow damage"
  applies-to: "Helmet"
  type: "BOW;BOW_MOB"
  group: "SIMPLE"
  applies:
    - HELMET
  levels:
    1:
      condition: "%attacker is holding% = CROSSBOW or %attacker offhand item% = CROSSBOW : %allow%"
      effects:
        - "INCREASE_DAMAGE:20"
```
Also tested with bows, can't seem to get it working either

### "/ae plinfo" link

https://paste.md-5.net/ifepotirav

### Server Log

No error on console
