### ISSUE TITLE
%level of skill% condition not working

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#2603]
### Describe the bug

Tried to use that condition but doesn't work.
This message shows on chat:
![image](https://user-images.githubusercontent.com/66658478/150791814-d858073d-dcce-41cf-8637-3616c94fabf1.png)

### How to reproduce

Try to use that condition (with any TYPE). This is my enchant:

```
  levels:
    1:
      condition:
        - '%level of skill repair% > 200 : %continue%'
      effects:
        - 'MESSAGE:test'
```

### "/ae plinfo" link

https://paste.md-5.net/oqumilitog.css
