### ISSUE TITLE
INCREASE_DAMAGE, EXTRA_DAMAGE, etc. do not affect Ender Dragon

### ISSUE THREAD

**Issue by t347549** [GC-spigot/AdvancedEnchantments#2617]
### Describe the bug

INCREASE_DAMAGE, EXTRA_DAMAGE, etc. do not affect the Ender Dragon, however it seems PLAY_SOUND recognizes that I hit the dragon.

### How to reproduce

I used this enchantment to test:

 ``` 
 Test:
  display: "&7Test"
  description: "Increases damage against ender dragon"
  applies-to: "Bows"
  type: 'BOW_MOB'
  group: "SIMPLE"
  applies:
  - BOW
  levels:
    1:
      condition:
        - "%victim mob type% = ENDER_DRAGON : %allow%"
      effects:
          - "INCREASE_DAMAGE:9999"
          - "PLAY_SOUND:BLOCK_AMETHYST_BLOCK_CHIME"
 ```
 This enchant's effect would (and does currently) one-shot every normal mob but does not seem to affect the Ender Dragon at all, so I tacked on PLAY_SOUND to see if the enchant is even recognizing the dragon, and it seems like it does as a sound plays when my arrow lands on the dragon.
 
 I also tested this without the condition, and it doesn't affect the dragon still. So I think it's a problem with the effect itself.
 
It might be worth checking this with Wither since they're both boss mobs, I wasn't able to because I didn't know how to fight one.

### "/ae plinfo" link

https://paste.md-5.net/hegahaqovo
