### ISSUE TITLE
LAVA_WALKER still having effect after item dropping on death

### ISSUE THREAD

**Issue by NeuTraLZero** [GC-spigot/AdvancedEnchantments#2623]
### Describe the bug

After the player wearing an item lava walker enchantment dies and drop their items, the lava walker effect is still in effect permanently until they retrieve that item or another item with the same enchantment and equip then unequip it

### How to reproduce

Example enchantment:
```
firewalker:
  display: "&7Fire Walker"
  description: "Grant ability to walk on lava"
  applies-to: "Boots"
  type: "EFFECT_STATIC"
  group: "SIMPLE"
  applies:
    - BOOTS
  levels:
    1:
      effects:
        - "LAVA_WALKER"
```

### "/ae plinfo" link

https://paste.md-5.net/gogahuqida
