### ISSUE TITLE
Orb %increased% is negative

### ISSUE THREAD

**Issue by bdagenais2** [GC-spigot/AdvancedEnchantments#2644]
### Describe the bug

The lore for an item with an orb applied displays a negative number. I assume this is because we reduced the number of slots an item can have, and I imagine the orb %increased% variable is hardcoded to measure the difference from the default number of slots.

Screenshot of issue: https://i.ibb.co/gTgDmXv/image.png

Relevant pieces of our config:

```
[...]
  # Orbs allow applying x number of enchants
  orb:
    lore: '&7%max% Enchantment Slots &7(Orb +%increased%)'
    weapon:
      material: EYE_OF_ENDER
      custom-model-data: 0
      name: '&aWeapon Enchantment Orb'
      lore:
      - '&a%success%% Success Rate'
      - ''
      - '&6+%new% Enchantment slots'
      - '&6%max% Max Enchantment Slots'
      - ''
      - '&7Increases the # of enchantment'
      - '&7slots on a weapon by %new%,'
      - '&7up to a maximum of %max%'
      - ''
      - '&8Drag n'' drop onto an item to apply'
[...]
# Limit number of enchantments item can have
slots:
  enabled: true
  # Max number of enchantments
  max: 3
  # Max slots increasement with slot increaser
  # This is a total slot number that can be with upgrades
  max-increase-of-slots: 5
  # Should it be displayed in lore?
  display-in-lore: false
  display: '&eItem Slots&7: %left%'
  message:
  - '&cYou cannot apply that enchantment! There are no free slots left!'
[...]
```

### How to reproduce

I think reducing these lines of the config, restarting the server, and then applying an orb to an item will cause the issue:

```
  max: 3
  # Max slots increasement with slot increaser
  # This is a total slot number that can be with upgrades
  max-increase-of-slots: 5
```

### Screenshots / Videos

https://i.ibb.co/gTgDmXv/image.png

### "/ae plinfo" link

https://paste.md-5.net/wudenogohe
