### ISSUE TITLE
Alchemist "add-up-chances" bug

### ISSUE THREAD

**Issue by ProfessionalBoatDrifter** [GC-spigot/AdvancedEnchantments#2650]
### Describe the bug

Alchemist add up success chances (and goes beyond 100% on either success or failure) `add-up-chances: false`.

### How to reproduce

1. Set Alchemist settings to the example below.
2. Reload/restart.
3. Give yourself two books of any level but same success chance.
4. Use /Alchemist
5. Submit the books.
6. Preview the combined book (chances added and exceeding 100%)
7. Claim the combined book (chances added and exceeding 100% still)

Settings:
```
alchemist:
  settings:
    combine-books: true
    combine-dust: false
  books:
    add-up-chances: false
    pre-set-chances:
      enabled: false
      success: 100
      destroy: 50
  dusts:
    add-up: true
```

### "/ae plinfo" link

https://paste.md-5.net/uyajabiqin

### Server Log

No errors
