### ISSUE TITLE
BOW_SHOOT and BOW/BOW_MOB no longer work together

### ISSUE THREAD

**Issue by NeuTraLZero** [GC-spigot/AdvancedEnchantments#2653]
### Describe the bug

An enchantment with both BOW_SHOOT and BOW/BOW_MOB stopped working together after 8.8.16 update
No console errors are given.

### How to reproduce

example enchantment:
```
levitationshot:
  display: "&7Levitation Shot"
  description: "Fires slow homing shulker bullet"
  applies-to: "Bow"
  type: "BOW_SHOOT;BOW;BOW_MOB"
  group: "SIMPLE"
  applies:
    - BOW
  levels:
    1:
      cooldown: 1
      effects:
        - "HOMING:32:2:0.75"
        - "CHANGE_ARROW:SHULKER_BULLET:REMOVE:DISALLOWED"
        - "POTION_OVERRIDE:LEVITATION:0:30 %victim%"
        - "PARTICLE:END_ROD:25:0.5 %victim%"
        - "PLAY_SOUND_OUTLOUD:ENTITY_SHULKER_BULLET_HIT:1:1 %victim%"
        - "ACTIONBAR:&4Levitated by %attacker name%! %victim%"
```
Before update: bullet homes in on victim and victim gets levitated
After update: bullet homes in on victim but victim DO NOT get levitated

### "/ae plinfo" link

https://paste.md-5.net/emizelepor

### Server Log

https://mcpaste.io/4d405b0e608c24d4
