### ISSUE TITLE
INCREASE_DAMAGE not working in some cases

### ISSUE THREAD

**Issue by NeuTraLZero** [GC-spigot/AdvancedEnchantments#2654]
### Describe the bug

~~When both enchantments below are enchanted on a sword, the sword still deals 20% more damage to End mobs from Voidstrike but does not deal 50% more damage from Critical at all even if the mob is/is not the mob specified~~
The first enchantment work just fine but the second one do not apply increased damage. Particles, sound and cooldown still activate as normal

### How to reproduce

~~Used enchantment 1:~~
~~voidstrike:
  display: "&7Voidstrike"
  description: "Increase damage to End-related mobs or mobs affected by weakness"
  applies-to: "Sword"
  type: "ATTACK;ATTACK_MOB"
  group: "SIMPLE"
  applies:
    - SWORD
  levels:
    1:
      condition:
        - "%victim mob type% = ENDERMAN or %victim mob type% = ENDER_DRAGON or %victim mob type% = ENDERMITE or %victim mob type% = SHULKER or %victim has potion effect WEAKNESS% = true  : %allow%"
        - "%damage cause% = THORNS : %stop%"
      effects:
        - "INCREASE_DAMAGE:20"~~

Used enchantment 2:    
```
critical:
  display: "&7Critical"
  description: "Normal attacks deal critical damage up to once every 10 seconds"
  applies-to: "Sword"
  type: "ATTACK;ATTACK_MOB"
  group: "SIMPLE"
  applies:
    - SWORD
  levels:
    1:
      cooldown: 10
      condition:
        - "%is critical% = true : %stop%"
        - "%damage cause% = THORNS : %stop%"
        - "%damage cause% = SWEEP_ATTACK : %stop%"
      effects:
        - "INCREASE_DAMAGE:50 %attacker%"
        - "PARTICLE:CRIT:50:0.5 %victim%"
        - "PLAY_SOUND_OUTLOUD:ENTITY_PLAYER_ATTACK_CRIT:1:1 %victim%"
        - "ACTIONBAR:&cVoidstrike is now on cooldown %attacker%"
        - "WAIT:200"
        - "ACTIONBAR:&aVoidstrike is now recharged %attacker%"
```

### "/ae plinfo" link

https://paste.md-5.net/uvixebepes

### Server Log

No console error or log
