### ISSUE TITLE
Custom Model Data not working for alchemist, tinker and confirmation inventory

### ISSUE THREAD

**Issue by PeterMa9621** [GC-spigot/AdvancedEnchantments#2673]
### Describe the bug

The custom model data doesn't work for items in the alchemist inventory, tinkerer inventory and confirmation inventory.
For the tinkerer inventory, the custom model data for  `money` and `exp` items also don't work.

### How to reproduce

1. Open `config.yml` or `tinkerer.yml`
2. For `config.yml`, find `confirmation-inventory` or `enchanter.inventory`. For `tinkerer.yml`, find `inventory` and `items`.
3. Add `custom-model-data` for any items
4. Reload plugin or restart the server
5. Open the alchemist inventory in-game by using the command `/ae open XXX alchemist` to check if the textures of items get changed.
6. Open the confirmation inventory by buying an enchant book in the enchanter inventory to check if the textures of items get changed.
7. Open the tinkerer inventory to check if the textures of items get changed.

### "/ae plinfo" link

https://paste.md-5.net/opolagilal

**Comment by GC-spigot** [comment]
Added for all of them, use `customModelData` for Alchemist

**Comment by PeterMa9621** [comment]
Hey there, I can confirm the custom model data works for these inventories but not the output items from the tinkerer.
Below is the configuration of the output items in `tinkerer.yml`
```
items:
  money:
    type: PAPER
    id: 0
    customModelData: 100    # not working
    custom-model-data: 100  # not working
    name: "&cMoney Voucher &7(%amount%)"
    lore:
      - "&cReceived from &fEnchanter"
      - "&cReceived by &f%name%"
  exp:
    type: EXP_BOTTLE
    id: 0
    customModelData: 100    # not working
    custom-model-data: 100  # not working
    name: "&a&lExperience Bottle &7(throw)"
    lore:
      - "&dValue &f%amount% XP"
      - "&dEnchanter &fServer Enchanter"
 ```
