### ISSUE TITLE
Tinkerer bugs

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#2678]
### Describe the bug

I guess tinkerer isn't working the way is proposed.

**1. I can't remove confirmation.** 
Even turning confirm-agree to false, isn't working. Notice that this is default config and it have two "enable" options. I even try to remove the second one, but still don't working. 
```
  items:
    agree:
      type: STAINED_GLASS_PANE
      id: 14
      name: "&eClick to ACCEPT trade"
      lore: [ ]
    placeholder-items:
      type: THIN_GLASS
      id: 0
      name: " "
      lore: [ ]
    confirm-agree:
      enable: false
      type: STAINED_GLASS_PANE
      id: 5
      name: "&aClick to confirm the transaction"
      lore: [ ]
      enabled: true
      sound: BLOCK_LEVER_CLICK
    confirm-agree-tinkerer:
      enable: false
      type: STAINED_GLASS_PANE
      id: 5
      name: "&aClick to confirm the transaction"
      lore: [ ]
```

**2. Just left buttom confirmation works (GUI)**
The right confirmation buttom (item) doens't work and is only possible to use the left one.

**3. I can't remove the middle glass pane in GUI**
I can't change the item in the middle, don't matter what I put on config.

### How to reproduce

**Problem 1:**
Try to set "enabled" to false and see don't make any change.

**Problem 2:**
Do /tinkerer, add some items and try to confirm the trade using the right item confirmation. Doesn't work.
![image](https://user-images.githubusercontent.com/66658478/157694420-8cd3975f-74cc-4d02-99da-ab317b9263ad.png)

**Problem 3:**
Try to change to another item besides glass pane and will not change anything. I tried:
```
    placeholder-items:
      type: PAPER
      id: 0
      name: " "
      lore: [ ]
```
and
```
    placeholder-items:
      type: PAPER
      name: " "
      lore: [ ]
```

### "/ae plinfo" link

https://paste.md-5.net/ayelozivof
