### ISSUE TITLE
SET_BLOCK not working properly

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#2679]
### Describe the bug

The effect SET_BLOCK just work with one block. If you you that configuration doesn't work:
```
  type: 'MINING'
  group: 'RARO'
  applies:
    - ALL_SHOVEL
    1:
      chance: 100
      effects:
        - 'SET_BLOCK:FARMLAND:3:3:3'
```
   
But that does:
```
  type: 'MINING'
  group: 'RARO'
  applies:
    - ALL_SHOVEL
    1:
      chance: 100
      effects:
        - 'SET_BLOCK:FARMLAND'
```

I was to create a enchant to hoe dirt in a area. But I only can change one block.
Also, would be great to this enchant work with RIGHT_CLICK too.

### How to reproduce

Try to create a enchant with SET_BLOCK using a number, examples:
```
  type: 'MINING'
  group: 'RARO'
  applies:
    - ALL_SHOVEL
    1:
      chance: 100
      effects:
        - 'SET_BLOCK:FARMLAND:3' #in that case it still works but only applies on broken block
```
```
  type: 'MINING'
  group: 'RARO'
  applies:
    - ALL_SHOVEL
  levels:
    1:
      chance: 100
      effects:
        - 'SET_BLOCK:FARMLAND:3:3'
```
```
  type: 'MINING'
  group: 'RARO'
  applies:
    - ALL_SHOVEL
    1:
      chance: 100
      effects:
        - 'SET_BLOCK:FARMLAND:3:3:3'
```
```
  type: 'MINING'
  group: 'RARO'
  applies:
    - ALL_SHOVEL
    1:
      chance: 100
      effects:
        - 'SET_BLOCK:FARMLAND:3:1:3'
```

### "/ae plinfo" link

https://paste.md-5.net/udazalonef
