### ISSUE TITLE
DISABLE_KNOCKBACK incompatibility with OldCombatMechanics plugin

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#2680]
### Describe the bug

As OldCombatMechanics forces the player to knockback, the enchantment type DISABLE_KNOCKBACK doesn't work.
If I disable the plugin, that enchantment works properly but if I'm using it, it don't.

What should be done in this case, if I need the OldCombatMechanics plugin?

### How to reproduce

1. Install AdvancedEnchantments and OldCombatMechanics ;
2. Create a enchantment with disable knockback;
```
antikb:
  display: '%group-color%Anti kb'
  description: "test"
  applies-to: 'Armas'
  type: 'ATTACK'
  group: 'SIMPLE'
  applies:
    - 'ALL_SWORD'
    - 'ALL_AXE'
    - 'TRIDENT'
  levels:
    1:
      chance: 100
      cooldown: 10
      effects:
        - 'DISABLE_KNOCKBACK:80 %victim%'
        - 'ACTIONBAR:&3test %attacker%'
```
3. Try to activate it.

### "/ae plinfo" link

https://paste.md-5.net/udazalonef
