### ISSUE TITLE
DEFENSE_BOW type isn't working in the latest version

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#2681]
### Describe the bug

DEFENSE_BOW is not activating the enchantment. Don't know if is a external reason.

### How to reproduce

1. Create a enchantmente with DEFENSE_BOW type;
```
test:
  display: '%group-color%Test'
  description: "Test"
  applies-to: 'Armaduras'
  type: 'DEFENSE_BOW'
  group: 'SIMPLE'
  applies:
    - ALL_ARMOR
  levels:
    1:
      effects:
        - 'MESSAGE:&ctest %victim%'
```
2. Use a player to test it;
3. Try to active the enchantment using the player.

### "/ae plinfo" link

https://paste.md-5.net/opebitokom
