### ISSUE TITLE
STEAL_GUARD effect is not working

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#2682]
### Describe the bug

Sorry about a lot of issues reported past hours, server admins and I test almost everything on the plugin this week.

STEAL_GUARD effect is not working. We try many sources and many different ways. Like adding %victin%, %attacker%, removing all, etc...

Please try it.

### How to reproduce

1. Create a enchantment with STEAL_GUARD effect, like this one:
```
brainwashed :
  display: '%group-color%Brain Washed '
  description: "test"
  applies-to: 'Arcos'
  type: 'ATTACK_MOB'
  group: 'SIMPLE'
  applies:
    - BOW
    - CROSSBOW
  levels:
    1:
      chance: 100
      cooldown: 5
      effects:
        - 'STEAL_GUARD'
        - 'MESSAGE:&3test! %attacker%'
```
2. Create a enchantment with GUARD effect, like this one:
```
spirits:
  display: "%group-color%Spirits"
  description: "Chance to spawn guard blazes."
  applies-to: "Armor"
  type: "DEFENSE"
  group: "ULTIMATE"
  applies:
    - ALL_ARMOR
  levels:
    1:
      chance: 2
      cooldown: 8
      effects:
        - "GUARD:BLAZE:8:3:%victim%"
```
3. Fight until the Spirits enchantment is activated. Then, use the Brainwashed to steal it. No matter how many times we do, the guard won't be stolen. Yes, we pulled the entire bow.

### "/ae plinfo" link

https://paste.md-5.net/opebitokom
