### ISSUE TITLE
Custom model data doesn't work for the exchange items from the tinkerer

### ISSUE THREAD

**Issue by PeterMa9621** [GC-spigot/AdvancedEnchantments#2688]
### Describe the bug

The custom model data doesn't work for the exchange items from the tinkerer.
Below is my configuration of the exchange items in tinkerer.yml
```
items:
  money:
    type: PAPER
    id: 0
    customModelData: 100    # not working
    custom-model-data: 100  # not working
    name: "&cMoney Voucher &7(%amount%)"
    lore:
      - "&cReceived from &fEnchanter"
      - "&cReceived by &f%name%"
  exp:
    type: EXP_BOTTLE
    id: 0
    customModelData: 100    # not working
    custom-model-data: 100  # not working
    name: "&a&lExperience Bottle &7(throw)"
    lore:
      - "&dValue &f%amount% XP"
      - "&dEnchanter &fServer Enchanter"
```

### How to reproduce

1. Use the config I provided above
2. Open tinkerer inventory, try to exchange enchanted item
3. The exchanged item (money, exp) doesn't have custom model data

### "/ae plinfo" link

https://paste.md-5.net/eyiyilowep
