### ISSUE TITLE
Enchantment Conditions - PAPI KingdomsX placeholder

### ISSUE THREAD

**Issue by ProfessionalBoatDrifter** [GC-spigot/AdvancedEnchantments#2699]
### Describe the bug

Using Kingdoms placeholders returns with an error and does not execute the effect.
This happens whether you use Kingdom's own placeholder, or as described here: https://ae.advancedplugins.net/enchantments/enchantment-conditions/variables#placeholderapi-support

This may be due to KingdomsX implementing it internally in their plugin as stated here: https://github.com/CryptoMorin/KingdomsX/wiki/Placeholders#placeholders-modifiers **in the paragraph immediately above the #placeholder-modifiers link**.

PlaceholderAPI's section: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#kingdomsx

I wasn't sure if it's an issue that AE has to resolve or if KingdomsX has to make a change. Since AE is the plugin which checks the condition, I figured this was the right choice.

Enchantment config:
```
veinminer:
  display: "%group-color%Vein Miner"
  # description: "\n&eUnique &fenchantment.\n\n&fInstantly mine ore veins.\n\n&e1s cooldown\n&dSouls needed&f: &d2\n\n&fTier: &eUnique"
  description: "\n&eUnique &fenchantment.\n\n&fInstantly mine ore veins.\n\n&e1s cooldown\n&2Resource Points&f: 3\n\n&fTier: &eUnique"
  applies-to: "Pickaxes"
  group: "UNIQUE"
  settings:
    newVersionsOnly: true # Only load this enchantment if server version is 1.13 or higher
  type: "MINING"
  applies:
    - "ALL_PICKAXE"
  levels:
    "1":
      #chance: 15
      # souls: 2
      cooldown: 1
      # condition: "%block type% contains ORE : %allow%" # Soul cost
      # condition: "%block type% contains ORE && %player kingdoms_resource_point% >= 3 : %allow%" # Test 1
      condition: "%block type% contains ORE && %kingdoms_resource_point% >= 3 : %allow%" # Test 2
      effects:
        - "VEIN_MINE"
        - "CONSOLE_COMMAND:k admin resourcepoints %player kingdoms_name% remove 3"
```

### How to reproduce

1. Enchant an item using the config posted in "Describe the bug".
2. Break an ore.
3. Error message and no "VEIN_MINE" effect.

### Screenshots / Videos

In-game error message:
![ae-placeholder-condition](https://user-images.githubusercontent.com/16565567/159135104-28f4c1f6-7b74-46c4-833f-1d461b737183.PNG)

### "/ae plinfo" link

https://paste.md-5.net/etupayesej
