### ISSUE TITLE
High Damage Outputs multiply kills

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#2739]
### Describe the bug

Whenever you kill a player with a CE that has high damage output, they die multiple times in a single blow.

NOTE: It happens in my main server, but I also tested in my local server with only AE, Factions, DM, Anti cooldown plugin and it still works.

### How to reproduce

Create a CE with high damage output and kill them with it, they die multiple times. It mostly happens if they die within the proc of the high CE damage output.
here are test CE's I made, this CE is in my server but ofc there's a CD, but in this, there's no CD to check out the bug:
```
planetarystrike:
  display: '%group-color%Planetary Strike'
  description: "A chance to smite and slow your opponent\nand deal a burst of damage.\nRequires: Thundering Blow IV."
  applies-to: 'Weapons'
  type: 'ATTACK'
  group: 'PLANETARY'
  applies:
    - ALL_SWORD
    - ALL_AXE
  settings:
    required-enchants:
      - 'thunderingblow:4'
    removed-enchants:
      - 'thunderingblow'
  levels:
    1:
      effects:
        - 'CURE:SPEED %victim%'
        - 'LIGHTNING %victim%'
        - 'EXTINGUISH %victim%'
        - 'MESSAGE:&8&l** PLANETARY STRIKE **'
        - 'ADD_HARM:60 %victim%'
        - 'POTION:SLOW:2:200 %victim%'
        - 'POTION:SLOW_DIGGING:2:200 %victim%'
```

### Screenshots / Videos
I can also send my enchantments.yml file to you in private for you to see my CEs.
Local Server:
https://www.youtube.com/watch?v=OVwHyY2Wefk\
Main Server(With kill counter on scoreboard):
https://www.youtube.com/watch?v=wb_pJ3G_zRM&feature=youtu.be

### "/ae plinfo" link

https://paste.md-5.net/nudipanose

### Server Log

https://mcpaste.io/11b5bd941aaf0cff
