### ISSUE TITLE
WAIT and HARM bug again

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#2742]
### Describe the bug

Harm and Wait bug again
The thing is, why does it work on divine damnation and on rupture it does not?

### How to reproduce

Here are my CEs used in the video, and reproduce the things i did on the video.
Rupture:
```
rupture:
  display: '%group-color%Rupture'
  description: "Bleeds, weakens removes regen from your opponent, after the bleed duration\nthere will be a slight burst of damage\nRequires: Deep Bleed VI."
  applies-to: 'Swords'
  group: 'PLANETARY'
  type: 'ATTACK'
  applies:
    - ALL_SWORD
  settings:
    required-enchants:
      - 'deepbleed:6'
    removed-enchants:
      - 'deepbleed'
  levels:
    '1':
      effects:
        - 'CURE:REGENERATION %victim%'
        - 'POTION:WEAKNESS:0:100 %victim%'
        - 'MESSAGE:&4&l** RUPTURE ** %attacker%'
        - 'MESSAGE:&4&l** RUPTURED ** %victim%'
        - 'PLAY_SOUND_OUTLOUD:ENTITY_STRIDER_DEATH'    
        - 'ADD_HARM:<random number>3-6</random number> %victim%'
        - 'WAIT:10'
        - 'ADD_HARM:<random number>3-6</random number> %victim%'
        - 'WAIT:10'
        - 'ADD_HARM:<random number>3-6</random number> %victim%'
        - 'WAIT:10'
        - 'ADD_HARM:<random number>3-6</random number> %victim%'
        - 'WAIT:10'
        - 'ADD_HARM:<random number>3-6</random number> %victim%'
        - 'WAIT:10'
        - 'ADD_HARM:<random number>3-6</random number> %victim%'
        - 'WAIT:10'
        - 'ADD_HARM:<random number>3-6</random number> %victim%'
        - 'WAIT:10'
        - 'ADD_HARM:<random number>3-6</random number> %victim%'
        - 'WAIT:10'
        - 'ADD_HARM:<random number>3-6</random number> %victim%'
        - 'WAIT:10'
        - 'ADD_HARM:<random number>3-6</random number> %victim%'
        - 'WAIT:10'
        - 'ADD_HARM:<random number>3-6</random number> %victim%'
        - 'WAIT:10'
        - 'ADD_HARM:30 %victim%'
```
Divine Damnation:
```
divinedamnation:
  display: '%group-color%Divine Damnation'
  description: "&fStuns and removes resistance from your opponent.\n&fthey will also receive a burst of damage after the removal of resistance."
  applies-to: 'Sword'
  type: 'ATTACK'
  group: 'GODLY'
  applies:
    - ALL_SWORD
  levels:
    1:
      effects:
        - 'CURE:RESISTANCE %victim%'
        - 'POTION:SLOW:40:100 %victim%'
        - 'WAIT:40'
        - 'PLAY_SOUND:ENTITY_ILLUSIONER_PREPARE_MIRROR'
        - 'PLAY_SOUND:ENTITY_ILLUSIONER_PREPARE_MIRROR %victim%'
        - 'MESSAGE:&2&l** &2&lDIVINE DAMNATION &2&l** %attacker%'
        - 'MESSAGE:&2&l** &2&lDAMNED &2&l** %victim%'
        - 'ADD_HARM:40 %victim%'
```

### Screenshots / Videos

https://www.youtube.com/watch?v=ZY12WpBWAFg&feature=youtu.be

### "/ae plinfo" link

https://paste.md-5.net/ekabiqiyoz

### Server Log

https://mcpaste.io/a5c492fc24161d8e
