### ISSUE TITLE
FREEZE enchantment not working

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#2745]
### Describe the bug

The FREEZE type enchantment is not working. Nothing happens when activated. 

### How to reproduce

Create a enchantment using FREEZE type, like this one:

```
test:
  display: '%group-color%test'
  description: "test"
  applies-to: 'Machados'
  type: 'ATTACK'
  group: 'SIMPLE'
  applies:
    - 'ALL_AXE'
  levels:
    1:
      cooldown: 30
      chance: 100
      effects:
        - 'FREEZE:120 %victim%'
```

### "/ae plinfo" link

https://paste.md-5.net/dorabewive
