### ISSUE TITLE
ITEM_BREAK doesn't work

### ISSUE THREAD

**Issue by poityTMK** [GC-spigot/AdvancedEnchantments#2770]
### Describe the bug

I created an enchant with the ITEM_BREAK type but every time it should activate nothing happens, I thought it was a problem of the effects but changing the type of spell the effects work correctly

### How to reproduce

to reproduce the problem just apply an enchant with type ITEM_BREAK to an item

### "/ae plinfo" link

https://paste.md-5.net/fuqogociqi

**Comment by Burchard36** [comment]
Can you provide us with the enchantment you are using, please? We need to know a little more information 

I tried this enchantment, and it works for me:

```yaml
ohnoitbroke:
  display: "%group-color%Dont break me"
  description: "I do things when i broke"
  applies-to: "Items"
  type: "ITEM_BREAK"
  group: "UNIQUE"
  applies:
    - ALL_ARMOR
    - ALL_SWORD
    - ALL_TOOL
    - ALL_PICKAXE
    - ALL_SHOVEL
    - ALL_AXE
    - ALL_HOE
  levels:
    1:
      effects:
        - "POTION:RESISTANCE:1:300"
 ```
 

https://user-images.githubusercontent.com/48583030/165003083-2208ae32-3107-4362-b7d4-73a6089e482e.mp4
