### ISSUE TITLE
Wrong indentation in lores and messages chats 

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#2779]
### Describe the bug

When I create a enchantment, I break lines for a better lore. So I do:

```
destruicaoplanetaria:
  display: '%group-color%Destruição Planetária'
  description: " Inimigos que atingirem o portador\n estão sujeitos a convocarem a\n destruição. Ela destrói todos os\n efeitos positivos de todos os\n inimigos em uma área de 1.600\n blocos.\n"
```

And, the plugin for itself break the lines automatically in messages from this enchantments, for example:
1. /enchants
2. Right click helding a enchanted book

### How to reproduce

Create this enchantment, or use any with a long lore:

Then check that enchantment on /enchants gui:
![image](https://user-images.githubusercontent.com/66658478/165119075-e1532b6d-615b-4986-83ca-1d3d12e4c396.png)

And check the enchantment description in chat with right click:
![image](https://user-images.githubusercontent.com/66658478/165117646-c4fcf492-153e-4d79-b731-50c32a1d3d04.png)

### Screenshots / Videos

Obs.: That's the my configuration for item lore in /enchants
```
    item:
      type: ENCHANTED_BOOK
      id: 0
      custom-model-data: 0
      force-glow: false
      # What command should be ran when player clicks on one of the enchantments?
      # %max-lvl% - Displays max. level in numbers, %max-lvl-roman% - displays max. level in roman numerals
      command: ""
      name: '&r%ench-colors%'
      lore:
        - "&e%desc%"
        - "&b» &fAplicação: &7%applies-to%"
        - "&b» &fNível máximo: &7%max-lvl%"
```

### "/ae plinfo" link

https://paste.md-5.net/uhovitinis.css
