### ISSUE TITLE
Armorsets problem

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#2790]
### Describe the bug

About Variables:
Variables dont work whatever you put may it be defense / aoe or attacker, they only work if you remove the variable but returns to the attacker/victim depends if your effect is DEFENSE or ATTACK so something like ATTACK: ADD_HARM:50 %victim% won't work, returns null / no effects, only ADD_HARM:50 will work, but will proc it to attacker instead.

About Shift:
SHIFT effect is also bugged, gives permanent potion effects even though i put ticks on potion effect and it seems to run twice as shown in the video below since the 'MESSAGE' shows up twice.

### How to reproduce

Armor set effect code:
SHIFT ONE:
```
SHIFT:
    cooldown: 3
    effects:
      - 'POTION:RESISTANCE:2:120'
      - 'POTION:STRENGTH:3:120'
      - 'WAIT:60'
      - "MESSAGE:&c&lGOD'S STRENGTH: &aGod Strength is now up!"
```

VARIABLE ONE:
```
ATTACK:
    chance: 100
    effects:
      - 'INCREASE_DAMAGE:10'
      - 'ADD_HARM:500 %victim%'
```

### Screenshots / Videos

https://streamable.com/uqmrpj

### "/ae plinfo" link

https://paste.md-5.net/iqoponizik

### Server Log

https://mcpaste.io/957a91250e28f502
