### ISSUE TITLE
compatibility problem with MythicMobs on kill-mobs

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#2797]
### Describe the bug

All kill_mob enchants cannot work and show error when mob is killed

Mythicmobs 5.0.0 + version changed their API, this will broke all plugins that uses old APIs

### How to reproduce

1. install mythicmobs 5.0.3 (latest)
2. use enchantments with kill mob, demo below
```
test:
  display: "%group-color%test"
  description: "do something after kill a mob"
  applies-to: "Swords"
  type: "KILL_MOB"
  group: "FABLED"
  applies:
    - ALL_SWORD
  levels:
    1:
      effects:
        - "MORE_DROPS:1"
        - "MESSAGE:&cactivated"
```
3. kill a mob
4. 

### Screenshots / Videos

error:

![image](https://user-images.githubusercontent.com/61608872/166442644-78451615-eb72-42eb-b2de-f9965bedccea.png)

### "/ae plinfo" link

https://paste.md-5.net/kinohemosu

### Server Log

https://mcpaste.io/6f5f0dd8f5943eab
