### ISSUE TITLE
Older clients bug with effects

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#2798]
### Describe the bug

Unlimited potion effect for older clients, so far i tested with 1.16+ this bug does not happen

So to be frank, main source of this bug is from Static effect CE

Video shows:
1.17.1 on left 1.12.2 on right,
EDIT: also happens with 1.8.9 ( Tested )

### How to reproduce

Create a custom weapon with right-click event, make potion effects last like 5 seconds also make sure you're wearing a static CE, you will know once you see the video.

CEs used:
```
  type: 'EFFECT_STATIC'
  group: 'PLANETARY'
  applies:
    - ALL_ARMOR
  levels:
    1:
      effects:
        - 'POTION:STRENGTH:0'
    2:
      effects:
        - 'POTION:STRENGTH:1'
```

Custom Sword Effect:
```
events:
  RIGHT_CLICK:
    cooldown: 10
    effects:
      - 'POTION:STRENGTH:2:120'
      - 'POTION:RESISTANCE:2:120'
      - 'PLAY_SOUND_OUTLOUD:ENTITY_ENDER_DRAGON_GROWL'
      - "MESSAGE:&c&l** GOD'S STRENGTH **"
      - 'WAIT:200'
      - "MESSAGE:&cGod's Strength is now ready!"
```

### Screenshots / Videos

https://streamable.com/maq032

### "/ae plinfo" link

https://paste.md-5.net/zebupujuka

### Server Log

https://mcpaste.io/49a931a627033cdd
