### ISSUE TITLE
Enabling drag and drop upgrades (solution in description)

### ISSUE THREAD

**Issue by Joeychuwu** [GC-spigot/AdvancedEnchantments#2827]
### Describe the bug

drag and drop upgrading enchantments doesn't work with upgrade set to true like this

```
combining:
  enabled: true
  chances:
    # If true, Success and Destroy chances will effect combining
    use-chances: true
    # If true, item will break (if Protection is added, protection will be removed).
    break-item: false
    # If higher level of enchantment already on item is applied, should the enchantment upgrade?
    upgrade: true
```

it has to be set to yes (and i believe use_chances have to be set to true as well) so it looks like this in the config.yml

```
combining:
  enabled: true
  chances:
    # If true, Success and Destroy chances will effect combining
    use-chances: true
    # If true, item will break (if Protection is added, protection will be removed).
    break-item: false
    # If higher level of enchantment already on item is applied, should the enchantment upgrade?
    upgrade: yes
```

### How to reproduce

described above

### "/ae plinfo" link

https://paste.md-5.net/sanuhitoqe
