### ISSUE TITLE
player die with pumpkin effect will drop helmet 

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#2832]
### Describe the bug

when a player attack another player and the victim die with pumpkin effect, the victim's helmet will drop off, attacker can use this method to steal other people's helmett

### How to reproduce

1. have pumpkin enchantment
```
pumpkin:
  display: "%group-color%pumpkin"
  description: "pumpkin helmet player"
  applies-to: "Weapons"
  type: "ATTACK"
  group: "FABLED"
  applies:
    - ALL_SWORD
    - ALL_AXE
  levels:
    1:
      effects:
        - "PUMPKIN:40 %victim%"
        - "PLAY_SOUND_OUTLOUD:BLOCK_ANVIL_LAND"
        - "MESSAGE:&c[&6米&e奈&2β&a] &factivated"
```
2. kill a player

### Screenshots / Videos

https://www.youtube.com/watch?v=9o_uZdbNg1E

### "/ae plinfo" link

https://paste.md-5.net/cojefucume

### Server Log

https://paste.denizenscript.com/View/96518
