### ISSUE TITLE
Static Effect in 1.8

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#2849]
### Describe the bug

Static potion effect in 1,8 cannot be replaced by any potion level even when the potion level is higher than the static effect.

### How to reproduce

Create a static effect and try to create a CE that has a higher potion level on proc, it will not work on 1.8 but it will on like 1.16+

EX:
Static:
```
  type: 'EFFECT_STATIC'
  applies:
    - ALL_ARMOR
  levels:
    1:
      effects:
        - 'POTION:SPEED:1'
```

The higher potion level effect enchantment:
```
  type: 'DEFENSE'
  applies:
    - ALL_CHESTPLATE
  settings:
    removeable: false
  levels:
    '1':
      cooldown: 10
      effects:
        - 'CURE:SLOW %victim%'
        - 'POTION:SPEED:9:40 %victim%'
```

### Screenshots / Videos

-

### "/ae plinfo" link

https://paste.md-5.net/iwadinokas

### Server Log

https://mcpaste.io/c330e7d695508f76
