### ISSUE TITLE
ADD_DURABILITY repairs other armor pieces even if they don't have the enchant

### ISSUE THREAD

**Issue by xlsalvolx** [GC-spigot/AdvancedEnchantments#2881]
### Describe the bug

the ADD_DURABILITY effect will repair other armor pieces even if they don't have the enchant, you just need to have the enchant on one armor piece, wear it and it will repair other pieces too

### How to reproduce

1. Use this enchant
```
rejuvination:
  display: "%group-color%Rejuvination"
  description: "Repairs armor on attack or when you get damaged"
  applies-to: "armors"
  type: "DEFENSE;DEFENSE_MOB;ATTACK;ATTACK_MOB"
  group: "ENCHANT"
  applies:
    - ALL_ARMOR
  levels:
    1:
      chance: 8
      effects:
        - "ADD_DURABILITY:-1"
    2:
      chance: 10
      effects:
        - "ADD_DURABILITY:-2"
    3:
      chance: 12
      effects:
        - "ADD_DURABILITY:-3"
```
2. Apply the enchant to a random armor piece
3. Wear the armor piece with the enchant and other armor pieces without enchants
4. Consume some durability of all 4 armor pieces
5. Try to trigger the enchant attacking a mob
6. You can see all 4 armor pieces will get repaired

### "/ae plinfo" link

https://paste.md-5.net/mewucudoce
