### ISSUE TITLE
Keep_on_death absorption/duplication bug

### ISSUE THREAD

**Issue by xlsalvolx** [GC-spigot/AdvancedEnchantments#2882]
### Describe the bug

The keep_on_death effect will trigger on weapons even if the player is still alive but at 0 red health and has yellow hearts from the absorption potion effect. This will make the item disappear from your inventory forever until you die. After you die, the item will reappear.

The bug has a side effect: if you also happen to have an armor item with soulbound on it after you triggered the disappearing of the weapon, the armor will randomly duplicate on death. This is NOT caused by absorption, but by dying from the raw damage. You just need to die by raw damage to trigger the armor piece duplication, but the bug is easier to trigger if you are also using absorption.

### How to reproduce

1. Give yourself the absorption potion effect
2. Apply this enchant to a weapon and a head item/armor item and wear it:
```
soulboundtest:
  display: "%group-color%Soulbound test"
  description: "You keep the item on death"
  applies-to: "Anything"
  type: "DEATH;PASSIVE_DEATH"
  group: "SOULBOUND"
  applies:
    - PLAYER_HEAD
    - ALL_TOOLS
    - ALL_SWORD
    - ALL_AXE
    - ALL_ARMOR
    - BOW
    - CROSSBOW
    - TRIDENT
  levels:
    1:
      chance: 100
      cooldown: 0
      effects:
        - "KEEP_ON_DEATH"
```
3. Damage yourself removing red hearts only (you can do this using the rawdamage some plugins can do, like mythicmobs)
4. Keep doing it until your weapon disappears
5. Kill yourself
6. You will respawn with a lot more duped armor items and the weapon back

### Screenshots / Videos

I understand this is a very weird bug so i made a video:

https://www.youtube.com/watch?v=1Gf2SBuLQlc

Keep in mind this bug is much more common than you may think, a lot of stuff in various plugins does raw damage (for example in my server there are hundreds of mythicmobs doing raw damage ignoring yellow hearts and targeting red hearts) triggering the bug and the duplication.

Note: i tested the bug with a head item in the video, but the duplication occurs on any armor enchanted with soulbound too.

### "/ae plinfo" link

https://paste.md-5.net/ejuxuqeqek
