### ISSUE TITLE
Extra damage is acting like Add_harm

### ISSUE THREAD

**Issue by SoraShiunin** [GC-spigot/AdvancedEnchantments#2900]
### Describe the bug

Extra _damage isn't being reduced by any reduction. Its acting exactly like Add_harm.
It came to my attention that players were suddenly oneshotting armored mobs and found this to be the reason.
Not even STOP_ATTACK stops the damage. 
Enchant used on video:
```
testenchant:
  display: '&4Test Damage'
  description: ""
  applies-to: 'Bows'
  type: 'BOW;BOW_MOB'
  group: 'UNIQUE'
  applies:
    - ALL_BOW
    - ALL_CROSSBOW
  levels:
    1:
      effects:
        - 'EXTRA_DAMAGE:10 %victim%'
```

### How to reproduce

Use Extra Damage type enchant. 

### Screenshots / Videos

https://youtu.be/vz3vk3-jVHA

### "/ae plinfo" link

https://paste.md-5.net/suruleqala

### Server Log

Necessary?
