### ISSUE TITLE
CATCH_FISH does not work when fishing rod is in offhand

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#2919]
### Describe the bug

CATCH_FISH does not work when fishing rod is in offhand

### How to reproduce

```
anglersinsight:
  display: '%group-color%Angler''s Insight'
  description: 'Chance to get experience from fishing.'
  applies-to: 'Fishing Rods'
  type: 'CATCH_FISH'
  group: 'COMMON'
  applies:
  - FISHING_ROD
  levels:
    1:
      chance: 20
      effects:
      - 'EXP:<random number>2-5</random number>'
    2:
      chance: 20
      effects:
      - 'EXP:<random number>5-9</random number>'
    3:
      chance: 20
      effects:
      - 'EXP:<random number>8-13</random number>'
    4:
      chance: 20
      effects:
      - 'EXP:<random number>12-16</random number>'
    5:
      chance: 100
      effects:
      - 'EXP:<random number>15-20</random number>'
```

Use level 5 of this enchant. Fish with the fishing rod in your offhand. Get no experience.

### "/ae plinfo" link

https://paste.md-5.net/foqomugula
