### ISSUE TITLE
PULL_AWAY effect does not work with SHIELD_BLOCK type

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#2924]
### Describe the bug

PULL_AWAY effect does not work with SHIELD_BLOCK type

### How to reproduce

```
repel:
  display: '%group-color%Repel'
  description: "Chance to repel your attacker when attacked."
  applies-to: 'Shields'
  type: 'SHIELD_BLOCK'
  group: 'EPIC'
  applies:
  - SHIELD
  levels:
    1:
      chance: 20
      cooldown: 5
      effects:
      - 'PULL_AWAY:2.0 %attacker%'
      - 'ADD_DURABILITY_CURRENT_ITEM:5'
      - 'ACTIONBAR:&d&lRepel %victim%'
    2:
      chance: 20
      cooldown: 5
      effects:
      - 'PULL_AWAY:2.5 %attacker%'
      - 'ADD_DURABILITY_CURRENT_ITEM:5'
      - 'ACTIONBAR:&d&lRepel %victim%'
    3:
      chance: 20
      cooldown: 5
      effects:
      - 'PULL_AWAY:3.0 %attacker%'
      - 'ADD_DURABILITY_CURRENT_ITEM:5'
      - 'ACTIONBAR:&d&lRepel %victim%'
    4:
      chance: 20
      cooldown: 5
      effects:
      - 'PULL_AWAY:3.5 %attacker%'
      - 'ADD_DURABILITY_CURRENT_ITEM:5'
      - 'ACTIONBAR:&d&lRepel %victim%'
    5:
      chance: 20
      cooldown: 5
      effects:
      - 'PULL_AWAY:4.0 %attacker%'
      - 'ADD_DURABILITY_CURRENT_ITEM:5'
      - 'ACTIONBAR:&d&lRepel %victim%'
```

Test this enchantment

### "/ae plinfo" link

https://paste.md-5.net/avepakapoj
