### ISSUE TITLE
Soulbound items will disappear if you are at 0 red health but you still have yellow hearts

### ISSUE THREAD

**Issue by xlsalvolx** [GC-spigot/AdvancedEnchantments#2933]
### Describe the bug

Items will still disappear if you get to get at 0 red health but you still have absorption yellow hearts

### How to reproduce

1. Enchant some items with soulbound:
```
soulbound:
  display: "%group-color%Soulbound"
  description: "Keep items on death"
  applies-to: "any weapon or armor"
  type: "DEATH;PASSIVE_DEATH"
  group: "SOULBOUND"
  applies:
    - PLAYER_HEAD
    - ALL_TOOLS
    - ALL_SWORD
    - ALL_AXE
    - ALL_ARMOR
    - BOW
    - CROSSBOW
    - TRIDENT
  levels:
   1:
      chance: 100
      effects:
        - "KEEP_ON_DEATH"
```
2. Get yourself at 0 red health
3. Items will disappear even if you are still alive
4. Kill youself to get the items back

Many external plugins can do this special kind of damage, rendering the enchant very unusable.
You can reproduce this issue by installing the mythicmobs plugin and inserting this custom mob i made for you to test this issue:
```
example:
  Mobtype: husk
  Display: 'Example'
  Health: 200
  Damage: 0
  DamageModifiers:
  - DROWNING 0
  Options:
    FollowRange: 50
    AlwaysShowName: false
    MovementSpeed: 0.2
    PreventOtherDrops: true
    Despawn: true
    Silent: false
    PreventItemPickup: true
    PreventSunburn: true
  Skills:
  - removeowner @self ~onSpawn
  - damage{a=10;i=true} @PIR{r=10} ~onTimer:20
```
This mob will damage any players in range of 10 block bypassing the yellow hearts.
You can install it adding it as a .txt file in the "mobs" folder in the mythicmobs folder once you install the plugin.

### Screenshots / Videos

https://www.youtube.com/watch?v=TGyYqScz6N8

### "/ae plinfo" link

https://paste.md-5.net/uyefozusam
