### ISSUE TITLE
Soulbound will DELETE any armor you are wearing without the soulbound enchant if you die with a soulbound enchanted item

### ISSUE THREAD

**Issue by xlsalvolx** [GC-spigot/AdvancedEnchantments#2934]
### Describe the bug

If you have an item with the soulbound enchant in your inventory and you die while wearing any armor that doesn't have the soulbound enchant, the armor will get deleted.

### How to reproduce

1. Enchant an item with soulbound: 
```
soulbound:
  display: "%group-color%Soulbound"
  description: "Keep items on death"
  applies-to: "any weapon or armor"
  type: "DEATH;PASSIVE_DEATH"
  group: "SOULBOUND"
  applies:
    - PLAYER_HEAD
    - ALL_TOOLS
    - ALL_SWORD
    - ALL_AXE
    - ALL_ARMOR
    - BOW
    - CROSSBOW
    - TRIDENT
  levels:
   1:
      chance: 100
      effects:
        - "KEEP_ON_DEATH"
```
2. Wear any kind of armor
3. Die
4. The armor is gone

### Screenshots / Videos

https://www.youtube.com/watch?v=O_tcoH9NvEg

### "/ae plinfo" link

https://paste.md-5.net/iricisokal
