### ISSUE TITLE
Duplication Bug: Activating a SHIELD_BLOCK enchantment in your offhand will duplicate the item in your main hand

### ISSUE THREAD

**Issue by WhatsTheBadNews** [GC-spigot/AdvancedEnchantments#2935]
### Describe the bug

If you hold a shield and another item at the same time, when the shield activates in your offhand, it will duplicate the item in your main hand.

### How to reproduce

1. Add the following enchantment and put it on a shield
```
reflect:
  display: '%group-color%Reflect'
  description: "Chance to reflect partial damage back at the attacker."
  applies-to: 'Shields'
  type: 'SHIELD_BLOCK'
  group: 'LEGENDARY'
  applies:
  - SHIELD
  levels:
    1:
      chance: 100
      cooldown: 5
      effects:
        - 'ADD_HARM:<math>%raw damage%*0.3</math> %attacker%'
        - 'ADD_DURABILITY_CURRENT_ITEM:10'
        - 'ACTIONBAR:&6&lReflect %victim%'
    2:
      chance: 100
      cooldown: 5
      effects:
        - 'ADD_HARM:<math>%raw damage%*0.4</math> %attacker%'
        - 'ADD_DURABILITY_CURRENT_ITEM:10'
        - 'ACTIONBAR:&6&lReflect %victim%'
    3:
      chance: 100
      cooldown: 5
      effects:
        - 'ADD_HARM:<math>%raw damage%*0.5</math> %attacker%'
        - 'ADD_DURABILITY_CURRENT_ITEM:10'
        - 'ACTIONBAR:&6&lReflect %victim%'
    4:
      chance: 100
      cooldown: 5
      effects:
        - 'ADD_HARM:<math>%raw damage%*0.6</math> %attacker%'
        - 'ADD_DURABILITY_CURRENT_ITEM:10'
        - 'ACTIONBAR:&6&lReflect %victim%'
    5:
      chance: 100
      cooldown: 5
      effects:
        - 'ADD_HARM:<math>%raw damage%*0.7</math> %attacker%'
        - 'ADD_DURABILITY_CURRENT_ITEM:10'
        - 'ACTIONBAR:&6&lReflect %victim%'
```
2. Put the shield in your offhand and another item in your main hand
3. Block with the shield
4. Whichever item you were holding in your main hand will be duplicated and replace the shield

### "/ae plinfo" link

https://paste.md-5.net/jojayunipu
