### ISSUE TITLE
Another soulbound duplication bug

### ISSUE THREAD

**Issue by xlsalvolx** [GC-spigot/AdvancedEnchantments#2952]
### Describe the bug

Your items with soulbound will get duplicated if you die from raw damage

### How to reproduce

1. Give yourself soulbound on any item:
```
soulbound:
  display: "%group-color%Soulbound"
  description: "Keep items on death"
  applies-to: "any weapon or armor"
  type: "DEATH;PASSIVE_DEATH"
  group: "SOULBOUND"
  applies:
    - PLAYER_HEAD
    - ALL_TOOLS
    - ALL_SWORD
    - ALL_AXE
    - ALL_ARMOR
    - BOW
    - CROSSBOW
    - TRIDENT
  levels:
   1:
      chance: 100
      effects:
        - "KEEP_ON_DEATH"
```

2. Die from raw damage (like the one from mythicmobs). You can use the exact same mob i provided last time to test this issue.
```
example:
  Mobtype: husk
  Display: 'Example'
  Health: 200
  Damage: 0
  DamageModifiers:
  - DROWNING 0
  Options:
    FollowRange: 50
    AlwaysShowName: false
    MovementSpeed: 0.2
    PreventOtherDrops: true
    Despawn: true
    Silent: false
    PreventItemPickup: true
    PreventSunburn: true
  Skills:
  - removeowner @self ~onSpawn
  - damage{a=10;i=true} @PIR{r=10} ~onTimer:20

```
3. Items will get duplicated on death from the raw damage.

### Screenshots / Videos

https://www.youtube.com/watch?v=gXPwQ7q8Rpg&feature=youtu.be

### "/ae plinfo" link

https://paste.md-5.net/aviqagabox
