### ISSUE TITLE
New soulbound dupe issue

### ISSUE THREAD

**Issue by xlsalvolx** [GC-spigot/AdvancedEnchantments#2963]
### Describe the bug

Items with soulbound will get duped if you get killed by anything doing fast enough raw damage

### How to reproduce

1.  Apply this enchant to anything
```
soulbound:
  display: "%group-color%Soulbound"
  description: "You will keep the items on death"
  applies-to: "anything"
  type: "DEATH;PASSIVE_DEATH"
  group: "SOULBOUND"
  applies:
    - PLAYER_HEAD
    - ALL_TOOLS
    - ALL_SWORD
    - ALL_AXE
    - ALL_ARMOR
    - BOW
    - CROSSBOW
    - TRIDENT
  levels:
    1:
      chance: 100
      effects:
        - "KEEP_ON_DEATH"
```

2. Get killed by a player that is using raw damage, for example a raw damage skill from mythicmobs, i made an item and a skill for you to easily test it out
3. Create a .yml or .txt with this item and apply it into your "items" folder in your mythicmobs folder:
```
testsword:
  Id: netherite_sword
  Display: '&4&ltestsword'
  Lore: 
  - '&5&oTest bruh'
  - '&7&oRight click looking at a player to kill him'
  Skills:
  - skill{s=testdamage} ~onUse
```
 4. Create a .yml or .txt with this skill and apply it into your "skills" folder in your mythicmobs folder:
```
testdamage:
  Skills:
  - damage{a=2;ia=true;preventknockback=true} @target
```
5. Get killed by a player using the skill in the sword while having the soulbound items in your inventory
6. This may take more than one try, but eventually items will get duped

It can be reproduced with mobs too:

```
testboy:
  Mobtype: skeleton
  Display: '&7&l&mXXX&4&lT&c&le&4&ls&c&lt&6&lB&e&lo&6&ly&7&l&mXXX'
  Health: 200
  Damage: 0
  DamageModifiers:
  - DROWNING 0
  Options:
    FollowRange: 50
    AlwaysShowName: false
    MovementSpeed: 0.2
    PreventOtherDrops: true
    Despawn: true
    Silent: false
    PreventItemPickup: true
    PreventSunburn: true
  Skills:
  - removeowner @self ~onSpawn
  - damage{a=2;ia=true;preventknockback=true;repeat=5;repeatInterval=1} @target ~onTimer:5
```

### Screenshots / Videos

https://www.youtube.com/watch?v=mePFG2DnnfE

### "/ae plinfo" link

https://paste.md-5.net/adopuyuwen
