### ISSUE TITLE
Soulbound items disappearing when killed by raw damage

### ISSUE THREAD

**Issue by xlsalvolx** [GC-spigot/AdvancedEnchantments#2964]
### Describe the bug

Soulbound items will now disappear when dying from raw damage

**This only happens if the enchant has a chance and the chance fails**

### How to reproduce

1. Enchant some items with this soulbound enchant with chance 50:
```
soulbound:
  display: "%group-color%Soulbound"
  description: "You may keep the item on death"
  applies-to: "anything"
  type: "DEATH;PASSIVE_DEATH"
  group: "SOULBOUND"
  applies:
    - PLAYER_HEAD
    - ALL_TOOLS
    - ALL_SWORD
    - ALL_AXE
    - ALL_ARMOR
    - BOW
    - CROSSBOW
    - TRIDENT
  levels:
    1:
      chance: 50
      effects:
        - "KEEP_ON_DEATH"
```
2. Die from raw damage while keeping the items in your inventory (no need to equip anything)
You can use this mob from mythicmobs for the raw damage:
```
testboy:
  Mobtype: skeleton
  Display: '&7&l&mXXX&4&lT&c&le&4&ls&c&lt&6&lB&e&lo&6&ly&7&l&mXXX'
  Health: 200
  Damage: 0
  DamageModifiers:
  - DROWNING 0
  Options:
    FollowRange: 50
    AlwaysShowName: false
    MovementSpeed: 0.2
    PreventOtherDrops: true
    Despawn: true
    Silent: false
    PreventItemPickup: true
    PreventSunburn: true
  Skills:
  - damage{a=10;ia=true;preventknockback=true} @target ~onTimer:20
```
3. Some items will disappear when dying to his raw damage. Try again and again and eventually all the items will be gone.

### Screenshots / Videos

https://www.youtube.com/watch?v=vi9MiQhQL4A&feature=youtu.be

### "/ae plinfo" link

https://paste.md-5.net/uzuvosubes
