### ISSUE TITLE
[Bug] Timber gives 1 too little logs

### ISSUE THREAD

**Issue by Folas1337** [GC-spigot/AdvancedEnchantments#2972]
### Describe the bug

When breaking a tree or any construction made of any kind of logs and timer triggers, it drops 1 too little log blocks.
If I am breaking a tree consisting of 6 logs, I'll be left with 5 after chopping it down with timber.

### How to reproduce

- Load a world
- Get an axe
- Ideally apply Timber 3
- Chop down a tree of 6 blocks
- End up with 5 log blocks in the end

### Screenshots / Videos

https://youtu.be/rrIOInVGjm0
(This video was taken on a production server but I was able to reproduce it with the latest version of AE on a test server as well with nothing but AE installed!)

### "/ae plinfo" link

https://paste.md-5.net/betimuwehu

### Server Log

https://mcpaste.io/e7210c9d449606f9

**Comment by Awpmeister2170** [comment]
Hello can you please attach the Enchantment here.

**Comment by Folas1337** [comment]
Like this?
```yaml
trench:
  display: "%group-color%Trench"
  description: "Chance to break in 3x3 area."
  applies-to: "Pickaxes, Shovels"
  type: "MINING"
  group: "ULTIMATE"
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
  levels:
    1:
      chance: 13
      condition:
        - "%player is sneaking% = true : %stop%"
      effects:
        - "TRENCH:3"
    2:
      chance: 26
      condition:
        - "%player is sneaking% = true : %stop%"
      effects:
        - "TRENCH:3"
    3:
      chance: 36
      condition:
        - "%player is sneaking% = true : %stop%"
      effects:
        - "TRENCH:3"
    4:
      chance: 49
      condition:
        - "%player is sneaking% = true : %stop%"
      effects:
        - "TRENCH:3"
    5:
      chance: 59
      condition:
        - "%player is sneaking% = true : %stop%"
      effects:
        - "TRENCH:3"
    6:
      chance: 72
      condition:
        - "%player is sneaking% = true : %stop%"
      effects:
        - "TRENCH:3"
    7:
      chance: 85
      condition:
        - "%player is sneaking% = true : %stop%"
      effects:
        - "TRENCH:3"
    8:
      chance: 90
      condition:
        - "%player is sneaking% = true : %stop%"
      effects:
        - "TRENCH:3"
    9:
      chance: 100
      condition:
        - "%player is sneaking% = true : %stop%"
      effects:
        - "TRENCH:3"
```
