### ISSUE TITLE
Another disappearing items bug with soulbound

### ISSUE THREAD

**Issue by xlsalvolx** [GC-spigot/AdvancedEnchantments#2977]
### Describe the bug

If you have more of 2 identical items with soulbound in your hotbar they will all disappear except for one on your death

### How to reproduce

1. Enchant one item with this enchant:
```
soulbound:
  display: "%group-color%Soulbound"
  description: "You could keep items on death"
  applies-to: "anything"
  type: "DEATH;PASSIVE_DEATH"
  group: "SOULBOUND"
  applies:
    - PLAYER_HEAD
    - ALL_TOOLS
    - ALL_SWORD
    - ALL_AXE
    - ALL_ARMOR
    - BOW
    - CROSSBOW
    - TRIDENT
  levels:
    1:
      chance: 100
      effects:
        - "KEEP_ON_DEATH"
```
2. Duplicate the item in your hotbar using creative mode
3. You need to have at least 3 identical items with soulbound in your hotbar
4. They MUST be on your hotbar
5. Kill yourself with any method, like /kill
6. Every identical item you had will disappear except for one

### Screenshots / Videos

https://www.youtube.com/watch?v=Mj1ZEYqErvs&feature=youtu.be

### "/ae plinfo" link

https://paste.md-5.net/cavonadela
