### ISSUE TITLE
Beetroots crop issue with TP_DROPS

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#2982]
### Describe the bug

Using TP_DROPS effect in beetroot does not grant the right drop amount.
It will give 1x beetroot + 1x beetroot seed per crop, even if the hoe has fortune enchantment.

### How to reproduce

```
tpdrops:
  display: 'test'
  description: "test"
  applies-to: 'Ferramentas'
  type: 'MINING'
  group: 'ULTRA'
  applies:
    - ALL_HOE
  levels:
    1:
      condition: "%player_has_empty_slot% = yes : %allow%"
      chance: 100
      effects:
        - 'TP_DROPS'
```
Test any tp_drops enchantment in beetroot crop.

### Screenshots / Videos

with TP_DROPS https://cdn.discordapp.com/attachments/636223972719067157/1006642496803192862/unknown.png
with fortune III and without TP_DROPS https://cdn.discordapp.com/attachments/636223972719067157/1006642867944562718/unknown.png

### "/ae plinfo" link

https://paste.md-5.net/xakijoyato
