### ISSUE TITLE
STEAL_GUARD effect is not working

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#2984]
### Describe the bug

STEAL_GUARD effect is not working. We try many sources and many different ways. Like adding %victin%, %attacker%

### How to reproduce

Create a enchantment with STEAL_GUARD effect, like this one:

```
brainwashed :
  display: '%group-color%Brain Washed '
  description: "test"
  applies-to: 'Arcos'
  type: 'ATTACK_MOB;BOW;BOW_MOB'
  group: 'SIMPLE'
  applies:
    - BOW
    - CROSSBOW
  levels:
    1:
      chance: 100
      cooldown: 5
      effects:
        - 'STEAL_GUARD'
        # also tried STEAL_GUARD %attacker% and STEAL_GUARD' %victim%
        - 'MESSAGE:&3test! %attacker%' #that message works
```

Create a enchantment with GUARD effect, like this one:
```
spirits:
  display: "%group-color%Spirits"
  description: "Chance to spawn guard blazes."
  applies-to: "Armor"
  type: "DEFENSE"
  group: "ULTIMATE"
  applies:
    - ALL_ARMOR
  levels:
    1:
      chance: 2
      cooldown: 8
      effects:
        - "GUARD:IRON_GOLEM:8:3:%victim%"
```
Fight until the Spirits enchantment is activated. Then, use the Brainwashed to steal it. We tried to shot on the mob and the player, both didn't worked.

### "/ae plinfo" link

https://paste.md-5.net/xakijoyato
