### ISSUE TITLE
Lore description

### ISSUE THREAD

**Issue by Kalasky** [GC-spigot/AdvancedEnchantments#2994]
### Describe the bug

Lore description is not being added to item lore's despite the config section being enabled:

```
  # Should enchantment descriptions be added under enchant names in lores?
  lore-descriptions:
    enabled: true
    display: "%group-color%* &8%description%"
```

### How to reproduce

Drag and drop an enchanted book on whatever item you're enchanting, thee enchant will display but no lore description will be added underneath.

### Screenshots / Videos

https://gyazo.com/47c04e1f60575c302be3e4458c6c8c4d

### "/ae plinfo" link

https://paste.md-5.net/esuqiqejoy

### Server Log

https://mcpaste.io/83fc48381f93d85d
