### ISSUE TITLE
How to use custom model data in alchemist?

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#3001]
### Describe the bug

This is more a question. I asked on discord more than one time but got no anwser.

I tried this way:
```
      item:
        type: DIAMOND
        custom-model-data: 5
        damage: 0
```

The diamond item works but the custom model data is not applied.

### How to reproduce

This is a question.
Also, I don't have the alchemist.yml file, like is said on [8.12.3 Changelog](https://www.spigotmc.org/resources/1-8-1-19-2-%E2%AD%95-advancedenchantments-%E2%AD%90-450-custom-enchants-%E2%AD%90create-custom-enchantments-%E2%9C%85-50-sale.43058/update?update=462941)

### "/ae plinfo" link

https://paste.md-5.net/opumeludef
