### ISSUE TITLE
Another Soulbound disappearing issue

### ISSUE THREAD

**Issue by xlsalvolx** [GC-spigot/AdvancedEnchantments#3005]
### Describe the bug

Multiple indentical items with soulbound will disappear if the player will die and the soulbound has a chance to fail

### How to reproduce

1. Use this enchant
```
soulbound:
  display: "%group-color%Soulbound"
  description: "You may keep the items on death"
  applies-to: "anything"
  type: "DEATH;PASSIVE_DEATH"
  group: "SOULBOUND"
  applies:
    - PLAYER_HEAD
    - ALL_TOOLS
    - ALL_SWORD
    - ALL_AXE
    - ALL_ARMOR
    - BOW
    - CROSSBOW
    - TRIDENT
  levels:
    1:
      chance: 40
      effects:
        - "KEEP_ON_DEATH"
    2:
      chance: 60
      effects:
        - "KEEP_ON_DEATH"
    3:
      chance: 80
      effects:
        - "KEEP_ON_DEATH"
```
2. Enchant a sword (or anything else)
3. Get in creative mode
4. Create multiple copies of the item
5. Kill yourself
6. Again
7. And again
8. Eventually every copy of the item will disappear (if the chance fails in one item that item will disappear)
9. Cry

### Screenshots / Videos

https://www.youtube.com/watch?v=MsF8eYIsKVA&feature=youtu.be

### "/ae plinfo" link

https://paste.md-5.net/edoletogab
