### ISSUE TITLE
%applies-to% variable reads applies: parameter. When it should read applies-to: parameter instead

### ISSUE THREAD

**Issue by Bounty38** [GC-spigot/AdvancedEnchantments#3016]
### Describe the bug

Hello, can't translate `%applies-to%` variable. Obviously simply translating `applies-to: Helmet` parameter won't solve problem completely. 
Its not used everywhere for some reason. For example: in command /enchants it uses `%applies-to%` variable and reads `applies:` 
its not translated but if I go with /ae info it shows the correct translation that I corrected in Enchantments.yml file.
I believe it relies on `ALL_HELMET` parameter but I failed to find anything on that as well. 

Also feel free to attend 
https://discord.com/channels/376425582139015168/1016842394060193812

### How to reproduce

Simply try to translate anything after applies-to: parameter. Book itself will be translated normally but /enchants menu will not.

Here's the example:
```
aquatic:
  display: "%group-color%Жабры"
  description: "Позволяет дышать под водой."
  applies-to: "Шлемы"
  type: "EFFECT_STATIC"
  group: "SIMPLE"
  applies:
    - ALL_HELMET
  levels:
    1:
      effects:
        - "POTION:WATER_BREATHING:0"
```

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/47916099/188757720-ea1ea80a-d06a-48f6-9da1-3b3f090434be.png) - in /enchants menu
![image](https://user-images.githubusercontent.com/47916099/188757752-7c98b266-148a-49ef-9b27-74278dbe3c77.png) - Book itself
