### ISSUE TITLE
PULL_CLOSER not working

### ISSUE THREAD

**Issue by Dharuzz** [GC-spigot/AdvancedEnchantments#3034]
### Describe the bug

I'm trying to use PULL_CLOSER enchantment and it isn't working.
Script:
```yaml
pull:
  display: '%group-color%PULL'
  description: 'P U L L'
  applies-to: 'Weapons'
  group: 'PVP'
  type: 'ATTACK'
  applies:
    - 'ALL_SWORD'
    - 'ALL_AXE'
  settings:
    disable-in-enchanter: true
  levels:
    '1':
      chance: 100
      effects:
        - 'PULL_CLOSER %victim%'
```

### How to reproduce

Make an enchantment with `PULL_CLOSER %victim%` and attack another player.

### "/ae plinfo" link

https://paste.md-5.net/pawuqisete

### Server Log

https://mcpaste.io/143d4bfa68c9340c
