### ISSUE TITLE
Golden helmet not working with ALL_HELMET

### ISSUE THREAD

**Issue by smuddgge** [GC-spigot/AdvancedEnchantments#3060]
### Describe the bug

When putting wearing a golden helmet with an ALL_HELMET enchantment on, it does not work.

### How to reproduce

```yaml
glowing:
  display: '%group-color%Glowing'
  description: 'Gives you permanent Night Vision.'
  applies-to: 'Helmets'
  type: 'EFFECT_STATIC'
  group: 'EPIC'
  applies:
  - ALL_HELMET
  - TURTLE_HELMET
  levels:
    1:
      effects:
      - 'POTION:NIGHT_VISION:0'
```

Putting this enchantment on a Golden_Helmet does not give you night vision

<img width="993" alt="Screenshot 2022-10-13 at 23 09 11" src="https://user-images.githubusercontent.com/68658429/195720046-cb474636-bbf0-4be6-80c5-d35c43278179.png">

### "/ae plinfo" link

https://paste.md-5.net/nefemeguso

**Comment by Awpmeister2170** [comment]
Hello add GOLDEN_HELMET to the Armor items section in the helmet: tab and then add golden helmet to your Applies section and this will resolve your issue.

**Comment by smuddgge** [comment]
<img width="1040" alt="Screenshot 2022-10-15 at 18 16 42" src="https://user-images.githubusercontent.com/68658429/195999459-4606841b-f13f-48ec-ab92-2a17c9f66bf4.png">

This still does not work.

```yml
glowing:
  display: '%group-color%Glowing'
  description: 'Gives you permanent Night Vision.'
  applies-to: 'Helmets'
  type: 'EFFECT_STATIC'
  group: 'EPIC'
  applies:
  - ALL_HELMET
  - GOLDEN_HELMET
  - TURTLE_HELMET
  levels:
    1:
      effects:
      - 'POTION:NIGHT_VISION:0'
      ```
