### ISSUE TITLE
Can't use restore on swords

### ISSUE THREAD

**Issue by ToXer04** [GC-spigot/AdvancedEnchantments#3067]
### Describe the bug

I'm trying to make a restore enchantments which restore half the durability of the item when in reaches 0 durability... it works on pickaxes and armors but not on swords, I tried using ADD_DURABILITY_CURRENT_ITEM, ADD_DURABILITY_ITEM and ADD_DURABILITY but none of these worked on swords... can you help me out?

### How to reproduce

run a paper 1.19 minecraft server with advanced enchantments 9.0.0b3 and create this enchantment:
```
restore:
  display: 'Restore'
  description: "Once broken, the tool has\na chance of losing\nthe enchant and repairing\nhalf of its durability"
  applies-to: 'Swords, Armor'
  type: 'ITEM_BREAK'
  group: 'SIMPLE'
  applies:
  - ALL_SWORD
  - ALL_ARMOR
  levels:
    1:
      chance: 100
      effects:
        - "REMOVE_ENCHANT:restore"
        - "ADD_DURABILITY:<round><math>-1 * (%maximum durability%/2)</math></round>"
        - "ADD_DURABILITY_ITEM:<round><math>-1 * (%maximum durability%/2)</math></round>"
        - "ADD_DURABILITY_CURRENT_ITEM:<round><math>-1 * (%maximum durability%/2)</math></round>"
        - "PLAY_SOUND:ITEM_TOTEM_USE"
```
then apply it to a sword and destroy it

### "/ae plinfo" link

https://paste.md-5.net/wefumidaro

### Server Log

https://mcpaste.io/1ad7036161d790b0
