### ISSUE TITLE
RIGHT_CLICK_BLOCK HAND whenever you right klick

### ISSUE THREAD

**Issue by Bop191** [GC-spigot/AdvancedEnchantments#3068]
### Describe the bug

Hello, I am making a enchantment for a crossbow that will spawn cobwebs on impact. Once the crossbow has shot it will execute a command that will spawn the cobwebs: `aec`, but this didn't work. The discord team told me to remove the parenthesis on `- "PLAYER_COMMAND:(aec 1) %attacker%"` but since I removed them this happends...

Whenever a player right klicks a block, the player and the console will receive `RIGHT_CLICK_BLOCK HAND`.
I have no idea why this is happening. I am using the newest version *(9.0.0.b14)*, could anyone help me?

Here is `my enchantments.yml` file:
```
webster:
  display: "%group-color%Webster"
  description: "Spawn cobwebs on inpact but recharge time\nis greatly increased."
  applies-to: "Crossbow"
  type: "BOW_SHOOT"
  group: "ULTIMATE"
  applies:
    - CROSSBOW
  levels:
    1:
      #cooldown: 30
      effects:
        - "PLAYER_COMMAND:aec 1 %attacker%"
    2:
      #cooldown: 28
      effects:
        - "PLAYER_COMMAND:aec 2 %attacker%"
    3:
      #cooldown: 26
      effects:
        - "PLAYER_COMMAND:aec 3 %attacker%"
    4:
      #cooldown: 23
      effects:
        - "PLAYER_COMMAND:aec 4 %attacker%"
    5:
      #cooldown: 20
      effects:
        - "PLAYER_COMMAND:aec 5 %attacker%"
```

### How to reproduce

I think you can reproduce it when your `enchantments.ylm` file has a not been programmed the right way. Most likely the console will say there is something wrong with the file, but in this case it messages the player with `RIGHT_CLICK_BLOCK HAND`.

### Screenshots / Videos

https://prnt.sc/AbNolpp_Xc_H
The console will receive the same message.

### "/ae plinfo" link

https://paste.md-5.net/upawacuwib

### Server Log

There is nothing to see on the logs.
