### ISSUE TITLE
Armor Enchants not working when worn(Same applies to when joining server)

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#3071]
### Describe the bug

Armor Enchants not working when worn unless you /reapply, same as when joining server.

### How to reproduce
Try joining a server with these enchants below. also try wearing an item with these enchants below as well, its either it will not take effect, or mass delay.
Example Enchants not working:
```
alienimplants:
  display: '%group-color%Alien Implants'
  description: "Never lose hunger forever. Requires Implants III.\n&4&lWARNING:\n&cMake sure to use /reapply when wearing."
  applies-to: 'Helmets'
  type: 'REPEATING'
  time: 5
  group: 'HEROIC'
  applies:
    - ALL_HELMET
  settings:
    required-enchants:
      - 'implants:3'
    removed-enchants:
      - 'implants'
  levels:
    1:
      chance: 100
      effects:
        - 'MESSAGE: DEBUG ALIEN IMPLANTS'
        - 'ADD_FOOD:10'
        
godlyoverload:
  display: '%group-color%Godly Overload'
  description: "Heroic Enchantment. A very large\npermanent increase in hearts. Requires\nOverload III enchant on item to apply."
  applies-to: 'Armor'
  type: 'EFFECT_STATIC'
  group: 'HEROIC'
  settings:
    required-enchants:
      - 'overload:3'
    removed-enchants:
      - 'overload'
  applies:
    - ALL_ARMOR
  levels:
    1:
      effects:
        - 'POTION:HEALTH_BOOST:2'
    2:
      effects:
        - 'POTION:HEALTH_BOOST:3'
    3:
      effects:
        - 'POTION:HEALTH_BOOST:4'
     
gears:
  display: '%group-color%Gears'
  description: 'Added speed when equipped.'
  applies-to: 'Boots'
  type: 'EFFECT_STATIC'
  group: 'LEGENDARY'
  applies:
    - ALL_BOOTS
  levels:
    1:
      effects:
        - 'POTION:SPEED:0'
    2:
      effects:
        - 'POTION:SPEED:1'
    3:
      effects:
        - 'POTION:SPEED:2'
```

### Screenshots / Videos

https://streamable.com/ki8dfr

### "/ae plinfo" link

https://paste.md-5.net/iyaselarir

### Server Log

https://mcpaste.io/8ca0db627b28cace
