### ISSUE TITLE
Conditions not working, giving error

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#3072]
### Describe the bug

Conditions are giving errors in console, and they do not work

### How to reproduce

Make a condition based enchant, and see.
here are some enchants I tested it with:
```
ATTACK:
    cooldown: 2
    condition:
        - "%victim health% > 20 : %stop%"
    effects:
      - 'ADD_HEALTH:<random number>2-6</random number>'
      - 'MESSAGE: &4&l** THIRST &7(&c+ %random%HP&7) &4&l**'
```
```
arsonist:
  display: '%group-color%Arsonist'
  description: "Chance to deal more damage whilst on fire."
  applies-to: 'Melee'
  type: 'ATTACK'
  group: 'ULTIMATE'
  applies:
    - ALL_SWORD
    - ALL_AXE
  levels:
    1:
      cooldown: 10
      condition:
        - '%attacker is on fire% = true : %allow%'
      effects:
        - 'INCREASE_DAMAGE:15 %attacker%'
    2:
      cooldown: 6
      condition:
        - '%attacker is on fire% = true : %allow%'
      effects:
        - 'INCREASE_DAMAGE:20 %attacker%'
    3:
      cooldown: 3
      condition:
        - '%attacker is on fire% = true : %allow%'
      effects:
        - 'MESSAGE:ARSONIST TEST %attacker%'
        - 'INCREASE_DAMAGE:25 %attacker%'
```

### Screenshots / Videos

https://mcpaste.io/f231de0dd790039e

### "/ae plinfo" link

https://paste.md-5.net/ijucenidan

### Server Log

https://mcpaste.io/63ad305ffa1943bd
