### ISSUE TITLE
Condition error[1.8]?

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#3085]
### Describe the bug

It gave me this error, even though victim health is not above 15, the effect works and an error pops up in my chat

### How to reproduce

Create an armorset with a condition like this:
```
events:
  ATTACK:
    cooldown: 3
    condition:
        - '%victim health% > 15 : %stop%'
    effects:
      - 'ADD_HEALTH:<random number>2-6</random number>'
      - 'MESSAGE: &4&l** THIRST &7(&c+ %random%HP&7) &4&l**'
```

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/89855789/199521930-d8da2584-870b-4683-8ea8-4b16df4c25d6.png)

### "/ae plinfo" link

https://paste.md-5.net/nonojazucu

### Server Log

https://mcpaste.io/665eed138927e4ac

**Comment by illudota** [comment]
Same as this, no errors or anything but its not working, the debugg message not popping up.
```
events:
  ATTACK:
    condition:
      - '%victim is on fire% = true : %allow%'
    effects:
      - 'INCREASE_DAMAGE:20 %attacker%'
      - 'MESSAGE: &4&l** ARMORSET DISABLED &7(&cIS BEING FIXED&7) &4&l**'
```
