### ISSUE TITLE
Enchantment doesn't work in gamemode survival, but does work in gamemode creative.

### ISSUE THREAD

**Issue by Bop191** [GC-spigot/AdvancedEnchantments#3105]
### Describe the bug

I made a enchantment that teleports the player at the position where the trident has landed. The enchantment does work when you are in gamemode creative, but does not work in gamemode survival.

Here's the enchantment code from *enchantments.yml*.
```
blink:
  display: "%group-color%Blink"
  description: "Makes your trident teleport you away."
  applies-to: "Trident"
  type: "ARROW_HIT"
  group: "LEGENDARY"
  applies:
    - TRIDENT
  not-applyable-with:
    - "RIPTIDE"
    - "CHANNELING"
  levels:
    1:
      effects:
        - "TELEPORT location=%hit location%"
```

Does anyone know how to add 1 to the y-level of your location?

### How to reproduce

No idea.

### Screenshots / Videos

https://media.giphy.com/media/zv5VjaluQRbBmXkRpc/giphy-downsized-large.gif

### "/ae plinfo" link

https://paste.md-5.net/kejizafavi

### Server Log

Does not apply
