### ISSUE TITLE
Possible Dupe exploit

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#3123]
### Describe the bug

You can dupe if the effect procs and u swap items fast, it works mostly on 'HELD' type but it could possibly work with other types too.

### How to reproduce

You can dupe if the effect procs and u swap items fast, it works mostly on 'HELD' type but it could possibly work with other types too.

Code:
```
abiding:
  display: '%group-color%Abiding'
  description: "Makes your weapon/tool unbreakable for Non-PvP purposes, best for:\n&cMining, Grinding, Bowboosting etc."
  applies-to: 'Weapons and tools'
  type: 'KILL_MOB;SWING;HELD'
  group: 'LEGENDARY'
  applies:
    - ALL_AXE
    - ALL_SWORD
    - ALL_PICKAXE
    - ALL_SPADE
    - BOW
  levels:
    1:
      cooldown: 5
      effects:
        - 'MESSAGE:&6&l** ABIDING **'
        - 'ADD_DURABILITY_CURRENT_ITEM:-100'
```

### Screenshots / Videos

https://streamable.com/h0iisv

### "/ae plinfo" link

https://paste.md-5.net/evitahisan

### Server Log

https://mcpaste.io/baf997b943fc7ec8
