### ISSUE TITLE
Bug with EFFECT_STATIC enchantment type

### ISSUE THREAD

**Issue by Replaycchi** [GC-spigot/AdvancedEnchantments#3128]
### Describe the bug

Hi, i've got a weird bug about custom enchant with "EFFECT_STATIC" type, user can equip the armor, then unequip it and they still have the bonus, then the opposite when they equip it (if they still have the bonus effect) the bonus is lost until you move an armor in the armor slot.

```
eclatant:
  display: "%group-color%Éclatant"
  description: "&e&oDonne l'effet Vision Nocturne de manière permanente."
  applies-to: "Casques"
  type: "EFFECT_STATIC"
  group: "COMMUN"
  applies:
    - ALL_HELMET
  levels:
    1:
      effects:
        - "POTION:NIGHT_VISION:0"
```

```
surcharge:
  display: "%group-color%Surcharge"
  description: "&e&oDévérrouille des coeurs supplémentaires (non cumulable)."
  applies-to: "Armures"
  type: "EFFECT_STATIC"
  group: "MYTHIQUE"
  applies:
    - ALL_ARMOR
  levels:
    1:
      effects:
        - "POTION:HEALTH_BOOST:0"
    2:
      effects:
        - "POTION:HEALTH_BOOST:1"
```

### How to reproduce

equip the armor with "EFFECT_STATIC" type then unequip it.

### Screenshots / Videos

![bug ae](https://user-images.githubusercontent.com/85904547/206898466-d9372871-d3aa-43e1-97b0-782f95bb58ab.gif)

### "/ae plinfo" link

https://paste.md-5.net/ugomajiliw
