### ISSUE TITLE
FREEZE effect not working on 1.8.8

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#3148]
### Describe the bug

FREEZE is not working, does nothing.

### How to reproduce

```
freeze:
  display: '%group-color%Freeze'
  description: "Freeze"
  applies-to: 'Swords'
  type: 'ATTACK'
  group: 'HEROIC'
  applies:
    - ALL_SWORD
  levels:
    1:
      effects:
        - 'FREEZE:100 %victim%'
 ```

### Screenshots / Videos

None, but try it and you'll see

### "/ae plinfo" link

https://paste.md-5.net/efezacomit

### Server Log

https://mcpaste.io/24661851871281d7
