### ISSUE TITLE
Alchemist let-plugin-count not working correctly

### ISSUE THREAD

**Issue by smuddgge** [GC-spigot/AdvancedEnchantments#3159]
### Describe the bug

Alchemist does not calculate the price.

### How to reproduce

When setting this value.
`alchemist.yml`
```yaml
price:
      # Set false to use money economy instead of XP.
      experience: false
      # If true the plugin will calculate the price.
      let-plugin-count: true
      # Your custom price here.
      # Only works if let-plugin-count is false.
      custom-price: 1000
```

The plugin does not calculate the price, it always defaults to 1000.

### "/ae plinfo" link

https://paste.md-5.net/lefuhucoya
