### ISSUE TITLE
REPEATING effect activate multiple times

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#3165]
### Describe the bug

I have this enchantment which the code is:

```
implantesalienigenas:
  display: '%group-color%Implantes Alienígenas'
  description: " Chance de restaurar vida e fome."
  applies-to: 'Capacetes'
  type: 'REPEATING'
  time: 5
  group: 'HEROICO'
  settings:
    required-enchants:
      - 'implantes:6'
    removed-enchants:
      - 'implantes'
  applies:
    - ALL_HELMET
    - TURTLE_HELMET
  levels:
    1:
      effects:
        - 'ADD_HEALTH:3'
        - 'ADD_FOOD:3'
    2:
      effects:
        - 'ADD_HEALTH:4'
        - 'ADD_FOOD:4'
```

And sometimes the enchantment activate multiple times, sometimes work normally.

### How to reproduce

1. Create a REPEATING enchantment type effect
2. Apply on a helmet and wear it 
3. Enable debug mode
4. Unequip and equip until you see the enchantment bug and starts to activate wrongly

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/66658478/215270573-7aaeb23a-8e3c-480b-b647-8cab2fad4827.png)

### "/ae plinfo" link

https://paste.md-5.net/waxupacagi.css
