### ISSUE TITLE
console spam abount conditions.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3188]
### Describe the bug

enchant are worked but console keep spamming. i dicussed on discord but nobody answerd.

### How to reproduce

```
인듀어:
  display: "%group-color%인듀어"
  description: "일반 공격에 의한\n넉백이 면역됩니다."
  type: "DEFENSE;DEFENSE_MOB;DEFENSE_BOW;DEFENSE_BOW_MOB"
  group: "레어"
  applies-to: ""
  applies:
    - ALL_LEGGINGS
  levels:
    1:
      condition: "%victim has potion effect HERO_OF_THE_VILLAGE% = true : deny"
      effects:
        - "STOP_KNOCKBACK"
```
it worked but console keep spamming. where can i fix it?

### Screenshots / Videos

![화면 캡처 2023-02-16 020124](https://user-images.githubusercontent.com/25452835/219235415-f882b13d-60b5-44bb-b276-8dbd87d441d1.png)

### "/ae plinfo" link

https://paste.md-5.net/eqigolojis
