### ISSUE TITLE
Inquisitive (EXP) incompatibility with Sweeping Edge

### ISSUE THREAD

**Issue by iLemon** [GC-spigot/AdvancedEnchantments#3190]
### Describe the bug

Hey, so if you have Inquisitive on a sword with Sweeping Edge, you don't seem to earn XP from the mobs killed by the sweeping edge.

```yml
inquisitive:
  display: '%group-color%Inquisitive'
  description: 'Increases EXP drops from mobs.'
  applies-to: 'Swords'
  type: 'KILL_MOB'
  group: 'LEGENDARY'
  applies:
    - ALL_SWORD
  levels:
    1:
      effects:
        - 'EXP:<math>%exp% * (1.0 + 0.25 * %level%)</math> %victim%'
    2:
      effects:
        - 'EXP:<math>%exp% * (1.0 + 0.25 * %level%)</math> %victim%'
    3:
      effects:
        - 'EXP:<math>%exp% * (1.0 + 0.25 * %level%)</math> %victim%'
    4:
      effects:
        - 'EXP:<math>%exp% * (1.0 + 0.25 * %level%)</math> %victim%'
```
From testing with this sword:
![image](https://user-images.githubusercontent.com/18317307/219680132-0844036f-013e-4e09-be9f-956e3193e5ec.png)

I get the following results:
Killing 10x Blaze at once with Sweeping Edge: 60 XP
Killing 10x Blaze one by one without Sweeping Edge: 300 XP

### How to reproduce

Add the Inquisitve enchantment as configured above. Add it to your sword with Sweeping Edge and kill 10x mobs at once. You'll only get the XP for one mobs worth.

### "/ae plinfo" link

https://paste.md-5.net/oyucewakek
