### ISSUE TITLE
Tinkerer will stop working after a server restart if the "tinkerer-confirm-trade-item" is disabled

### ISSUE THREAD

**Issue by xlsalvolx** [GC-spigot/AdvancedEnchantments#3223]
### Describe the bug

    tinkerer-confirm-trade-item:
      # If you want to disable this item
      # set to false.
      enabled: false

If this is put to false the tinkerer will stop working after the server is restarted

It will work until the server is online, but after restarting it will stop working completely

### How to reproduce

do this
      enabled: true >  enabled: false

### "/ae plinfo" link

https://paste.md-5.net/mezaziwene

**Comment by reussy** [comment]
Hey @xlsalvolx,

Please use the option:

```
general:
  settings:
    # If true the confirmation items for the user and tinkerer will be displayed.
    enabled-confirm-items: true
```
