### ISSUE TITLE
Trench isn't stopped from '%player is sneaking% = true : %stop%'

### ISSUE THREAD

**Issue by Folas1337** [GC-spigot/AdvancedEnchantments#3254]
### Describe the bug

I used to use the following config to stop trench from working when users sneak and that worked fine up until I updated to the latest effect rewrite:
```yaml
trench:
  display: '%group-color%Trench'
  description: |-
    &r[&6General Purpose&r]
    Chance to break
    compatible blocks in
    a 3x3x3 area around
    the broken block.
    Guaranteed on max level.
  applies-to: Pickaxes, Shovels
  type: MINING
  group: ULTIMATE
  applies:
  - ALL_PICKAXE
  - ALL_SPADE
  levels:
    '1':
      chance: 100
      condition:
      - '%player is sneaking% = true : %stop%'
      effects:
      - BREAK_BLOCK @Trench{r=3}
```
(I increased the chance to 100 for testing purposes)

### How to reproduce

Use the provided config, apply trench on any item and sneak while breaking a block.
It won't stop trench from applying unfortunately.

### "/ae plinfo" link

https://paste.md-5.net/obovuyemek

### Server Log

https://mcpaste.io/2da9fcc14377cca0
