### ISSUE TITLE
Timber dupes Logs

### ISSUE THREAD

**Issue by Joeychuwu** [GC-spigot/AdvancedEnchantments#3269]
### Describe the bug

Using the Timber enchantment dupes logs for some reason, nothing else.
I let all files newly generate with the big version 9 update and didnt do much editing to anything, currently my Timber looks like this:
```yml
timber:
  display: '%group-color%Timber'
  description: Chance to break a tree in one hit
  applies-to: Axes
  group: ULTIMATE
  type: MINING
  applies:
    - ALL_AXE
  levels:
    '1':
      effects:
        - BREAK_TREE @Block
```
Tested everything else about it and fully isolated it to Timber, there's nothing else involved.
interestingly enough it only dupes the log that is being hit, but non of the ones that get removed due to the timber enchant.

### How to reproduce

be on my server
put timber on axe
hit log with said axe
poof 2 log instead of 1

### "/ae plinfo" link

https://paste.md-5.net/onewujufen

### Server Log

https://mcpaste.io/7402786b49eb787c
