### ISSUE TITLE
Golden Helmet with enchants don't work

### ISSUE THREAD

**Issue by Truongvv10** [GC-spigot/AdvancedEnchantments#3290]
### Describe the bug

Trying to put glowing enchant to give nighvision on a golden helmet doesn't work. Tried with other helmet and they work perfectly.

### How to reproduce

put glowing enchant to give nighvision on a golden helmet

### Screenshots / Videos

**Enchantment YML**
```yml
glowing:
  display: '%group-color%Glowing'
  description: |-
    Gives permanent night vision
    to see in the dark.

     {#FFFFFD}+ {#D9CAC3}ᴘʀᴏᴄ ᴄʜᴀɴᴄᴇ ● &f100%
  applies-to: Helmet, Heads
  type: EFFECT_STATIC
  group: SIMPLE
  applies:
  - ALL_HELMET
  - TURTLE_HELMET
  - PLAYER_HEAD
  levels:
    '1':
      effects:
      - POTION:NIGHT_VISION:0
```

**Config YML**
```yml
armor-items:
  # Items that count as helmet
  helmet:
  - HEAD
  - SKULL_ITEM
  - SKULL
  - PLAYER_HEAD
  - CREEPER_HEAD
  - DRAGON_HEAD
  - ZOMBIE_HEAD
  - NETHERITE_HELMET
  - DIAMOND_HELMET
  - GOLD_HELMET
  - GOLDEN_HELMET
  - IRON_HELMET
  - CHAINMAIL_HELMET
  - LEATHER_HELMET
  - TURTLE_SHELL
  - PUMPKIN
  - CARVED_PUMPKIN
  - TURTLE_HELMET
  # - "FEATHER" # Custom Item Example
  # Items that count as chest plate
  chest-plate:
  - NETHERITE_CHESTPLATE
  - DIAMOND_CHESTPLATE
  - GOLD_CHESTPLATE
  - GOLDEN_CHESTPLATE
  - IRON_CHESTPLATE
  - CHAINMAIL_CHESTPLATE
  - LEATHER_CHESTPLATE
  - ELYTRA
  # - "LEATHER" # Custom Item Example
  # Items that count as leggings
  leggings:
  - LEGS
  - DIAMOND_LEGGINGS
  - NETHERITE_LEGGINGS
  - GOLD_LEGGINGS
  - GOLDEN_LEGGINGS
  - IRON_LEGGINGS
  - CHAINMAIL_LEGGINGS
  - LEATHER_LEGGINGS
  # - "PAPER" # Custom Item Example
  # Items that count as boots
  boots:
  - FEET
  - DIAMOND_BOOTS
  - NETHERITE_BOOTS
  - GOLD_BOOTS
  - GOLDEN_BOOTS
  - IRON_BOOTS
  - CHAINMAIL_BOOTS
  - LEATHER_BOOTS
# - "EGG"
```

### "/ae plinfo" link

https://paste.md-5.net/ejajuserer
