### ISSUE TITLE
exception java.lang.NullPointerException: Main entity cannot be null

### ISSUE THREAD

**Issue by antibitcoin** [GC-spigot/AdvancedEnchantments#3300]
### Describe the bug

Error in console non-stop

https://paste.dedimc.io/ruhuhexoka

### How to reproduce

Just run the server

### "/ae plinfo" link

https://paste.md-5.net/zisopajoqi.css

### Server Log

https://paste.dedimc.io/ruhuhexoka

**Comment by Truongvv10** [comment]
I have this issue to with the following enchant.

```yml
implants:
  display: '%group-color%Implants'
  description: |-
    Chance to heal +1 health passively
    and restores +1 hunger every few
    seconds.

     {#FFFF00}+ {#D9CAC3}ᴘʀᴏᴄ ᴄʜᴀɴᴄᴇ ● &f30&8/&f50&8/&f70
  applies-to: Helmets, Heads
  type: REPEATING
  group: ULTIMATE
  applies:
  - ALL_HELMET
  - TURTLE_HELMET
  - PLAYER_HEAD
  levels:
    '1':
      chance: 30
      time: 5
      cooldown: 5
      effects:
      - ADD_HEALTH:1 @Attacker
      - ADD_FOOD:1 @Attacker
    '2':
      chance: 50
      time: 5
      cooldown: 5
      effects:
      - ADD_HEALTH:1 @Attacker
      - ADD_FOOD:1 @Attacker
    '3':
      chance: 70
      time: 5
      cooldown: 5
      effects:
      - ADD_HEALTH:1 @Attacker
      - ADD_FOOD:1 @Attacker
```
