### ISSUE TITLE
[Bug] Timber gives 1 too many logs

### ISSUE THREAD

**Issue by Folas1337** [GC-spigot/AdvancedEnchantments#3304]
### Describe the bug

*This one's giving me a giggle cause I reported the exact opposite in September 2022, see #2972*

Anyways, now I'm getting exactly 1 too many logs every time Timber works.

Here's the timber from enchantments.yml:
```yaml
timber:
  display: '%group-color%Timber'
  description: |-
    &r[&6General Purpose&r]
    Chance to break
    an entire tree.
    Can fail on bigger trees.
    Guaranteed on max level.
  applies-to: Axes
  group: ULTIMATE
  type: MINING
  applies:
  - ALL_AXE
  levels:
    '1':
      chance: 15
      # cooldown: 5
      conditions:
      - '%player is sneaking% = true : %stop%'
      effects:
      - BREAK_TREE
    '2':
      chance: 35
      # cooldown: 5
      conditions:
      - '%player is sneaking% = true : %stop%'
      effects:
      - BREAK_TREE
    '3':
      chance: 55
      # cooldown: 6
      conditions:
      - '%player is sneaking% = true : %stop%'
      effects:
      - BREAK_TREE
    '4':
      chance: 75
      # cooldown: 6
      conditions:
      - '%player is sneaking% = true : %stop%'
      effects:
      - BREAK_TREE
    '5':
      conditions:
      - '%player is sneaking% = true : %stop%'
      effects:
      - BREAK_TREE
```
I also tried this with the effect `BREAK_TREE @Block` but that also wouldn't do the trick

### How to reproduce

- Load a world
- Get an axe
- Ideally apply Timber 3 (or even Timber 5 from my enchantments.yml)
- Chop down a tree of 6 blocks
- End up with 7 log blocks in the end

### Screenshots / Videos

(Hopefully none required as this is really easy to reproduce)

### "/ae plinfo" link

https://paste.md-5.net/geyekemuka

### Server Log

https://mcpaste.io/56c12d87049d2710
