### ISSUE TITLE
CONSOLE_COMMAND wipes out any Colon in the following command

### ISSUE THREAD

**Issue by R411gun** [GC-spigot/AdvancedEnchantments#3316]
### Describe the bug

When you want to use colons in a command they will just get replaced by a space
     - CONSOLE_COMMAND:say hello there :)
will result in hello there  )

this is kinda problematic because there are a lot of commands that require you to
define the plugin in front of the command
minecraft:give or essentials:give as an example

This only affects Versions after the rewrite

### How to reproduce

Use this Enchantment on a Sword and right click

```
test:
  display: "Test"
  description: something
  applies-to: Sword
  type: RIGHT_CLICK
  group: FABLED
  applies:
  - ALL_SWORD
  levels:
    "1":
      cooldown: 1
      effects:
      - CONSOLE_COMMAND:say hello there :)
```

### "/ae plinfo" link

https://paste.md-5.net/ocudayareq
