### ISSUE TITLE
MINING works with MORE_DROPS but other triggers don't work with MORE_DROPS

### ISSUE THREAD

**Issue by KaiOffline** [GC-spigot/AdvancedEnchantments#3320]
### Describe the bug

Just as the title says, I am trying to attempt to make something similar to a looting for bow, by using the MORE_DROPS effect, however it seems MORE_DROPS along with something like SHOOT;SHOOT_MOB;KILL_MOB or anything along these lines isn't working

### How to reproduce

Very easy to reproduce, simply add this enchant to enchantments.yml (I've also tried to use KILL_MOB):

 ```
plunder:
   display: '%group-color%Plunder'
   description: Chance to get more drops from shooting mobs.
   applies-to: Bow
   type: SHOOT;SHOOT_MOB
   group: UNIQUE
   applies:
   - BOW
   - CROSSBOW
   levels:
     '1':
       chance: 30
       effects:
         - MORE_DROPS:<random number>1-2</random number>
     '2':
       chance: 60
       effects:
         - MORE_DROPS:<random number>2-3</random number>
     '3':
       effects:
         - MORE_DROPS:8
```

We tested by using the MINING trigger along with MORE_DROPS:

```
moredropstest:
   display: '%group-color%More Drops'
   description: Chance to get more drops from mining blocks.
   applies-to: Pickaxe
   type: MINING
   group: UNIQUE
   applies:
   - ALL_PICKAXE
   levels:
     '1':
       effects:
         - MORE_DROPS:15
```

### Screenshots / Videos

Ticket: [tickettool link](https://tickettool.xyz/direct?url=https://cdn.discordapp.com/attachments/1096927859286749194/1103244344259002398/transcript-aenchantments-3851.html)

### "/ae plinfo" link

https://paste.md-5.net/atunayusay

### Server Log

Doesn't seem to be necessary.
