### ISSUE TITLE
%potion effect level% does not work

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#3321]
### Describe the bug

condition potion %potion effect level <effect> <level>% does not work

### How to reproduce

the given format is
%potion effect level <effect> <level>%
I tried 
```

      - '%potion effect level FAST_DIGGING 3%: %stop%'
      - '%potion effect level FAST_DIGGING 3% = true: %stop%'
      - '%potion effect level FAST_DIGGING% = 3: %stop%'
      - '%player potion effect level FAST_DIGGING 3%: %stop%'
      - '%player potion effect level FAST_DIGGING 3% = true: %stop%'
      - '%player potion effect level FAST_DIGGING% = 3: %stop%'
```
The original write method does no work
no matter how i write the condition according to discord staff and community people reply, none of them works.

### Screenshots / Videos

https://youtu.be/Qgh4tjD8Pbg

### "/ae plinfo" link

https://paste.md-5.net/cecaxaxeka

### Server Log

https://paste.denizenscript.com/View/109432

**Comment by GC-spigot** [comment]
Can you show your enchant? You may need to add %victim or %attacker to specify which user to check

**Comment by hkkongou** [comment]
> Can you show your enchant? You may need to add %victim or %attacker to specify which user to check Correct format is `%attacker potion effect level FAST_DIGGING 3% = true : %allow%`

my enchant used to test this yesterday is
```
fast_dig:
  display: '%group-color%fast_dig'
  description: dig faster.
  applies-to: Tools
  type: HELD
  group: LEGENDARY
  applies:
  - ALL_PICKAXE
  - ALL_SPADE
  - ALL_AXE
  levels:
    '1':
      condition:
      - '%potion effect level FAST_DIGGING 3%: %stop%'
      - '%potion effect level FAST_DIGGING 3% = true: %stop%'
      - '%potion effect level FAST_DIGGING% = 3: %stop%'
      - '%player potion effect level FAST_DIGGING 3%: %stop%'
      - '%player potion effect level FAST_DIGGING 3% = true: %stop%'
      - '%player potion effect level FAST_DIGGING% = 3: %stop%'
      effects:
      - POTION:FAST_DIGGING:4
      - MESSAGE:§cactivated
```

And,
the condition format you show above will trigger the effect at any time, even when I have no any potion effect, which should not be normal.

My expectation is that only when FAST_DIGGING level 3 will trigger the effect

I am trying to make an ae enchant which make people have haste affect(FAST_DIGGING), and it will only trigger when player have low level of FAST_DIGGING or no effect.(otherwise the ae effect will wipe out players with stronger effect). I tried to use this %potion effect level % condition with multiple OR statement, but i found out that a single %potion effect level% is already malfunctioning.

![image](https://user-images.githubusercontent.com/61608872/236223876-9ac25c96-7bfe-4332-b0c5-2c37c2198f83.png)
