### ISSUE TITLE
Effect Failure: CANCEL_USE:<MATERIAL>:<TICKS>

### ISSUE THREAD

**Issue by VinceSMC** [GC-spigot/AdvancedEnchantments#3350]
### Describe the bug

It appears that the effect **CANCEL_USE:ARROW:1** is not functioning properly. 

The implementation was carried out as follows:

```
endless-quiver:
  display: '%group-color%Endless Quiver'
  description: |-
    Increases the chance to not
    consume an arrow by 3% per level.
  applies-to: Bow
  type: ATTACK;ATTACK_MOB;SHOOT;SHOOT_MOB
  group: UNCOMMON
  applies:
  - BOW
  levels:
    '1':
      chance: 100
      effects:
      - CANCEL_USE:ARROW:1 @Attacker
```

### How to reproduce

By replicating this enchantment and applying it to a bow.

### "/ae plinfo" link

1.19.4, Latest plugin version.

### Server Log

https://paste.smcdownloads.com/qohugusahe.csharp
