### ISSUE TITLE
Disabled World + HELD Enchant Not Functional

### ISSUE THREAD

**Issue by COVID-GUH** [GC-spigot/AdvancedEnchantments#3364]
### Describe the bug

The combination of a type:HELD, and disabled world setting does not seem to work. I tried also disabling in the config.yml.

Relevant configurations in the reproduce sections.

### How to reproduce

`enchantments.yml`
```yml
nimble:
  display: '%group-color%Nimble'
  description: Extreme speed boost when holding your tool.
  applies-to: Tools
  type: HELD
  group: LEGENDARY
  applies:
  - ALL_PICKAXE
  - ALL_HOE
  - ALL_SHOVEL
  settings:
    disabled-worlds:
      - 'newmap'
  levels:
    '1':
      effects:
      - POTION:SPEED:2
    '2':
      effects:
      - POTION:SPEED:3
```
`config.yml`
```yml
disable-enchants:
  # Disable enchants in specific world
  newmap: # world name
    - nimble
```

### Screenshots / Videos

<img width="330" alt="image" src="https://github.com/GC-spigot/AdvancedEnchantments/assets/62044207/c51981f9-247a-43b0-90f4-25d4c271b87d">

<img width="564" alt="image" src="https://github.com/GC-spigot/AdvancedEnchantments/assets/62044207/5de43601-0d98-4782-992d-4747fd24faf6">

### "/ae plinfo" link

https://paste.md-5.net/lipulacefi
