### ISSUE TITLE
Incorrect chance calculation

### ISSUE THREAD

**Issue by justtos** [GC-spigot/AdvancedEnchantments#3392]
### Describe the bug

If an enchant has a chance below `1` it will always activate.

### How to reproduce

Using the default Disarmor enchant from Cosmic preset.

```
disarmor:
  display: '%group-color%Disarmor'
  description: |-
    A slight chance of removing one
    piece of armor from your enemy
    when they are at low health.
  applies-to: Sword
  type: ATTACK
  group: LEGENDARY
  applies:
  - ALL_SWORD
  levels:
    '1':
      chance: 0.4
      cooldown: 6
      effects:
      - REMOVE_RANDOM_ARMOR @Victim
      - MESSAGE:§6§l** YOU HAVE BEEN DISARMORED ** @Victim
    '2':
      chance: 0.8
      cooldown: 6
      effects:
      - REMOVE_RANDOM_ARMOR @Victim
      - MESSAGE:§6§l** YOU HAVE BEEN DISARMORED ** @Victim
    '3':
      chance: 1.0
      cooldown: 6
      effects:
      - REMOVE_RANDOM_ARMOR @Victim
      - MESSAGE:§6§l** YOU HAVE BEEN DISARMORED ** @Victim
    '4':
      chance: 1.2
      cooldown: 6
      effects:
      - REMOVE_RANDOM_ARMOR @Victim
      - MESSAGE:§6§l** YOU HAVE BEEN DISARMORED ** @Victim
    '5':
      chance: 1.4
      cooldown: 6
      effects:
      - REMOVE_RANDOM_ARMOR @Victim
      - MESSAGE:§6§l** YOU HAVE BEEN DISARMORED ** @Victim
    '6':
      chance: 1.6
      cooldown: 6
      effects:
      - REMOVE_RANDOM_ARMOR @Victim
      - MESSAGE:§6§l** YOU HAVE BEEN DISARMORED ** @Victim
    '7':
      chance: 1.8
      cooldown: 6
      effects:
      - REMOVE_RANDOM_ARMOR @Victim
      - MESSAGE:§6§l** YOU HAVE BEEN DISARMORED ** @Victim
    '8':
      chance: 2
      cooldown: 6
      effects:
      - REMOVE_RANDOM_ARMOR @Victim
      - MESSAGE:§6§l** YOU HAVE BEEN DISARMORED ** @Victim
```

1. Enchant one sword with Disarmor 1 (*with a chance of 0.4*)
2. Hit a player wearing armor once
3. See a random peace of their armor gets removed **everytime** (respecing the 6 seconds cooldown)

To verifiy that this is not the expected behaviour you can do two things:
1. Change the chance to above 1 and it will be resolved
2. Try any of the higher levels of Disarmor

### "/ae plinfo" link

https://paste.md-5.net/zonozufewu

### Server Log

Will provide if proven necessary.
