### ISSUE TITLE
Gkit "kit-use" sound isn't working.

### ISSUE THREAD

**Issue by Royul2k** [GC-spigot/AdvancedEnchantments#3397]
### Describe the bug

In the gkits.yml the "kit-use" sound isn't playing, I tested the same sound I was using with inventory-open and that worked but when I enter it in kit-use, it doesn't work.

### How to reproduce

Paste a sound into kit-use

### "/ae plinfo" link

https://paste.md-5.net/wuzubojure

**Comment by reussy** [comment]
Hey @Royul2k,

Fixed!

Make sure use Minecraft Sounds 1.13 >

```yaml
sounds:
    # Inventory opening sound
    # * Sound is played on inventory open via command
    inventory-open: "UI_BUTTON_CLICK"
    # Usage of kit sound
    # * Sound played upon the use of the available kits
    kit-use: "ENTITY_PLAYER_LEVELUP"
```
