### ISSUE TITLE
veinminer dupe

### ISSUE THREAD

**Issue by aaa8881** [GC-spigot/AdvancedEnchantments#3426]
### Describe the bug

veinminer produces more ore than it exists when both silk touch and veinminer exist. 

enchantments.yml
```
veinminer:
  display: '%group-color%연쇄 채광'
  description: |-
    광석을 캘 때 주변에 붙어있는 광석들도
    연쇄적으로 채광됩니다.
    &a+ &f쿨타임: &e10&8/&e5&8/&e1초
  applies-to: 곡괭이
  group: ULTIMATE
  type: MINING
  applies:
  - ALL_PICKAXE
  levels:
    '1':
      cooldown: 10
      settings:
        whitelist:
          - "COAL_ORE"
          - "COPPER_ORE"
          - "IRON_ORE"
          - "GOLD_ORE"
          - "LAPIS_ORE"
          - "REDSTONE_ORE"
          - "DIAMOND_ORE"
          - "EMERALD_ORE"
          - "NETHER_QUARTZ_ORE"
          - "NETHER_GOLD_ORE"
          - "ANCIENT_DEBRIS"
          - "DEEPSLATE_COAL_ORE"
          - "DEEPSLATE_COPPER_ORE"
          - "DEEPSLATE_IRON_ORE"
          - "DEEPSLATE_GOLD_ORE"
          - "DEEPSLATE_LAPIS_ORE"
          - "DEEPSLATE_REDSTONE_ORE"
          - "DEEPSLATE_DIAMOND_ORE"
          - "DEEPSLATE_EMERALD_ORE"
      effects:
      - BREAK_BLOCK @Veinmine

```

### How to reproduce

1. silk touch and veinminer both in pickaxe
2. mine more than 8 blocks
3. 9 ore block pops out

- happens worse with 27 ( 3x3x3 ) 

### "/ae plinfo" link

https://paste.md-5.net/juwofezoge
