### ISSUE TITLE
Null Checks in conditions do not work hence no maps, trees. [SET_VARIABLE] [<CONDITION>]

### ISSUE THREAD

**Issue by Skullslice** [GC-spigot/AdvancedEnchantments#3449]
### Describe the bug

```yaml
hashmaptest:
  display: '%group-color%maptest'
  description: |-
    Your 5th hit in a row
    will instantly KILL
  applies-to: Helmets
  type: ATTACK;ATTACK_MOB
  group: RESPLENDENT
  applies:
  - ALL_HELMET
  levels:
    '1':
      chance: 100
      effects:
      - "SET_VARIABLE:hitcounter%attacker name%:0<condition>%hitcounter%attacker name%% = null : %allow%</condition>"
      - "SET_VARIABLE:hitcounter%attacker name%:0<condition>%hitcounter%attacker name%% = '' : %allow%</condition>"
      - "SET_VARIABLE:hitcounter%attacker name%:0<condition>%hitcounter%attacker name%% = undefined : %allow%</condition>"
      - "SET_VARIABLE:hitcounter%attacker name%:0<condition>%hitcounter%attacker name%% = false : %allow%</condition>"
      - "MESSAGE:%hitcounter%attacker name%% <-- This number should be zero @Attacker"
```
The expected outcome of this enchantment is to message the user 0
instead it it messages the placeholder %hitcounterusername%

This is a big bug because in order to use the SET_VARIABLE effect in production servers, it needs to support variable init checks or null checks or return false for undefined variables.

### How to reproduce

copy and paste the hashmaptest enchantment

### "/ae plinfo" link

https://paste.md-5.net/oxofomucim
