### ISSUE TITLE
using %victim name% with @Attacker target prioritizes the placeholder over the target

### ISSUE THREAD

**Issue by Skullslice** [GC-spigot/AdvancedEnchantments#3450]
### Describe the bug

Example Working Enchantment:
```yaml
ultra:
  display: '%group-color%Ultra'
  description: |-
    After 5 kills in a row
    your next hit deals 5x
    increased damage.
  applies-to: Helmets
  type: ATTACK;ATTACK_MOB
  group: RESPLENDENT
  applies:
  - GOLDEN_SWORD
  levels:
    '1':
      chance: 100
      effects:
      - "SET_VARIABLE:killcounter%attacker name%:<math>%custom_killcounter%attacker name%% + 1</math><condition>%victim health% < %damage% : %allow%</condition>"
      - "MESSAGE:%custom_killcounter%attacker name%% @Attacker<condition>%custom_killcounter%attacker name%% < 5 AND %victim health% < %damage% : %allow%</condition>"
      - "INCREASE_DAMAGE:<math>%raw damage% * 4</math> @Attacker<condition>%custom_killcounter%attacker name%% = 5 : %allow%</condition>"
      - "MESSAGE:&7[&f(&a5x&f)&d damage] @Attacker<condition>%custom_killcounter%attacker name%% = 5 : %allow%</condition>"
      - "SET_VARIABLE:killcounter%attacker name%:0<condition>%custom_killcounter%attacker name%% = 5 : %allow%</condition>"
```
Not Working:
```yaml
ultra:
  display: '%group-color%Ultra'
  description: |-
    After 5 kills in a row
    your next hit deals 5x
    increased damage.
  applies-to: Helmets
  type: ATTACK;ATTACK_MOB
  group: RESPLENDENT
  applies:
  - GOLDEN_SWORD
  levels:
    '1':
      chance: 100
      effects:
      - "SET_VARIABLE:killcounter%attacker name%:<math>%custom_killcounter%attacker name%% + 1</math><condition>%victim health% < %damage% : %allow%</condition>"
      - "MESSAGE:%custom_killcounter%attacker name%% @Attacker<condition>%custom_killcounter%attacker name%% < 5 AND %victim health% < %damage% : %allow%</condition>"
      - "INCREASE_DAMAGE:<math>%raw damage% * 4</math> @Attacker<condition>%custom_killcounter%attacker name%% = 5 : %allow%</condition>"
      - "MESSAGE:&7[&f(&a5x&f)&d damage&7 against %victim name%] @Attacker<condition>%custom_killcounter%attacker name%% = 5 : %allow%</condition>"
      - "SET_VARIABLE:killcounter%attacker name%:0<condition>%custom_killcounter%attacker name%% = 5 : %allow%</condition>"
```

### How to reproduce

add %victim name% before @Attacker inside of a MESSAGE effect line

### "/ae plinfo" link

https://paste.md-5.net/uvisazojek
