### ISSUE TITLE
Broken customWeapons and ArmorSets

### ISSUE THREAD

**Issue by KingCueio** [GC-spigot/AdvancedEnchantments#3463]
### Describe the bug

It seems that the "events" or **trigger** are not working via their functionality as I have tried putting effects such as "        - 'POTION:INCREASE_DAMAGE:0:60 @Victim' and attacking the player but it didn't give the player any potion.

### How to reproduce

```
# Advanced Sets
# These sets are fully creatable, to create your own simply copy this file, rename it and edit it however you want!

# ** Set Materials:
# * LEATHER (change-able color) https://github.com/GC-spigot/AdvancedEnchantments/wiki/�-Colored-Leather-Armor
# * IRON
# * GOLD
# * CHAIN
# * DIAMOND

# ** Enchantment effects are supported - view enchantments.yml to see all effects available for sets.

#  ** Set Events
#    Change upon what event should sets trigger
#    - EFFECT_STATIC : Gives permanent potion effect (as long as armor piece is worn)
#    - ATTACK : Set Event run only when attacking another player
#    - DEFENSE : Set Event run only when being attacked
#    - DEFENSE_BOW : Set Event run only when player gets shot by a bow
#    - MINING : Gives effects when block is mined
#    - ATTACK_MOB : Gives effects when player attacks mob
#    - KILL_MOB : Effects given when attacked mob is killed
#    - BOW : Effects given when player is shot by another player
#    - KILL_PLAYER : Effects given when attacker kills a player
#    - DEATH : Runs when player dies due to another player.
#    - RIGHT_CLICK : Runs when player right clicks held item
#    - BOW_MOB : Effects given when mob is shot by player
#    - FIRE : Effects given when player is on fire
#    - EXPLOSION : Effects given when player gets hit by explosion
#    - SWING : Enchant runs when player swings
#    - FALL_DAMAGE : Set Event runs when player takes fall damage
#    - DEFENSE_MOB : Set Event runs when mob attacks a player
#    - SHIFT : Set Event runs when player toggles crouching (shifts)
#    - ITEM_BREAK : Set Event runs when player toggles crouching (shifts)
#    - CATCH_FISH : Set Event runs when player catches a fish
# Set Events & Enchant types are intercompatible together

# ** Creating set effects, this explains the system
#events:
#  <any of the effects from the list>:
#    chance: <chance of effects activating, 1-100> (Optional)
#    cooldown: <cooldown period after effects activate, in seconds> (Optional)
#    effects: <effects are available in enchantments.yml>
#    # E.g.: - 'INCREASED_DAMAGE:10'

name: 'Rune'
material: DIAMOND
settings:
  equipped:
    - '&a&l(!) &aYou have activated the Rune-Forged Guardian set!'
  unequipped:
    - '&c&l(!) &cYou have deactivated the Rune-Forged Guardian set!'
items:
  helmet:
    name: '&a&lRune-Forged Hood'
    # Custom Model Data (for 1.13+ servers with custom item packs)
    # Set custom model data integer
    customModelData: 0
    # Item Flags
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/ItemFlag.html
    itemFlags: []
    #  - 'HIDE_POTION_EFFECTS' # An Example Item Flag
    lore:
      - ''
      - '&7&*oA lost item that emerged'
      - '&7&oIn our dimension, it was said to'
      - '&7&oBe one of weapons in the old'
      - '&7&oDimension that is powerful to'
      - '&7&oBroke pass the barrier of dimensions.'
      - ''
      - '&a&lRUNE-FORGED GUARDIAN SET BONUS'
      - '&aDeal +8% damage to all enemies.'
      - '&aEnemies deal +8% less damage to you.'
      - '&7&o(Requires all 4 supreme items.)'
    enchants: # Supports AdvancedEnchantments CE
      - "protection:4"
      - "unbreaking:3"
  chestplate:
    name: '&a&lRune-Forged Vest'
    # Custom Model Data (for 1.13+ servers with custom item packs)
    # Set custom model data integer
    customModelData: 0
    # Item Flags
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/ItemFlag.html
    itemFlags: []
    #  - 'HIDE_POTION_EFFECTS' # An Example Item Flag
    lore:
      - ''
      - '&7&*oA lost item that emerged'
      - '&7&oIn our dimension, it was said to'
      - '&7&oBe one of weapons in the old'
      - '&7&oDimension that is powerful to'
      - '&7&oBroke pass the barrier of dimensions.'
      - ''
      - '&a&lRUNE-FORGED GUARDIAN SET BONUS'
      - '&aDeal +8% damage to all enemies.'
      - '&aEnemies deal +8% less damage to you.'
      - '&7&o(Requires all 4 supreme items.)'
    enchants: # Supports AdvancedEnchantments CE
      - "protection:4"
      - "unbreaking:3"
  leggings:
    name: '&a&lRune-Forged Leggings'
    # Custom Model Data (for 1.13+ servers with custom item packs)
    # Set custom model data integer
    customModelData: 0
    # Item Flags
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/ItemFlag.html
    itemFlags: []
    #  - 'HIDE_POTION_EFFECTS' # An Example Item Flag
    lore:
      - ''
      - '&7&*oA lost item that emerged'
      - '&7&oIn our dimension, it was said to'
      - '&7&oBe one of weapons in the old'
      - '&7&oDimension that is powerful to'
      - '&7&oBroke pass the barrier of dimensions.'
      - ''
      - '&a&lRUNE-FORGED GUARDIAN SET BONUS'
      - '&aDeal +8% damage to all enemies.'
      - '&aEnemies deal +8% less damage to you.'
      - '&7&o(Requires all 4 supreme items.)'
    enchants: # Supports AdvancedEnchantments CE
      - "protection:4"
      - "unbreaking:3"
  boots:
    name: '&a&lRune-Forged Boots'
    # Custom Model Data (for 1.13+ servers with custom item packs)
    # Set custom model data integer
    customModelData: 0
    # Item Flags
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/ItemFlag.html
    itemFlags: []
    #  - 'HIDE_POTION_EFFECTS' # An Example Item Flag
    lore:
      - ''
      - '&7&*oA lost item that emerged'
      - '&7&oIn our dimension, it was said to'
      - '&7&oBe one of weapons in the old'
      - '&7&oDimension that is powerful to'
      - '&7&oBroke pass the barrier of dimensions.'
      - ''
      - '&a&lRUNE-FORGED GUARDIAN SET BONUS'
      - '&aDeal +8% damage to all enemies.'
      - '&aEnemies deal +8% less damage to you.'
      - '&7&o(Requires all 4 supreme items.)'
    enchants: # Supports AdvancedEnchantments CE
      - "protection:4"
      - "unbreaking:3"
events:
  ATTACK:
    chance: 100
    effects:
      - 'POTION:INCREASE_DAMAGE:0:60'
```

### "/ae plinfo" link

https://paste.md-5.net/epaxehahig
