### ISSUE TITLE
"Dupe" bug with a fishing rod

### ISSUE THREAD

**Issue by Nashlord** [GC-spigot/AdvancedEnchantments#3469]
### Describe the bug

The effect I put on a fishing rod enchantment is triggered by catching an invisible itemadder armorstand (See video).

### How to reproduce

Try putting an enchantment that executes a command on a fishing rod and catch an itemadder armorstand.
The enchantment I use in the video:

```
explorateur_peche:
  display: '&7'
  description: |-
    Permet d'avoir 1% de chance de
    pêcher un diamant.
    &f
    &8✤ &7Equipements : &fCanne ㆀ
  applies-to: Fishing Rod
  type: CATCH_FISH
  group: RARE
  applies:
  - FISHING_ROD
  levels:
    '1':
      chance: 100
      effects:
      - CONSOLE_COMMAND:jobs grantxp %player_name% Explorateur 1
```

### Screenshots / Videos

https://gyazo.com/5f396ac8ed2c4755a0a093ad3bc26b8e

### "/ae plinfo" link

https://paste.md-5.net/faqotacogo
