### ISSUE TITLE
CATCH_FISH/default enchantment bait does not work

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#3480]
### Describe the bug

default enchantment bait does not activate. checking by tuning 100% chance, 0 cooldown, with message indication

and also, no extra fish

### How to reproduce

fish

```
bait:
  display: '%group-color%Bait'
  description: Chance to receive double fishing drops.
  applies-to: Fishing Rod
  type: CATCH_FISH
  group: LEGENDARY
  applies:
    - FISHING_ROD
  levels:
    '1':
      chance: 15
      cooldown: 10
      effects:
        - MORE_DROPS:1
    '2':
      chance: 18
      cooldown: 15
      effects:
        - MORE_DROPS:1
    '3':
      chance: 100
      cooldown: 0
      effects:
        - MORE_DROPS:10
        - MESSAGE:§6bait @Victim
```

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/61608872/0d75013b-e2c3-42d6-828d-93549cdf9494)

### "/ae plinfo" link

https://paste.md-5.net/gukejazegi
