### ISSUE TITLE
Strike enchantment destroys mob's and player's drops

### ISSUE THREAD

**Issue by denisdnu** [GC-spigot/AdvancedEnchantments#3482]
### Describe the bug

Hi! I have an enchantment as follows:
```
strike:
  display: '%group-color%Удар'
  description: "Імовірність вдарити блискавкою в противника"
  applies-to: Мечі, Лук, Арбалет, Тризуб
  type: ATTACK;ATTACK_MOB;SHOOT;SHOOT_MOB
  group: SIMPLE
  settings:
    newVersionsOnly: true # Only load this enchantment if server version is 1.13 or higher
  applies:
  - TRIDENT
  - BOW
  - CROSSBOW
  - ALL_SWORD
  levels:
    '1':
      chance: 24
      cooldown: 3
      effects:
      - LIGHTNING @Victim
    '2':
      chance: 32
      cooldown: 3
      effects:
      - LIGHTNING @Victim
    '3':
      chance: 40
      cooldown: 4
      effects:
      - LIGHTNING @Victim
```

Unfortunately, it destroys both, killed mob drops, and user soul fire placed by the AngelChest plugin on user death. 

### How to reproduce

Apply enchantment to an applicable weapon, and kill a mob that can drop items. Drops that have been stricken by lightning will disappear.

### "/ae plinfo" link

https://paste.md-5.net/tamiciyata
