### ISSUE TITLE
has enchantment placeholders

### ISSUE THREAD

**Issue by SirJben** [GC-spigot/AdvancedEnchantments#3487]
### Describe the bug

```
%has enchantment in hand of <enchant>%
%has enchantment in hand of <enchant> level <level>%
%has enchantment in <slot>%
```
won't work

Tried with vanilla enchantments and AE enchantments

### How to reproduce

Tried with this 
`%attacker has enchantment in hand of KNOCKBACK%`,
`%victim has enchantment in hand of KNOCKBACK%`,
`%player has enchantment in hand of KNOCKBACK%`,

```
test:
  display: '%group-color%Test'
  description: |-
    Testing placeholders
  applies-to: Swords
  type: ATTACK_MOB
  group: ULTIMATE
  applies:
    - ALL_SWORD
  levels:
    '1':
      conditions:
        - '%attacker has enchantment in hand of KNOCKBACK% = true : %allow%'
      effects:
        - MESSAGE:It works!
```

### "/ae plinfo" link

https://paste.md-5.net/ulukuvepim
