### ISSUE TITLE
%damaged from behind% condition is not working

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#3529]
### Describe the bug

This condition is not working, is not returning properly.

### How to reproduce

Create a enchantment with this condition:

```
    1:
      conditions:
        - "%damaged from behind% = true : %allow%"
        - "%is hostile% = true : %chance%+50"
      chance: 50
      cooldown: 110
      effects:
        - 'CANCEL_EVENT @Victim'
```

Test with a zombie attacking you.

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/66658478/f6d4b25d-f1c7-469d-9f10-2e7fd9af93b8)

### "/ae plinfo" link

https://paste.md-5.net/odakipomab
