### ISSUE TITLE
SET_MAX_CATCH_TIME effect is not working

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#3530]
### Describe the bug

I don't know why but this enchantment type is not working. I was previous on 9.0.0 and was working normal until the update.
That message display on trigger:

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/66658478/d361a281-bd64-421e-bed2-17ebd32edeff)

### How to reproduce

Create a enchantment with SET_MAX_CATCH_TIME effect.

```
  type: "ROD_CAST" #also tried with CATCH_FISH
  applies:
    - FISHING_ROD
  levels:
    1:
      chance: 15
      cooldown: 40
      effects:
        - 'SET_MAX_CATCH_TIME:80'
```

And try.

### "/ae plinfo" link

https://paste.md-5.net/odakipomab
