### ISSUE TITLE
Permanent EFFECT_STATIC and REPEATING enchants

### ISSUE THREAD

**Issue by LambChomps** [GC-spigot/AdvancedEnchantments#3535]
### Describe the bug

I've seen this reported similar ways multiple times for a long time but for many updates it has remained unfixed so posting this in hopes to provide a bit more information. 
Both EFFECT_STATIC and REPEATING effect triggers don't detect when armors with the enchant are equipped/unequipped in ways other than "shift-clicking". This very easily leads to effects like Overload giving permanent health boost simply by equipping a chestplate with the enchant to get the effect, then removing the chestplate by any other means and not being detected as no longer equipped to also remove the effect.

### How to reproduce

```yaml
overload:
  display: '%group-color%Overload'
  description: |-
    Gain a constant flat health boost.
  applies-to: Chestplates
  type: EFFECT_STATIC
  group: LEGENDARY
  applies:
    - ALL_CHESTPLATE
  levels:
    '1':
      effects:
        - POTION:HEALTH_BOOST:0
```
1. Shift-click a chestplate with the above enchant to get the effect.
2. Normal click to remove the chestplate, or press a number key to move the chestplate to a hotbar slot.
3. Health boost effect will now be permanent without the chestplate equipped, any other armor can be equipped and effect will persist.

This works with REPEATING effects the exact same way, unequipping them with the same method will still function as if the effect is equipped.

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/84216914/2978975e-d378-4e44-91b3-20cc1191870e

### "/ae plinfo" link

https://paste.md-5.net/equhopuhip
