### ISSUE TITLE
DISABLE_ACTIVATION is not working

### ISSUE THREAD

**Issue by KingCueio** [GC-spigot/AdvancedEnchantments#3536]
```
### Describe the bug

The disable activation in the effect of your plugin is not working, when we are doing a pvp. The CE should proc the effect but at the same time, it's not parsing the effect as if it's not in the code.

### How to reproduce

wood:
  display: '%group-color%Wood'
  description: "Wood cannot be magnetized. Chance to disable Magnet\nenchant from the enemy for 7 seconds. At max level, the chance is 100%."
  applies-to: 'Chestplates'
  type: 'ATTACK'
  group: 'SIMPLE'
  applies:
    - ALL_CHESTPLATE
  levels:
    1:
      chance: 2
      cooldown: 5
      effects:
        - 'DISABLE_ACTIVATION:magnet:7'
    2:
      chance: 4
      cooldown: 5
      effects:
        - 'DISABLE_ACTIVATION:magnet:7'
    3:
      chance: 6
      cooldown: 5
      effects:
        - 'DISABLE_ACTIVATION:magnet:7'
    4:
      chance: 8
      cooldown: 5
      effects:
        - 'DISABLE_ACTIVATION:magnet:7'
    5:
      chance: 10
      cooldown: 5
      effects:
        - 'DISABLE_ACTIVATION:magnet:7'
    6:
      chance: 12
      cooldown: 5
      effects:
        - 'DISABLE_ACTIVATION:magnet:7'
    7:
      chance: 14
      cooldown: 5
      effects:
        - 'DISABLE_ACTIVATION:magnet:7'
    8:
      chance: 16
      cooldown: 5
      effects:
        - 'DISABLE_ACTIVATION:magnet:7'
    9:
      chance: 18
      cooldown: 5
      effects:
        - 'DISABLE_ACTIVATION:magnet:7'
    10:
      chance: 100
      cooldown: 5
      effects:
        - 'DISABLE_ACTIVATION:magnet:7'

### Screenshots / Videos

_No response_

### "/ae plinfo" link

https://paste.md-5.net/qifahoqaya

### Server Log

_No response_
```
