### ISSUE TITLE
 [URGENT] Hook with lands not working properly, once again

### ISSUE THREAD

**Issue by Nashlord** [GC-spigot/AdvancedEnchantments#3552]
### Describe the bug

The hook with lands only half works, yes the enchantments work correctly again if lands is on the server. BUT, only in the world where claims are enabled in the lands config, so in my case, only in the "World" world.

Impossible to make a 3x3 enchantment that works only in the Nether or the End for example. Besides, the "break tree" enchantment is also affected, it only works in the player's claims, nowhere else.

Example of an enchantment that does not work :
```
legendaire_nether:
  display: '&7'
  description: |-
    Procure 20% de chance de miner sur
    3x3 blocs dans le Nether.
  applies-to: Pickaxes, Shovels
  type: MINING
  group: LEGENDAIRE
  applies:
  - ALL_PICKAXE
  - ALL_AXE
  levels:
    '1':
      chance: 20
      settings:
        worldBlacklist:
          - "world"
          - "ressource"
          - "world_the_end"
          - "ile1"
          - "ile2"
          - "ile3"
      effects:
      - BREAK_BLOCK @Trench{r=3}
```

### How to reproduce

1. Install the lands and ae plugin on the server.
2. Just put "world" at the very top of the lands config, in "claim-worlds_list".
3. Try making a trench or break-tree enchantment that works in a world other than "world".

I did a maintenance on my server and just removed the lands plugin to test, all enchantments worked fine without the lands plugin on the server.

### Screenshots / Videos

Error in console when trying to use break-tree enchantment outside of my claims. Or that I use the trench to break blocks outside of my claims : https://pastebin.com/Wv42Bk4w

### "/ae plinfo" link

https://paste.md-5.net/femarinawo
