### ISSUE TITLE
Trench+ more_drops cause shulker box dupe

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#3554]
### Describe the bug

use trench enchantment with more_drop, if trench affect range contains shulker box, the shulker box will be duped

### How to reproduce

1. find ores
2. place shulkerbox next to ores
3. dig ores
4. shulkerbox will be multiplied with the ores
```
more_drops:
  display: '%group-color%more_drops'
  description: words
  applies-to: '&fpickaxe'
  type: MINING
  group: FABLED
  applies:
  - ALL_PICKAXE
  levels:
    '1':
      chance: 100
      conditions: 
      - '%block type% contains ORE : %allow%'
      effects:
      - MORE_DROPS:100
```

```
trench:
  display: '%group-color%trench'
  description: trench
  applies-to: '&fshovel,hoe'
  type: MINING
  group: FABLED
  applies:
  - ALL_PICKAXE
  - ALL_SPADE
  levels:
    '1':
      chance: 100
      effects:
      - BREAK_BLOCK @Trench{r=3}
```

### Screenshots / Videos

https://youtu.be/MVS_Vzfjcb0

### "/ae plinfo" link

https://paste.md-5.net/dojemuqizo

### Server Log

https://paste.denizenscript.com/View/113383
