### ISSUE TITLE
mob kill MORE_DROPS does not prevent "colored" shulkerbox dupe

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#3555]
### Describe the bug

if a mob have "colored" shulker box, kill a mob with more_drops enchantment, can dupe shulkerbox

*Must be "colored" shulker box, default one is patched but other color does not

### How to reproduce

1. get a zombie holding "colored" shulker box, such as orange shulker box
2. kill the mob with more drops
```
more_drop_mob:
  display: '%group-color%more_drop_mob'
  description: more_drop_mob
  applies-to: '&fsword'
  type: KILL_MOB
  group: FABLED
  applies:
  - ALL_SWORD
  levels:
    '1':
      chance: 100
      effects:
      - MORE_DROPS:100
```
### Screenshots / Videos

https://youtu.be/6oa61XdHQfc

### "/ae plinfo" link

https://paste.md-5.net/epapegeqex

### Server Log

https://paste.denizenscript.com/View/113384
