### ISSUE TITLE
Veinmine+trench give abnormal extra blocks (dupe)

### ISSUE THREAD

**Issue by hkkongou** [GC-spigot/AdvancedEnchantments#3556]
### Describe the bug

if veinmine and trench use together, if they have same affect ores, both of them give ores after ore is breaked.

### How to reproduce

1. setblock 5 ores
2. break the block with veinmine and trench
3. it gives 9

```
trench:
  display: '%group-color%trench'
  description: trench
  applies-to: '&fshovel,hoe'
  type: MINING
  group: FABLED
  applies:
  - ALL_PICKAXE
  - ALL_SPADE
  levels:
    '1':
      chance: 100
      effects:
      - BREAK_BLOCK @Trench{r=3}
```

```
veinmine:
  display: '%group-color%veinmine'
  description: veinmine
  applies-to: '&fpickaxe'
  group: ULTIMATE
  type: MINING
  applies:
  - ALL_PICKAXE
  levels:
    '1':
      settings:
        whitelist:
          - "COAL_ORE"
          - "COPPER_ORE"
          - "IRON_ORE"
          - "GOLD_ORE"
          - "LAPIS_ORE"
          - "REDSTONE_ORE"
          - "DIAMOND_ORE"
          - "EMERALD_ORE"
          - "NETHER_QUARTZ_ORE"
          - "NETHER_GOLD_ORE"
          - "ANCIENT_DEBRIS"
          - "DEEPSLATE_COAL_ORE"
          - "DEEPSLATE_COPPER_ORE"
          - "DEEPSLATE_IRON_ORE"
          - "DEEPSLATE_GOLD_ORE"
          - "DEEPSLATE_LAPIS_ORE"
          - "DEEPSLATE_REDSTONE_ORE"
          - "DEEPSLATE_DIAMOND_ORE"
          - "DEEPSLATE_EMERALD_ORE"
      effects:
      - BREAK_BLOCK @Veinmine
```

### Screenshots / Videos

https://youtu.be/yzZnb3CamRk

### "/ae plinfo" link

https://paste.md-5.net/dojemuqizo

### Server Log

https://paste.denizenscript.com/View/113383
