### ISSUE TITLE
Spammy WARN console message (Failed to calculate '%exp%*(1.0+0.25*4)': Invalid syntax or outcome)

### ISSUE THREAD

**Issue by SirvydasS** [GC-spigot/AdvancedEnchantments#3561]
### Describe the bug

Getting spammy WARN message in console when killing mobs in farm with sword who has inquisitive enchant.

```
inquisitive:
  display: '%group-color%Inquisitive'
  description: Chance to increase EXP drops from mobs.
  applies-to: Swords
  type: KILL_MOB
  group: LEGENDARY
  applies:
    - ALL_SWORD
  levels:
    '1':
      chance: 30
      cooldown: 4
      effects:
        - EXP:<math>%exp% * (1.0 + 0.25 * %level%)</math> @Victim
    '2':
      chance: 35
      cooldown: 4
      effects:
        - EXP:<math>%exp% * (1.0 + 0.25 * %level%)</math> @Victim
    '3':
      chance: 40
      cooldown: 4
      effects:
        - EXP:<math>%exp% * (1.0 + 0.25 * %level%)</math> @Victim
    '4':
      chance: 45
      cooldown: 4
      effects:
        - EXP:<math>%exp% * (1.0 + 0.25 * %level%)</math> @Victim

```
### How to reproduce

Have sword with inquisitive  enchant and kill a lot mobs.

### "/ae plinfo" link

https://paste.md-5.net/dekodeqezu

### Server Log

https://pastebin.com/ggCKKghd
