### ISSUE TITLE
Cure the ABSORPTION effect is not working, checked all debug infos

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#3562]
### Describe the bug

The cure type effect is working normally, but, not with ABSORPTION effect.
Even with all debug messages showing that is curing it, it doesn't.

(I'm 1 version below but there is nothing on updated that is related to it).

### How to reproduce

1. Create a enchantment with cure absorption, like the example below:

```
  levels:
    1:
      conditions:
        - "%victim has potion effect ABSORPTION% = true : %allow%"
      chance: 1
      cooldown: 360
      effects:
        - 'CURE:ABSORPTION @Victim'
```
2. Add the absortion effect on you, you may use /effect give nickname minecraft:absorption 40 2
3. Try to parse it. In my case, I used DEFENSE_MOB
4. Check the debug information
5. Nothing happens

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/66658478/8d64de99-1759-44f1-aa02-23a6247b0a9a)

The condition worked, the effect "parsed" but didn't.

### "/ae plinfo" link

https://paste.md-5.net/ihacipiqiv
