### ISSUE TITLE
%has potion effect% Condition only checking victim on hit.

### ISSUE THREAD

**Issue by LambChomps** [GC-spigot/AdvancedEnchantments#3564]
### Describe the bug

(Tested using ATTACK;ATTACK_MOB;SHOOT;SHOOT_MOB, unsure how this effects other triggers)
%has potion effect% and %potion effect level% conditions will only check when the _victim_ has the specified potion and what their level of the potion is ignoring any "victim" or "attacker".

Using the example put in how to reproduce, while only the attacker has slowness the outcome is:
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/84216914/16f05bac-dc91-4c2e-8056-1d701a2bf666)

Whereas the outcome while the victim has slowness is:
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/84216914/22a3d81d-df48-4377-ae84-615439814c26)

### How to reproduce

```yaml
test6:
  display: '%group-color%Enchant Name 6'
  description: |-
    Enchant Description.
  applies-to: Test
  type: ATTACK;ATTACK_MOB;SHOOT;SHOOT_MOB
  group: BASIC
  applies:
    - ALL_SWORD
    - BOW
  levels:
    '1':
      effects:
        - "MESSAGE:%has potion effect slow% | %attacker has potion effect slow% | %victim has potion effect slow% | %victim has potion effect strength%"
        - "MESSAGE:%potion effect level slow% | %attacker potion effect level slow% | %victim potion effect level slow% | %potion effect level strength%"
 ```

### "/ae plinfo" link

https://paste.md-5.net/ucuzosowag
