### ISSUE TITLE
MORE_DROP doesn't work for CATCH_FISH trigger

### ISSUE THREAD

**Issue by aaa8881** [GC-spigot/AdvancedEnchantments#3571]
### Describe the bug

MORE_DROPS doesn't seem to work with CATCH_FISH trigger.

used to work at some point ( I wasn't very aware but players claim it worked at some point, and doesn't work at another point )

seems to be working around at version 9.1.x , stopped working since 9.2.x 

### How to reproduce

```
bait:
  display: '%group-color%전설의 낚시꾼'
  description: |-
    낚시할 때 획득한 아이템을
    추가로 1개 더 얻습니다.
    &a+ &f쿨타임: &e10초
    &a+ &f발동 확률: &b10&8/&b20&8/&b30%
  applies-to: 낚싯대
  type: CATCH_FISH
  group: LEGENDARY
  applies:
  - FISHING_ROD
  levels:
    '1':
      chance: 10
      cooldown: 10
      effects:
      - MORE_DROPS:1
    '2':
      chance: 20
      cooldown: 10
      effects:
      - MORE_DROPS:1
    '3':
      chance: 30
      cooldown: 10
      effects:
      - MORE_DROPS:1
```

try

### "/ae plinfo" link

https://paste.md-5.net/qinequtawe
