### ISSUE TITLE
Vanilla Enchantment - '%has enchantment in hand of <enchant>% Not working

### ISSUE THREAD

**Issue by KingCueio** [GC-spigot/AdvancedEnchantments#3576]
### Describe the bug

"  '%player has enchantment in hand of SILK_TOUCH% = true" is not working, even if it's saying it's true. It doesn't parse into the code as it will only just bypass the condition itself. 

Kindly check **all Vanilla Enchantment** with this condition, as we tried doing this with other vanilla enchantment. But it seems it's not working.

But it do works on Advanced Enchantments though

### How to reproduce

```
viridium:
  display: '%group-color%Viridium'
  description: "Chance to get extra souls from emerald ores.\nHigher levels gives chance to get experience aswell.\nThis enchantment cannot be removed."
  applies-to: 'PICKAXE'
  type: 'MINING'
  group: 'LOST'
  applies:
    - ALL_PICKAXE
  levels:
    1:
      chance: 100
      conditions:
        - '%player has enchantment in hand of SILK_TOUCH% = true : %stop%'
        - '%block type% = EMERALD_ORE : %allow% '
      effects:
        - 'ADD_SOULS:650'
        - 'MESSAGE:[10s] The essence of viridium intertwined with your pickaxe, granting you extra souls.'
```

### "/ae plinfo" link

https://paste.md-5.net/enibotozof
