### ISSUE TITLE
DISABLE_ACTIVATION not working latest ver

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#3579]
### Describe the bug

DISABLE_ACTIVATION effect is not working

### How to reproduce

Try with these enchants:
The enchant deactivator:
```infinityvoid:
  display: '%group-color%&lInfinity Void'
  description: 'On proc, your target will not be able to move and pearl out for a long duration.'
  applies-to: 'Swords'
  type: 'ATTACK'
  group: 'FOUR'
  applies:
    - ALL_SWORD
  levels:
    1:
      effects:
        - 'DISABLE_ACTIVATION:warcry:5 @Victim'
        - 'DISABLE_ACTIVATION:ionshell:5 @Victim'
        - 'DISABLE_ACTIVATION:windwalker:5 @Victim'
        - 'DISABLE_ACTIVATION:clarity:5 @Victim'
        - 'WAIT:5'
        - 'MESSAGE:{#7A0041}&l** INFINITY VOID ** @Attacker'
        - 'MESSAGE:{#7A0041}&l** YOU HAVE BEEN VOIDED&7(5s) ** @Victim'
        - 'POTION:SLOW:40:100 @Victim'
        - 'POTION:BLINDNESS:0:100 @Victim'
        - 'CANCEL_USE:ENDER_PEARL:100 @Victim'
```

The deactivated enchant:
```
ionshell:
  display: '%group-color%&lIon Shell'
  description: 'Gain permanent immunity to negative buffs(Except for Infinity Void).'
  applies-to: 'Armor'
  type: 'DEFENSE'
  group: 'FOUR'
  applies:
    - ALL_ARMOR
  levels:
    1:
      effects:
        - CURE:WITHER
        - CURE:WEAKNESS
        - CURE:SLOW
        - CURE:SLOW_DIGGING
        - CURE:BLINDNESS
```

### Screenshots / Videos

https://streamable.com/j0b969

### "/ae plinfo" link

https://paste.md-5.net/okohomevad

### Server Log

https://mcpaste.io/3adfaa678b6164ba

**Comment by illudota** [comment]
on latest version, it gets deactivated, however, it is deactivated forever and doesnt come back:
```
test:
  display: '%group-color%&lTest'
  description: "test"
  applies-to: 'Armor'
  type: 'REPEATING'
  group: 'FOUR'
  applies:
    - ALL_ARMOR
  levels:
    1:
      time: 1
      effects:
        - 'MESSAGE:{#7A0041}&l** TEST **'
```

```
test2:
  display: '%group-color%&lTest II'
  description: "test 2"
  applies-to: 'Swords'
  type: 'ATTACK'
  group: 'FOUR'
  applies:
    - ALL_SWORD
  levels:
    1:
      effects:
        - 'DISABLE_ACTIVATION:test:100 @Victim'
        - 'MESSAGE:DISABLED @Attacker'
```
