### ISSUE TITLE
Math Library <math>

### ISSUE THREAD

**Issue by Skullslice** [GC-spigot/AdvancedEnchantments#3581]
### Describe the bug

I had to use the papi math expansion to parse a player location variable because the variable provided by the plugin itself was rounded to int instead of double. I shouldn't have to use papi for this, and advanced enchantments shouldnt be rounding numbers everywhere under the sun. Why not put number formatting into the hands of enchantment makers with something like evalEX? https://ezylang.github.io/EvalEx/references/functions.html which is what the papi math placeholder uses.
Here is the enchantment that I had to recode with PAPI because AE wasn't up to the task for this one.
```yaml
gladiator:
  display: '%group-color%Gladiator'
  description: |-
    Gladiator test
  applies-to: Mystics
  type: ATTACK;ATTACK_MOB
  group: RESPLENDENT
  applies:
  - GOLDEN_SWORD
  levels:
    '1':
      chance: 100
      effects:
      - "SET_VARIABLE:distance:%math_abs(sqrt(({attacker player_x_long}-{victim player_x_long})^2+({attacker player_y_long}-{victim player_y_long})^2+({attacker player_z_long}-{victim player_z_long})^2))%"
      - "INCREASE_DAMAGE:100 @Victim<condition>%custom_distance% < 2.5 : %allow%</condition>"
      - "DECREASE_DAMAGE:<math>%custom_distance% * 40</math> @Victim<condition>%custom_distance% < 2.5 : %allow%</condition>"
      - "MESSAGE:&7[&dtest distance&7] &f-> %custom_distance%! @Attacker"
```
I am not 100% sure because I haven't tested everything else but I believe there's other places where AE unnecessarily rounds numbers where that should be up to the creators of the enchantment. I needed this distance enchantment to have precise location variable but since AE rounded the variable %victim x% %victim y% %victim z% to INT and left out the precision, I had to use a third party location from PAPI placeholders. I know its a difficult feat to implement or change existing features but I believe you guys can work on this or change the existing math to support evalEX functions. This should be available to end users as it is available in other plugins.

### How to reproduce

Not bug but feature request.

### "/ae plinfo" link

https://paste.md-5.net/ulexebinaf
