### ISSUE TITLE
Experience custom enchant dupes itemsadder custom block 

### ISSUE THREAD

**Issue by Truongvv10** [GC-spigot/AdvancedEnchantments#3644]
### Describe the bug

# When mining a custom block, it dupes when using _experience enchant_ on it and _high efficiency_. Custom blocks are usually noteblocks

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/67742370/83c14b7a-ef33-4933-bc44-96803976b6aa)

```yml
sacredexperience:
  display: "%group-color%Sacred Experience"
  description: |-
    Chance to get more experience
    from mining blocks.

     {#AB20FD}+ {#D9CAC3}ᴘʀᴏᴄ ᴄʜᴀɴᴄᴇ ● &f30&8/&f45&8/&f60&8/&f70&8/&f80
     {#AB20FD}+ {#D9CAC3}ᴄᴏᴏʟᴅᴏᴡɴ     ● &f1 ꜱᴇᴄᴏɴᴅ
     {#AB20FD}+ {#D9CAC3}ᴍᴜꜱᴛ ʜᴀᴠᴇ    ● &fᴇxᴘᴇʀɪᴇɴᴄᴇ 5
  applies-to: Pickaxe, Axe, Spades
  type: MINING
  group: SACRED
  settings:
    not-applyable-with:
      - detonate
      - blast
    required-enchants:
      - experience:5
    removed-enchants:
      - experience
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
    - ALL_AXE
    - ALL_HOE
  levels:
    "1":
      chance: 30
      cooldown: 1
      effects:
        #- "CONSOLE_COMMAND:cmi ctellraw Truongvv <T>19</T>"
        - EXP:<random number>10-40</random number> @Block
    "2":
      chance: 45
      cooldown: 1
      effects:
        #- "CONSOLE_COMMAND:cmi ctellraw Truongvv <T>20</T>"
        - EXP:<random number>10-40</random number> @Block
    "3":
      chance: 60
      cooldown: 1
      effects:
        #- "CONSOLE_COMMAND:cmi ctellraw Truongvv <T>21</T>"
        - EXP:<random number>15-40</random number> @Block
    "4":
      chance: 70
      cooldown: 1
      effects:
        #- "CONSOLE_COMMAND:cmi ctellraw Truongvv <T>22</T>"
        - EXP:<random number>15-40</random number> @Block
    "5":
      chance: 80
      cooldown: 1
      effects:
        #- "CONSOLE_COMMAND:cmi ctellraw Truongvv <T>23</T>"
        - EXP:<random number>10-40</random number> @Block
```

### How to reproduce

Put experience on your pickaxe with high efficiency. 

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/67742370/0198c03c-603c-4241-906c-03ac7a74fb1d

### "/ae plinfo" link

https://paste.md-5.net/sexedeyeki

### Server Log

https://mcpaste.io/afc75946c218d7a1
