### ISSUE TITLE
Incompatibility with MythicLib

### ISSUE THREAD

**Issue by SoraShiunin** [GC-spigot/AdvancedEnchantments#3645]
### Describe the bug

AE Do_Harm on target/victim does nothing with mythiclib installed. (Which is needed to run MythicMobs and MMOItems). I guess this is because of their damage calculation thing with mmoitems.
**Everything else seems to work**. So I thought I'd bring the issue here after 2 months of inactivity from mythiclib :(.
If anything can be done to change it so it works with MythicLib, I'd appreciate it.

### How to reproduce

Use an enchant similar to:
```
teststick2:
  display: '%group-color%Do Harm 2'
  description: |-
    &fDamages extra 
  applies-to: Axes
  type: ATTACK_MOB
  group: UNIQUE
  applies:
  - STICK
  - BOW
  levels:
    '1':
      effects:
      - DO_HARM:6 @VICTIM
```

Expected result: The stick does 6 extra damage. 
Actual result: 1 damage is dealt to the mob.

### Screenshots / Videos

https://www.youtube.com/watch?v=PPuW1xqIhnk

### "/ae plinfo" link

https://paste.md-5.net/eqepeyeciw
