### ISSUE TITLE
Internal placeholders such as %food% or %time% aren't working as intended

### ISSUE THREAD

**Issue by Folas1337** [GC-spigot/AdvancedEnchantments#3648]
### Describe the bug

Any of the placeholders that AE provides for the config such as %food% or %time% don't seem to be resolved and when trying to use them, I'm giving the error message of "Condition <condition> contains letters, but must be numeric only." even for plugins which are pre defined.

It seems this was introduced in version 9.3.18 cause when downgrading from it to 9.3.17 it works again, probably with the following change: `Fixes with condition regex parsing`

So if you could look into that, I'd be more than happy.

### How to reproduce

I made the following changes for Implants so people can still eat to get saturation if they wanted to:
```yaml
implants:
  display: '%group-color%Implants'
  description: |-
    &r[&6General Purpose&r]
    Chance to gain
    hunger bars every
    few seconds.
  applies-to: Helmets
  type: REPEATING
  time: 5
  group: ULTIMATE
  applies:
  - ALL_HELMET
  levels:
    '1':
      time: 5
      conditions:
      - '%food% > 18 : %stop%'
      chance: 30
      effects:
      - ADD_FOOD:1
```
And that ends up in the screenshot error below.

### Screenshots / Videos

![grafik](https://github.com/GC-spigot/AdvancedEnchantments/assets/39222968/3019917a-5023-4765-9c81-e14d776d67cf)
![grafik](https://github.com/GC-spigot/AdvancedEnchantments/assets/39222968/bb3845f6-b3d4-4000-8ec0-513a3a2b8ada)

### "/ae plinfo" link

https://paste.md-5.net/omofewituh
