### ISSUE TITLE
effect not working when using nested placeholders

### ISSUE THREAD

**Issue by Skullslice** [GC-spigot/AdvancedEnchantments#3652]
### Describe the bug

```yaml
explotrench:
  display: '%group-color%Explosive Trench'
  description: Explodes blocks in area.
  applies-to: Pickaxes, Shovels
  type: MINING
  group: CHAOS
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
  levels:
    '1':
      chance: 100
      cooldown: 8
      effects:
        - "CONSOLE_COMMAND:execute as %formatter_text_lowercase_{player_world_type}% run summon minecraft:tnt %block x% %block y% %block z% {Fuse:160}"
```
the debug output shows something is recognized by parsing+ but the effect is never run in my console
![2023-09-10_07 39 27](https://github.com/GC-spigot/AdvancedEnchantments/assets/53416455/180dccfd-550d-4e87-b371-79835431aa11)
![2023-09-10_07 41 12](https://github.com/GC-spigot/AdvancedEnchantments/assets/53416455/7ae3daaf-2c32-435b-b624-a6792edd1862)
![2023-09-10_07 45 46](https://github.com/GC-spigot/AdvancedEnchantments/assets/53416455/5303c47d-e9c6-4c85-bdd9-de8cec2d9ecc)

### How to reproduce

I think it occurs because parsing+ isnt handling the placeholders correctly because papi parse handles it just fine but for me it doesnt work in the enchants.yml am i formatting it wrong or is parsing+ handling it wrong?

### "/ae plinfo" link

https://paste.md-5.net/kuhuhipele

### Server Log

https://mclo.gs/CU6UqHe

**Comment by ThomasWega** [comment]
Seems like you just have wrong command in the effects. If I use 

```yaml
      effects:
        - "CONSOLE_COMMAND:execute in %formatter_text_lowercase_{player_world_type}% run summon minecraft:tnt %block x% %block y% %block z% {Fuse:160}"
```

it works just fine

**Comment by ThomasWega** [comment]
this is not us, this is the way formatter placeholders from PAPI works. If you check console, you will see what the issue is. Formatter returns "nether", but the dimension is named "the_nether"

**Comment by Skullslice** [comment]
for future enchanters this is how i fixed it:
```yaml
explotrench:
  display: '%group-color%Explosive Trench'
  description: Explodes blocks in area.
  applies-to: Pickaxes, Shovels
  type: MINING
  group: CHAOS
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
  levels:
    '1':
      chance: 100
      cooldown: 8
      effects:
        - "CONSOLE_COMMAND:execute in overworld run summon minecraft:tnt %block x% %block y% %block z% {Fuse:160}<condition>%player_world_type% = overworld : %allow%</condition>"
        - "CONSOLE_COMMAND:execute in the_end run summon minecraft:tnt %block x% %block y% %block z% {Fuse:160}<condition>%player_world_type% = end : %allow%</condition>"
        - "CONSOLE_COMMAND:execute in the_nether run summon minecraft:tnt %block x% %block y% %block z% {Fuse:160}<condition>%player_world_type% = nether : %allow%</condition>"
```
