### ISSUE TITLE
TRIGGER CATCH_FISH still works with entities

### ISSUE THREAD

**Issue by Nashlord** [GC-spigot/AdvancedEnchantments#3654]
### Describe the bug

the effect of a fishing rod enchantment is triggered when you try to fish for entities, be it a mob stack or an itemadder's invisible armorstand, for example.

### How to reproduce

- Put the enchantment below on a fishing rod.
- Place a monster, with an egg for example, and try to fish it several times until the effect is triggered. 
- you should receive an emerald in your inventory.

```
emeraude_peche:
  display: '&7'
  description: |-
    Procure 10% de chance de pêcher
    un quartz du Nether
  applies-to: Fishing Rod
  type: CATCH_FISH
  group: EPIQUE
  applies:
  - FISHING_ROD
  levels:
    '1':
      chance: 10
      conditions:
      - '%player checkitem_getinfo:offhand_custommodeldata:% = 3 : %stop%'
      cooldown: 5
      effects:
      - CONSOLE_COMMAND:give %player_name% emerald 1
```

### Screenshots / Videos

https://gyazo.com/f6c620c937ea8c3aa4e8374282161a97

### "/ae plinfo" link

https://paste.md-5.net/uxojesukiw
