### ISSUE TITLE
CUSTOMFISHING plugin conflict

### ISSUE THREAD

**Issue by Nashlord** [GC-spigot/AdvancedEnchantments#3656]
### Describe the bug

If I have an advancedenchant on my rod, no matter what the enchantment, I catch a vanilla fish in addition to the custom fish. 

I'm only supposed to catch the custom fish, Customfishing disables vanilla fish. And it was still working fine before I updated advancedenchant this morning. I was using version 9.3.9 until now.

Plugin customfishing : https://polymart.org/resource/customfishing.2723

### How to reproduce

- Install the customfishing plugin, activate it in the world you want and deactivate the vanilla fish drop.
- Try fishing with a rod that has a fishing advancedenchant.

I don't think you need a texture pack to install customfishing.

The enchantment I used to test :
```
emeraude_peche_test:
  display: '&ctest'
  description: |-
    Procure 10% de chance de pêcher
  applies-to: Fishing Rod
  type: CATCH_FISH
  group: EPIQUE
  applies:
  - FISHING_ROD
  levels:
    '1':
      chance: 5
      conditions:
      - '%player checkitem_getinfo:offhand_custommodeldata:% = 3 : %stop%'
      cooldown: 5
      effects:
      - CONSOLE_COMMAND:give %player_name% emerald 1
```

### Screenshots / Videos

https://gyazo.com/4ba92bbc7e9680dcb4210229e94f62c2

### "/ae plinfo" link

https://paste.md-5.net/nohomamesu
