### ISSUE TITLE
REPEATING seems to be bugged during world change.

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#3662]
### Describe the bug

Repeating enchant still working even if you take the item off.

### How to reproduce

```
lethaltempo:
  display: '{#ffd555}&lL{#f4ce5b}&le{#e9c761}&lt{#dec067}&lh{#d3b96d}&la{#c8b373}&ll {#bcac78}&lT{#b1a57e}&le{#a69e84}&lm{#9b978a}&lp{#909090}&lo'
  description: "Permanent Speed III and immunity to all debuffs."
  applies-to: 'Boots'
  type: 'REPEATING'
  group: 'EXCLUSIVES'
  applies:
    - ALL_BOOTS
  settings:
    removeable: false
  levels:
    1:
      time: 1
      chance: 100
      effects:
      - 'POTION:SPEED:3:80'
      - 'CURE_PERMANENT:BLINDNESS'
      - 'CURE_PERMANENT:WEAKNESS'
      - 'CURE_PERMANENT:SLOW'
      - 'CURE_PERMANENT:SLOW_DIGGING'
```
Use this, then switch to another world then take it off and see it'll never go away.

### Screenshots / Videos

https://streamable.com/b7v8lg

### "/ae plinfo" link

https://paste.md-5.net/ramodefipo

### Server Log

https://mcpaste.io/5deb5d979ea34739
