### ISSUE TITLE
exploit to farm unlimited mcmmo with a SWING type enchant

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#3688]
### Describe the bug

After **9.0.0b81** some triggers became incompatible in many ways. 

This enchantment with this type and conditions can exploit the experience from mcmmo

Check this video: https://imgur.com/tzdx5Ta

### How to reproduce

1. Create this enchantment:
```
lala:
  display: '%group-color%lala'
  description: " lala"
  applies-to: 'Picaretas'
  type: "SWING"
  group: 'RARO'
  applies:
    - ALL_PICKAXE
  levels:
    1:
      chance: 85
      cooldown: 14
      conditions:
        - '%can break% = true : %continue%'
        - '%block type% = OBSIDIAN : %allow%'
      effects:
        - 'BREAK_BLOCK @Block'
```

2. Apply on a item
3. Left click on a ancient debris with mcmmo installed

### Screenshots / Videos

 https://imgur.com/tzdx5Ta

### "/ae plinfo" link

https://paste.md-5.net/exajefehoq
