### ISSUE TITLE
ADD_DURABILITY it does not work correctly

### ISSUE THREAD

**Issue by axeldupuy** [GC-spigot/AdvancedEnchantments#3728]
### Describe the bug

ADD_DURABILITY_ITEM: If you have armor with the same enchantment level, only repair 1 piece of armor

ADD_DURABILITY_ARMOR repairs all armor pieces even if they are not enchanted. But the amount does not stack if they have the same enchantment level; for example: helmet lvl1 (+5), chest lvl2 (+10): when I receive damage all my armor is repaired +15, but if I have helmet lvl1 (+5), chest lvl1 (+5): all my armor is repaired +5

ADD_DURABILITY_CURRENT_ITEM, works the same as ADD_DURABILITY_ITEM

```
durabilidad:
  display: 'durabilidad'
  description: |-
    durabilidad
  applies-to: Armor
  type: DEFENSE
  group: ELITE
  applies:
    - ALL_ARMOR
  levels:
    '1':
      cooldown: 5
      effects:
        - ADD_DURABILITY_ARMOR:-5
    '2':
      cooldown: 5
      effects:
        - ADD_DURABILITY_ARMOR:-10
```

### How to reproduce

ADD_DURABILITY_ITEM: If you have armor with the same enchantment level, only repair 1 piece of armor

ADD_DURABILITY_ARMOR repairs all armor pieces even if they are not enchanted. But the amount does not stack if they have the same enchantment level; for example: helmet lvl1 (+5), chest lvl2 (+10): when I receive damage all my armor is repaired +15, but if I have helmet lvl1 (+5), chest lvl1 (+5): all my armor is repaired +5

ADD_DURABILITY_CURRENT_ITEM, works the same as ADD_DURABILITY_ITEM

```
durabilidad:
  display: 'durabilidad'
  description: |-
    durabilidad
  applies-to: Armor
  type: DEFENSE
  group: ELITE
  applies:
    - ALL_ARMOR
  levels:
    '1':
      cooldown: 5
      effects:
        - ADD_DURABILITY_ARMOR:-5
    '2':
      cooldown: 5
      effects:
        - ADD_DURABILITY_ARMOR:-10
```

WITHOUT COOLDOWN IT WORKS WELL

### "/ae plinfo" link

https://paste.md-5.net/igusadatow
