### ISSUE TITLE
[REQUEST] Pointers for materials.

### ISSUE THREAD

**Issue by SirJben** [GC-spigot/AdvancedEnchantments#3778]
### Describe the bug

Add materials for pointers too.

e.g.
```
  applies:
    - ALL_SWORD
    - ALL_AXE
  levels:
    '1':
      effects:
        - DECREASE_DAMAGE:40 @Attacker ~DEFENSE ~ALL_AXE
        - DECREASE_DAMAGE:50 @Attacker ~DEFENSE ~ALL_SWORD
```

### How to reproduce

N/A

### "/ae plinfo" link

N/A
