### ISSUE TITLE
Issue with FIREBALL (BOW)

### ISSUE THREAD

**Issue by Frostyeiz** [GC-spigot/AdvancedEnchantments#378]
uhmm so it boost player up (like rocket escape) instead of shooting a fireball...
```
hellfire:
  display: '%group-color%Hellfire'
  description: "ll"
  applies-to: 'll'
  type: 'BOW'
  group: 'ULTIMATE'
  applies:
  - BOW
  levels:
    1:
      chance: 10
      cooldown: 3
      effects:
      - 'FIREBALL %victim%'
```
