### ISSUE TITLE
enchantments are not applied to golden armor

### ISSUE THREAD

**Issue by aaa8881** [GC-spigot/AdvancedEnchantments#3786]
### Describe the bug

enchantments are not applied to golden armor
ae 9.5.7

### How to reproduce

```yml
nightvision:
  display: '%group-color%야간 투시경'
  description: 영구적으로 야간 투시 효과를 얻습니다.
  applies-to: 투구
  type: EFFECT_STATIC
  group: ELITE
  applies:
  - LEATHER_HELMET
  - IRON_HELMET
  - GOLDEN_HELMET
  - DIAMOND_HELMET
  - NETHERITE_HELMET
  - CHAINMAIL_HELMET
  levels:
    '1':
      effects:
      - POTION:NIGHT_VISION:0
      ```

1. apply something like above to golden armor
2. check if it works
      
      

### Screenshots / Videos

prob don't need. already posted in ae discord ticket if need. 

### "/ae plinfo" link

-

### Server Log

-

**Comment by aaa8881** [comment]
```
nightvision:
  display: '%group-color%야간 투시경'
  description: 영구적으로 야간 투시 효과를 얻습니다.
  applies-to: 투구
  type: EFFECT_STATIC
  group: ELITE
  applies:
  - ALL_HELMET
  levels:
    '1':
      effects:
      - POTION:NIGHT_VISION:0
      ```

just for information, used to be ``ALL_HELMET`` instead of listing all helmet material. just tried to make sure ``ALL_HELMET`` is not broken.
