### ISSUE TITLE
AOE effects dont work latest version AE and 1.20.2 paper **MAJOR ISSUE**

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#3795]
### Describe the bug

AOE effects not working, all my AOE enchants that used to work now don't work.

### How to reproduce

create an AOE effect and see for yourself.

### Screenshots / Videos

none, but its easy to reproduce. but try out this test enchant and see.
```
test:
  display: 'test'
  description: "test"
  applies-to: Swords
  group: EXCLUSIVES
  type: RIGHT_CLICK
  applies:
    - ALL_SWORD
  settings:
    removeable: false
  levels:
    '1':
      cooldown: 5
      effects:
        - 'PLAY_SOUND_OUTLOUD:ENTITY_DRAGON_FIREBALL_EXPLODE'
        - 'REMOVE_HEALTH:5 @Aoe{radius=5,target=damageable}'
```

### "/ae plinfo" link

https://paste.md-5.net/yimedoveta

### Server Log

https://mcpaste.io/2d349878f44d652d
