### ISSUE TITLE
AOE issue (REOPEN)

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#3799]
### Describe the bug

https://github.com/GC-spigot/AdvancedEnchantments/issues/3795
This was closed so i have to reopen because the issue still persists, listen.

Ok so I did some testing and it shows that removing target=damageable makes it work, the thing is we're not allies or whatsoever and he is damageable, as you can see on the video.

### How to reproduce

Check clip below.
Used enchants on the clips:

Enchant working:
```
test:
  display: 'Test'
  description: "test"
  applies-to: 'Swords'
  type: 'RIGHT_CLICK'
  group: 'EXCLUSIVES'
  applies:
    - ALL_SWORD
  settings:
    removeable: false
  levels:
    1:
      effects:
        - 'PLAY_SOUND_OUTLOUD:ENTITY_DRAGON_FIREBALL_EXPLODE'
        - 'DO_HARM:5 @Aoe{radius=5}'
        - 'MESSAGE:TEST @Aoe{radius=5}'
```

Enchant not working:
```
test:
  display: 'Test'
  description: "test"
  applies-to: 'Swords'
  type: 'RIGHT_CLICK'
  group: 'EXCLUSIVES'
  applies:
    - ALL_SWORD
  settings:
    removeable: false
  levels:
    1:
      effects:
        - 'PLAY_SOUND_OUTLOUD:ENTITY_DRAGON_FIREBALL_EXPLODE'
        - 'DO_HARM:5 @Aoe{radius=5,target=damageable}'
        - 'MESSAGE:TEST @Aoe{radius=5,target=damageable}'
```

### Screenshots / Videos

https://streamable.com/b2icvp

### "/ae plinfo" link

https://paste.md-5.net/naviduhebu

### Server Log

https://mcpaste.io/24f80ff77e43946a
