### ISSUE TITLE
EFFECT_STATIC and REPEATING types not working

### ISSUE THREAD

**Issue by SuperiorHome0** [GC-spigot/AdvancedEnchantments#3802]
### Describe the bug

EFFECT_STATIC and REPEATING both do not work with
these effects I was testing:

- POTION:<POTION>:<LEVEL>:[TICKS]
- POTION_OVERRIDE:<POTION>:<LEVEL>:[TICKS]
- LAVA_WALKER
- WATER_WALKER
- FLY

When the type is used there are no error commands in console
or any feedback from the plugin in-game, and the enchantments do not work.

### How to reproduce

To reproduce I pasted in the glowing enchantment and it simply did not work at all

glowing:
  display: '%group-color%Glowing'
  description: Gives permanent night vision.
  applies-to: Helmet
  type: EFFECT_STATIC
  group: SIMPLE
  applies:
    - ALL_HELMET
  levels:
    '1':
      effects:
        - POTION:NIGHT_VISION:0
  
Down below is the original enchantment I tested, and both the default enchantment glowing and the one I created produce the same results.

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/150862319/0fdf74ec-50df-4e66-bf62-26c7ab05eb6c)

### "/ae plinfo" link

https://paste.md-5.net/jolesiguva

### Server Log

https://mclo.gs/Uprv2Fv

**Comment by austv** [comment]
@SuperiorHome0 latest version is working fine, try this instead:

```
  type: 'EFFECT_STATIC'
  group: 'CELESTIALBLESSINGS'
  applies:
    - ALL_CHESTPLATE
  levels:
    1:
      effects:
        - 'POTION:FAST_DIGGING:0'
```
