### ISSUE TITLE
armor-items: bug

### ISSUE THREAD

**Issue by SirJben** [GC-spigot/AdvancedEnchantments#3832]
### Describe the bug

For some reason, when I tried to add PAPER or WOODEN_PICKAXE might other item too in armor-section: and if I have this enchantment
```
vikingpetpal:
  display: '%group-color%♦ &fVikings Vain'
  description: "Gives Strength."
  applies-to: "Helmets"
  removeable: false
  type: "EFFECT_STATIC"
  group: "SIMPLE"
  applies:
  - WOODEN_PICKAXE
  - PAPER
  levels:
    '1':
      effects:
      - POTION:STRENGTH:1
```
I can get the bug effects where it stays.

P.S. I am trying to reproduce this #2703, his helmets are custom helmets of WOODEN_PICKAXE. 
P.P.S. The effects work normally in ordinary armors. 

### How to reproduce

Have PAPER or WOODEN_PICKAXE in armor-items: config.yml and then either right-click the item or shift+left-click and it will apply the effect without going in the armor slot inventory.

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/63577950/9811b393-bf64-442a-b0cf-52b33116dfa5)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/63577950/aa652ab3-142b-4cab-b4c7-639b420b3713)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/63577950/0fcac1d4-8abe-4ba1-8740-a8319b26ab18)

### "/ae plinfo" link

https://paste.md-5.net/tutidesowo
