### ISSUE TITLE
Enchantments applying where they shouldn't

### ISSUE THREAD

**Issue by Folas1337** [GC-spigot/AdvancedEnchantments#3835]
### Describe the bug

This is a rather complicated bug report but I'll try to be as concise as possible.

I'll start with the easiest: Experience. By default you can enchant shovels and pickaxes BUT the condition says it only applies if the block you've broken is an ORE! Problem is, you normally NEVER break any ORES with a SHOVEL. So that's already broken but worse than that, if you remove the condition to make it work for shovels, too, you have now created an infinite source of experience for no cost (except for time). Because now you can break sugar cane (for example) with your pickaxe that has Experience and it'll drop experience orbs every time.

The same seems to be happening for pretty much all enchantments, another example would be Reforged. You put it on your pickaxe and start breaking sugar cane again and it repairs while never taking any damage, basically turning it into free Mending.

Therefor I suggest one of two things:
1. Enchantments by default only apply to blocks that "make sense", like ores and stone blocks for pickaxes and sand, gravel, soul soil, dirt etc. for shovels
2. And this might be the more flexible solution. You add a new condition variable which allows to check for block tags such as "#minecraft:mineable/shovel" which shows up when you hit F3 and look at a block because with this I could simply add
```yaml
conditions:
  - %block tag% = #minecraft:mineable/shovel OR %block tag% = #minecraft:mineable/pickaxe
```
to the enchantment and would be done.

Either solution is fine with me but this definitely needs to be implemented/fixed in my opinion. I don't even see this as a feature request but certainly more of a bug fix cause this is probably the outcome anyone would expect from these enchantments.

### How to reproduce

Not applicable

### Screenshots / Videos

Not applicable

### "/ae plinfo" link

https://paste.md-5.net/faqedosuwe

### Server Log

Not applicable

**Comment by Folas1337** [comment]
Still here and hoping for an update soon :)
I'd definitely appreciate at least some acknowledgement or reaction of some kind so I know if I can expect this, even if it's just in the far future :)

**Comment by GC-spigot** [comment]
Hey! Yes I can confirm Ive seen this. Will be updating default enchants once Im free (currently focused on advancedseasons).

**Comment by Folas1337** [comment]
> Hey! Yes I can confirm Ive seen this. Will be updating default enchants once Im free (currently focused on advancedseasons).

Totally fine if you're busy with something else, just wanted to know if it's been overlooked or anything, so thanks for the response!

But you said "Will be updating default enchants"?! I didn't mean to say you should change the enchants like in enchantments.yml but instead make those effects compatible with the tools you're using.
I wanted to make either the effects only target blocks that work with the tool you are using, it would probably ideally be done in code, otherwise the conditions might become really complicated to write.

But I guess you'll read it in more detail when you actually get time to look at it and until then I may stay patient. Thanks once more! :)

**Comment by ThomasWega** [comment]
This is what I've came up with. I've added %block tags% placeholder which returns an array of block Tags. This would be what it returns for stone

```yaml
[minecraft@mineable/pickaxe,minecraft@base_stone_overworld,minecraft@nether_carver_replaceables,minecraft@moss_replaceable,minecraft@overworld_carver_replaceables,minecraft@sculk_replaceable_world_gen,minecraft@goats_spawnable_on,minecraft@dripstone_replaceable_blocks,minecraft@lush_ground_replaceable,minecraft@stone_ore_replaceables,minecraft@snaps_goat_horn,minecraft@sculk_replaceable,minecraft@azalea_root_replaceable]
```

now, this is how you might use it in an enchantment

```yaml
bok:
  display: '%group-color%Test'
  description: Test.
  applies-to: Pickaxes, Shovels
  type: MINING
  group: SIMPLE
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
  levels:
    '1':
      chance: 100
      conditions:
        - '%block tags% contains minecraft@mineable/pickaxe : %allow%'
      effects:
        - MESSAGE:%block tags%
```

please note that the formatting changed for the Key. It's not ```minecraft:mineable/pickaxe``` as you'd expect but it's ```minecraft@mineable/pickaxe```. The reason for this is we already pass different formatting with ```:``` so we needed to change the character to something else to properly parse the whole key.

One thing to also note is that I have not tested the performance of this. I doubt it will cause any issues, but just beware of that.

Hope this is what you wanted

**Comment by Folas1337** [comment]
Sounds on point by dearest @ThomasWega 

I'll give this a try and even give feedback on here if it worked. It's certainly a feature I'm very much looking forward to!! Thanks a bunch for the effort already! 💛

**Comment by ThomasWega** [comment]
You will need to wait for the next update though :)

**Comment by Folas1337** [comment]
Literally trying yours:
```
bok:
  display: '%group-color%Test'
  description: Test.
  applies-to: Pickaxes, Shovels
  type: MINING
  group: SIMPLE
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
  levels:
    '1':
      chance: 100
      #conditions:
      #  - '%block tags% contains minecraft@mineable/pickaxe : %allow%'
      effects:
        - MESSAGE:Test %block tags%
```
And I'm getting this message in chat:
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/39222968/4c8fa790-996a-4588-99f6-6c5818444a28)

What... the hecc? I am 100% on version 9.5.27 and if I add the condition back, it works on nothing, no matter what I try, even blocks that do definitely have the `#minecraft:mineable/pickaxe` block tag...

Could you please reopen this and check it again? I'd be very grateful @ThomasWega
