### ISSUE TITLE
HELD trigger not working as expected.

### ISSUE THREAD

**Issue by TheBadshah** [GC-spigot/AdvancedEnchantments#3840]
### Describe the bug

it only works when enchant is applied not on changing/holding item
once effect is removed / cleared we wont get it again by changing/holding item

### How to reproduce

Default haste enchant can be used to check that

```
haste:
  display: '%group-color%Haste'
  description: Allows you to swing your tools faster.
  applies-to: Tools
  type: HELD
  group: SIMPLE
  applies:
  - ALL_PICKAXE
  - ALL_SPADE
  - ALL_AXE
  levels:
    '1':
      effects:
      - POTION:FAST_DIGGING:0
    '2':
      effects:
      - POTION:FAST_DIGGING:1
    '3':
      effects:
      - POTION:FAST_DIGGING:2
```

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/116473315/e58088ca-7ece-4136-8e1a-4f43451edd0f

### "/ae plinfo" link

https://paste.md-5.net/tulunehame
