### ISSUE TITLE
AOE effect not working

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#3841]
### Describe the bug

AOE effect is not working at all latest version

### How to reproduce

try this:
```
test:
  display: 'Test'
  description: "test"
  applies-to: 'Swords'
  type: 'RIGHT_CLICK'
  group: 'EXCLUSIVES'
  applies:
    - ALL_SWORD
  settings:
    removeable: false
  levels:
    1:
      effects:
        - 'MESSAGE:TEST AOE'
        - 'REMOVE_HEALTH:6 @Aoe{radius=5,target=damageable}'
        - 'MESSAGE:TEST @Aoe{radius=5,target=damageable}'
```

### Screenshots / Videos

https://streamable.com/hqrsqd

### "/ae plinfo" link

https://paste.md-5.net/esoyivalev

### Server Log

https://mcpaste.io/a272324937d4e6b1
