### ISSUE TITLE
INCREASE_DAMAGE not worked frequently

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3843]
### Describe the bug

Increase_damage is not triggered from time to time.
This occurs after updating AE from version 9.3.11 to the latest version.
As you can see in the video, if the enchant is applied, 20 damage should be done,
but only 9 damage was done, and the damage was applied normally after reconnecting.
And then it doesn't apply again over time, but it also applies over time.

### How to reproduce

I can't reproduce why this is not triggered either. Repeatedly, it was triggered or not from time to time.
but i can confirm this bugs happend after update version of AE.

검성:
  display: '%group-color%검성'
  description: 데미지가 대폭 증가합니다.
  applies-to: 
  type: ATTACK_MOB
  group: 레전더리
  applies:
  - ALL_SWORD
  levels:
    '1':
      conditions:
      - "%has enchantment in hand of 검성% = true : %allow%"
      - '%attacker has potion effect HERO_OF_THE_VILLAGE% = true : %stop%'
      effects:
      - INCREASE_DAMAGE:<random number>100-110</random number> @Victim
    '2':
      conditions:
      - "%has enchantment in hand of 검성% = true : %allow%"
      - '%attacker has potion effect HERO_OF_THE_VILLAGE% = true : %stop%'
      effects:
      - INCREASE_DAMAGE:<random number>110-120</random number> @Victim
    '3':
      conditions:
      - "%has enchantment in hand of 검성% = true : %allow%"
      - '%attacker has potion effect HERO_OF_THE_VILLAGE% = true : %stop%'
      effects:
      - INCREASE_DAMAGE:<random number>120-130</random number> @Victim
    '4':
      conditions:
      - "%has enchantment in hand of 검성% = true : %allow%"
      - '%attacker has potion effect HERO_OF_THE_VILLAGE% = true : %stop%'
      effects:
      - INCREASE_DAMAGE:<random number>130-140</random number> @Victim

### Screenshots / Videos

https://youtu.be/hjF5DMUe8nc

### "/ae plinfo" link

https://paste.md-5.net/acijikogah

**Comment by ThomasWega** [comment]
Please send the enchantment formatted correctly

**Comment by Ecilpse** [comment]
> Please send the enchantment formatted correctly https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

```
검성:
  display: '%group-color%검성'
  description: 데미지가 대폭 증가합니다.
  applies-to: 
  type: ATTACK_MOB
  group: 레전더리
  applies:
  - ALL_SWORD
  levels:
    '1':
      conditions:
      - "%has enchantment in hand of 검성% = true : %allow%"
      - '%attacker has potion effect HERO_OF_THE_VILLAGE% = true : %stop%'
      effects:
      - INCREASE_DAMAGE:<random number>100-110</random number> @Victim
    '2':
      conditions:
      - "%has enchantment in hand of 검성% = true : %allow%"
      - '%attacker has potion effect HERO_OF_THE_VILLAGE% = true : %stop%'
      effects:
      - INCREASE_DAMAGE:<random number>110-120</random number> @Victim
    '3':
      conditions:
      - "%has enchantment in hand of 검성% = true : %allow%"
      - '%attacker has potion effect HERO_OF_THE_VILLAGE% = true : %stop%'
      effects:
      - INCREASE_DAMAGE:<random number>120-130</random number> @Victim
    '4':
      conditions:
      - "%has enchantment in hand of 검성% = true : %allow%"
      - '%attacker has potion effect HERO_OF_THE_VILLAGE% = true : %stop%'
      effects:
      - INCREASE_DAMAGE:<random number>130-140</random number> @Victim
```

**Comment by ThomasWega** [comment]
I can see you are using custom mobs. Try with normal mobs and see if the issue persists please

**Comment by Ecilpse** [comment]
> I can see you are using custom mobs. Try with normal mobs and see if the issue persists please
The same problem happened with vanilla mobs.

**Comment by Ecilpse** [comment]
is it not checked yet?

**Comment by ThomasWega** [comment]
It's weird that sometimes it works for you and sometimes it doesn't. I did pretty tough testing and still was not able to replicate this. Maybe some other plugin is sometimes modifying the damage event. The only thing we do is listen to the EntityDamageEvent and increase the damage. If you can isolate the issue more and do some debugging (ex. seeing if the enchantment even runs), I will be happy to address this issue more. There is nothing I can do now unfortunately

**Comment by Ecilpse** [comment]
> 9.3.11 to the latest version.

If the AE version is 9.3.11 version, it works normally. not other settings changed.
I think this is a problem caused by AE changing the algorithm of INCREASE_DAMAGED in patches between version 9.3.11 and version 9.5.20.

**Comment by Ecilpse** [comment]
https://github.com/GC-spigot/AdvancedEnchantments/assets/25452835/0923e111-d198-407a-baae-d381bda14311

after cast skill mythicmobs + mmoitems, INCREASE_DAMAGED was not worked.

**Comment by ThomasWega** [comment]
does the mob have ignore-enchantments attribute by any chance?

**Comment by Ecilpse** [comment]
> does the mob have ignore-enchantments attribute by any chance?

no.

i found some critical clues. this problems has been updated after 9.4.3

i tested several build.

9.5.20 x
9.5.1 x
9.4.4 x
9.4.3 x
9.4.2 o
9.4.0 o

**Comment by ThomasWega** [comment]
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/84a587cc-019a-4c02-8682-cdf45206b4ef)
this would make sense haha

**Comment by Ecilpse** [comment]
tested mob has not any options for enchants attribute
```
데미지_측정:
  Type: HUSK
  Health: 10000
  Damage: 1
  BossBar:
    Enabled: true
    Title: '&f<caster.hp>&7/&6<caster.mhp>'
    Range: 50
    Color: RED
    Style: SEGMENTED_12
    DarkenSky: false
  Options:
    PreventJockeyMounts: true
    NoDamageTicks: 5
    MovementSpeed: 0.2
    ShowHealth: false
    PreventRandomEquipment: true
    AlwaysShowName: false
    Persistent: false
    Despawn: false
    PreventOtherDrops: true
    FollowRange: 50
    Silent: true
    KnockbackResistance: 1
    PreventSunburn: true
    Collidable: false
  DamageModifiers:
  - FALL 0
  AIGoalSelectors:
  - clear
  AITargetSelectors:
  - 0 clear
```

**Comment by Ecilpse** [comment]
> ![image](https://private-user-images.githubusercontent.com/82312488/294721164-84a587cc-019a-4c02-8682-cdf45206b4ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MDk4NDEsIm5iZiI6MTcwNDYwOTU0MSwicGF0aCI6Ii84MjMxMjQ4OC8yOTQ3MjExNjQtODRhNTg3Y2MtMDE5YS00YzAyLTg2ODItY2RmNDUyMDZiNGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDA2MzkwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4OWVlM2ZmYzFlYTY5NjdlNjQ2YjcxMmQ1MzdkZTIzZDE4NTA3M2JhNDAxOWVlZmZhNWNmNjg1MzgxNTlhYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BZj7n9iOjnzyiipYFW_ZCrBRMYPtTtonUeLkHMJpD3w) this would make sense haha

tested mob has not any options for enchants attribute
```
데미지_측정:
  Type: HUSK
  Health: 10000
  Damage: 1
  BossBar:
    Enabled: true
    Title: '&f<caster.hp>&7/&6<caster.mhp>'
    Range: 50
    Color: RED
    Style: SEGMENTED_12
    DarkenSky: false
  Options:
    PreventJockeyMounts: true
    NoDamageTicks: 5
    MovementSpeed: 0.2
    ShowHealth: false
    PreventRandomEquipment: true
    AlwaysShowName: false
    Persistent: false
    Despawn: false
    PreventOtherDrops: true
    FollowRange: 50
    Silent: true
    KnockbackResistance: 1
    PreventSunburn: true
    Collidable: false
  DamageModifiers:
  - FALL 0
  AIGoalSelectors:
  - clear
  AITargetSelectors:
  - 0 clear
```
