### ISSUE TITLE
ARROW_HIT effect doesn't seems to work

### ISSUE THREAD

**Issue by TheBadshah** [GC-spigot/AdvancedEnchantments#3847]
### Describe the bug

The enchant never triggers even though there's no condition or something.

### How to reproduce

```
teleport:
  display: '%group-color%Teleport'
  description: 'Teleports you to the where the arrow lands'
  applies-to: 'Bows'
  type: 'ARROW_HIT'
  group: 'EVENT'
  applies:
    - BOW
  levels:
    1:
      effects:
        - 'TELEPORT location=%hit location%'
        - 'MESSAGE:a' 
```
        
        

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/116473315/7da6c788-d5e1-4e4f-b31e-43c1f61fc04f

### "/ae plinfo" link

https://paste.md-5.net/wajohiveko
