### ISSUE TITLE
AOE issue(Faction members getting damaged by target=damageable)

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#3848]
### Describe the bug

My alt shouldn't be damaged by AOE as the targets should only be damageable, AOE used to work fine but now it even damages faction members.

see how when I hit my alt with a normal attack, it says you can't hurt because it cancels damage, but AOE just bypasses that and hurts my faction members.

The latest update fixed AOE not working, now what's left is this, where AOE still damages some undamageable people, like Faction members / ally members, please add compatibility, thanks! so Faction servers won't experience this.

### How to reproduce

get Factions plugin, make a test CE that target is only damageable and activate it, see how your faction member gets damaged as well.

```
test:
  display: 'Test'
  description: "test"
  applies-to: 'Swords'
  type: 'RIGHT_CLICK'
  group: 'EXCLUSIVES'
  applies:
    - ALL_SWORD
  settings:
    removeable: false
  levels:
    1:
      effects:
        - 'MESSAGE:TEST AOE'
        - 'REMOVE_HEALTH:5 @Aoe{radius=5,target=damageable}'
        - 'MESSAGE:TEST @Aoe{radius=5,target=damageable}'
```

### Screenshots / Videos

https://streamable.com/r1pmv5

### "/ae plinfo" link

https://paste.md-5.net/uyorufejuw

### Server Log

https://mcpaste.io/158585c1338c44a8
