### ISSUE TITLE
ADD_ENCHANT dupe

### ISSUE THREAD

**Issue by SirJben** [GC-spigot/AdvancedEnchantments#3850]
### Describe the bug

ADD_ENCHANT duplicates.

### How to reproduce

```
soulboundtest1:
  display: '%group-color%Soulbound'
  description: You may not lost your item on death
  applies-to: any armor or weapon
  type: DEATH;PASSIVE_DEATH
  group: SOULBOUND
  applies:
  - PLAYER_HEAD
  - ALL_TOOLS
  - ALL_SWORD
  - ALL_AXE
  - ALL_ARMOR
  - BOW
  - CROSSBOW
  levels:
    '1':
      chance: 100
      effects:
      - REMOVE_ENCHANT:soulboundtest1
      - KEEP_ON_DEATH
    '2':
      chance: 100
      effects:
      - REMOVE_ENCHANT:soulboundtest1
      - ADD_ENCHANT:soulboundtest1:1
      - KEEP_ON_DEATH
    '3':
      chance: 100
      effects:
      - REMOVE_ENCHANT:soulboundtest1
      - ADD_ENCHANT:soulboundtest1:2
      - KEEP_ON_DEATH
      ```

### Screenshots / Videos

https://i.gyazo.com/3aaeb3a58dec95be4fefa3c8fa31c829.mp4

### "/ae plinfo" link

9.5.21

**Comment by ThomasWega** [comment]
Should be fixed in the next version

**Comment by ThomasWega** [comment]
You don't actually need to remove the enchantment but only downgrade it.

This works fine
```yaml
soulboundtest1:
  display: '%group-color%Soulbound'
  description: You may not lost your item on death
  applies-to: any armor or weapon
  type: DEATH;PASSIVE_DEATH
  group: SIMPLE
  applies:
  - PLAYER_HEAD
  - ALL_TOOLS
  - ALL_SWORD
  - ALL_AXE
  - ALL_ARMOR
  - BOW
  - CROSSBOW
  levels:
    '1':
      chance: 100
      effects:
      - REMOVE_ENCHANT:soulboundtest1
      - KEEP_ON_DEATH
    '2':
      chance: 100
      effects:
      - ADD_ENCHANT:soulboundtest1:1
      - KEEP_ON_DEATH
    '3':
      chance: 100
      effects:
      - ADD_ENCHANT:soulboundtest1:2
      - KEEP_ON_DEATH
```
