### ISSUE TITLE
Duplication glitch 

### ISSUE THREAD

**Issue by TheBadshah** [GC-spigot/AdvancedEnchantments#3853]
### Describe the bug

with combination of wait and any durability effect you can dupe the item which have the enchantment by moving it from its slot.

### How to reproduce

Use an enchant with combination of wait and any durability.

 like:

```
test1:
  display: '{#004455}🛡 Heart of the Warden'
  description: test
  applies-to: Chestplate
  type: RIGHT_CLICK
  group: EVENT
  settings:
    removeable: false
  applies:
    - ALL_CHESTPLATE
  levels:
    1:
      cooldown: 20
      conditions:
        - '%player is sneaking% = FALSE : %stop%'
        - '%player player_item_in_hand% = AIR : %allow%'
      effects:
        - 'MESSAGE:on'
        - 'WAIT:200'
        - 'ADD_DURABILITY_CURRENT_ITEM:-10'
        - 'MESSAGE:off'
```

Now after its effect activates remove the Chestplate from Chest slot.

tada

### Screenshots / Videos

https://clipchamp.com/watch/YTRPIfjWfvR

### "/ae plinfo" link

https://paste.md-5.net/ivetitaden
