### ISSUE TITLE
Trench

### ISSUE THREAD

**Issue by VladikIar4ik** [GC-spigot/AdvancedEnchantments#3861]
### Describe the bug

that Trench doesn't work with sands, dirt, etc.
Even using ALL_SHOVEL with it.

bulldozer:
  display: "&7Бульдозер"
  description: ""
  applies-to: "Tools"
  settings:
  group: Unique
  type: MINING
  applies:
  - ALL_PICKAXE
  - ALL_SHOVEL
  levels:
    1:
      settings:
        - "SAND"
        - "DIRT"
        - "GRASS_BLOCK"
      effects:
      - BREAK_BLOCK @Trench{r=3}
    2:
      effects:
      - BREAK_BLOCK @Trench{r=3}

### How to reproduce

bulldozer:
  display: "&7Бульдозер"
  description: ""
  applies-to: "Tools"
  settings:
  group: Unique
  type: MINING
  applies:
  - ALL_PICKAXE
  - ALL_SHOVEL
  levels:
    1:
      settings:
        - "SAND"
        - "DIRT"
        - "GRASS_BLOCK"
      effects:
      - BREAK_BLOCK @Trench{r=3}
    2:
      effects:
      - BREAK_BLOCK @Trench{r=3}

### Screenshots / Videos

https://youtu.be/bbH8tCcd6-E

### "/ae plinfo" link

https://paste.md-5.net/opofutuqor

**Comment by ThomasWega** [comment]
It works absolutely fine, you just have improper formatting. 

```yaml
trench:
  display: '%group-color%Trench'
  description: Chance to break in 3x3 area.
  applies-to: Pickaxes, Shovels
  type: MINING
  group: ULTIMATE
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
  levels:
    '1':
      chance: 13
      effects:
        - BREAK_BLOCK @Trench{r=3}
    '2':
      chance: 26
      effects:
        - BREAK_BLOCK @Trench{r=3}
    '3':
      chance: 36
      effects:
        - BREAK_BLOCK @Trench{r=3}
    '4':
      chance: 49
      effects:
        - BREAK_BLOCK @Trench{r=3}
    '5':
      chance: 59
      effects:
        - BREAK_BLOCK @Trench{r=3}
    '6':
      chance: 72
      effects:
        - BREAK_BLOCK @Trench{r=3}
    '7':
      chance: 85
      effects:
        - BREAK_BLOCK @Trench{r=3}
    '8':
      chance: 90
      effects:
        - BREAK_BLOCK @Trench{r=3}
    '9':
      chance: 100
      effects:
        - BREAK_BLOCK @Trench{r=3}
```

if you want to blacklist some materials, that's in config.yml under settings trench-blacklist
