### ISSUE TITLE
CUSTOM HEADS DO NOT LOAD WITH THE FORMATS I FOUND

### ISSUE THREAD

**Issue by Duplimon** [GC-spigot/AdvancedEnchantments#3878]
### Describe the bug

I spent several days trying to make custom heads appear in the /enchanter menu, but it never happened, I used the formats they gave me and I still didn't achieve anything.

### How to reproduce

type: PLAYER_HEAD
value: base64
id: 3

type: PLAYER_HEAD
owner: base64
id: 3

type: PLAYER_HEAD
material: base64
id: 3

type: PLAYER_HEAD
skin: base64
id: 3

advanced-heads: ID

type: PLAYER_HEAD
value: nick
id: 3

....

### Screenshots / Videos

.

### "/ae plinfo" link

https://paste.md-5.net/lazaxitoxe

### Server Log

.

**Comment by ThomasWega** [comment]
correct, it did not work. Will be fixed in the next version. Just make sure the ```head``` is outside of the item section

example:
```yaml
      item:
        type: PLAYER_HEAD
        id: 0
        custom-model-data: 0
        force-glow: false
      enchant-group: SIMPLE
      price: exp:400
      head: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjcwNWZkOTRhMGM0MzE5MjdmYjRlNjM5YjBmY2ZiNDk3MTdlNDEyMjg1YTAyYjQzOWUwMTEyZGEyMmIyZTJlYyJ9fX0=
      sound: BLOCK_ANVIL_LAND
      name: "&f&lSimple Enchantment &7(Right Click)"
      lore:
        - "&7Examine to receive a random"
        - "&fsimple &7enchantment book."
        - ""
        - "&b&lCOST &f%price% EXP &7(You need %left% more EXP)"
```
