### ISSUE TITLE
Command Effect Type for Armors Idea

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#3880]
### Describe the bug

EFFECT TYPE IDEA: COMMAND 
You know why I found this very cool? Imagine let's say, binded abilities in Minecraft! this will make minecraft like a damn league of legends game or games that have keybinds

Let's say
```
globalsilence:
  display: 'Global Silence'
  description: "Silence all enemies around you (/globalsilence to activate)"
  applies-to: Armor
  group: EXCLUSIVES
  type: COMMAND
  applies:
    - ALL_SWORD
  settings:
    removeable: false
  command: /globalsilence
  levels:
    '1':
      cooldown: 60
      effects:
        - 'DISABLE_ACTIVATION:test:5 @Aoe{radius=5,target=damageable}'
```

then players can bind the command to a key themselves by then, how cool would that be? I know we have RIGHT_CLICK, but imagine abilities with keybinds, so a command type would be very revolutionary for this plugin, I have never seen anything like it. what do you think?

### How to reproduce

none

### Screenshots / Videos

none

### "/ae plinfo" link

none

### Server Log

none
