### ISSUE TITLE
Broken customWeapon file

### ISSUE THREAD

**Issue by KingCueio** [GC-spigot/AdvancedEnchantments#3882]
### Describe the bug

same issue as https://github.com/GC-spigot/AdvancedEnchantments/issues/3463

The event or trigger doesn't work in the file itself.

### How to reproduce

```
# Advanced Sets Weapons
#
# What set should be required in order to apply effects from this weapon?
# Set to '' to not require a set
requireSet: ''
material: IRON_AXE
customModelData: 0
itemFlags: []
name: '&6&lApex Axe'
lore:
- '&f&lGrade: &6&lA'
- ''
- '&6&lAPEX WEAPON BONUS'
- '&6&lDeal +7.5% damage to all enemies.'
enchants:
- sharpness:%3-8%
- unbreaking:%1-5%
events:
  ATTACK_MOB:
    chance: 100
    effects:
    - LIGHTNING @Aoe{radius=5,target=damageable}
    cooldown: 0
```

### "/ae plinfo" link

https://paste.md-5.net/eroritomiv
