### ISSUE TITLE
endless implants (ADD_FOOD)

### ISSUE THREAD

**Issue by wundertraume** [GC-spigot/AdvancedEnchantments#3886]
### Describe the bug

Just try putting your default implants on yourself and take it off, you will have an infinite food boost forever 

### How to reproduce

```
implants:
  display: '%group-color%Импланты'
  description: |-
    Шанс восстановить еду
    каждые несколько секунд.
  applies-to: Шлем
  type: REPEATING
  group: ULTIMATE
  applies:
    - ALL_HELMET
    - PLAYER_HEAD
  levels:
    '1':
      chance: 20
      time: 5
      effects:
        - ADD_FOOD:1
    '2':
      chance: 40
      time: 5
      effects:
        - ADD_FOOD:1
    '3':
      chance: 60
      time: 4
      effects:
        - ADD_FOOD:1
    '4':
      chance: 80
      time: 4
      effects:
        - ADD_FOOD:1
    '5':
      chance: 100
      time: 4
      effects:
        - ADD_FOOD:1
```

### Screenshots / Videos

https://youtu.be/F3VwtLA0Xrc

### "/ae plinfo" link

https://paste.md-5.net/umekajegol
