### ISSUE TITLE
Enchants Command Doesn't Tab Complete

### ISSUE THREAD

**Issue by Kaludii** [GC-spigot/AdvancedEnchantments#3892]
### Describe the bug

Hello, the `/enchants` command that is under `menus/customcommands.yml` does not tab-complete when enabled.

### How to reproduce

Enable `/enchants` command similar to below and see that it doesnt tab-complete ingame.

menus/customcommands.yml:
```
enchantments:
  # Is this command enabled?
  enabled: true
  # Change the command
  # Use it in game: /<command>
  command: /enchants
  # Permission for command
  # Set to '' to disable
  permission: ''
  # Message when opening menu
  # Set to [] to disable
  message:
  - '&7Showing list of all enchantments...'
```

### "/ae plinfo" link

https://paste.md-5.net/ijayolakeb
