### ISSUE TITLE
Disarm Hooked_Entitys does not work.

### ISSUE THREAD

**Issue by i407250234i** [GC-spigot/AdvancedEnchantments#3897]
### Describe the bug

Good day. I'm looking forward to increase the charm of the fishing rod in fighting, but i don't know if hook_entity is the right trigger to disarm. As the Discord support mentioned, it might not be implemented yet and linked me to GitHub.
The Enchantment looks like this...  
Ty for your awesome work

```
steal:
  display: '%group-color%Steal'
  description: Disarm your oponent and get some exp and money from fishing the oponent.
  applies-to: Fishing Rod
  type: HOOK_ENTITY
  group: ULTIMATE
  applies:
    - FISHING_ROD
  levels:
    '1':
      chance: 5
      cooldown: 12
      effects:
        - STEAL_EXP:<random number>10-50</random number> @Victim
        - STEAL_MONEY:<random number>10-50</random number> @Victim
        - DISARM @Victim
    '2':
      chance: 15
      cooldown: 12
      effects:
        - STEAL_EXP:<random number>25-100</random number> @Victim
        - STEAL_MONEY:<random number>25-100</random number> @Victim
        - DISARM @Victim
```

### How to reproduce

Put Disarm on a hooked_Entity Trigger using enchantment.

### "/ae plinfo" link

https://paste.md-5.net/hovasoliwa
