### ISSUE TITLE
Request: Ability to add more alias to commands in the config

### ISSUE THREAD

**Issue by Kaludii** [GC-spigot/AdvancedEnchantments#3908]
### Describe the bug

Suggestion: As the title states, it'd be nice to be able to add more alias' for commands, specifically the `/ae info` command. We can do this through commands.yml or mycommand plugin but that doesnt tab complete the enchants.

Something like below, but for ae info:
```
  enchanter:
    # Is command enabled?
    enabled: true
    # Main command to open Enchanter
    command: /enchanter
    # List of commands that will act as the command
    aliases:
    - e
    - ce
```

### How to reproduce

Read above.

### "/ae plinfo" link

https://paste.md-5.net/siraxalape
