### ISSUE TITLE
Dupe/offhand override when applying  ADD_DURABILITY_CURRENT_ITEM

### ISSUE THREAD

**Issue by xenxero1** [GC-spigot/AdvancedEnchantments#3909]
### Describe the bug

Found a dupe bug using this custom enchant

```
counter:
  display: '%group-color%Counter'
  description: placeholder.
  applies-to: Shields
  settings:
    showActionBar: true
  type: SHIELD_BLOCK
  group: LEGENDARY
  applies:
    - SHIELD
  levels:
    '1':
      cooldown: 1
      effects:
        - ADD_DURABILITY_CURRENT_ITEM:-20 
        - POTION:SLOWNESS:3:60 @Attacker
        - POTION:SPEED:1:60 @Self
        - DO_HARM:6 @Attacker
```

Applying this to a shield, and having someone attack while you block, will remove whatever item is in their off-hand, and replace it with an exact copy of this shield including enchants, ae enchants, and durability.

The issue lies with `- ADD_DURABILITY_CURRENT_ITEM:-20 ` as removing it from the effects list prevents the item replacement from occuring. This is not ideal for a long term solution however.

### How to reproduce

Add the following enchant to enchantments.yml

```
counter:
  display: '%group-color%Counter'
  description: placeholder.
  applies-to: Shields
  settings:
    showActionBar: true
  type: SHIELD_BLOCK
  group: LEGENDARY
  applies:
    - SHIELD
  levels:
    '1':
      cooldown: 1
      effects:
        - ADD_DURABILITY_CURRENT_ITEM:-20 
        - POTION:SLOWNESS:3:60 @Attacker
        - POTION:SPEED:1:60 @Self
        - DO_HARM:6 @Attacker
```
        
Either have a player or yourself hold a shield with this enchantment applied.

The other player hits the shield while having an item in their off-hand.

Dupe achieved.

### "/ae plinfo" link

https://paste.md-5.net/viqolecopo

**Comment by xenxero1** [comment]
Reconfirmed presence in AE version 9.6.2

**Comment by ThomasWega** [comment]
Could you please send a video showcase?

**Comment by xenxero1** [comment]
Sure thing, here are some videos.

WITH durability effect present (DUPE):
https://youtu.be/rObbbEAUck0

WITHOUT durability effect (NO DUPE):
https://youtu.be/3jhS9_MfEF4


Here is the enchantment I'm using 
```
counter:
  display: '%group-color%Counter'
  description: |-
    Counter an enemies attack with your own.
  applies-to: Shields
  settings:
    showActionBar: true
  type: SHIELD_BLOCK
  group: FABLED
  applies:
    - SHIELD
  levels:
    '1':
      cooldown: 5e
      effects:
        - ADD_DURABILITY_CURRENT_ITEM:-20 @Self
        - POTION:SLOWNESS:3:60 @Attacker
        - POTION:SPEED:1:60 @Self
        - DO_HARM:6 @Attacker
```
