### ISSUE TITLE
More buggy behavior with "required-enchants" and anvils

### ISSUE THREAD

**Issue by Leomelonseeds** [GC-spigot/AdvancedEnchantments#3930]
### Describe the bug

So `not-applyable-with` appears to be fixed with anvils, but `required-enchants` has an issue where if `removed-enchants` has the same enchantment as `required-enchants`, no matter if it is vanilla or custom, the anvil will not allow you to combine it altogether, showing the "X" in the GUI. If `removed-enchants` is unset, then there is no issue combining the items.

On this topic, is it perhaps a limitation of the Spigot API that we cannot show the "X" for other cases? For example, if I place swords with fire aspect and ice aspect (incompatible vanilla and custom enchant respectively) in the 1st and 2nd slots of the anvil, the resultant slot will still show a sword with fire aspect, even though vanilla behavior would be to disallow the combination, showing an "X". 

### How to reproduce

Below is the relevant enchant, requiring the vanilla fire aspect enchant to apply. 
- Place a sword enchanted with fire aspect 2 in the first slot, and an immolate book in the second slot, and see that the anvil will not let you combine them.
- Now remove the `removed-enchants` section, and repeat the above. Now the anvil combine works fine.
```
immolate:
  display: '%group-color%Immolate'
  description: |-
    Sets all enemies within hit
    range on fire. Requires Fire
    Aspect II to apply.
  applies-to: Sword
  type: ATTACK;ATTACK_MOB
  group: LEGENDARY
  applies:
  - ALL_SWORD
  settings:
    required-enchants:
    - fire_aspect:2
    removed-enchants:
    - fire_aspect
  levels:
    '1':
      effects:
      - PARTICLE:BURN:20:2 @Aoe{radius=3, target=damageable}
      - BURN:4 @Aoe{radius=3, target=damageable}
      - PARTICLE:BURN:20:2 @Aoe{radius=3, target=mobs}
      - BURN:4 @Aoe{radius=3, target=mobs}
    '2':
      effects:
      - PARTICLE:BURN:20:2 @Aoe{radius=3, target=damageable}
      - BURN:8 @Aoe{radius=3, target=damageable}
      - PARTICLE:BURN:20:2 @Aoe{radius=3, target=mobs}
      - BURN:8 @Aoe{radius=3, target=mobs}
```
      

### "/ae plinfo" link

https://paste.md-5.net/cifuyihomo
