### ISSUE TITLE
BUG - Disable Enchant Feature

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#3937]
### Describe the bug

```
disable-enchants:
  # Disable enchants in specific world
  raidworld: # world name
    - gears
```
this doesn't work, 

### How to reproduce

```
disable-enchants:
  # Disable enchants in specific world
  raidworld: # world name
    - gears
```

```
gears:
  display: '%group-color%&lGears'
  description: Added speed when equipped.
  applies-to: Boots
  type: EFFECT_STATIC
  group: ONE
  applies:
  - ALL_BOOTS
  levels:
    '1':
      effects:
      - POTION:SPEED:2
```

### Screenshots / Videos

None

### "/ae plinfo" link

I like my plugins private, butserver version: 1.20.2-R0.1-SNAPSHOT
