### ISSUE TITLE
BUG - Disable enchant in specific world broken

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#3938]
### Describe the bug

```
disable-enchants:
  # Disable enchants in specific world
  raidworld: # world name
    - gears
```
this feature doesn't work, enchants still work on world "raidworld"

### How to reproduce

```
disable-enchants:
  # Disable enchants in specific world
  raidworld: # world name
    - gears
```

```
gears:
  display: '%group-color%&lGears'
  description: Added speed when equipped.
  applies-to: Boots
  type: EFFECT_STATIC
  group: ONE
  applies:
  - ALL_BOOTS
  levels:
    '1':
      effects:
      - POTION:SPEED:2
```

### Screenshots / Videos

None

### "/ae plinfo" link

I like my plugins private, but server version: 1.20.2-R0.1-SNAPSHOT, AE version: 9.6.0 

### Server Log

Log was too big + I prefer my logs private
