### ISSUE TITLE
Broken condition customWeapon file

### ISSUE THREAD

**Issue by KingCueio** [GC-spigot/AdvancedEnchantments#3940]
### Describe the bug

The conditions in customWeapon file doesn't work.

It does not work with any condition type

### How to reproduce

```
# Advanced Sets Weapons
#
# What set should be required in order to apply effects from this weapon?
# Set to '' to not require a set
requireSet: ''
material: IRON_AXE
customModelData: 0
itemFlags: []
name: '&6&lApex Axe'
lore:
- '&f&lGrade: &6&lA'
- ''
- '&6&lAPEX WEAPON BONUS'
- '&6&lDeal +7.5% damage to all enemies.'
enchants:
- sharpness:%3-8%
- unbreaking:%1-5%
events:
events:
  ATTACK_MOB:
    chance: 100
    conditions:
    - '%mob type% = SKELETON : %allow%'
    effects:
    - LIGHTNING @Aoe{radius=5,target=damageable}
    cooldown: 0
```

### "/ae plinfo" link

https://paste.md-5.net/yanokimute
