### ISSUE TITLE
Trench causing console spam everytime it is used

### ISSUE THREAD

**Issue by Kaludii** [GC-spigot/AdvancedEnchantments#3941]
### Describe the bug

Hello, we use Trench on our Detonate enchant, and every time someone uses it, it spams the console. It is present on the latest update from today as well.
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/63890666/0a391d17-7e3c-4765-92c5-6487945d5e1d)

### How to reproduce

Download the latest AE update, set the Detonate enchant similar to below, and use it. You will see that it starts spamming the console.
```
detonate:
  display: '%group-color%Detonate'
  description: Chance to break in 3x3 area.
  applies-to: Pickaxes and shovels
  type: MINING
  group: MYTHICAL
  applies:
  - ALL_PICKAXE
  - ALL_SPADE
  levels:
    '1':
      chance: 13
      effects:
      - BREAK_BLOCK @Trench{r=3}
    '2':
      chance: 26
      effects:
      - BREAK_BLOCK @Trench{r=3}
    '3':
      chance: 36
      effects:
      - BREAK_BLOCK @Trench{r=3}
    '4':
      chance: 49
      effects:
      - BREAK_BLOCK @Trench{r=3}
    '5':
      chance: 59
      effects:
      - BREAK_BLOCK @Trench{r=3}
```

### "/ae plinfo" link

https://paste.md-5.net/ijixisuqet
