### ISSUE TITLE
swap tools with HELD enchantments

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3943]
### Describe the bug

```
헤이스트:
  display: '%group-color%헤이스트'
  description: |-
    도구 사용시 영구적으로
    성급함 효과를 얻습니다.
  applies-to: 
  type: HELD
  group: 레전더리
  applies:
  - ALL_SWORD
  - NETHERITE_PICKAXE
  - DIAMOND_PICKAXE
  - NETHERITE_SPADE
  - DIAMOND_SPADE
  - NETHERITE_AXE
  - DIAMOND_AXE
  levels:
    '1':
      conditions:
      - '%is offhand% = false : %allow%'
      effects:
      - POTION:FAST_DIGGING:0
    '2':
      conditions:
      - '%is offhand% = false : %allow%'
      effects:
      - POTION:FAST_DIGGING:1
    '3':
      conditions:
      - '%is offhand% = false : %allow%'
      effects:
      - POTION:FAST_DIGGING:2
```
player can get buffs by swap item even though the condition is '%is offhand% = false: %allow%'

### How to reproduce

i reproduced in video : 
https://youtu.be/8YUvh2lPFL0

### "/ae plinfo" link

https://paste.md-5.net/temujexeli
