### ISSUE TITLE
Slot increaser applies stattrak, can't use stattrak anymore

### ISSUE THREAD

**Issue by TheLaoming** [GC-spigot/AdvancedEnchantments#3947]
### Describe the bug

So since [9.6.5 Changelog](https://www.spigotmc.org/resources/25-sale-%E2%AD%95-advancedenchantments-%E2%AD%90-450-custom-enchants-%E2%AD%90-create-custom-enchantments-%E2%9C%85.43058/update?update=530273). sometimes when I apply slot increaser, it applies stattrak instead (rarely mobtrak too) and it works with armors as well. I sent a video in one of my tickets. I can't also apply stattrak on any of items, it does nothing, i've tried also previous version.
```
stattrak:
    type: SLIME_BALL
    id: 0
    custom-model-data: 4
    force-glow: false
    name: '{#3785fb}S{#538cf1}t{#6f92e7}a{#8b99dd}t{#a6a0d2}T{#c2a7c8}r{#deadbe}a{#fab4b4}k™'
    lore:
    - '&r'
    - '&7Aplikuj tento &3StatTrak &7na svou'
    - '&7zbraň či nástroj a počítej celkový'
    - '&7počet zabitých hráčů!'
    - '&r'
    - '{#b69be0}➥ {#D4D0FD}Přetáhni na item pro aplikaci.'
    messages:
      success:
      - '&f᝼ {#66F00C}StatTrak byl aplikován na tvůj předmět!'
    settings:
      lore-display: '&7Zabito hráčů: &8%stats%'
```
I can use MobTrak and all other variants, but stattrak for some reason doesn't work.

Noticed these debug messages too:
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/75527300/673df6a4-4ba4-4da8-ba47-18f6fba24b4d)

### How to reproduce

Just use slot increaser on your item.

### "/ae plinfo" link

https://paste.md-5.net/wutoxijowu
