### ISSUE TITLE
HELD trigger causes dupe

### ISSUE THREAD

**Issue by xenxero1** [GC-spigot/AdvancedEnchantments#3955]
### Describe the bug

Attempting to make a weapon generate souls passively using this enchantment
```
magic:
  display: '%group-color%Magic'
  description: |-
    Generates Souls passively
  applies-to: Weapons
  type: HELD
  group: UNIMPLEMENTED
  applies:
    - ALL_SWORD
    - ALL_AXE
  levels:
    '1':
      cooldown: 5
      conditions:
        - '%souls on item% >= 100 : %stop%'
      effects:
        - ADD_SOULS:1 @Self
        - PARTICLE:SOUL:1:4 @Self
```
Adding ;REPEATING to the trigger makes it significantly worse, and causes dupe to trigger more frequently.

### How to reproduce

Add the posted enchantment to the game and add it to an axe or sword. Put the item in your hand and spam click it from the mainhand selected slot to other slots in your inventory, dupe.

### Screenshots / Videos

https://www.youtube.com/watch?v=Ce1bFxuv5aI&ab_channel=WildWankers

### "/ae plinfo" link

https://paste.md-5.net/faquxikivi
