### ISSUE TITLE
REPEATING trigger for held items does not actually trigger.

### ISSUE THREAD

**Issue by xenxero1** [GC-spigot/AdvancedEnchantments#3956]
### Describe the bug

Title. 
Have gone through almost every variation of the following enchantment, attempting to make something that triggers every few seconds that the item is held to generate souls.
```
magic2:
  display: '%group-color%Magic2'
  description: |-
    Generates Souls passively
  applies-to: Weapons
  type: REPEATING
  time: 5
  group: UNIMPLEMENTED
  applies:
    - ALL_SWORD
    - ALL_AXE
  levels:
    '1':
      conditions:
        - '%souls on item% >= 100 : %stop%'
      effects:
        - ADD_SOULS:1 @Self
        - PARTICLE:SOUL:1:4 @Self
```
Have tried many many variations of placement for the time condition, within effects, in Settings, in lots of configurations with staff in a ticket. Confirmed to not work as intended for held items. Changing trigger to HELD;REPEATING does not fix the issue, instead introducing a dupe bug as stated in another posted bug report. 

Full correspondence with discord staff and trial attempts can be found in `1198042261020225677` or #need-help-with-5523

### How to reproduce

Add posted enchantment to the enchantments.yml , add to item, see that it does not trigger routinely.

### "/ae plinfo" link

https://paste.md-5.net/faquxikivi

**Comment by ThomasWega** [comment]
also, make sure to move your `time` setting to the effects block

```yaml
levels:
    '1':
      time: 5
      conditions:
        - '%souls on item% >= 100 : %stop%'
      effects:
        - ADD_SOULS:1 @Self
        - PARTICLE:SOUL:1:4 @Self
```
