### ISSUE TITLE
Feature Request: Add effects to Projectiles

### ISSUE THREAD

**Issue by xenxero1** [GC-spigot/AdvancedEnchantments#3957]
### Describe the bug

Trying to add a right_click skill to weapons that launches a projectile that does something upon hit, but it seems that I am unable to make these projectiles have/apply any effects beyond their vanilla properties.

```
icebolt:
  display: '%group-color%Ice Bolt'
  description: |-
    Right click to fire an Ice Bolt
  applies-to: Weapons
  type: RIGHT_CLICK
  group: UNIMPLEMENTED
  applies:
    - ALL_SWORD
    - ALL_AXE
  levels:
    '1':
      cooldown: 5
      conditions:
        - '%souls on item% >= 1 : %allow%'
      effects:
        - REMOVE_SOULS:1 @Self
        - PARTICLE:SNOWFLAKE:8:2 @Self
        - 'MESSAGE:&8ICEBOLT'
        - PROJECTILE:SNOWBALL
```
Attempting to add any effects to a VICTIM here will throw a console error trying to invoke `"org.bukkit.entity.LivingEntity.getType()" because "<parameter2>" is null`

I would like to have a way to apply affects to players based on the projectile hitting them, to avoid using hitscan abilities with @EyeHeight or @AoE.

Additionally I wanted to see about adding a way to edit projectiles properties for things like adding velocity. Where the snowball is well and played out, llama spit is far more visually interesting, but it's default velocity makes it nearly impossible to use practically.

### How to reproduce

Feature Request

### "/ae plinfo" link

https://paste.md-5.net/xofeqopujo

### Server Log

https://mcpaste.io/17627e3de872846e
