### ISSUE TITLE
Haste works in Off-Hand

### ISSUE THREAD

**Issue by MartiThaWizz** [GC-spigot/AdvancedEnchantments#3988]
### Describe the bug

Basically saying this is very easy to replicate get haste on a pickaxe and put it onto any tool specified. Put it into your off-hand and you have haste 3. The AE Staff Team truly tried to help over discord but to no avail. Conditions work, changing HELD to MINING doesn't work. This can be easily fixed if you change how HELD functions or fix how MINING functions.

### How to reproduce

Haste 3 on pickaxe and put it into your off-hand

### "/ae plinfo" link

https://paste.md-5.net/ikibazepof.css

**Comment by ThomasWega** [comment]
```yaml
      conditions:
        - '%item slot% = offhand : %stop%'
      effects:
        - POTION:FAST_DIGGING:2
```
