### ISSUE TITLE
Removing enchantments causes loot generation to fail

### ISSUE THREAD

**Issue by kkshah96** [GC-spigot/AdvancedEnchantments#3992]
### Describe the bug

Loot generation produces an error, and does not generate any loot after removing enchantments from `enchantments.yml`

Error message:

```
05.02 21:57:09 [Server] INFO Failed to generate AdvancedEnchantments Random Loot for item RANDOM_ENCHANT_BOOK: error is located in console. 
05.02 21:57:09 [Server] INFO It is most likely a configuration issue and this item's configuration should be checked before reporting.
05.02 21:57:09 [Server] WARN java.lang.IllegalArgumentException: bound must be positive
05.02 21:57:09 [Server] WARN at java.base/java.util.Random.nextInt(Random.java:322)
05.02 21:57:09 [Server] WARN at java.base/java.util.concurrent.ThreadLocalRandom.nextInt(ThreadLocalRandom.java:453)
05.02 21:57:09 [Server] WARN at AdvancedEnchantments-9.6.10.jar//net.advancedplugins.ae.enchanthandler.enchantments.AEnchants.getRandomEnchant(AEnchants.java:87)
05.02 21:57:09 [Server] WARN at AdvancedEnchantments-9.6.10.jar//net.advancedplugins.ae.handlers.commands.MCI.getRandomBook(MCI.java:681)
05.02 21:57:09 [Server] WARN at AdvancedEnchantments-9.6.10.jar//net.advancedplugins.ae.handlers.lootPopulation.PopulationHandler.getLoot(PopulationHandler.java:135)
05.02 21:57:09 [Server] WARN at AdvancedEnchantments-9.6.10.jar//net.advancedplugins.ae.handlers.lootPopulation.listeners.WorldLootPopulator.generateLoot(WorldLootPopulator.java:44)
05.02 21:57:09 [Server] WARN at AdvancedEnchantments-9.6.10.jar//net.advancedplugins.ae.handlers.lootPopulation.listeners.WorldLootPopulator.populate(WorldLootPopulator.java:32)
05.02 21:57:09 [Server] WARN at net.minecraft.world.level.chunk.Chunk.loadCallback(Chunk.java:801)
05.02 21:57:09 [Server] WARN at net.minecraft.world.level.chunk.Chunk.onChunkLoad(Chunk.java:736)
05.02 21:57:09 [Server] WARN at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1339)
05.02 21:57:09 [Server] WARN at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1383)
05.02 21:57:09 [Server] WARN at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1367)
05.02 21:57:09 [Server] WARN at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1320)
05.02 21:57:09 [Server] WARN at net.minecraft.server.level.ChunkProviderServer.s(ChunkProviderServer.java:430)
05.02 21:57:09 [Server] WARN at net.minecraft.server.level.ChunkProviderServer$b.x(ChunkProviderServer.java:868)
05.02 21:57:09 [Server] WARN at net.minecraft.server.level.ChunkProviderServer.d(ChunkProviderServer.java:426)
05.02 21:57:09 [Server] WARN at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1440)
05.02 21:57:09 [Server] WARN at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1352)
05.02 21:57:09 [Server] WARN at net.minecraft.util.thread.IAsyncTaskHandler.bu(IAsyncTaskHandler.java:114)
05.02 21:57:09 [Server] WARN at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1544)
05.02 21:57:09 [Server] WARN at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1214)
05.02 21:57:09 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
05.02 21:57:09 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:840)
```

Updated `lootConfiugration.yml`:

```
# Configuration file for random loot generated in world and villager trades
#  Random locations include:
#   * Any chests generated in wild, e.g. mob spawner rooms, mineshaft etc.
#  Configure Villager Trades. Villagers can trade custom enchantment books and admin items, e.g. white scrolls, orbs, dusts.

# ------ Random Loot Section ------ #
randomLoot:
  # Should random loot be generated in world?
  randomLootEnabled: true

  # Maximum number of custom items to be generated in a random loot container
  maxItemsPerContainer: 2

  # Chance of any item(s) being generated
  chanceOfItems: 100

  # Blacklisted groups, these group books cannot generate in random loot
  blacklisted-groups:
    - 'STAFF'

  # Chances format:
  # ITEM_NAME: Chance (0 to 100)
  chances:
    SLOT_INCREASER: 0
    WHITE_SCROLL: 0
    MYSTERY_DUST: 0
    SECRET_DUST: 0
    MAGIC_DUST: 0
    BLACK_SCROLL: 0
    RANDOMIZER: 0
    RENAME_TAG: 0
    BLOCKTRAK: 0
    FISHTRAK: 0
    STATTRAK: 0
    MOBTRAK: 0
    SOUL_TRACKER: 0
    SOUL_GEM: 0
    TRANSMOG_SCROLL: 0
    HOLY_WHITE_SCROLL: 0
    ARMOR_ORB: 0
    WEAPON_ORB: 0
    TOOL_ORB: 0
    RANDOM_ENCHANT_BOOK: 100

# ------ Villager Trades Section ------ #
villagerTrades:
  # Should villagers be able to trade custom books / items?
  villagerTradesEnabled: false

  # Should villagers trade admin items as well? E.g. Whitescroll, Blackscroll, Magic Dust
  # If set to false, they will only trade custom enchantment books
  tradeAllLoot: true

  # Chance of any item(s) being added as a trade
  chanceOfItems: 3

  # Blacklisted groups, these group books cannot be in villager trades
  blacklisted-groups:
    - 'STAFF'

  # Chances format:
  # ITEM_NAME: Chance (0 to 100)
  chances:
    SLOT_INCREASER: 5
    WHITE_SCROLL: 12
    MYSTERY_DUST: 0
    SECRET_DUST: 15
    MAGIC_DUST: 12
    BLACK_SCROLL: 7
    RANDOMIZER: 10
    RENAME_TAG: 8
    BLOCKTRAK: 3
    FISHTRAK: 3
    STATTRAK: 3
    MOBTRAK: 3
    SOUL_TRACKER: 2
    SOUL_GEM: 15
    TRANSMOG_SCROLL: 8
    HOLY_WHITE_SCROLL: 4
    ARMOR_ORB: 2
    WEAPON_ORB: 2
    TOOL_ORB: 2
    RANDOM_ENCHANT_BOOK: 10
```

Updated `enchantments.yml`:

```
aquatic:
  display: '%group-color%Aquatic'
  description: Breathe underwater.
  applies-to: Helmets
  type: EFFECT_STATIC
  group: SIMPLE
  applies:
    - ALL_HELMET
  levels:
    '1':
      effects:
        - POTION:WATER_BREATHING:0
glowing:
  display: '%group-color%Glowing'
  description: Gives permanent night vision.
  applies-to: Helmet
  type: EFFECT_STATIC
  group: SIMPLE
  applies:
    - ALL_HELMET
  levels:
    '1':
      effects:
        - POTION:NIGHT_VISION:0
```

### How to reproduce

1. Update the `lootConfiguration.yml` as above
2. Loot generation seems to work fine / no errors in logs
3. Update the `enchantments.yml` as above, to only have a few enchantments
4. Error starts appearing whenever a new chest is loaded into game

### "/ae plinfo" link

https://paste.md-5.net/kehejihaxo
