### ISSUE TITLE
Armorset static effect not reapplying on world change unlike normal enchants

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#3996]
### Describe the bug

Armorset static effects are not reapplying on world change unlike normal enchants.
see clip below

Only few plugins in server, meaning its no plugin conflict, check clip and plinfo.

### How to reproduce

see clip below

Used enchants/armorset effects

Custom Enchant:
```
gears:
  display: '%group-color%&lGears'
  description: Added speed when equipped.
  applies-to: Boots
  type: EFFECT_STATIC
  group: ONE
  applies:
  - ALL_BOOTS
  levels:
    '1':
      effects:
      - POTION:SPEED:2
```

Armorset Effect:
```
events:
  ATTACK:
    chance: 100
    effects:
    - INCREASE_DAMAGE:10 @Victim
    cooldown: 0
  DEFENSE:
    chance: 100
    effects:
    - NEGATE_DAMAGE:50
    cooldown: 0
  EFFECT_STATIC:
    effects:
    - POTION:STRENGTH:0
    cooldown: 0
    chance: 100
```

### Screenshots / Videos

https://streamable.com/mylnfe

### "/ae plinfo" link

https://paste.md-5.net/vudanirone

### Server Log

https://mcpaste.io/e36492e7c719d5ac
