### ISSUE TITLE
EXP effect is not working when the item is enchanted with silk touch

### ISSUE THREAD

**Issue by leogianfagna** [GC-spigot/AdvancedEnchantments#4005]
### Describe the bug

The player doesn't receive the experience from "EXP" effect if the tool is enchanted with **silk touch**.

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/142264317/8b18e407-ab33-4c2f-a876-df71c8e539d8)

### How to reproduce

1. Enchant a item with ANY enchantment which the effect is "EXP:<amount>"
2. Enchant with the vanillew silk touch
3. Try it

E.g:
```yml
    1:
      chance: 12
      cooldown: 5
      effects:
        - 'EXP:<random number>2-4</random number>'
```

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/142264317/18589612-6297-4288-a78d-a7d4fe437e5b)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/142264317/0bc86b1a-bac7-4b08-a084-ce92ec5c3f0f)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/142264317/62099f48-29f1-4f1e-8a67-c6db391294ef)

### "/ae plinfo" link

https://paste.md-5.net/xuhajoluri
