### ISSUE TITLE
Feature "per level description" is not working

### ISSUE THREAD

**Issue by leogianfagna** [GC-spigot/AdvancedEnchantments#4006]
### Describe the bug

All the enchantments book from all levels are with the same description.
A big note is, this feature was working properly some days ago. But, just stopped to work.

I have the plugin in two servers, with different versions. I didn't changed any config and both stopped work.

### How to reproduce

Create an enchantment with description per level, like this:
```yml
test:
  display: '%group-color%Teste'
  description: "test description 1"
  applies-to: 'Armaduras'
  type: 'DEFENSE;DEFENSE_MOB'
  group: 'SIMPLE'
  settings:
    showActionBar: true
  applies:
    - ALL_ARMOR
  levels:
    1:
      chance: 2
      cooldown: 200
      effects:
        - 'POTION:DAMAGE_RESISTANCE:0:40 @Victim'
    2:
      description: "test description 2"
      chance: 3
      cooldown: 180
      effects:
        - 'POTION:DAMAGE_RESISTANCE:0:80 @Victim'
    3:
      description: "test description 3"
      chance: 4
      cooldown: 160
      effects:
        - 'POTION:DAMAGE_RESISTANCE:1:120 @Victim'
    4:
      description: "test description 4"
      chance: 5
      cooldown: 140
      effects:
        - 'POTION:DAMAGE_RESISTANCE:1:160 @Victim'
```

Them give yourself the book with:
1. /ae givebook NICK teste 1 1 100 0
2. /ae givebook NICK teste 2 1 100 0

See that the description didn't changed.

### "/ae plinfo" link

https://paste.md-5.net/xuhajoluri
