### ISSUE TITLE
AE Placeholder doesn't work in enchants GUI

### ISSUE THREAD

**Issue by leogianfagna** [GC-spigot/AdvancedEnchantments#4010]
### Describe the bug

As this image describe:
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/142264317/e023f6e3-b39d-4238-8785-41684c395d77)

# [!]
The placeholder **works normally** using /papi parse

### How to reproduce

Go to AdvancedEnchantments/menus/customcommands.yml

Try to use the placeholder on **inventory**, like this:

```yml
  inventory:
    size: 36
    go-back-item: true
    display-page-number: false
    name: '&f'
    items:
      '11':
        type: BOOK
        id: 0
        custom-model-data: 1
        force-glow: false
        group: SIMPLES
        name: 'teste'
        lore:
        - ' &7→ &fteste placeholder: %advancedenchantments_total_simple%'
```

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/142264317/4640777a-5165-45a3-9973-d7c37af6a25f)

### "/ae plinfo" link

https://paste.md-5.net/ipukipomih
