### ISSUE TITLE
Enchantments Not Working on Golden Armor

### ISSUE THREAD

**Issue by detraismc** [GC-spigot/AdvancedEnchantments#4027]
### Describe the bug

Enchantments not working on Golden Armor even it has "ALL_ARMOR" in it.
Any armor works fine like leather armor, only golden armor that not working.

Golden tools and golden sword also works fine, only golden armor.

### How to reproduce

Enchant golden armor with any enchantment, the effect not working.

Here my Enchantments.yml :

```
samudra:
  display: '%group-color%Samudra'
  description: Memberikan conduit power permanent.
  applies-to: ʙᴏᴏᴛꜱ
  type: EFFECT_STATIC
  group: UNIQUE
  applies:
    - ALL_BOOTS
  levels:
    '1':
      effects:
        - POTION:CONDUIT_POWER:0

matakucing:
  display: '%group-color%Mata Kucing'
  description: Memberikan night vision permanent.
  applies-to: ʜᴇʟᴍᴇᴛꜱ
  type: EFFECT_STATIC
  group: RARE
  applies:
    - ALL_HELMET
  levels:
    '1':
      effects:
        - POTION:NIGHT_VISION:0

molten:
  display: '%group-color%Molten'
  description: |-
    Ketika diserang berpeluang 15% per level
    membuat musuh tersebut terbakar selama 2
    detik per level.
    Cooldown 2 detik.
  applies-to: ᴀʀᴍᴏʀ
  type: DEFENSE;DEFENSE_MOB
  group: UNIQUE
  applies:
    - ALL_ARMOR
  levels:
    '1':
      chance: 15
      cooldown: 2
      effects:
        - BURN:2 @Attacker
    '2':
      chance: 30
      cooldown: 2
      effects:
        - BURN:4 @Attacker
    '3':
      chance: 45
      cooldown: 2
      effects:
        - BURN:6 @Attacker
    '4':
      chance: 60
      cooldown: 2
      effects:
        - BURN:8 @Attacker
```
        

Server Version: Paper 1.20.4
Plugin Version: Latest 9.6.17

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/54352760/388db588-b9a3-4f9f-b30c-6573755ab5bb)
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/54352760/51764c65-7731-4ba2-a3c4-6d7197f32d69)

### "/ae plinfo" link

https://paste.md-5.net/vamelekoro
