### ISSUE TITLE
Placeholder statistic_mine_block gets increased by ~593 instead of 1

### ISSUE THREAD

**Issue by MattDeWeerd** [GC-spigot/AdvancedEnchantments#4033]
### Describe the bug

It seems that when the enchant **Smelting** is on a pickaxe, the statistic placeholder for statistic_mine_block gets increased by ~593 instead of 1. 

```
smelting:
  display: '%group-color%Smelting'
  description: Chance to smelt mined blocks.
  applies-to: Pickaxes
  type: MINING
  group: SIMPLE
  applies:
    - ALL_PICKAXE
    - ALL_SHOVEL
  levels:
    '1':
      chance: 33
      effects:
        - SMELT
    '2':
      chance: 66
      effects:
        - SMELT
    '3':
      chance: 100
      effects:
        - SMELT
```

### How to reproduce

1. Check your statistic by running: `/papi parse me %statistic_mine_block%`
2. Give yourself a pickaxe and enchant it with any level of smelting
3. Mine a block
4. Check your statistic again by by running: `/papi parse me %statistic_mine_block%`

The value returned will be much larger than expected

### Screenshots / Videos

https://medal.tv/games/minecraft/clips/1X8s3TCz1A1oSA/d1337UegU4Tn?invite=cr-MSxKSmosMjQxMDY3Njgs

### "/ae plinfo" link

https://paste.md-5.net/egalubuwib
