### ISSUE TITLE
No Lore Custom Enchant Setting [SUGGESTION]

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#4034]
### Describe the bug

An setting to not add a specific custom enchant lore when added, let's say:
```
test:
  display: 'Test'
  description: ""
  applies-to: Armor
  type: ATTACK
  group: EXCLUSIVES
  applies:
    - ALL_ARMOR
  settings:
    removeable: false
    nolore: true
  levels:
    '1':
      effects:
        - MESSAGE:TEST @Attacker
```

This would be good for creating weapons with multi stats/enchantments.

### How to reproduce

none

### Screenshots / Videos

none

### "/ae plinfo" link

none

### Server Log

none
