### ISSUE TITLE
Advanceditems condition on DEFENSE trigger not working

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#4046]
### Describe the bug

Advanceditems condition on DEFENSE trigger not working, on ATTACK trigger it works though

Same issue in AdvancedItems, it seems like the Advanceditems condition is bugged on DEFENSE trigger in both plugins.
https://github.com/GC-spigot/AdvancedItems/issues/29

### How to reproduce

**This one won't work as it's condition is AdvancedItems**
```
test:
  display: 'test'
  description: ""
  applies-to: 'Armor'
  type: 'DEFENSE'
  group: 'EXCLUSIVES'
  applies:
    - ALL_ARMOR
  levels:
    1:
      conditions:
        - '%advanceditems helmet type% = test1: %allow%'
        - '%advanceditems chestplate type% = test2: %allow%'
        - '%advanceditems leggings type% = test3: %allow%'
        - '%advanceditems boots type% = test4: %allow%'
      effects:
        - CANCEL_EVENT
        - PLAY_SOUND:ENTITY_BAT_TAKEOFF:0.7 @Victim
```

**This one will work since it's condition is not advanceditems**
```
test:
  display: 'test'
  description: ""
  applies-to: 'Armor'
  type: 'DEFENSE'
  group: 'EXCLUSIVES'
  applies:
    - ALL_ARMOR
  levels:
    1:
      conditions:
        - '%victim health% > 15 : %stop%'
      effects:
        - CANCEL_EVENT
        - PLAY_SOUND:ENTITY_BAT_TAKEOFF:0.7 @Victim
```

**The condition works on ATTACK trigger though, this is an example:**
```
test:
  display: 'Test'
  description: ""
  applies-to: Armor
  type: ATTACK
  group: EXCLUSIVES
  applies:
    - ALL_ARMOR
  settings:
    removeable: false
  levels:
    '1':
      conditions:
        - '%advanceditems helmet type% = test1: %allow%'
        - '%advanceditems chestplate type% = test2: %allow%'
        - '%advanceditems leggings type% = test3: %allow%'
        - '%advanceditems boots type% = test4: %allow%'
      effects:
        - POTION:STRENGTH:0:100 @Attacker
```

**so yeah the advanceditems condition on DEFENSE trigger is BROKEN**

### Screenshots / Videos

https://streamable.com/dsnvnt

### "/ae plinfo" link

https://paste.md-5.net/ovijitijiy

### Server Log

https://mcpaste.io/cf47b03981dbcf5c
