### ISSUE TITLE
Add Blackscroll apply event

### ISSUE THREAD

**Issue by leogianfagna** [GC-spigot/AdvancedEnchantments#4048]
### Describe the bug

I want to when apply a blackscroll, the required-enchants is given back as well.

So for example, I have a enchantment with these options:
```yml
firstenchant:
  display: '%group-color%First Enchant'
  settings:
    required-enchants:
      - 'secondeenchant:3'
    removed-enchants:
      - 'secondeenchant'
```

So when I apply the blackscroll, I will receive the **firstenchant** and the **secondeenchant**! So the players will not lost their required enchantments.

If this is not planned, I would suggest to add black scroll apply event to the API, so I can do it!
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/142264317/aae84aff-6371-40b9-9a0b-47e17307bbba)

### How to reproduce

This is feature request.

### "/ae plinfo" link

-
