### ISSUE TITLE
"SHOOT" trigger not worked.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#4057]
### Describe the bug

i make add durability when shoot arrow, but it not works. i also tried set delay before add durability.

### How to reproduce

```
test:
  display: '%group-color%test'
  type: SHOOT
  group: 커먼
  applies:
  - BOW
  levels:
    '1':
      chance: 20
      effects:
      - ADD_DURABILITY_ITEM:1
    '2':
      chance: 25
      effects:
      - ADD_DURABILITY_ITEM:2
    '3':
      effects:
      - ADD_DURABILITY_ITEM:9
  ```

### "/ae plinfo" link

https://paste.md-5.net/egameziwig

**Comment by SirJben** [comment]
Make sure your enchantments has description:
```
test:
  display: '%group-color%test'
  description: "Shoot shoot shoot"
  type: SHOOT_MOB
  group: SIMPLE
  applies:
  - BOW
  levels:
    '1':
      chance: 20
      effects:
      - ADD_DURABILITY_ITEM:1
    '2':
      chance: 25
      effects:
      - ADD_DURABILITY_ITEM:2
    '3':
      effects:
      - ADD_DURABILITY_ITEM:9
      ```
      
      and open AE ticket next time. https://discord.gg/advancedplugins
