### ISSUE TITLE
lootConfiguration throwing error in function AManager.getRandomFreeSlot

### ISSUE THREAD

**Issue by EuSouVoce** [GC-spigot/AdvancedEnchantments#4058]
### Describe the bug

The world populator is crashing the server trying to populate loot on a chest that (when tried to open as spectator) "Unable to open. Loot not generated yet".

``net.advancedplugins.ae.utils.AManager.getRandomFreeSlot(AManager.java:1242)``
``net.advancedplugins.ae.handlers.lootPopulation.listeners.WorldLootPopulator.generateLoot(WorldLootPopulator.java:50)``
``net.advancedplugins.ae.handlers.lootPopulation.listeners.WorldLootPopulator.populate(WorldLootPopulator.java:32)``

But, as the same way, the loot does generate when opening the inventory in gamemodes other than spectator.

### How to reproduce

file: ``lootConfiguration.yml``
```yaml
# ------ Random Loot Section ------ #
randomLoot:
  # Should random loot be generated in world?
  randomLootEnabled: true

  # Maximum number of custom items to be generated in a random loot container
  maxItemsPerContainer: 2

  # Chance of any item(s) being generated
  chanceOfItems: 20

  # Chances format:
  # ITEM_NAME: Chance (0 to 100)
  chances:
    SLOT_INCREASER: 5
    WHITE_SCROLL: 12
    MYSTERY_DUST: 0
    SECRET_DUST: 15
    MAGIC_DUST: 12
    BLACK_SCROLL: 7
    RANDOMIZER: 10
    RENAME_TAG: 8
    BLOCKTRAK: 4
    STATTRAK: 4
    MOBTRAK: 4
    SOUL_TRACKER: 0
    SOUL_GEM: 0
    TRANSMOG_SCROLL: 10
    HOLY_WHITE_SCROLL: 2
    ARMOR_ORB: 2
    WEAPON_ORB: 2
    TOOL_ORB: 2
    RANDOM_ENCHANT_BOOK: 2

# ------ Villager Trades Section ------ #
villagerTrades:
  # Should villagers be able to trade custom books / items?
  villagerTradesEnabled: false

  # Should villagers trade admin items as well? E.g. Whitescroll, Blackscroll, Magic Dust
  # If set to false, they will only trade custom enchantment books
  tradeAllLoot: true

  # Chance of any item(s) being added as a trade
  chanceOfItems: 3

  # Chances format:
  # ITEM_NAME: Chance (0 to 100)
  chances:
    SLOT_INCREASER: 5
    WHITE_SCROLL: 12
    MYSTERY_DUST: 0
    SECRET_DUST: 15
    MAGIC_DUST: 12
    BLACK_SCROLL: 7
    RANDOMIZER: 10
    RENAME_TAG: 8
    BLOCKTRAK: 4
    STATTRAK: 4
    MOBTRAK: 4
    SOUL_TRACKER: 2
    SOUL_GEM: 15
    TRANSMOG_SCROLL: 8
    HOLY_WHITE_SCROLL: 4
    ARMOR_ORB: 2
    WEAPON_ORB: 2
    TOOL_ORB: 2
    RANDOM_ENCHANT_BOOK: 10
```

### "/ae plinfo" link

https://paste.md-5.net/dibuliyiqu

### Server Log

https://mcpaste.io/5f649843c1f5500e
