### ISSUE TITLE
COMMAND trigger doesn't work

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#4062]
### Describe the bug

doesn't work. says unknown command
```
test2:
  display: '&Test'
  description: ""
  applies-to: 'Armor'
  type: 'COMMAND'
  group: 'EXCLUSIVES'
  applies:
    - ALL_ARMOR
  levels:
    1:
      chance: 100
      cooldown: 0
      command: test2
      effects:
        - MESSAGE:TEST
```

### How to reproduce

```
test2:
  display: '&Test'
  description: ""
  applies-to: 'Armor'
  type: 'COMMAND'
  group: 'EXCLUSIVES'
  applies:
    - ALL_ARMOR
  levels:
    1:
      chance: 100
      cooldown: 0
      command: test2
      effects:
        - MESSAGE:TEST
```
try this

### Screenshots / Videos

none

### "/ae plinfo" link

https://paste.md-5.net/ivoluludiq

### Server Log

https://mcpaste.io/2c65f323a73d177c
