### ISSUE TITLE
"/apply" command not worked for POTION_OVERRIDE of HELD type effect enchantments.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#4064]
### Describe the bug

previously i reported some issues on #3991 .
The content of this issue is that the player's potion effect is removed
by change or respawn world generated by mythic dungeons.

To solve this problem indirectly, when the player respawn or changes the world,
perform "/apply playername" command by console.

POTION_OVERRIDE of EFFECT_STATIC type is applied, but the POTION_OVERRIDE of HELD type does not seem to be.

i think "/apply" command not worked for POTION_OVERRIDE of HELD type enchantments.

https://studio.youtube.com/video/qekTfHhBS10/edit](https://studio.youtube.com/video/qekTfHhBS10/edit

### How to reproduce

```
test:
  display: '%group-color%test'
  description: "test"
  applies-to: test
  type: HELD
  group: test
  applies:
  - ALL_SWORD
  levels:
    '1':
      effects:
      - POTION_OVERRIDE:FAST_DIGGING:0
    '2':
      effects:
      - POTION_OVERRIDE:FAST_DIGGING:1
    '3':
      effects:
      - POTION_OVERRIDE:FAST_DIGGING:2
```

### Screenshots / Videos

https://youtu.be/qekTfHhBS10
(i disable apply messages for players.)
### "/ae plinfo" link

https://paste.md-5.net/ozexorafis
