### ISSUE TITLE
Items duplicate on death if their durability is modified on the same tick as a players death.

### ISSUE THREAD

**Issue by xenxero1** [GC-spigot/AdvancedEnchantments#4071]
### Describe the bug

I believe this is caused by the method used to modify durability, as this is one of several dupes i've found that always involve durability.

```
skyrocketsword:
  display: '%group-color%Skyrocket Sword'
  description: |-
    Launch yourself into the air with Right Click
  applies-to: Bread
  type: RIGHT_CLICK
  group: UNIMPLEMENTED
  applies:
    - ALL_SWORD
  levels:
    '1':
      cooldown: 1.5
      effects:
        - ADD_DURABILITY_CURRENT_ITEM:-1 @Self
        - EXPLODE:2.5:false:false @Self
        - WAIT:2
        - BOOST:UP:15
        - PARTICLE:WHITE_SMOKE:20:4 @Self
```
Using this enchantment, whenever a player explodes themselves to death, they respawn with a copy of their sword, and one is left in their grave. I am using the Graves plugin, but I believe they use the standardized death handling system and that they are not the cause of this dupe.

If I add in a line   - WAIT:1 between the durability effect, and the explosion, I can prevent the dupe, but this still remains a problem because any player that activates an ability and is killed at the same tick, would still result in a dupe. 

### How to reproduce

Use the provided enchantment on a sword.
```
skyrocketsword:
  display: '%group-color%Skyrocket Sword'
  description: |-
    Launch yourself into the air with Right Click
  applies-to: Bread
  type: RIGHT_CLICK
  group: UNIMPLEMENTED
  applies:
    - ALL_SWORD
  levels:
    '1':
      cooldown: 1.5
      effects:
        - ADD_DURABILITY_CURRENT_ITEM:-1 @Self
        - WAIT:1
        - EXPLODE:2.5:false:false @Self
        - WAIT:2
        - BOOST:UP:15
        - PARTICLE:WHITE_SMOKE:20:4 @Self
```
Right click to activate
Set your health to near-zero.
Right click and die with the activation.

You should see the item duplicated into your inventory when you respawn.

### Screenshots / Videos

I did not take a video, as this is a live enchant on my server, I confiscated the duplicated items and watched it happen, then implemented my 1 tick wait spacer to prevent the dupe.

### "/ae plinfo" link

https://paste.md-5.net/eqagofiqaw
