### ISSUE TITLE
PreciousStones Support

### ISSUE THREAD

**Issue by SamGamerYT** [GC-spigot/AdvancedEnchantments#4084]
### Describe the bug

Plugins like Trench, VeinMiner and other block break enchantments keeps bugging out with PreciousStones

### How to reproduce

Use any of the block-break enchantment

### "/ae plinfo" link

https://paste.md-5.net/ifeguvexad

**Comment by SamGamerYT** [comment]
No news?

**Comment by SamGamerYT** [comment]
Been 3 weeks and people are still griefing other player's bases with the ce, if it can't be fixed I will have to switch the plugin

**Comment by GC-spigot** [comment]
Usually all protection plugins are support by default, unless they do not cancel the BlockBreakEvent themselves (which they should). However, this is now integrated and ready for next update.

**Comment by SamGamerYT** [comment]
```
trench:
  display: '%group-color%Trench'
  description: Chance to break in 3x3 area.
  applies-to: Pickaxes, Shovels
  type: MINING
  group: ULTIMATE
  applies:
  - ALL_PICKAXE
  - ALL_SPADE
  disabled-worlds:
  - 'parkour'
  - 'parkour2'
  levels:
    '1':
      chance: 5
      condition:
        - "%can break% = true : %allow%"
      effects:
      - BREAK_BLOCK @Trench{r=3}
    '2':
      chance: 10
      condition:
        - "%can break% = true : %allow%"
      effects:
      - BREAK_BLOCK @Trench{r=3}
    '3':
      chance: 15
      condition:
        - "%can break% = true : %allow%"
      effects:
      - BREAK_BLOCK @Trench{r=3}
    '4':
      chance: 25
      condition:
        - "%can break% = true : %allow%"
      effects:
      - BREAK_BLOCK @Trench{r=3}
    '5':
      chance: 30
      condition:
        - "%can break% = true : %allow%"
      effects:
      - BREAK_BLOCK @Trench{r=3}
    '6':
      chance: 30
      condition:
        - "%can break% = true : %allow%"
      effects:
      - BREAK_BLOCK @Trench{r=3}
    '7':
      chance: 45
      condition:
        - "%can break% = true : %allow%"
      effects:
      - BREAK_BLOCK @Trench{r=3}
    '8':
      chance: 55
      condition:
        - "%can break% = true : %allow%"
      effects:
      - BREAK_BLOCK @Trench{r=3}
    '9':
      chance: 60
      condition:
        - "%can break% = true : %allow%"
      effects:
      - BREAK_BLOCK @Trench{r=3}
      ```
