### ISSUE TITLE
Error description of enchantments

### ISSUE THREAD

**Issue by TopicflyOffi** [GC-spigot/AdvancedEnchantments#4092]
### Describe the bug

Unable to place the description of enchantments above other information (maximum levels / On which type of object the enchantment can be applied), even though the placeholder %desc% is at the top in my configuration, the description remains at the bottom.

Configuration of the "customcommands.yml" file under the "enchantment-info" category :
```
      '4':
        type: ENCHANTED_BOOK
        id: 0
        custom-model-data: 0
        force-glow: false
        name: '&7Information %ench-colors%'
        lore:
        - ''
        - '%desc%'
        - ''
        - '&fApplicable sur &8&l» %group-color%%applies-to%'
        - '&fNiveau max &8&l» %group-color%%max-lvl%'
```

### How to reproduce

Place the placeholder %desc% at the top in the 'customcommands.yml' configuration file, and the description will remain at the bottom of the displayed item.

### Screenshots / Videos

Information about my enchantment, with what I want to achieve (Red line) and what I get despite the configuration. : https://i.goopics.net/5nq1ga.png

Configuration : https://i.goopics.net/1na8d9.png

### "/ae plinfo" link

https://paste.md-5.net/oyanimazoc
