### ISSUE TITLE
ItemsAdder CustomBlocks whitelist

### ISSUE THREAD

**Issue by Lerphie** [GC-spigot/AdvancedEnchantments#4099]
### Describe the bug

Greetings, I have custom blocks from ItemsAdder, how do I specify them in the "Whitelist:" category ?

```
veinminer:
  display: '&7VeinMiner'
  description: Chance veinmining blocks
  applies-to: Pickaxe
  group: RARE
  type: MINING
  applies:
    - ALL_PICKAXE
  levels:
    '1':
      chance: 15
      cooldown: 4
      settings:
        whitelist:
          - "COAL_ORE"
          - "COPPER_ORE"
          - "IRON_ORE"
          - "GOLD_ORE"
          - "LAPIS_ORE"
          - "REDSTONE_ORE"
          - "DIAMOND_ORE"
          - "EMERALD_ORE"
          - "NETHER_QUARTZ_ORE"
          - "NETHER_GOLD_ORE"
          - "ANCIENT_DEBRIS"
          - "DEEPSLATE_COAL_ORE"
          - "DEEPSLATE_COPPER_ORE"
          - "DEEPSLATE_IRON_ORE"
          - "DEEPSLATE_GOLD_ORE"
          - "DEEPSLATE_LAPIS_ORE"
          - "DEEPSLATE_REDSTONE_ORE"
          - "DEEPSLATE_DIAMOND_ORE"
          - "DEEPSLATE_EMERALD_ORE"
          - "NOTE_BLOCK"
      effects:
        - BREAK_BLOCK @Veinmine
```

At the moment I have to specify this as "note_block", but that's a terrible idea. Basically your plugin should have a Hook to the API-ItemsAdder

### How to reproduce

*

### Screenshots / Videos

*

### "/ae plinfo" link

https://paste.md-5.net/qulexikahi

### Server Log

*
