### ISSUE TITLE
Disappearing items by killing yourself with ender_pear

### ISSUE THREAD

**Issue by imtorich** [GC-spigot/AdvancedEnchantments#4108]
### Describe the bug

AE ver. 9.7.5
There is enchantment:

```
Soulbound:
  display: '%group-color%Soulbound'
  description: Chance to keep an item on death
  Enchantment: Weapons and Tools
  type: DEATH;PASSIVE_DEATH
  group: LEGENDARY
  applies to:
    - ALL_TOOLS
    - ALL_SWORD
    - BOW
    - CROSSBOW
  levels:
    '1':
      chance: 30
      cooldown: 300
      effects:
        - KEEP_ON_DEATH
    '2':
      chance: 60
      cooldown: 300
      effects:
        - KEEP_ON_DEATH
    '3':
      chance: 90
      cooldown: 300
      effects:
        - KEEP_ON_DEATH
```

And, if the player kills himself with ender_pearl, the enchanted item disappears if the chance is not in the player's favor.

### How to reproduce

-

### Screenshots / Videos

https://imgur.com/a/0yIXmko

### "/ae plinfo" link

https://paste.md-5.net/kacixuciqa
