### ISSUE TITLE
REPEATING trigger not working

### ISSUE THREAD

**Issue by illudota** [GC-spigot/AdvancedEnchantments#4117]
### Describe the bug

```
testgears:
  display: '%group-color%&lGears'
  description: Added speed when equipped.
  applies-to: Boots
  type: REPEATING
  group: EXCLUSIVES
  applies:
  - ALL_BOOTS
  levels:
    '1':
      time: 1
      chance: 100
      effects:
      - POTION:SPEED:2:20
```

Doesn't work at all.

### How to reproduce

```
testgears:
  display: '%group-color%&lGears'
  description: Added speed when equipped.
  applies-to: Boots
  type: REPEATING
  group: EXCLUSIVES
  applies:
  - ALL_BOOTS
  levels:
    '1':
      time: 1
      chance: 100
      effects:
      - POTION:SPEED:2:20
```

### Screenshots / Videos

None

### "/ae plinfo" link

9.7.5 AE

### Server Log

n/a
