### ISSUE TITLE
Item pointers

### ISSUE THREAD

**Issue by Skullslice** [GC-spigot/AdvancedEnchantments#4119]
### Describe the bug

I am trying to make an armor set and whenever i take the set off, the messages keep going.

### How to reproduce

here is the exact enchantment that produces the issue using version three at the bottom.
```yaml
slots:
  display: '%group-color%Testing Slots'
  applies-to: Helmets
  type: EFFECT_STATIC;ATTACK;ATTACK_MOB;REPEATING
  description: SET CHECK
  group: LEGENDARY
  applies:
  - ALL_HELMET
  - ALL_CHESTPLATE
  - ALL_LEGGINGS
  - ALL_BOOTS
  - ALL_SWORD
  levels:
    '1':
      description: |-
        25% damage bonus with whole set and invisibility when low health.
      chance: 100
      time: 1
      effects:
        - "SET_VARIABLE:helmet%attacker name%:true<condition>%is removal% = false AND %item slot% = helmet : %allow%</condition> ~EFFECT_STATIC"
        - "SET_VARIABLE:helmet%attacker name%:false<condition>%is removal% = true AND %item slot% = helmet : %allow%</condition> ~EFFECT_STATIC"
        - "SET_VARIABLE:chestplate%attacker name%:true<condition>%is removal% = false AND %item slot% = chestplate : %allow%</condition> ~EFFECT_STATIC"
        - "SET_VARIABLE:chestplate%attacker name%:false<condition>%is removal% = true AND %item slot% = chestplate : %allow%</condition> ~EFFECT_STATIC"
        - "SET_VARIABLE:legs%attacker name%:true<condition>%is removal% = false AND %item slot% = leggings : %allow%</condition> ~EFFECT_STATIC"
        - "SET_VARIABLE:legs%attacker name%:false<condition>%is removal% = true AND %item slot% = leggings : %allow%</condition> ~EFFECT_STATIC"
        - "SET_VARIABLE:boots%attacker name%:true<condition>%is removal% = false AND %item slot% = boots : %allow%</condition> ~EFFECT_STATIC"
        - "SET_VARIABLE:boots%attacker name%:false<condition>%is removal% = true AND %item slot% = boots : %allow%</condition> ~EFFECT_STATIC"
        - "SET_VARIABLE:sword%attacker name%:true<condition>%attacker has enchantment in hand of slots% = true : %allow%</condition> ~REPEATING"
        - "SET_VARIABLE:sword%attacker name%:false<condition>%attacker has enchantment in hand of slots% = false : %allow%</condition> ~REPEATING"
        - "INCREASE_DAMAGE:25 @Victim <condition>%custom_helmet%attacker name%% = true AND %custom_chestplate%attacker name%% = true AND %custom_legs%attacker name%% = true AND %custom_boots%attacker name%% = true AND %custom_sword%attacker name%% = true : %allow%</condition> ~ATTACK ~ATTACK_MOB"
        - "LIGHTNING @Victim <condition>%custom_helmet%attacker name%% = true AND %custom_chestplate%attacker name%% = true AND %custom_legs%attacker name%% = true AND %custom_boots%attacker name%% = true AND %custom_sword%attacker name%% = true : %allow%</condition> ~ATTACK ~ATTACK_MOB"
        - "MESSAGE:%custom_sword%attacker name%% @Attacker ~REPEATING"
        - "MESSAGE:%custom_helmet%attacker name%% @Attacker ~EFFECT_STATIC"
        - "MESSAGE:%custom_chestplate%attacker name%% @Attacker ~EFFECT_STATIC"
        - "MESSAGE:%custom_legs%attacker name%% @Attacker ~EFFECT_STATIC"
        - "MESSAGE:%custom_boots%attacker name%% @Attacker ~EFFECT_STATIC"
```
put the enchantment on all pieces of the set and then take everything off again and chat spamming keeps going until server shutdown even though nothing is being used.

### "/ae plinfo" link

https://paste.md-5.net/kefunineci

**Comment by Skullslice** [comment]
i also tested ~HELD instead of repeating and if you switch off your sword into an empty hotbar slot, you get a big spam in chat after a minute or so but it isnt REPEATING spam like with REPEATING.

**Comment by Skullslice** [comment]
https://www.youtube.com/watch?v=XkLF9LJvrTs

**Comment by GC-spigot** [comment]
Why do you have REPEATING and EFFECT_STATIC together? This might be your issue. Use only REPEATING.

**Comment by Skullslice** [comment]
that very well might fix it, but using pointers it should be possible to use both types at once. i can update the booleans instantly with effect_static and with repeating i have to wait for the check to happen. regardless of type, the two lines controlling the sword boolean
```
- "SET_VARIABLE:sword%attacker name%:true<condition>%attacker has enchantment in hand of slots% = true : %allow%</condition> ~REPEATING"
        - "SET_VARIABLE:sword%attacker name%:false<condition>%attacker has enchantment in hand of slots% = false : %allow%</condition> ~REPEATING"
```
 do not seem to work. Switching off the sword and the boolean remains true even though it is marked as repeating. In staff chat somebody mentioned that %has enchantment% should be working in this version so any advice?

**Comment by Skullslice** [comment]
hello i want to give an update with the situation, I fixed the enchantment and here is the updated way to give a set bonus without using AE sets:
```yaml
slots:
  display: '%group-color%Testing Slots'
  applies-to: Helmets
  type: ATTACK;ATTACK_MOB;REPEATING
  description: SET CHECK
  group: LEGENDARY
  applies:
  - ALL_HELMET
  - ALL_CHESTPLATE
  - ALL_LEGGINGS
  - ALL_BOOTS
  - ALL_SWORD
  levels:
    '1':
      description: |-
        25% damage bonus with whole set and invisibility when low health.
      chance: 100
      time: 1
      effects:
        - "SET_VARIABLE:helmet%attacker name%:5<condition>%has enchantment in helmet of slots% = true : %allow%</condition> ~REPEATING"
        - "SET_VARIABLE:helmet%attacker name%:0<condition>%has enchantment in helmet of slots% contains enchantment : %allow%</condition> ~REPEATING"
        - "SET_VARIABLE:chestplate%attacker name%:7<condition>%has enchantment in chestplate of slots% = true : %allow%</condition> ~REPEATING"
        - "SET_VARIABLE:chestplate%attacker name%:0<condition>%has enchantment in chestplate of slots% contains enchantment : %allow%</condition> ~REPEATING"
        - "SET_VARIABLE:legs%attacker name%:4<condition>%has enchantment in leggings of slots% = true : %allow%</condition> ~REPEATING"
        - "SET_VARIABLE:legs%attacker name%:0<condition>%has enchantment in leggings of slots% contains enchantment : %allow%</condition> ~REPEATING"
        - "SET_VARIABLE:boots%attacker name%:4<condition>%has enchantment in boots of slots% = true : %allow%</condition> ~REPEATING"
        - "SET_VARIABLE:boots%attacker name%:0<condition>%has enchantment in boots of slots% contains enchantment : %allow%</condition> ~REPEATING"
        - "SET_VARIABLE:sword%attacker name%:10<condition>%has enchantment in hand of slots% = true : %allow%</condition> ~REPEATING"
        - "SET_VARIABLE:sword%attacker name%:0<condition>%has enchantment in hand of slots% contains enchantment : %allow%</condition> ~REPEATING"
        - "SET_VARIABLE:bonus%attacker name%:<math>%custom_helmet%attacker name%% + %custom_chestplate%attacker name%% + %custom_legs%attacker name%% + %custom_boots%attacker name%% + %custom_sword%attacker name%%</math> ~REPEATING"
        - "MESSAGE:%custom_bonus%attacker name%% ~REPEATING"
```
The above should be treated as a template for creating set bonuses WITHOUT ae sets because it doesn't include per armor bonus like mine does. developer can close this but should know of the shortcomings of ae sets and should update it when you have time.

**Comment by Skullslice** [comment]
I have updated the template with an armor boolean, you can check it on attack to confirm they are wearing the full set.

```yaml
slots:
  display: '%group-color%Testing Slots'
  applies-to: Helmets
  type: ATTACK;ATTACK_MOB;REPEATING
  description: SET CHECK
  group: LEGENDARY
  applies:
  - ALL_HELMET
  - ALL_CHESTPLATE
  - ALL_LEGGINGS
  - ALL_BOOTS
  - ALL_SWORD
  levels:
    '1':
      description: |-
        25% damage bonus with whole set and invisibility when low health.
      chance: 100
      time: 1
      effects:
        - "SET_VARIABLE:helmet%attacker name%:5<condition>%has enchantment in helmet of slots% = true : %allow%</condition> ~REPEATING"
        - "SET_VARIABLE:helmet%attacker name%:0<condition>%has enchantment in helmet of slots% contains enchantment : %allow%</condition> ~REPEATING"
        - "SET_VARIABLE:chestplate%attacker name%:7<condition>%has enchantment in chestplate of slots% = true : %allow%</condition> ~REPEATING"
        - "SET_VARIABLE:chestplate%attacker name%:0<condition>%has enchantment in chestplate of slots% contains enchantment : %allow%</condition> ~REPEATING"
        - "SET_VARIABLE:legs%attacker name%:4<condition>%has enchantment in leggings of slots% = true : %allow%</condition> ~REPEATING"
        - "SET_VARIABLE:legs%attacker name%:0<condition>%has enchantment in leggings of slots% contains enchantment : %allow%</condition> ~REPEATING"
        - "SET_VARIABLE:boots%attacker name%:4<condition>%has enchantment in boots of slots% = true : %allow%</condition> ~REPEATING"
        - "SET_VARIABLE:boots%attacker name%:0<condition>%has enchantment in boots of slots% contains enchantment : %allow%</condition> ~REPEATING"
        - "SET_VARIABLE:sword%attacker name%:10<condition>%has enchantment in hand of slots% = true : %allow%</condition> ~REPEATING"
        - "SET_VARIABLE:sword%attacker name%:0<condition>%has enchantment in hand of slots% contains enchantment : %allow%</condition> ~REPEATING"
        - "SET_VARIABLE:armor%attacker name%:false"
        - "SET_VARIABLE:armor%attacker name%:true<condition>%has enchantment in helmet of slots% = true AND %has enchantment in chestplate of slots% = true AND %has enchantment in leggings of slots% = true AND %has enchantment in boots of slots% = true : %allow%</condition>"
        - "SET_VARIABLE:bonus%attacker name%:<math>%custom_helmet%attacker name%% + %custom_chestplate%attacker name%% + %custom_legs%attacker name%% + %custom_boots%attacker name%% + %custom_sword%attacker name%%</math> ~REPEATING"
        - "MESSAGE:%custom_bonus%attacker name%% Full Armor Set ? %custom_armor%attacker name%% ~REPEATING"
```
