### ISSUE TITLE
DEATH type enchants on armor always trigger even when armor is not equipped

### ISSUE THREAD

**Issue by MylaChuu** [GC-spigot/AdvancedEnchantments#4137]
### Describe the bug

When having an enchantment with the DEATH effect on armor it will always trigger even when the armor piece is not being worn (It does respect cooldowns, it just triggers when the armor is not being worn)

This is my enchant:
```
phoenix:
  display: '%group-color%Phoenix'
  description: Chance to revive yourself on death.
  applies-to: Chestplates
  type: DEATH
  group: MYTHICAL
  applies:
    - ALL_CHESTPLATE
  levels:
    1:
      chance: 24
      cooldown: 900
      effects:
        - "CANCEL_EVENT"
        - "PARTICLE:TOTEM:500:1"
        - "PLAY_SOUND_OUTLOUD:BLOCK_BEACON_POWER_SELECT:1.2:1"
        - "POTION:ABSORPTION:2:200 @Victim"
        - "POTION:REGENERATION:9:60 @Victim"
        - "WAIT:18000"
        - 'ACTION_BAR:괅 &aPhoenix is ready'
    2:
      chance: 38
      cooldown: 600
      effects:
        - "CANCEL_EVENT"
        - "PARTICLE:TOTEM:500:1"
        - "PLAY_SOUND_OUTLOUD:BLOCK_BEACON_POWER_SELECT:1.2:1"
        - "POTION:ABSORPTION:4:400 @Victim"
        - "POTION:REGENERATION:9:60 @Victim"
        - "WAIT:12000"
        - 'ACTION_BAR:괅 &aPhoenix is ready'
    3:
      chance: 48
      cooldown: 480
      effects:
        - "CANCEL_EVENT"
        - "PARTICLE:TOTEM:500:1"
        - "PLAY_SOUND_OUTLOUD:BLOCK_BEACON_POWER_SELECT:1.2:1"
        - "POTION:ABSORPTION:9:800 @Victim"
        - "POTION:REGENERATION:9:60 @Victim"
        - "WAIT:9600"
        - 'ACTION_BAR:괅 &aPhoenix is ready'
```

I have also added a video showing it triggering everytime im supposed to die and as soon as i drop it on the ground it stops

### How to reproduce

1. Create an enchant with the DEATH type as the trigger for armor
2. Put it on a piece of armor and do not equip it
3. Get killed by a mob and the effect will still trigger
4. Drop the item with the enchant
5. Effect stops triggering

### Screenshots / Videos

https://youtu.be/8NQRd2eFpgU

### "/ae plinfo" link

https://paste.md-5.net/jaruwoboco

### Server Log

https://mcpaste.io/b1e756ecf3cd2d80
