### ISSUE TITLE
player can get a permanent effect_static effect.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#4172]
### Describe the bug

sometimes player can get permanent effect_static effect when equip armor applied with effect_static by double click.

### How to reproduce

```
test:
  display: '%group-color%test'
  description: test
  applies-to: 
  type: EFFECT_STATIC
  group: epic
  applies:
  - ALL_BOOTS
  levels:
    '1':
      effects:
      - POTION:SPEED:0
    '2':
      effects:
      - POTION:SPEED:1
    '3':
      effects:
      - POTION:SPEED:2
```

### Screenshots / Videos

https://youtu.be/fVZnpNaVduw

### "/ae plinfo" link

https://paste.md-5.net/ihuyipoboh
