### ISSUE TITLE
Gemify + Trench Enchantment bug

### ISSUE THREAD

**Issue by xMarnel** [GC-spigot/AdvancedEnchantments#4175]
### Describe the bug

Gemify + Trench combo on a pickaxe is bugging. 

### How to reproduce

Enchant pickaxe with Trench and Gemify.

### Screenshots / Videos

![multi bug](https://github.com/GC-spigot/AdvancedEnchantments/assets/80050200/318f1de8-048c-4bc5-9f2c-c645bfb9f957)

### "/ae plinfo" link

https://paste.md-5.net/idafekoxiw

### Server Log

https://mcpaste.io/b53800889d01f1ea

**Comment by ThomasWega** [comment]
Will be fixed in the next update. If you want, you can update the enchantment with this:

```yaml
gemify:
  display: '%group-color%Gemify'
  description: Chance for an ore block to turn into it's block
  applies-to: Pickaxe
  type: MINING
  group: FABLED
  settings:
    showActionBar: true
  applies:
    - ALL_PICKAXE
  levels:
    '1':
      chance: 3
      cooldown: 5
      effects:
        - PARTICLE:GLOW:30:0.5 @Block
        - PLAY_SOUND:ENTITY_PLAYER_LEVELUP @Self
        - 'SET_BLOCK:GOLD_BLOCK @Block <condition>%block type% contains GOLD_ORE : %allow%</condition>'
        - 'SET_BLOCK:IRON_BLOCK @Block <condition>%block type% contains IRON_ORE : %allow%</condition>'
        - 'SET_BLOCK:COAL_BLOCK @Block <condition>%block type% contains COAL_ORE : %allow%</condition>'
        - 'SET_BLOCK:EMERALD_BLOCK @Block <condition>%block type% contains EMERALD_ORE : %allow%</condition>'
        - 'SET_BLOCK:COPPER_BLOCK @Block <condition>%block type% contains copper_ore : %allow%</condition>'
        - 'SET_BLOCK:REDSTONE_BLOCK @Block <condition>%block type% contains redstone_ore : %allow%</condition>'
        - 'SET_BLOCK:LAPIS_BLOCK @Block <condition>%block type% contains lapis_ore : %allow%</condition>'
        - 'SET_BLOCK:DIAMOND_BLOCK @Block <condition>%block type% contains diamond_ore : %allow%</condition>'
```
