### ISSUE TITLE
ADD_DURABILITY not working with Repeating

### ISSUE THREAD

**Issue by markusew** [GC-spigot/AdvancedEnchantments#420]
The following enchant is not working for me and I believe its an issue with the combination of Repeating and ADD_DURABILITY
```yaml
autorepair:
  display: '%group-color%Auto repair'
  description: "Passively heals you every few seconds."
  applies-to: 'Almost Everything'
  type: 'REPEATING'
  time: 5
  group: 'EPIC'
  applies:
  - ALL_ARMOR
  - ALL_AXE
  - ALL_SWORD
  - ALL_PICKAXE
  - ALL_SPADE
  - ALL_HOE
  - BOW
  - SHEARS
  - FISHING_ROD
  levels:
    1:
      effects:
      - 'ADD_DURABILITY:-1'
```

It's not working for armor or tools as intended. It works for 2 cycles on worn armor whenever you log in (relogging will make it work for 2 cycles again). It's not working whatsoever for tools whether they are held or not.
