### ISSUE TITLE
[Compatibility] IA multiple_break action & EvenMoreFish 

### ISSUE THREAD

**Issue by TheLaoming** [GC-spigot/AdvancedEnchantments#4205]
### Describe the bug

Hey,
I would like you to add compatibility for **IA** (in some way) and [EvenMoreFish](https://github.com/Oheers/EvenMoreFish) plugin.
Right now Itemsadder items using action `multiple_break:` in `block_break:` event, doesn't react to AE's enchants at all
```
events:
      block_break:
        play_sound:
            name: entity.generic.explode
            volume: 0.9
            pitch: 1
        multiple_break:
          keep_ores: false
          drop_all_blocks:
            enabled: true
            need_silk_touch: false
          size: 3
          depth: 2
```
When you create IA item with this event, it wont' work with enchant like this:
```
unbreakable:
  display: '%group-color%Unbreakable'
  description: |-
    {#BD99CA}You can't break it!
  applies-to: All
  type: MINING
  group: RELIC
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
  levels:
    '1':
      effects:
        - REPAIR
```
Seems like mining action is not supported at all here.

Other compatibility you can add, is for popular EvenMoreFish plugin and it's **bait** system. The way EMF adds it's own lore doesn't work with FishTrak. Even this [fix](https://github.com/GC-spigot/AdvancedEnchantments/issues/4159) didn't fix my problem. Once the bait is applied to the rod, it works just fine. The real problem comes when you use all of your baits. 

**When the fishtrak and then bait is applied:**
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/75527300/6f52a972-2f12-4f2f-858c-e4a83f5f796e)
**When the rod is out of baits, EMF (probably) clears the lore here**
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/75527300/53f61c4f-e12e-478d-aec3-bb05da12bfbb)
**And then you caught a fish and AE re-applies the fishtrak, but empty lines are still there.**
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/75527300/2c88c671-1f54-448b-b4a8-7da6819689de)

This can be done endlessly until you run out of baits.
Maybe add a solution by set lore order or clear those empty lines?

Thanks!

### How to reproduce

**IA:**
Create IA item using block break event & multiple_break action. Then apply any mining enchant, for example that one from me above. It won't work.

**EMF:**
Apply fishtrak and then any bait using /emf admin bait <yourBait>. Use all of the baits and then check lore of the rod, there will be empty lines and anytime you do this, another one is added.

### "/ae plinfo" link

https://paste.md-5.net/asapelehes
