### ISSUE TITLE
Add migration ways for unicode enchant key names to latin alphabet

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#4206]
### Describe the bug

i made enchantments names korean.
but AE changes NBT to PDC, all enchantments has broken due to PersistentDataContainer is limited to latin alphabet only.
is there anyways to migrate them? tons of items and tools are all broken. its very critical issues.

### How to reproduce

1. make a enchant name with korean
2. update version of AE switched from NBT to PDC.

### "/ae plinfo" link

https://paste.md-5.net/fuliruyusu

**Comment by Ecilpse** [comment]
If the key value of PDC is latin alpha only,
Can you add "pdc" sections to entente.yml to provide it to read and convert the value of the pdc setion first during migration?
Then, it is possible even if people have written the enchantments name in a language other than latin alphabet.

```
스팀팩:
  pdc: 'test'
  display: '%group-color%스팀팩'
  description: |-
    피격시 낮은 확률로
    이동속도가 증가합니다.
  applies-to: 
  type: DEFENSE;DEFENSE_MOB;DEFENSE_PROJECTILE;DEFENSE_MOB_PROJECTILE
  group: 튜토리얼
  applies:
  - ALL_BOOTS
  levels:
    '1':
      chance: 40
      effects:
      - "POTION:SPEED:0:40"
```
