### ISSUE TITLE
Dupe bug with JetsHoppers plugin

### ISSUE THREAD

**Issue by Traizel** [GC-spigot/AdvancedEnchantments#4282]
### Describe the bug

When using the JetsHoppers plugin with AE, you can easily dupe the hopper and create infinite hoppers when using enchants that change how blocks are dropped/picked up (EX: Telepathy, Auto Smelt, etc)

### How to reproduce

1. Install AE and JetsHoppers plugins onto paper server
2. Enchant a pickaxe with Telepathy, auto smelt, detonate, and/or atomic detonate
3. Place down an custom hopper from the JetsHoppers plugin
4. Mine the hopper (or near the hopper for explosion enchants like detonate)
5. You will see the jetshopper in your inventory, as well as a new second hopper on the ground

### Screenshots / Videos

https://www.youtube.com/watch?v=NCRRLyVuM2E

### "/ae plinfo" link

https://paste.md-5.net/olezafanam

### Server Log

https://pastes.dev/GAaBJE0NOa

**Comment by ArmonicPvP** [comment]
This is probably happening because the hopper goes directly into your inventory instead of dropping as an item. You should probably add this to your Telepathy config in the meantime to (potentially) hotfix the bug.

```
settings:
        blacklist:
          - "COAL_ORE"
```

Add that before the effects line on your config.

**Comment by Traizel** [comment]
> This is probably happening because the hopper goes directly into your inventory instead of dropping as an item. You should probably add this to your Telepathy config in the meantime to (potentially) hotfix the bug.
> 
> ```
> settings:
>         blacklist:
>           - "HOPPER"
> ```
> 
> Add that before the effects line on your config.

I added the code like so:

`telepathy:
  display: '%group-color%Telepathy'
  description: |-
    Automatically places blocks broken
    by tools in your inventory.
  applies-to: Tools
  type: MINING
  group: UNIQUE
  applies:
  - ALL_PICKAXE
  - ALL_SPADE
  - ALL_AXE
  levels:
    '1':
      chance: 40
      settings:
        blacklist:
          - "HOPPER"
      effects:
      - TP_DROPS
    '2':
      chance: 60
      settings:
        blacklist:
          - "HOPPER"
      effects:
      - TP_DROPS
    '3':
      chance: 80
      settings:
        blacklist:
          - "HOPPER"
      effects:
      - TP_DROPS
    '4':
      settings:
        blacklist:
          - "HOPPER"
      effects:
      - TP_DROPS`

The hopper still duplicates when mining it, not sure if im doing my syntax wrong but it isnt ignoring hoppers still

**Comment by ArmonicPvP** [comment]
Can you try with just a regular hopper and see if it's ignored? I would think that would work unless whitelist/blacklist doesn't work on TP_DROPS. I'll test it on my server here in a few minutes

**Comment by Traizel** [comment]
Can confirm the hopper still isn't ignored when mining a vanilla hopper with Telepathy

**Comment by ThomasWega** [comment]
You could try checking with conditions

**Comment by Traizel** [comment]
I modified the telepathy enchant like so:

```
telepathy:
  display: '%group-color%Telepathy'
  description: |-
    Automatically places blocks broken
    by tools in your inventory.
  applies-to: Tools
  type: MINING
  group: UNIQUE
  applies:
  - ALL_PICKAXE
  - ALL_SPADE
  - ALL_AXE
  levels:
    '1':
      chance: 40
      settings:
        blacklist:
          - "HOPPER"
      condition:
      - '%block type% = HOPPER : %stop%'
      effects:
      - TP_DROPS
    '2':
      chance: 60
      settings:
        blacklist:
          - "HOPPER"
      condition:
      - '%block type% = HOPPER : %stop%'
      effects:
      - TP_DROPS
    '3':
      chance: 80
      settings:
        blacklist:
          - "HOPPER"
      condition:
      - '%block type% = HOPPER : %stop%'
      effects:
      - TP_DROPS
    '4':
      settings:
        blacklist:
          - "HOPPER"
      condition:
      - '%block type% = HOPPER : %stop%'
      condition:
      - '%block type% = HOPPER : %stop%'
      effects:
      - TP_DROPS
```

The enchant still activates when mining a hopper. What am I doing wrong here?

Also I'd like to point out that this may be a solution for enchants like telepathy or auto smelt, but for enchants like detonate, you could just mine a different block next to the hopper and dupe it.
