### ISSUE TITLE
Player Head drop isn't working properly

### ISSUE THREAD

**Issue by SamGamerYT** [GC-spigot/AdvancedEnchantments#4310]
### Describe the bug

```
mmoguillotine:
  display: '%group-color%Guillotine'
  description: "A chance to gain your victim''s\n skull on kill"
  applies-to: 'Weapons'
  type: 'KILL_PLAYER;KILL_MOB'
  group: 'EXTRAS'
  applies:
    - ALL_SWORD
    - ALL_AXE
  levels:
    1:
      chance: 1
      cooldown: 2
      effects:
        - 'DROP_HEAD @Victim'
    2:
      chance: 2
      cooldown: 2
      effects:
        - 'DROP_HEAD @Victim'
    3:
      chance: 1
      cooldown: 43200
      effects:
        - 'DROP_HEAD @Victim'
    4:
      chance: 1
      cooldown: 43200
      effects:
        - 'DROP_HEAD @Victim'
    5:
      chance: 1
      cooldown: 43200
      effects:
        - 'DROP_HEAD @Victim'
    6:
      chance: 1
      cooldown: 43200
      effects:
        - 'DROP_HEAD @Victim'
    7:
      chance: 100
      effects:
        - DROP_HEAD
        ```
        
        
I'm using Level 7

### How to reproduce

In an Area with PvP Enabled

### "/ae plinfo" link

https://paste.md-5.net/lakebeyoja
