### ISSUE TITLE
Armorset custom enchant issue

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#4312]
### Describe the bug

Custom enchants don't work on armor sets. I have this:

```# Advanced Sets
# These sets are fully creatable, to create your own simply copy this file, rename it and edit it however you want!
# 
# ** Set Materials:
# * LEATHER (change-able color)
# * IRON
# * GOLD
# * CHAIN
# * DIAMOND
# 
# ** Enchantment effects are supported - view enchantments.yml to see all effects available for sets.
# 
#  ** Set Events
#    Change upon what event should sets trigger
#    - EFFECT_STATIC : Gives permanent potion effect (as long as armor piece is worn)
#    - ATTACK : Set Event run only when attacking another player
#    - DEFENSE : Set Event run only when being attacked
#    - DEFENSE_BOW : Set Event run only when player gets shot by a bow
#    - MINING : Gives effects when block is mined
#    - ATTACK_MOB : Gives effects when player attacks mob
#    - KILL_MOB : Effects given when attacked mob is killed
#    - BOW : Effects given when player is shot by another player
#    - KILL_PLAYER : Effects given when attacker kills a player
#    - DEATH : Runs when player dies due to another player.
#    - RIGHT_CLICK : Runs when player right clicks held item
#    - BOW_MOB : Effects given when mob is shot by player
#    - FIRE : Effects given when player is on fire
#    - EXPLOSION : Effects given when player gets hit by explosion
#    - SWING : Enchant runs when player swings
#    - FALL_DAMAGE : Set Event runs when player takes fall damage
#    - DEFENSE_MOB : Set Event runs when mob attacks a player
#    - SHIFT : Set Event runs when player toggles crouching (shifts)
#    - ITEM_BREAK : Set Event runs when player toggles crouching (shifts)
#    - CATCH_FISH : Set Event runs when player catches a fish
# Set Events & Enchant types are intercompatible together
# 
# ** Creating set effects, this explains the system
name: Santa's Suit
material: NETHERITE
settings:
  equipped:
  - '&a&l(!) &aYou have activated Santa''s Suit! You now have a chance of being revived
    when you die!'
  unequipped:
  - '&c&l(!) &cYou have deactivated Santa''s Suit!'
items:
  helmet:
    name: '&4&lS&f&la&4&ln&f&lt&4&la&f&l''s &4&lH&f&le&4&ll&f&lm&4&le&f&lt'
    lore:
    - ''
    - '&bOfficial Santa Suit'
    - '&bSnowball Points 2021'
    enchants:
    - protection:15
    - projectileprotection:15
    - fireprotection:15
    - blastprotection:15
    - aqua affinity:1
    - mending:1
    - durability:20
    - respiration:10
    - hardened:%1-1%
  chestplate:
    name: '&4&lS&f&la&4&ln&f&lt&4&la&f&l''s &4&lC&f&lh&4&le&f&ls&4&lt&f&lp&4&ll&f&la&4&lt&f&le'
    lore:
    - ''
    - '&bOfficial Santa Suit'
    - '&bSnowball Points 2021'
    enchants:
    - protection:15
    - projectileprotection:15
    - fireprotection:15
    - blastprotection:15
    - mending:1
    - durability:20
    - hardened:%1-1%
  leggings:
    name: '&4&lS&f&la&4&ln&f&lt&4&la&f&l''s &4&lL&f&le&4&lg&f&lg&4&li&f&ln&4&lg&f&ls'
    lore:
    - ''
    - '&bOfficial Santa Suit'
    - '&bSnowball Points 2021'
    enchants:
    - protection:15
    - projectileprotection:15
    - fireprotection:15
    - blastprotection:15
    - mending:1
    - durability:20
    - hardened:%1-1%
  boots:
    name: '&4&lS&f&la&4&ln&f&lt&4&la&f&l''s &4&lB&f&lo&4&lo&f&lt&4&ls'
    lore:
    - ''
    - '&bOfficial Santa Suit'
    - '&bSnowball Points 2021'
    enchants:
    - protection:15
    - projectileprotection:15
    - fireprotection:15
    - blastprotection:15
    - depth_strider:10
    - featherfalling:15
    - mending:1
    - durability:20
    - hardened:%1-1%
events:
  DEATH:
    chance: 10
    effects:
    - REVIVE %victim%
    cooldown: 0
```

And the "hardened" enchant doesn't work at all. I have tried hardened: 1 too. The hardened enchant DOES work as it works on gkits

### How to reproduce

Make my armor set above

### "/ae plinfo" link

https://paste.md-5.net/tomuvajupa

**Comment by ThomasWega** [comment]
Hey! It seems to work just fine? I've tried with this

```yaml
# These sets are fully creatable, to create your own simply copy this file, rename it and edit it however you want!
# 
# ** Set Materials:
# * LEATHER (change-able color)
# * IRON
# * GOLD
# * CHAIN
# * DIAMOND
# 
# ** Enchantment effects are supported - view enchantments.yml to see all effects available for sets.
# 
#  ** Set Events
#    Change upon what event should sets trigger
#    - EFFECT_STATIC : Gives permanent potion effect (as long as armor piece is worn)
#    - ATTACK : Set Event run only when attacking another player
#    - DEFENSE : Set Event run only when being attacked
#    - DEFENSE_BOW : Set Event run only when player gets shot by a bow
#    - MINING : Gives effects when block is mined
#    - ATTACK_MOB : Gives effects when player attacks mob
#    - KILL_MOB : Effects given when attacked mob is killed
#    - BOW : Effects given when player is shot by another player
#    - KILL_PLAYER : Effects given when attacker kills a player
#    - DEATH : Runs when player dies due to another player.
#    - RIGHT_CLICK : Runs when player right clicks held item
#    - BOW_MOB : Effects given when mob is shot by player
#    - FIRE : Effects given when player is on fire
#    - EXPLOSION : Effects given when player gets hit by explosion
#    - SWING : Enchant runs when player swings
#    - FALL_DAMAGE : Set Event runs when player takes fall damage
#    - DEFENSE_MOB : Set Event runs when mob attacks a player
#    - SHIFT : Set Event runs when player toggles crouching (shifts)
#    - ITEM_BREAK : Set Event runs when player toggles crouching (shifts)
#    - CATCH_FISH : Set Event runs when player catches a fish
# Set Events & Enchant types are intercompatible together
# 
# ** Creating set effects, this explains the system
name: "Santa's Suit"
material: NETHERITE
settings:
  equipped:
  - '&a&l(!) &aYou have activated Santa''s Suit! You now have a chance of being revived
    when you die!'
  unequipped:
  - '&c&l(!) &cYou have deactivated Santa''s Suit!'
items:
  helmet:
    name: '&4&lS&f&la&4&ln&f&lt&4&la&f&l''s &4&lH&f&le&4&ll&f&lm&4&le&f&lt'
    lore:
    - ''
    - '&bOfficial Santa Suit'
    - '&bSnowball Points 2021'
    enchants:
    - protection:15
    - projectileprotection:15
    - fireprotection:15
    - blastprotection:15
    - aqua affinity:1
    - mending:1
    - durability:20
    - respiration:10
    - hardened:%3%
  chestplate:
    name: '&4&lS&f&la&4&ln&f&lt&4&la&f&l''s &4&lC&f&lh&4&le&f&ls&4&lt&f&lp&4&ll&f&la&4&lt&f&le'
    lore:
    - ''
    - '&bOfficial Santa Suit'
    - '&bSnowball Points 2021'
    enchants:
    - protection:15
    - projectileprotection:15
    - fireprotection:15
    - blastprotection:15
    - mending:1
    - durability:20
    - hardened:%3%
  leggings:
    name: '&4&lS&f&la&4&ln&f&lt&4&la&f&l''s &4&lL&f&le&4&lg&f&lg&4&li&f&ln&4&lg&f&ls'
    lore:
    - ''
    - '&bOfficial Santa Suit'
    - '&bSnowball Points 2021'
    enchants:
    - protection:15
    - projectileprotection:15
    - fireprotection:15
    - blastprotection:15
    - mending:1
    - durability:20
    - hardened:%3%
  boots:
    name: '&4&lS&f&la&4&ln&f&lt&4&la&f&l''s &4&lB&f&lo&4&lo&f&lt&4&ls'
    lore:
    - ''
    - '&bOfficial Santa Suit'
    - '&bSnowball Points 2021'
    enchants:
    - protection:15
    - projectileprotection:15
    - fireprotection:15
    - blastprotection:15
    - depth_strider:10
    - featherfalling:15
    - mending:1
    - durability:20
    - hardened:%3%
events:
  DEATH:
    chance: 10
    effects:
    - REVIVE %victim%
    cooldown: 0
```

```yaml
hardened:
  display: '%group-color%Hardened'
  description: Chance to recover durability when damaged by players.
  applies-to: Armor
  type: DEFENSE_MOB
  group: LEGENDARY
  applies:
    - ALL_ARMOR
  levels:
    '1':
      chance: 25
      cooldown: 7
      effects:
        - ADD_DURABILITY_CURRENT_ITEM:1 @Victim
    '2':
      chance: 35
      cooldown: 7
      effects:
        - ADD_DURABILITY_CURRENT_ITEM:1 @Victim
    '3':
      chance: 100
      cooldown: 0
      effects:
        - MESSAGE:DURA @Victim
        - ADD_DURABILITY_CURRENT_ITEM:-10 @Victim
```


https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/24ef45e8-3b67-483b-80f7-a3718abd78a1
