### ISSUE TITLE
Grindstone weird interaction with Enchanted Books with only custom enchantments

### ISSUE THREAD

**Issue by ArmonicPvP** [GC-spigot/AdvancedEnchantments#4318]
### Describe the bug

When using enchanted books as the item for custom enchantment books and putting that into a grindstone with only the custom enchantment on it, you will not get any XP, and the resulting item is just a book with the name "Enchanted Book" (which is the name I have set in the config for it)

### How to reproduce

```
enchantment-book:
  # If true, books can be applied to items in anvils.
  anvil-application: true
  # If true, books can be applied to items by dragging and dropping them on the item in an inventory.
  drag-drop-application: true
  item:
    type: ENCHANTED_BOOK
    id: 0
    custom-model-data: 0
    force-glow: false
  # Variables: %enchant%, %enchant-no-color%, %description%, %level-description%, %applies%, %success%, %destroy%, %color%, %max-level%
  name: '&eEnchanted Book'
  lore:
  - '%group-color%%enchant-no-color% %level%
```

### Screenshots / Videos

![2024-05-24_18 56 04](https://github.com/GC-spigot/AdvancedEnchantments/assets/24983808/46aac498-02d4-4d6c-93b3-ae090034a471)

![2024-05-24_18 56 06](https://github.com/GC-spigot/AdvancedEnchantments/assets/24983808/e0f9efc2-d9f4-475c-a7c0-f51b60291e21)

![2024-05-24_18 57 14](https://github.com/GC-spigot/AdvancedEnchantments/assets/24983808/fd60bb7d-34ac-42f2-9cf9-4b438914f9c0)

### "/ae plinfo" link

https://paste.md-5.net/banopofotu
