### ISSUE TITLE
SHIELD_BLOCK trigger doesn't work at all

### ISSUE THREAD

**Issue by TheLaoming** [GC-spigot/AdvancedEnchantments#4321]
### Describe the bug

Unfortunately shield_trigger does not trigger at all, I've tried against mobs and even players.
```
test:
  display: '%group-color%Test'
  description: This enchant doesnt work.
  applies-to: Shields
  type: SHIELD_BLOCK
  group: UNCOMMON
  settings:
    showActionBar: true
  applies:
    - SHIELD
  levels:
    '1':
      chance: 100
      effects:
        - 'CURE_PERMANENT:SLOW @Victim'
        - 'CURE_PERMANENT:WEAKNESS @Victim'
```
I've tried multiple ways how to make it, even with conditions to check held item or is blocking, also with 100% chance to trigger.

### How to reproduce

Make a shiled enchant and try to trigger SHIELD_BLOCK trigger from ur wiki.

### "/ae plinfo" link

https://paste.md-5.net/nediqevaci
