### ISSUE TITLE
disabled-worlds setting for enchants is not working

### ISSUE THREAD

**Issue by xlsalvolx** [GC-spigot/AdvancedEnchantments#4330]
### Describe the bug

As title, the disabled-worlds setting for enchants is not working, at all

Example enchant:

```
soulbound:
  display: '%group-color%Soulbound'
  description: Potresti non perdere l'item alla morte
  applies-to: qualsiasi arma e armatura
  type: DEATH;PASSIVE_DEATH
  group: SOULBOUND
  settings:
    disabled-worlds:
      - 'testworld'
  applies:
  - PLAYER_HEAD
  - DRAGON_HEAD
  - SKELETON_SKULL
  - WITHER_SKELETON_SKULL
  - ZOMBIE_HEAD
  - CREEPER_HEAD
  - ALL_TOOLS
  - ALL_SWORD
  - ALL_AXE
  - ALL_ARMOR
  - BOW
  - CROSSBOW
  - TRIDENT
  - PRISMARINE_CRYSTALS
  - NETHER_STAR
  - BONE
  - SHIELD
  - BLAZE_ROD
  - STICK
  - ALLIUM
  - TOTEM_OF_UNDYING
  - SPYGLASS
  - FIRE_CHARGE
  - GLOBE_BANNER_PATTERN
  - NETHER_STAR
  levels:
    '1':
      chance: 100
      effects:
      - REMOVE_ENCHANT:soulbound:1
      - KEEP_ON_DEATH
    '2':
      chance: 100
      effects:
      - REMOVE_ENCHANT:soulbound:2
      - ADD_ENCHANT:soulbound:1
      - KEEP_ON_DEATH
    '3':
      chance: 100
      effects:
      - REMOVE_ENCHANT:soulbound:3
      - ADD_ENCHANT:soulbound:2
      - KEEP_ON_DEATH
```

Is the formatting right? It's not working for me in any way

### How to reproduce

1. Load the enchant
2. Change the disabled-worlds setting to a world to your liking
3. Kill yourself to activate the enchant
4. It's working (it should not)

### "/ae plinfo" link

https://paste.md-5.net/ayipesogir
