### ISSUE TITLE
REPEATING enchantments no longer work when they have a chance on them

### ISSUE THREAD

**Issue by ArmonicPvP** [GC-spigot/AdvancedEnchantments#4345]
### Describe the bug

REPEATING enchantments on armor no longer work when I have a chance on them. This was fixed in a patch before this and after I updated it started applying while the item was in my inventory and while I was wearing it. Now it does not work at all.

### How to reproduce

Use this. I have waited for over 10 minutes and have not gotten any food.

```
implants:
  display: '%group-color%Implants'
  description: Chance to restore food
  applies-to: Helmets
  type: REPEATING
  group: COMMON
  applies:
    - ALL_HELMET
  levels:
    '1':
      chance: 3
      time: 5
      effects:
        - ADD_FOOD:1
    '2':
      chance: 6
      time: 5
      effects:
        - ADD_FOOD:<random number>1-2</random number>
    '3':
      chance: 9
      time: 5
      effects:
        - ADD_FOOD:<random number>1-3</random number>
```

### "/ae plinfo" link

https://paste.md-5.net/ulaxujujoz
