### ISSUE TITLE
Grindstone no longer works for enchantment books

### ISSUE THREAD

**Issue by ArmonicPvP** [GC-spigot/AdvancedEnchantments#4346]
### Describe the bug

Grindstone no longer works with custom enchant books

### How to reproduce

Use this enchantment and config settings

```
ravenous:
  display: '%group-color%Ravenous'
  description: Chance to regain hunger while fighting
  applies-to: Swords, Axes
  type: ATTACK;ATTACK_MOB
  group: COMMON
  applies:
    - ALL_SWORD
    - ALL_AXE
  levels:
    '1':
      chance: 3
      cooldown: 2
      effects:
        - ADD_FOOD:<random number>1-3</random number> @Attacker
        - PLAY_SOUND:ENTITY_PLAYER_BURP:1:1
    '2':
      chance: 6
      cooldown: 2
      effects:
        - ADD_FOOD:<random number>1-3</random number> @Attacker
        - PLAY_SOUND:ENTITY_PLAYER_BURP:1:1
    '3':
      chance: 9
      cooldown: 2
      effects:
        - ADD_FOOD:<random number>2-4</random number> @Attacker
        - PLAY_SOUND:ENTITY_PLAYER_BURP:1:1
    '4':
      chance: 12
      cooldown: 2
      effects:
        - ADD_FOOD:<random number>2-4</random number> @Attacker
        - PLAY_SOUND:ENTITY_PLAYER_BURP:1:1
```

```
enchantment-book:
  # If true, books can be applied to items in anvils.
  anvil-application: true
  # If true, books can be applied to items by dragging and dropping them on the item in an inventory.
  drag-drop-application: true
  item:
    type: ENCHANTED_BOOK
    id: 0
    custom-model-data: 0
    force-glow: false
  # Variables: %enchant%, %enchant-no-color%, %description%, %level-description%, %applies%, %success%, %destroy%, %color%, %max-level%
  name: ''
  lore:
  - '%group-color%%enchant-no-color% %level%'
```

```
settings:
  # If true, right-click triggers will work on off-hand.
  right-click-triggers-on-off-hand: false
  # If true, grindstones will remove custom enchants from items and return a small amount of XP.
  grindstones-remove-custom-enchants: true
  ```

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/24983808/d2613fff-de3e-4df6-bdf2-a8a927261d19

### "/ae plinfo" link

https://paste.md-5.net/ulaxujujoz
