### ISSUE TITLE
AOE targeter issue with mythicmobs

### ISSUE THREAD

**Issue by xlsalvolx** [GC-spigot/AdvancedEnchantments#4348]
### Describe the bug

Hello, this is a very weird issue causing me a lot of trouble.

This is the enchant you can use to reproduce the issue:

```
psico:
  display: '%group-color%Psico'
  description: You may damage nearby mobs too
  applies-to: swords, axe, tools
  group: ENCHANTVERDE
  type: ATTACK_MOB
  applies:
  - ALL_TOOLS
  - ALL_SWORD
  - ALL_AXE
  - BONE
  - BLAZE_ROD
  - STICK
  - ALLIUM
  - TOTEM_OF_UNDYING
  - SPYGLASS
  - FIRE_CHARGE
  - GLOBE_BANNER_PATTERN
  - NETHER_STAR
  levels:
    '1':
      chance: 20
      cooldown: 2
      effects:
      - PARTICLE:REVERSE_PORTAL:16:0 @Aoe{radius=7,target=mobs}
      - PLAY_SOUND:ENTITY_ENDER_DRAGON_HURT:1.7
```

And here is the mob from mythicmobs i'm using to test:

```
testmob:
  Mobtype: skeleton
  Display: '&f&lTestmob'
  Health: 300
  Equipment:
  - diamond_helmet:4
  - diamond_sword:0
  Skills:
  - damage{a=20} @target ~onAttack
```

Very simple mob, as simple as it can get. 

Now, for some reason beyond me the @AOE targeter is causing the mob to HIT ME, using his damage skill even when the mob is not touching me (the onAttack trigger on the mob means it should damage me ONLY if he touches me).

I have no idea how this is possible since i'm using the AOE targeter to make just particles, but i tested with the BLEED and DO_HARM effects too and it's still causing this issue, so it's just the AOE, no matter what (i tested other targeters and the issue is not happening).

### How to reproduce

1. Install the test mob (in mythicmobs, into the mobs folder) and the custom test enchant
2. Apply the test enchant in a sword
3. spawn a couple of the test mobs, like this: "/mm mobs spawn testmob 10"
4. Hit them until the enchants activates
5. You will take wireless damage

### "/ae plinfo" link

https://paste.md-5.net/dejiwakiqu
