### ISSUE TITLE
headshot condition is broken

### ISSUE THREAD

**Issue by xlsalvolx** [GC-spigot/AdvancedEnchantments#4349]
### Describe the bug

Hello, the headshot condition is not working, at all

```
headshot:
  display: '%group-color%Headshot'
  description: Hit the head to do extra damage
  applies-to: bows
  type: SHOOT;SHOOT_MOB
  group: ENCHANTVERDE
  applies:
  - BOW
  - CROSSBOW
  - TRIDENT
  levels:
    '1':
      chance: 100
      condition:
      - '%is headshot% = true : %allow%'
      effects:
      - DO_HARM:12 @Victim
      - PARTICLE:CRIT_MAGIC:32:1 @Victim
      - PLAY_SOUND:BLOCK_NOTE_BLOCK_BELL:0.7:0.5
```

The enchant will activate regardless of the headshot

### How to reproduce

1. Install the enchant
2. Try it
3. Doesn't work as intended (the enchant will activate no matter what)

### "/ae plinfo" link

https://paste.md-5.net/ujicecipen

**Comment by ThomasWega** [comment]
Hey! I think you've had incorrect spacing. Here is the fixed format

```yaml
headshot:
  display: '%group-color%Headshot'
  description: Hit the head to do extra damage
  applies-to: bows
  type: SHOOT;SHOOT_MOB
  group: ENCHANTVERDE
  applies:
  - BOW
  - CROSSBOW
  - TRIDENT
  levels:
    '1':
      chance: 100
      conditions:
        - '%is headshot% = true : %allow%'
      effects:
        - MESSAGE:%is headshot%
        - DO_HARM:12 @Victim
        - PARTICLE:CRIT_MAGIC:32:1 @Victim
        - PLAY_SOUND:BLOCK_NOTE_BLOCK_BELL:0.7:0.5
```
