### ISSUE TITLE
REPEATING is not working with ADD_DURABILITY_CURRENT_ITEM

### ISSUE THREAD

**Issue by xlsalvolx** [GC-spigot/AdvancedEnchantments#4350]
### Describe the bug

```
rejuvination:
  display: '%group-color%Riparazione'
  description: Repair items by holding them in your hand
  applies-to: anything
  type: 'REPEATING'
  group: ENCHANTVERDE
  applies:
  - ALL_TOOLS
  - ALL_SWORD
  - ALL_AXE
  - BOW
  - CROSSBOW
  levels:
    '1':
      chance: 100
      time: 3
      effects:
      - ADD_DURABILITY_CURRENT_ITEM:3
```

Doens't work for some reason

### How to reproduce

1. Install the enchant
2. Try it
3. Not working

### "/ae plinfo" link

https://paste.md-5.net/oyabobuzed
