### ISSUE TITLE
Chance rate in REPEATING type enchantments is not working as expected

### ISSUE THREAD

**Issue by slyleight** [GC-spigot/AdvancedEnchantments#4359]
### Describe the bug

The **REPEATING** enchantments "chance rate" functionality appears to be broken, as it only functions correctly when set to 100%.

As far as I understand, the chance rate we set in the **REPEATING** enchantments is the **CHANCE THAT IT WILL START WORKING** after we equip the armor. 

For example;
```
immune:
  display: '%group-color%Immune'
  description: Chance to cure Blindness effect every 10 seconds.
  applies-to: Chestplate
  type: REPEATING
  group: HEROIC
  applies:
    - ALL_CHESTPLATE
  levels:
    1:
      chance: 50                      ##Chance rate to toggle the ON/OFF switch when we equip/unequip the armor.
      time: 1                         ##When the toggle is ON, how often does the enchantment try to work.
      cooldown: 10                    ##The cooldown after the enchantment works.
      effects:
        - 'CURE:BLINDNESS'
``` 
Think of it as an **imaginary on/off switch**. This enchantment has a 50% chance that the switch will either switch on or off. This only works when you equip the armor, not after you equip it.

If the switch turns ON when you equip the armour, the enchantment will work with 100% probability every 10 seconds. If the switch remains OFF when you equip the armor, it will never work, no matter how. You have to equip the armor again and hope that the switch will turn ON.

I noticed this problem when I checked with /ae debug enable.

### How to reproduce

1. Set up an enchantment with REPEATING type and a chance rate.
2. Turn on the debug mode to check. (Suggested)
3. Equip the item with the enchanment and see if its going to work. 
If it works, you will see that it works every time within specified cooldown. 
If not, it will never work. You have to unequip and re-equip.

### Screenshots / Videos

https://www.veed.io/view/eaffc710-69be-4fcb-9c38-aafa83ba18cc?panel=share

### "/ae plinfo" link

https://paste.md-5.net/iqazevicuw
