### ISSUE TITLE
REPEATING enchantments do not work after getting hit since the new REPEATING fix.

### ISSUE THREAD

**Issue by slyleight** [GC-spigot/AdvancedEnchantments#4408]
### Describe the bug

I'm using this plugin on a PVP server, and I also added some enchantments that cure speed effects on enemies.

The EFFECT_STATIC effect does not work after being cured, so players had to re-equip the item. I worked around this problem by changing the effect type to REPEATING.

This allowed me to give a SPEED 3 buff every three seconds, so our players wouldn't need to re-equip their boots during intense fights.

However, after the latest REPEATING bug fix, repeating enchantments do not work after getting hit by a player or a mob. (Think of it as any entity that can harm you having a cure effect.) I'd like to point out that the players and mobs hitting me do not have any enchantments that cure this effect.

It used to work before the update, but now it stops working. These enchants stop working after getting into combat. (I checked it in a private server, and it's not because of the PVP plugin.)

Here is the Gears enchantment, which I modified to fit my needs:

```
gears:
  display: '%group-color%Gears'
  description: '{#770ef8}Gain permanent {#FFC300}Speed {#770ef8}effect.'
  applies-to: Boots
  type: REPEATING
  group: LETHAL
  applies:
  - ALL_BOOTS
  levels:
    '1':
      time: 3
      effects:
      - POTION:SPEED:0:100
    '2':
      time: 3
      effects:
      - POTION:SPEED:1:100
    '3':
      time: 3
      effects:
      - POTION:SPEED:2:100
```

### How to reproduce

1. Equip an enchantment that is REPEATING and grants a Potion Effect.
2. Get hit by a player.
3. The effect stops working completely; it does not even attempt to repeat. It needs to be re-equipped for some reason.

### "/ae plinfo" link

https://paste.md-5.net/panutepogi
