### ISSUE TITLE
Missing documentation on WIki for settings and time groups.

### ISSUE THREAD

**Issue by xenxero1** [GC-spigot/AdvancedEnchantments#4417]
### Describe the bug

Hello, I have 2 problems presently, both are stemming from a lack of information in the wiki.

The first is that I am trying to create an enchantment that generates souls passively while held, to be a makeshift mana system. Recent patch notes indicate that type: REPEATING is now supported for held items, but I have been unable to get it to work, and there is no documentation on how you would implement it.

Secondly, I can't find any information on how to make an enchantment "require" another enchantment. I intend for all of my "souls/mana" based enchantments to require the Magic enchantment, so players don't randomly receive an unusable enchantment. I remember seeing documentation for it before, but it's not on the wiki. 

Both of my use-cases are present here;

```
magic:
  display: '%group-color%Magic'
  description: |-
    Generates Souls when held.
  applies-to: Weapons
  type: REPEATING
  group: EPIC
  applies:
    - ALL_SWORD
    - ALL_AXE
  settings:
    require:
    - "soulreaper"
  levels:
    '1':
      time: 2
      conditions:
        - '%souls on item% >= 100 : %stop%'
      effects:
        - ADD_SOULS:1 @Self
        - PARTICLE:SOUL:20:4 @Self`
```

A small addendum: without a soultracker, I'm not sure the souls are being tracked properly. When I have souls added and then apply the tracker, it shows 0 Souls, but increments normally after that.

Is there a way to automatically apply a soultracker in tandem with certain enchantments?

Support staff in the discord said this was the more appropriate place for this.

### How to reproduce
```
magic:
  display: '%group-color%Magic'
  description: |-
    Generates Souls when held.
  applies-to: Weapons
  type: REPEATING
  group: EPIC
  applies:
    - ALL_SWORD
    - ALL_AXE
  settings:
    require:
    - "soulreaper"
  levels:
    '1':
      time: 2
      conditions:
        - '%souls on item% >= 100 : %stop%'
      effects:
        - ADD_SOULS:1 @Self
        - PARTICLE:SOUL:20:4 @Self
```

### "/ae plinfo" link

https://paste.md-5.net/pobanunezi
