### ISSUE TITLE
ITEM_BREAK does not activate

### ISSUE THREAD

**Issue by Leomelonseeds** [GC-spigot/AdvancedEnchantments#4437]
### Describe the bug

It seems like the `ITEM_BREAK` effect doesn't activate when an item breaks.

### How to reproduce

Use this enchantment:
```
vulcan:
  display: '%group-color%Vulcan''s Blessing'
  description: |-
    When a gear item breaks, this enchantment
    will be decreased by one level, and the
    gear will be fully repaired.
  applies-to: Gear
  type: ITEM_BREAK
  group: LEGENDARY
  applies:
  - ALL_SWORD
  - ALL_HOE
  - ALL_AXE
  - ALL_SHOVEL
  - ALL_PICKAXE
  - ALL_ARMOR
  - BOW
  - CROSSBOW
  - TRIDENT
  levels:
    '1':
      effects:
      - ADD_DURABILITY_CURRENT_ITEM:5000
      - REMOVE_ENCHANT:vulcan
    '2':
      effects:
      - ADD_DURABILITY_CURRENT_ITEM:5000
      - REMOVE_ENCHANT:vulcan
      - ADD_ENCHANT:vulcan:1
    '3':
      effects:
      - MESSAGE:HELLO
      - ADD_DURABILITY_CURRENT_ITEM:5000
      - REMOVE_ENCHANT:vulcan
      - ADD_ENCHANT:vulcan:2
```

On a golden shovel. Break the golden shovel while `/ae debug enable` is enabled. No effects for `ITEM_BREAK` seem to be activating. 

### "/ae plinfo" link

https://paste.md-5.net/ejajaciral
