### ISSUE TITLE
REPEATING type was something problems.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#4438]
### Describe the bug

1. Originally, repeat enchantments was activated immediately after wearing it,
but after update 9.9.11, it is activated 100 seconds after wearing it.

2. repeat enchantment was not worked after hit by monster.

### How to reproduce

```
rudghk: #경화
  display: '%group-color%경화'
  description: |-
    일정 주기마다 흡수효과를 제공합니다.
  applies-to: 
  type: REPEATING
  group: RARE
  applies:
  - ALL_CHESTPLATE
  levels:
    '1':
      time: 100
      effects:
      - POTION_OVERRIDE:ABSORPTION:0:600
```

```
rhdqhr: #공복
  display: '%group-color%공복'
  description: |-
    일정 시간마다 확률적으로
    허기가 회복됩니다.
  applies-to: 
  type: REPEATING
  group: RARE
  applies:
  - ALL_HELMET
  - ALL_CHESTPLATE
  levels:
    '1':
      time: 1
      effects:
      - ADD_FOOD:1
```

### Screenshots / Videos

https://github.com/GC-spigot/AdvancedEnchantments/assets/25452835/bc9d2c56-88bd-4235-a954-3433b25fcc2c

### "/ae plinfo" link

https://paste.md-5.net/kumoqutiwo
