### ISSUE TITLE
Per group enchantment book item

### ISSUE THREAD

**Issue by leogianfagna** [GC-spigot/AdvancedEnchantments#4466]
### Describe the bug

Today we have this:
```yml
enchantment-book:
  # If true, books can be applied to items in anvils.
  anvil-application: false
  # If true, books can be applied to items by dragging and dropping them on the item in an inventory.
  drag-drop-application: true
  item:
    type: PAPER
    id: 0
    custom-model-data: 185007
    force-glow: false
```

But would be nice if we add this on GROUPS.YML instead, so we can set a different enchantment book for each group!

### How to reproduce

SUGGESTION

### Screenshots / Videos

SUGGESTION

### "/ae plinfo" link

SUGGESTION

### Server Log

SUGGESTION
