### ISSUE TITLE
The "/apply" command superimposes the trigger of repeat entrenchment (2)

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#4468]
### Describe the bug

#4401 
still not fixed. when i command "/apply [playername]", that player's repeat enchantments trigger superimposes.

### How to reproduce

equip repeat enchant
command "/apply player"
There is a enchantments that fills up one hunger every second, and the speed doubles after entering the "/apply" command.

### Screenshots / Videos

https://github.com/user-attachments/assets/bc2387af-bcfb-408c-8c03-03a1e0310534

### "/ae plinfo" link

https://paste.md-5.net/ipecojapaq

**Comment by Ecilpse** [comment]
when will be checked? i wait 3 weeks ago

**Comment by SirJben** [comment]
What enchantment you equip?

**Comment by Ecilpse** [comment]
> What enchantment you equip?

```
rhdqhr: #공복
  display: '%group-color%공복'
  description: |-
    일정 시간마다 확률적으로
    허기가 회복됩니다.
  applies-to: 
  type: REPEATING
  group: RARE
  applies:
  - ALL_HELMET
  - ALL_CHESTPLATE
  levels:
    '1':
      time: 7
      effects:
      - ADD_FOOD:1
      #- MESSAGE:&f {#cad1e0}발동함
    '2':
      time: 5
      effects:
      - ADD_FOOD:1
    '3':
      time: 3
      effects:
      - ADD_FOOD:1
    '4':
      time: 1
      effects:
      - ADD_FOOD:1
```
