### ISSUE TITLE
SET_BLOCK Effect Not Working Anymore

### ISSUE THREAD

**Issue by slyleight** [GC-spigot/AdvancedEnchantments#4488]
### Describe the bug

**Issue Description:**
I was trying to create a new enchantment that spawns a cobweb under the player when attacked. However, the SET_BLOCK effect is not working. I have tried various target functions such as *Victim, *Attacker, and *Block, but none of them work. Initially, I thought I might have missed something, but upon checking the default Gemify enchantment, I realized it is also not functioning anymore.

**Current Behavior:**
The SET_BLOCK effect is displayed as working in debug mode, but it does not produce the desired effect in the game.

**Expected Behavior:**
The SET_BLOCK effect should place a chosen block (e.g., cobweb) at the target location when triggered.

**Troubleshooting Steps Taken:**

- Verified the configuration syntax.
- Tested with different target functions (*Victim, *Attacker, *Block and *Block{with custom coordinates}).
- Checked the default Gemify enchantment to see if it worked, but it also failed.

```
gemify:
  display: '%group-color%Gemify'
  description: Chance for an ore block to turn into it's block
  applies-to: Pickaxe
  type: MINING
  group: FABLED
  settings:
    showActionBar: true
  applies:
    - ALL_PICKAXE
  levels:
    '1':
      chance: 3
      cooldown: 5
      effects:
        - PARTICLE:GLOW:30:0.5 @Block
        - PLAY_SOUND:ENTITY_PLAYER_LEVELUP @Self
        - 'SET_BLOCK:GOLD_BLOCK @Block <condition>%block type% contains GOLD_ORE : %allow%</condition>'
        - 'SET_BLOCK:IRON_BLOCK @Block <condition>%block type% contains IRON_ORE : %allow%</condition>'
        - 'SET_BLOCK:COAL_BLOCK @Block <condition>%block type% contains COAL_ORE : %allow%</condition>'
        - 'SET_BLOCK:EMERALD_BLOCK @Block <condition>%block type% contains EMERALD_ORE : %allow%</condition>'
        - 'SET_BLOCK:COPPER_BLOCK @Block <condition>%block type% contains copper_ore : %allow%</condition>'
        - 'SET_BLOCK:REDSTONE_BLOCK @Block <condition>%block type% contains redstone_ore : %allow%</condition>'
        - 'SET_BLOCK:LAPIS_BLOCK @Block <condition>%block type% contains lapis_ore : %allow%</condition>'
        - 'SET_BLOCK:DIAMOND_BLOCK @Block <condition>%block type% contains diamond_ore : %allow%</condition>'
```

### How to reproduce

**Steps to Reproduce:**

1. Create any kind of custom enchantment with the SET_BLOCK effect.
2. Apply the enchantment to a relevant item
3. Trigger the enchantment in-game
4. Realize the effect is not working.

### "/ae plinfo" link

https://paste.md-5.net/pepefotuvi
