### ISSUE TITLE
Inconsistent values being passed from GIVE_ITEM using %mob type%

### ISSUE THREAD

**Issue by someoldman** [GC-spigot/AdvancedEnchantments#4498]
### Describe the bug

I've created a custom enchant that gives the player the associated spawn egg.   The enchant works with all mobs successfully except Shulkers.   The %mob type% value is returned as "SHULKER" however in the logs the give command is trying to use "WHITE_SHULKER_spawn_egg".    No other mob type has this issue.

I've tested this with %victim name% and while this variable works for shulkers, it can't be used for any mobs that have multiple words in their naming such as "Tropical Fish".  (I raised the value returns in issue #4479)

example: 
%mob type% = TROPICAL_FISH
%victim name% = tropicalfish

### How to reproduce

```
givespawneggs:
  display: '%group-color%SpawnEggs'
  description: Gotta Catch Em All!
  applies-to: Axes
  type: KILL_MOB
  group: LEGENDARY
  applies:
    - ALL_AXE
  levels:
    '1':
     settings:
     conditions:
# This is the mob ignore list     
      - '%mob type% = ENDER_DRAGON : %stop%'
      - '%mob type% = VILLAGER : %stop%'
      - '%mob type% = WARDEN : %stop%'
      - '%mob type% = WITCH : %stop%'
      - '%mob type% = WITHER : %stop%'
      - '%mob type% = CREEPER : %stop%'
      - '%mob type% = ARMOR_STAND : %stop%' #Added as armour stands return as a %mob type% value
     chance: 100 # success percentage
     cooldown: 2 # cooldown in seconds between successful drops
     effects:
      - SET_VARIABLE:eType:%mob type%_spawn_egg
      - 'MESSAGE:§4<random word>Exeggcute! I choose you!,Congratulations</random word>'
      - GIVE_ITEM:%custom_eType% 
```

### "/ae plinfo" link

https://paste.md-5.net/bejiceburi
