### ISSUE TITLE
DO HARM effect giving error.

### ISSUE THREAD

**Issue by LioneLONeiL** [GC-spigot/AdvancedEnchantments#4500]
### Describe the bug

DO HARM effect giving error.

### How to reproduce

Use DO HARM effect enchant.

### "/ae plinfo" link

https://paste.md-5.net/widenukule

### Server Log

https://mcpaste.io/40c1a2bb9fcc59ff

**Comment by slyleight** [comment]
What is your code?

Did you forget to use Target such as -Victim, Self, Attacker ect. ?

Correct one should be;

` - DO_HARM:19 @Victim (or any other target)`

**Comment by LioneLONeiL** [comment]
Enchantments.yml : 
https://mcpaste.io/d5f4bc0053a93849

Its a default settings tho.

**Comment by ThomasWega** [comment]
What enchantment are you using?

**Comment by LioneLONeiL** [comment]
Its Default settings. 
I dont know which enchant is giving error. But sometimes error spamms. 
Ingame it shows DO HARM effect error.

**Comment by LioneLONeiL** [comment]
> What enchantment are you using?

Found out its Fishing Rod enchants giving error how to fix ??

**Comment by LioneLONeiL** [comment]
Enchant name sharpness hook

```
sharpnesshook:
  display: '%group-color%Sharpness Hook'
  description: Deal damage with the hook.
  applies-to: Fishing Rod
  type: HOOK_ENTITY
  group: ULTIMATE
  applies:
    - FISHING_ROD
  levels:
    '1':
      effects:
        - DO_HARM:2 @Victim
    '2':
      effects:
        - DO_HARM:4 @Victim
    '3':
      effects:
        - DO_HARM:6 @Victim
    '4':
      effects:
        - DO_HARM:9 @Victim
    '5':
      effects:
        - DO_HARM:12 @Victim
    '6':
      effects:
        - DO_HARM:15 @Victim
    '7':
      effects:
        - DO_HARM:19 @Victim
    '8':
      effects:
        - DO_HARM:23 @Victim
    '9':
      effects:
        - DO_HARM:27 @Victim

```
