### ISSUE TITLE
LAVA_WALKER not functioning

### ISSUE THREAD

**Issue by BirminghamBoy** [GC-spigot/AdvancedEnchantments#4504]
### Describe the bug

Enchantment with LAVA_WALKER effect does not function. In other words, player falls into lava with no blocks being placed underneath.

### How to reproduce

Add enchantment with below configuration and try walking over lava with the enchant applied to boots.
```
magmawalker:
  display: '%group-color%Magma Walker'
  description: Grants ability to walk on lava.
  applies-to: Boots
  type: EFFECT_STATIC
  group: COMMON
  applies:
    - ALL_BOOTS
  levels:
    '1':
      effects:
        - LAVA_WALKER
  settings:
    disabled-worlds:
      - 'Plots'
```

### "/ae plinfo" link

https://paste.md-5.net/woluxipaho
