### ISSUE TITLE
AE 9.9.19+ breaks all planter enchants

### ISSUE THREAD

**Issue by TheLaoming** [GC-spigot/AdvancedEnchantments#4517]
### Describe the bug

Since I updated to 9.9.19 or above, enchants like planter, potatoplanter, carrotplanter, replanter etc. are broken and doesn't work.
When I try version 9.9.18 or below, it's fine, so I guess it's related to latest trigger parsing or mining trigger change.

### How to reproduce

Use this or any other similar enchants:
```
potatoplanter:
  display: '%group-color%Potato Planter'
  description: |-
    {#BD99CA}Zasadí brambory v 3x3 oblasti
    {#BD99CA}pomocí shift+pravé kliknutí. Při
    {#BD99CA}III. úrovni nemá žádný cooldown.
  applies-to: Motyky
  type: RIGHT_CLICK
  settings:
    showActionBar: true
  group: UNCOMMON
  applies:
    - ALL_HOE
  levels:
    '1':
      conditions:
        - '%player is sneaking% = true : %allow%'
      cooldown: 3
      effects:
        - PLANT_SEEDS:1:POTATO
```
Even replanter doesn't work.

### "/ae plinfo" link

https://paste.md-5.net/alinosuyoj
