### ISSUE TITLE
Offhand Haste exploit

### ISSUE THREAD

**Issue by soapchan** [GC-spigot/AdvancedEnchantments#4524]
### Describe the bug

Using haste on a pickaxe in offhand applies the effect to the pickaxe in mainhand too.

### How to reproduce

Use a pickaxe with haste in offhand, and mine with other pickaxe.

### "/ae plinfo" link

.

**Comment by ThomasWega** [comment]
Hey! Just check with conditions

```yaml
    '3':
      conditions:
        - "%is offhand% = true : %stop%"
      effects:
        - POTION:FAST_DIGGING:2
```
