### ISSUE TITLE
ADD_ENCHANT can no longer use vanilla enchantments

### ISSUE THREAD

**Issue by Folas1337** [GC-spigot/AdvancedEnchantments#4549]
### Describe the bug

I used to have a custom enchantment which added the Sharpness (DAMAGE_ALL) enchantment onto a trident when it's used but that no longer seems to be working.

Instead I get the following error in the logs: <https://mclo.gs/SpTjzj2>

I am convinced this used to work on older versions but no longer does. I didn't exactly pinpoint however what the exact version was where it broke, I just hope you can fix it without that hint 🙏 

### How to reproduce

Put the following enchantment in your enchantments.yml:
```
folas1:
  display: '%group-color%Poseidon'
  description: |-
    &r[&4PvP&r + &aPvE&r]
    Adds Sharpness of the
    same level to the weapon.
  applies-to: Trident
  type: RIGHT_CLICK;SWING
  group: GRAY
  applies:
    - TRIDENT
  levels:
    '1':
      conditions:
        - '%item type% = TRIDENT : %allow%'
      effects:
        - ADD_ENCHANT:DAMAGE_ALL:1
    '2':
      conditions:
        - '%item type% = TRIDENT : %allow%'
      effects:
        - ADD_ENCHANT:DAMAGE_ALL:2
    '3':
      conditions:
        - '%item type% = TRIDENT : %allow%'
      effects:
        - ADD_ENCHANT:DAMAGE_ALL:3
    '4':
      conditions:
        - '%item type% = TRIDENT : %allow%'
      effects:
        - ADD_ENCHANT:DAMAGE_ALL:4
    '5':
      conditions:
        - '%item type% = TRIDENT : %allow%'
      effects:
        - ADD_ENCHANT:DAMAGE_ALL:5
```

Put said enchantment on a trident by using `/ae enchant folas1 1`. Then left click with the trident and get the error in your console.

### Screenshots / Videos

None required, I hope...

### "/ae plinfo" link

https://paste.md-5.net/iguzezezap

### Server Log

https://mcpaste.io/1348c344c8bb2bdb
