### ISSUE TITLE
DROP_HEAD @Victim Error

### ISSUE THREAD

**Issue by Larsundso** [GC-spigot/AdvancedEnchantments#4558]
### Describe the bug

DROP_HEAD throws an error when the effect is called.
Similar issues have been reported in the past, but they are marked as completed.

### How to reproduce

Apply:
```yml
decapitator:
  display: '%group-color%Decapitator'
  description: 'Chance to drop enemys head on kill.'
  applies-to: 'Swords, Axes'
  group: 'RARE'
  type: 'KILL_MOB'
  applies:
    - 'ALL_SWORD'
    - 'ALL_AXE'
  levels:
    '1':
      chance: 100
      effects:
        - 'DROP_HEAD @Victim'
```
Kill a mob (I tried with Pillagers and Zombies)

### "/ae plinfo" link

https://paste.md-5.net/yokuvucoki

### Server Log

https://mcpaste.io/358f9cbd83195340
