### ISSUE TITLE
Failed to generate AdvancedEnchantments Random Loot: zip file closed

### ISSUE THREAD

**Issue by Larsundso** [GC-spigot/AdvancedEnchantments#4559]
### Describe the bug

Enabling random loot generation and causing the server to render new chunks will result in a spammed console

### How to reproduce

Enable Random loot generation
Cause the server to render new chunks

lootConfiguration.yml:
```yml
# Configuration file for random loot generated in world and villager trades
#  Random locations include:
#   * Any chests generated in wild, e.g. mob spawner rooms, mineshaft etc.
#  Configure Villager Trades. Villagers can trade custom enchantment books and admin items, e.g. white scrolls, orbs, dusts.

# ------ Random Loot Section ------ #
randomLoot:
  # Should random loot be generated in world?
  randomLootEnabled: true

  # Maximum number of custom items to be generated in a random loot container
  maxItemsPerContainer: 2

  # Chance of any item(s) being generated
  chanceOfItems: 5

  # Blacklisted groups, these group books cannot generate in random loot
  blacklisted-groups:
    - 'STAFF'

  # Chances format:
  # ITEM_NAME: Chance (0 to 100)
  chances:
    SLOT_INCREASER: 0
    WHITE_SCROLL: 0
    MYSTERY_DUST: 0
    SECRET_DUST: 0
    MAGIC_DUST: 0
    BLACK_SCROLL: 0
    RANDOMIZER: 0
    RENAME_TAG: 0
    BLOCKTRAK: 0
    FISHTRAK: 0
    STATTRAK: 0
    MOBTRAK: 0
    SOUL_TRACKER: 0
    SOUL_GEM: 0
    TRANSMOG_SCROLL: 0
    HOLY_WHITE_SCROLL: 0
    ARMOR_ORB: 0
    WEAPON_ORB: 0
    TOOL_ORB: 0
    RANDOM_ENCHANT_BOOK: 10

# ------ Villager Trades Section ------ #
villagerTrades:
  # Should villagers be able to trade custom books / items?
  villagerTradesEnabled: true

  # Should villagers trade admin items as well? E.g. Whitescroll, Blackscroll, Magic Dust
  # If set to false, they will only trade custom enchantment books
  tradeAllLoot: true

  # Chance of any item(s) being added as a trade
  chanceOfItems: 3

  # Blacklisted groups, these group books cannot be in villager trades
  blacklisted-groups:
    - 'STAFF'

  # Chances format:
  # ITEM_NAME: Chance (0 to 100)
  chances:
    SLOT_INCREASER: 0
    WHITE_SCROLL: 0
    MYSTERY_DUST: 0
    SECRET_DUST: 0
    MAGIC_DUST: 0
    BLACK_SCROLL: 0
    RANDOMIZER: 0
    RENAME_TAG: 0
    BLOCKTRAK: 0
    FISHTRAK: 0
    STATTRAK: 0
    MOBTRAK: 0
    SOUL_TRACKER: 0
    SOUL_GEM: 0
    TRANSMOG_SCROLL: 0
    HOLY_WHITE_SCROLL: 0
    ARMOR_ORB: 0
    WEAPON_ORB: 0
    TOOL_ORB: 0
    RANDOM_ENCHANT_BOOK: 10

```

### "/ae plinfo" link

https://paste.md-5.net/sivobavegi

### Server Log

https://mcpaste.io/e7d662f17dc9c33b
