### ISSUE TITLE
BREAK_TREE vs Player placed blocks

### ISSUE THREAD

**Issue by Larsundso** [GC-spigot/AdvancedEnchantments#4561]
### Describe the bug

configuring the plugin to respect player placed blocks and using BREAK_TREE does not respect player placed blocks

### How to reproduce

relevant config.yml:
```yml
  # If this is enabled, BREAK_TREE effect will not break logs placed by players
  respect-player-placed-blocks: true
  # Get activated enchants listed in chat upon enchant type trigger
  enchants-debug-mode: false
  ```

enchant axe with BREAK_TREE enchantment
break a tree
break a player placed tree stem

### "/ae plinfo" link

https://paste.md-5.net/urixamofiy
