### ISSUE TITLE
not vanilla xp cost 

### ISSUE THREAD

**Issue by panos3500** [GC-spigot/AdvancedEnchantments#4565]
### Describe the bug

Greetings from greece

I contact support and redirect me to github for a possible bug.
So the bug starts with anvil usage combing armor with mending (in my case) for only 1 level instead of 2 (vanilla behavior)
I tried all the tools and armors and it seems to work properly only in swords and pickaxes.
Also "use-repair-cost: true/false" and the cost always remains at 1 instead of vanilla 2
Removing the AE plugin seems to return back to normal vanilla interaction (mending combine cost to 2 for armor piece)

Anvil Config below
```
# Whether AE should take control of anvils.
# If this is disabled, no custom enchantments will work in anvils.
enabled: true

# If true, AE will handle repair costs the same as vanilla.
# You can read more about it here https://minecraft.fandom.com/wiki/Anvil_mechanics.
use-repair-cost: true

# If true, enchantments that normally can't be put on items together (eg. Smite & Sharpness)
# will be allowed to be combined.
allow-illegal-vanilla-enchant-combinations: false
allow-illegal-custom-enchant-combinations: false


# The maximum levels vanilla enchants can be combined up to.
levels:
  # Armor Enchantments
  Protection: 4
  Fire-Protection: 4
  Feather-Falling: 4
  Blast-Protection: 4
  Projectile-Protection: 4
  Respiration: 3
  Aqua-Affinity: 1
  Thorns: 3
  Depth-Strider: 3
  Frost-Walker: 2
  Curse-of-Binding: 1
  Soul-Speed: 3
  # Sword Enchantments
  Sharpness: 5
  Smite: 5
  Bane-of-Arthropods: 5
  Knockback: 2
  Fire-Aspect: 2
  Looting: 3
  Sweeping-Edge: 3
  # Bow Enchantments
  Power: 5
  Punch: 2
  Flame: 1
  Infinity: 1
  # Crossbow Enchantments
  Multishot: 1
  Piercing: 4
  Quick-Charge: 3
  # Tool Enchantments
  Efficiency: 5
  Silk-Touch: 1
  Fortune: 3
  # Fishing Rod Enchantments
  Luck-of-the-Sea: 3
  Lure: 3
  # Anything Enchantments
  Unbreaking: 3
  Mending: 1
  Curse-of-Vanishing: 1
  # Trident Enchantments
  Channeling: 1
  Impaling: 5
  Loyalty: 3
  Riptide: 3
allow-backwards-enchant-books: false
```

### How to reproduce

On anvil mending on leggings for example and the cost will pop out as 2 for a moment and then will go to 1 

### "/ae plinfo" link

https://paste.md-5.net/nefojuriki

P.S. i just updated to 9.10.5 still the same
