### ISSUE TITLE
A black scroll from a villager

### ISSUE THREAD

**Issue by wundertraume** [GC-spigot/AdvancedEnchantments#4575]
### Describe the bug

A black scroll with villager gives out a book that will have random overlay values on the item.

### How to reproduce

lootConfiguration.yml

```
villagerTrades:
  # Should villagers be able to trade custom books / items?
  villagerTradesEnabled: true

  # Should villagers trade admin items as well? E.g. Whitescroll, Blackscroll, Magic Dust
  # If set to false, they will only trade custom enchantment books
  tradeAllLoot: true

  # Chance of any item(s) being added as a trade
  chanceOfItems: 1

  # Chances format:
  # ITEM_NAME: Chance (0 to 100)
  chances:
    STATTRAK: 20
    BLOCKTRAK: 20
    MOBTRAK: 20
    FISHTRAK: 20
    BLACK_SCROLL: 10
    SLOT_INCREASER: 10
```

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/3190ed42-2013-4641-9acc-0e857220b58b)

### "/ae plinfo" link

not need
