### ISSUE TITLE
Duplication glitch on REPEATING enchants that cost souls 

### ISSUE THREAD

**Issue by ValhallaCraft** [GC-spigot/AdvancedEnchantments#4596]
### Describe the bug

When a repeating type enchant has a soul cost it is easily duplicated when you right click equip from your hotbar and then scroll. 

### How to reproduce

Methods to replicate:
Have a REPEATING type enchant that costs souls like this one:
```
glowing:
  display: '{#FF9A8B}G{#FF928B}l{#FF8A8A}o{#FF828A}w{#FF7A89}i{#FF7289}n{#FF6A88}g'
  description: |-
   Gives permanent night vision. (Cost: 1 Soul/5 Seconds)
  applies-to: Helmet
  type: REPEATING
  group: UNIQUE
  applies:
  - ALL_HELMET
  levels:
    '1':
      time: 5
      souls: 1
      effects:
      - POTION:NIGHT_VISION:0:600
```

Have helmet in hot bar, right click to equip and then scroll. Player must be non-operator so the enchant is actively costing souls. 

### Screenshots / Videos

https://github.com/user-attachments/assets/8fba1404-8b77-4d12-ae3a-d0ff0d3a9cbb

### "/ae plinfo" link

https://paste.md-5.net/usadiyiyez

### Server Log

https://mclo.gs/Q3EeG2R
