### ISSUE TITLE
MMOItem Upgrade and AE Enchants Bug

### ISSUE THREAD

**Issue by Traizel** [GC-spigot/AdvancedEnchantments#4606]
### Describe the bug

When adding an AE enchant to a MMOItem, if you use the "upgrade" feature on MMOItems, the item will lose all AE enchants. I read a report from Phoenix Development

https://gitlab.com/phoenix-dvpmt/mmoitems/-/issues/1284

This suggests the issue is related to how AE places the enchant names on the lore of the item, not the enchants section. How can this be resolved?

### How to reproduce

1. Run a server on Paper 1.19.3
2. Install AE enchants, MMOItems, and MythicLib plugins
3. Create any MMOItem in "Armor"
example:
```
TEST:
  base:
    material: LEATHER_BOOTS
    name: '&eTest Boots'
    upgrade:
      workbench: false
      template: armor-less
      max: 150
```
5. Create an upgrade template
example:
```
armor-less:
    max-health: 1%
    max-durability: 200
```
6. Create an upgrade scroll in "Consumables"
example:
```
SCROLL_1:
  base:
    material: PAPER
    name: '&5&lUpgrade Scroll'
    enchants:
      unbreaking: 1.0
    hide-enchants: true
    lore:
    - §eCan upgrade any weapon
    - §eor piece of gear
    - §aDrag n Drop on gear to use!
    upgrade:
      sucess: 50.0
    tier: ULTRA_RARE
    required-level: 4
    revision-id: 22
```
7. Get the armor and apply any AE enchant to it
8. Upgrade the armor with an upgrade scroll
9. You should notice the AE enchant disappears

### Screenshots / Videos

https://youtu.be/Q81_WNr17Ss

### "/ae plinfo" link

https://paste.md-5.net/faxeratufo

### Server Log

https://pastes.dev/19fFSCPhPn
