### ISSUE TITLE
%force% Conditions in Enchantments

### ISSUE THREAD

**Issue by slyleight** [GC-spigot/AdvancedEnchantments#4622]
### Describe the bug

After the recent Nested Conditions update, I've been creating more complex enchantments. Currently, I'm working on an enchantment that generates a shield for the player, capable of absorbing a maximum of 250 points of damage. The shield should stop functioning after 5 seconds or when it's depleted.

I attempted to achieve this using the `%force%` condition. However, I've encountered an issue: when the `%force%` conditions fail, they return `NONE` as the condition result. When this happens, the effects still activate when they shouldn't. I was under the impression that `%force%` conditions behave like `%allow%`, but they forcefully trigger and ignore cooldown when the conditions are explicitly met.

As a result, my `%force%` conditions are behaving like unconditional effects, activating even when they shouldn’t.

```
soulshield1:
  display: '%group-color%Soul Shield'
  description:  |-
    {#770ef8}When you take damage, you gain a soul shield that blocks {#FFC300}Level x 25 Points{#770ef8} of damage. This shield lasts for 5 seconds.
    {#770ef8}To activate, {#FFC300}Level x 25 ☠ {#770ef8}souls are required.
  applies-to: HEROIC
  type: DEFENSE;DEFENSE_MOB
  group: LETHAL
  settings:
    showActionBar: true
  applies:
  - ALL_CHESTPLATE
  levels:
    '1':
      cooldown: 30
      conditions:
      - '%souls on item% >= 25 : %allow%'
      effects:
      ############################## Will activate once when the Soul Shield is triggered (ONE TIME ONLY) ##############################
      - REMOVE_SOULS:25 @Victim
      - SET_VARIABLE:soulshield_status_%victim name%:ON
      - 'SET_VARIABLE:soulshield_points_%victim name%:25 <condition>(%custom_soulshield_status_%victim name%% = ON) : %allow%</condition>'
      - 'ACTION_BAR:SOUL SHIELD triggered. @Victim <condition>(%custom_soulshield_status_%victim name%% = ON) : %allow% </condition>'
      - 'MESSAGE:%raw damage% @Attacker <condition>(%custom_soulshield_status_%victim name%% = ON) : %allow% </condition>'
      
      
      ############################## If the Soul Shield is active and its points are greater than the damage, it will trigger (FORCE) ##############################
      - 'CANCEL_EVENT <condition>(%raw damage% <= %custom_soulshield_points_%victim name%%) AND (%custom_soulshield_status_%victim name%% = ON) : %force% </condition>'
      - 'SET_VARIABLE:soulshield_points_%victim name%:<math>%custom_soulshield_points_%victim name%% - %raw damage%</math> <condition>(%raw damage% <= %custom_soulshield_points_%victim name%%) AND (%custom_soulshield_status_%victim name%% = ON) : %force% </condition>'
      
      ############################## If the Soul Shield is active and its points are less than the damage, it will trigger (FORCE) ##############################
      - 'NEGATE_DAMAGE:<math>%raw damage% - %custom_soulshield_points_%victim name%%</math> <condition>(%raw damage% > %custom_soulshield_points_%victim name%%) AND (%custom_soulshield_status_%victim name%% = ON) : %force% </condition>'
      - 'SET_VARIABLE:soulshield_points_%victim name%:0 <condition>(%raw damage% > %custom_soulshield_points_%victim name%%) AND (%custom_soulshield_status_%victim name%% = ON) : %force% </condition>'
      
      ############################## Will trigger when the Soul Shield is depleted (FORCE) ##############################
      - 'SET_VARIABLE:soulshield_status_%victim name%:OFF <condition>(%custom_soulshield_points_%victim name%% = 0) : %force% </condition>'
      - 'ACTION_BAR:SOUL SHIELD deactivated. @Attacker <condition>(%custom_soulshield_status_%victim name%% = OFF) : %force% </condition>'

      ######################## Will trigger after the 5-second shield duration expires (ONE TIME ONLY) ########################
      - 'WAIT:100 <condition>(%custom_soulshield_status_%victim name%% = ON) : %allow% </condition>'
      - 'ACTION_BAR:SOUL SHIELD depleted. @Attacker <condition>(%custom_soulshield_status_%victim name%% = ON) : %allow% </condition>'
      - 'SET_VARIABLE:soulshield_points_%victim name%:0 <condition>(%custom_soulshield_status_%victim name%% = ON) : %allow% </condition>'
      - 'SET_VARIABLE:soulshield_status_%victim name%:OFF <condition>(%custom_soulshield_status_%victim name%% = ON) : %allow% </condition>'

```

I still don't understand how can I make enchantments that works for certain amount of seconds. Is there a guide for that or it is not possible?

### How to reproduce

I described it above.

### Screenshots / Videos

%allow% does not activate the effect when NONE is returned.
![image](https://github.com/user-attachments/assets/1d4ab644-16d4-4304-8585-cb13f42dd3ea)

%force% does activate the effect when NONE is returned.
![image](https://github.com/user-attachments/assets/68b5be69-a153-4bef-a2b6-c6540a6d3c3b)

### "/ae plinfo" link

https://paste.md-5.net/afefowotid
