### ISSUE TITLE
AOE Targeting BYPASSING PVP PROTECTIONS in several cases.

### ISSUE THREAD

**Issue by slyleight** [GC-spigot/AdvancedEnchantments#4625]
### Describe the bug

I changed the Deranged enchantment to make it strike real lightning with `- LIGHTNING:true`, but when I uploaded it to our main server, I realized that the `- LIGHTNING:true **@Aoe{radius=5,target=damageable}**` target does not check the damageable property at all.

I noticed this issue after adding damage effects to AOE targets. This caused players in claims or WorldGuard regions with PvP disabled to still take damage.

Deranged
```
'5':
      chance: 15
      cooldown: 5
      effects:
      - LIGHTNING:true @Aoe{radius=5,target=damageable}
```
Shockwave Plus
```
'10':
      chance: 50
      cooldown: 15
      conditions:
      - '%victim health percentage% > 30 : %stop%'
      - '%souls on item% < 50 : %stop%'
      effects:
      - REMOVE_SOULS:50 @Self
      - PULL_AWAY:3.5 @Attacker
      - PULL_AWAY:3.5 @Aoe{r=3,target=damageable}
      - PLAY_SOUND_OUTLOUD:ENTITY_ENDERMAN_TELEPORT:0:16:0
      - PARTICLE:SONIC_BOOM:10:0.5
```
Cleave
```
'7':
      chance: 10
      cooldown: 10
      effects:
      - DO_HARM:<math>%raw damage% * 0.2</math> @Aoe{radius=5,target=damageable}
```

_**PS: Is it possible to add a target that only targets players, similar to mobs but with separate damageable settings?**_

### How to reproduce

- In our mob arena, where PvP is protected, players using the Deranged enchantment on mobs also target other players with AOE damage, despite the PvP protection in the wg region.

- In survival server even players within PvP-protected claims (using the common claim plugin) take damage if they are within the AOE radius.

- Additionally, I found that the Teams plugin conflicts with this. If a player is in a team, they are immune to AOE effects, regardless of whether they are allies or not. However, once removed from the team, they start taking damage, even in protected areas.

### Screenshots / Videos

https://streamable.com/yjy8f5

### "/ae plinfo" link

https://paste.md-5.net/qahefuyeni
