### ISSUE TITLE
Using souls from armor slots.

### ISSUE THREAD

**Issue by ValhallaCraft** [GC-spigot/AdvancedEnchantments#4631]
### Describe the bug

It currently isn't possible to use soul costs in armor slots, id like to request this as a feature as it seems like an oversight.

### How to reproduce

Feature Req

### "/ae plinfo" link

Feature Req

**Comment by ThomasWega** [comment]
Hey! What version have you used? In 9.11.3 I've fixed one issue with souls, so if you could re-test on latest please?

**Comment by ValhallaCraft** [comment]
hey! 9.11.4, when you have an enchant that repeats and costs souls from an armor slot like the one attatched below, the enchant wont trigger until you run /apply. Then it works normally!
```
glowing:
  display: '{#FF9A8B}G{#FF928B}l{#FF8A8A}o{#FF828A}w{#FF7A89}i{#FF7289}n{#FF6A88}g'
  description: |-
   Gives permanent night vision. (Cost: 1 Soul/5 Seconds)
  applies-to: Helmet
  type: REPEATING
  group: UNIQUE
  applies:
  - ALL_HELMET
  levels:
    '1':
      time: 5
      souls: 1
      effects:
      - POTION:NIGHT_VISION:0:600
```

https://github.com/user-attachments/assets/708ef8b3-9cb5-45a9-8bc3-b24436160a22

**Comment by slyleight** [comment]
Here’s a suggestion for you. One of my custom enchants works similarly to what you're aiming for.

```
immune:
  display: '%group-color%Immune'
  description: "Every 10 seconds, it grants immunity to
  all weakness effects with a Level x 2.5% chance.
  Requires 20 ☠ souls to activate."
  applies-to: Chestplate
  type: REPEATING
  settings:
    showActionBar: true
  group: LETHAL
  applies:
  - ALL_CHESTPLATE
  levels:
    '1':
      chance: 2.5
      time: 10
      conditions:
      - '%souls on item% < 20 : %stop%'
      effects:
      - REMOVE_SOULS:20 @Self
      - CURE:BLINDNESS
      - CURE:SLOW
      - CURE:POISON
      - CURE:SLOW_DIGGING
      - CURE:WEAKNESS
      - CURE:HUNGER
      - CURE:CONFUSION
      - CURE:WITHER
      - CURE:GLOWING
      - CURE:LEVITATION
      - CURE:SLOW_FALLING
      - CURE:BAD_OMEN
      - CURE:DARKNESS
```
