### ISSUE TITLE
Make TRENCH and PLANT_SEEDS work together

### ISSUE THREAD

**Issue by wundertraume** [GC-spigot/AdvancedEnchantments#4643]
### Describe the bug

harvest break 3x3 seeds, but the replanter does not plant 3x3 broken blocks, but only the one that was clicked

### How to reproduce

**harvest book:**
```
harvest:
  display: '%group-color%Комбайн'
  description: Возможность собрать урожай на участке 3х3.
  applies-to: Мотыга
  type: MINING
  group: FABLED
  applies:
    - ALL_HOE
  levels:
    '1':
      settings:
        whitelist:
          - CROPS
          - WHEAT
          - CARROT
          - CARROTS
          - POTATO
          - POTATOES
          - BEETROOT
          - BEETROOTS
          - COCOA
          - NETHER_WART
          - NETHER_WARTS
          - TORCHFLOWER
          - PITCHER_CROP
      chance: 13
      effects:
        - BREAK_BLOCK @Trench{r=3,it=true}
```

**replanter book:** 
```
replanter:
  display: '%group-color%Реплантер'
  description: |-
   Восстанавливает посевы, 
   когда вы их собираете.
    &8[&c&l!&8] &7Не работает с Комбайн
  applies-to: Мотыга
  type: MINING
  group: ELITE 
  applies:
    - ALL_HOE
  levels:
    '1':
      conditions:
        - '%is crop% = false : %stop%'
      effects:
        - PLANT_SEEDS:0:%block drop type%
```

plant and break

### Screenshots / Videos

https://youtu.be/6wbXunEIe_0

### "/ae plinfo" link

not need
