### ISSUE TITLE
TP_DROPS given farmland

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#4665]
### Describe the bug

TP_DROPS given farmland. it can't be obtain item through vanilla.
The oddity thing is, it doesn't happen when TP_DROPS chance is 100%, but it happens when it's a probability of 50%, etc.

### How to reproduce

https://github.com/user-attachments/assets/78e327bc-e6be-41a5-bf17-3b9729136b6b

### "/ae plinfo" link

https://paste.md-5.net/izajinizap

**Comment by ThomasWega** [comment]
I've tried using telepathy level 1 and cannot replicate this issue. Are you sure it's not incompatibility with some other plugin?

**Comment by Ecilpse** [comment]
> I've tried using telepathy level 1 and cannot replicate this issue. Are you sure it's not incompatibility with some other plugin?

```
tnghkr: #수확
  display: '%group-color%수확'
  description: |-
    확률적으로 도구로 파괴한
    블록이 인벤토리에
    자동으로 들어갑니다.
    &8작물통에는 발동하지 않습니다.
  applies-to: 
  type: MINING
  group: LEGENDARY
  applies:
  - ALL_PICKAXE
  - ALL_SHOVEL
  - ALL_AXE
  - ALL_HOE
  levels:
    '1':
      conditions:
      - '%block type% = NOTE_BLOCK : %stop%'
      - '%block type% = TRIPWIRE : %stop%'
      chance: 25
      effects:
      - TP_DROPS
    '2':
      conditions:
      - '%block type% = NOTE_BLOCK : %stop%'
      - '%block type% = TRIPWIRE : %stop%'
      chance: 50
      effects:
      - TP_DROPS
    '3':
      conditions:
      - '%block type% = NOTE_BLOCK : %stop%'
      - '%block type% = TRIPWIRE : %stop%'
      chance: 75
      effects:
      - TP_DROPS
    '4':
      conditions:
      - '%block type% = NOTE_BLOCK : %stop%'
      - '%block type% = TRIPWIRE : %stop%'
      effects:
      - TP_DROPS
```
im using this enchantments and there hasn't any region.
