### ISSUE TITLE
player can obtain two effect_static effects through skeleton skull.

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#4677]
### Describe the bug

player can obtain two effect_static effects through skeleton skull.

### How to reproduce

1. equip helemt A with effect_static enchant.
2. equip skeleton head
3. equip helemt B with another effect_static enchant.

### Screenshots / Videos

https://github.com/user-attachments/assets/36ada6c1-4b93-4172-bf13-08271b8a1b10

### "/ae plinfo" link

https://paste.md-5.net/zeyafojiwu

### Confirmation

I confirm

**Comment by ThomasWega** [comment]
You want to update your armor-items in config.yml to

```yaml
armor-items:
  # Items that count as helmet
  helmet:
    - "HEAD"
    - "SKULL_ITEM"
    - "SKULL"
    - "SKELETON_SKULL"
    - "WITHER_SKELETON_SKULL"
    - "PLAYER_HEAD"
    - "CREEPER_HEAD"
    - "DRAGON_HEAD"
    - "ZOMBIE_HEAD"
    - "NETHERITE_HELMET"
    - "DIAMOND_HELMET"
    - "GOLD_HELMET"
    - "GOLDEN_HELMET"
    - "IRON_HELMET"
    - "CHAINMAIL_HELMET"
    - "LEATHER_HELMET"
    - "TURTLE_SHELL"
    - "PUMPKIN"
    - "CARVED_PUMPKIN"
    - "TURTLE_HELMET"
```

No code changes. Default config will be changed next version to this though.
