### ISSUE TITLE
%has potion effect <effect>% is not working properly

### ISSUE THREAD

**Issue by minejango2** [GC-spigot/AdvancedEnchantments#4687]
### Describe the bug

%has potion effect <effect>% is not working properly
1. %has potion effect SLOWNESS% even not detected as conditions - have to write like %has potion effect SLOW% (1.12.2 name)
2. but this didn't detect target's potion effects after all
3. DARKNESS doesn't work too.

```
testenchants:
  display: "%group-color%Testname"
  description: Test
  applies-to: Helmets
  type: DEFENSE;DEFENSE_MOB;DEFENSE_PROJECTILE;DEFENSE_MOB_PROJECTILE
  group: UNIQUE
  applies:
    - ALL_HELMET
  levels:
    "1":
      effects:
        - WAIT:5
        - 'CURE:DARKNESS <condition>%victim has potion effect DARKNESS% = true : %allow%</condition>'
        - 'CURE:SLOWNESS <condition>%victim has potion effect SLOW% = true : %allow%</condition>'
        - 'CURE:SLOWNESS <condition>%victim has potion effect SLOWNESS% = true : %allow%</condition>'
```

(I thought that using all three effects at once could cause another bug, so I tested them line by line too.)

### How to reproduce

If %has potion effect <effect>% exists to detect the target's potion effect, please fix it so that it actually detects the potion effect.
If I am misunderstanding the purpose of this condition, please tell me what this condition is actually used for.

+ https://wiki.advancedplugins.net/abilities/conditions/conditions-variables 
%has potion effect <effect>%'s [PotionEffectTypes](https://helpch.at/docs/1.12.2/index.html?org/bukkit/potion/PotionEffectType.html) link is very old (its for 1.12.2), could you please update this?

### Screenshots / Videos

![ae capture 1](https://github.com/user-attachments/assets/ea9bc4ec-8ccc-4288-99f3-9b5f71ae5daa)
![ae capture 2](https://github.com/user-attachments/assets/bff22b74-2442-4e55-9537-f82b6fb44f7d)
![ae capture 3](https://github.com/user-attachments/assets/beefe6f6-53f6-418f-8226-d976a5c4197f)

### "/ae plinfo" link

https://paste.md-5.net/isutiruleg

### Filled out form correct and using latest version

I confirm
