### ISSUE TITLE
Bleed won't do any damage

### ISSUE THREAD

**Issue by xlsalvolx** [GC-spigot/AdvancedEnchantments#4701]
### Describe the bug

Hello, looks like the bleed effect is not doing any damage to enemies

### How to reproduce

test this enchant

```
psico:
  display: '%group-color%Psico'
  description: AOE bleeding
  applies-to: sword,axes
  group: ENCHANTGREEN
  type: ATTACK_MOB
  applies:
  - ALL_TOOLS
  - ALL_SWORD
  - ALL_AXE
  - BONE
  - BLAZE_ROD
  - STICK
  - ALLIUM
  - TOTEM_OF_UNDYING
  - SPYGLASS
  - FIRE_CHARGE
  - GLOBE_BANNER_PATTERN
  - NETHER_STAR
  levels:
    '1':
      chance: 100
      cooldown: 1
      effects:
      - BLEED:<random number>8-16</random number> @Aoe{radius=7,target=mobs}
      - PARTICLE:REVERSE_PORTAL:16:0 @Aoe{radius=7,target=mobs}
      - PLAY_SOUND:ENTITY_ENDER_DRAGON_HURT:1.7
```

### "/ae plinfo" link

https://paste.md-5.net/dedamubuvu

### Filled out form correct and using latest version

yeah sure
