### ISSUE TITLE
Trigging combat 

### ISSUE THREAD

**Issue by leogianfagna** [GC-spigot/AdvancedEnchantments#4714]
### Describe the bug

Area effects will trigger combat mode (by DeluxeCombat plugin), even if the effect doesn't affect the player.
In other words, the enchantment won't touch the player but still trigger a combat.

### How to reproduce

1. Create an enchantment that use @Aoe
```yml
  type: 'EAT'
  settings:
    showActionBar: true
  applies:
    - 'ALL_ARMOR'
  levels:  
    1:
      cooldown: 1
      chance: 100
      effects:
        - 'POTION:REGENERATION:5:180 @Aoe{radius=16,target=undamageable}'
        - 'POTION:FIRE_RESISTANCE:0:180 @Aoe{radius=16,target=undamageable}'
        - 'POTION:DAMAGE_RESISTANCE:2:180 @Aoe{radius=16,target=undamageable}'
        - 'POTION:ABSORPTION:0:180 @Aoe{radius=16,target=undamageable}'
```
2. Come close that a player YOU CAN HIT.
3. Use the enchantment
4. You see you will join combat, but the player next you won't be affect by the enchantment.

### Screenshots / Videos

https://github.com/user-attachments/assets/7618a9d7-d53d-439b-9124-b067ef1bc4b2

### "/ae plinfo" link

https://paste.md-5.net/jinuguboxi.css

### Filled out form correct and using latest version

I confirm
