### ISSUE TITLE
block limit work bad

### ISSUE THREAD

**Issue by wundertraume** [GC-spigot/AdvancedEnchantments#4727]
### Describe the bug

60:60 works bad, check: https://www.youtube.com/watch?v=yPu61Z3D9DQ

```
    '9':
      chance: 100
      effects:
        - BREAK_TREE:60:60 @Block
```

### How to reproduce

```
timber:
  display: '%group-color%Дровосек'
  description: Шанс сломать все дерево одним ударом.
  applies-to: Топор
  group: FABLED
  type: MINING
  applies:
    - ALL_AXE
  levels:
    '1':
      chance: 13
      effects:
        - BREAK_TREE:60:60 @Block
    '2':
      chance: 26
      effects:
        - BREAK_TREE:60:60 @Block
    '3':
      chance: 36
      effects:
        - BREAK_TREE:60:60 @Block
    '4':
      chance: 49
      effects:
        - BREAK_TREE:60:60 @Block
    '5':
      chance: 59
      effects:
        - BREAK_TREE:60:60 @Block
    '6':
      chance: 72
      effects:
        - BREAK_TREE:60:60 @Block
    '7':
      chance: 85
      effects:
        - BREAK_TREE:60:60 @Block
    '8':
      chance: 90
      effects:
        - BREAK_TREE:60:60 @Block
    '9':
      chance: 100
      effects:
        - BREAK_TREE:60:60 @Block
```

### "/ae plinfo" link

why

### Filled out form correct and using latest version

confirm
