### ISSUE TITLE
force-glow for enchantment-book

### ISSUE THREAD

**Issue by xlsalvolx** [GC-spigot/AdvancedEnchantments#4733]
### Describe the bug

```
enchantment-book:
  # If true, books can be applied to items in anvils.
  anvil-application: false
  # If true, books can be applied to items by dragging and dropping them on the item in an inventory.
  drag-drop-application: true
  item:
    type: KNOWLEDGE_BOOK
    id: 0
    custom-model-data: 0
    force-glow: true
```

### How to reproduce

1. give yourself the item
2. not glowing

### "/ae plinfo" link

https://paste.md-5.net/uyohiyefig

### Filled out form correct and using latest version

Type "I confirm" here
