### ISSUE TITLE
[Feature Request] Preset Chances from Enchanter

### ISSUE THREAD

**Issue by whuppo** [GC-spigot/AdvancedEnchantments#474]
Specifying `success` and/or `destroy` tags within the Enchanter customization when `enchant-group` is active should make the bought book have the specified success/destroy chance.

```
items:
  '2':
    item:
      type: STAINED_GLASS_PANE
      id: 0
      force-glow: false
    enchant-group: SIMPLE
    success: 75
    destroy: 50
    .
    .
```
This will make the bought book have a 75% success chance, and a 50% destroy chance.
```
items:
  '3':
    .
    .
    enchant-group: SIMPLE
    success: 50-75
    .
    .
```
This will make the bought book have a random chance between 50% and 75% and the destroy chance following the normal randomization.
