### ISSUE TITLE
Error with variable %player% in enchanter.yml

### ISSUE THREAD

**Issue by TopicflyOffi** [GC-spigot/AdvancedEnchantments#4759]
### Describe the bug

The variable %player% in the enchanter.yml menu configuration is no longer functional. Specifically, when used in the "console-command:" parameter, it no longer works and returns an error indicating incorrect command usage. I replaced %player% with my username directly, and now there's no issue; the item is successfully given.

One of the items configured with a "console-command:"
```
   35:
      item:
        type: EMPTY_MAP
        id: 0
        custom-model-data: 0
        force-glow: false
      price: exp:9000
      sound: ANVIL_USE
      console-command:
        - 'ae giveitem %player% whitescroll 1'
      name: "&fRune Protectrice"'
```

### How to reproduce

Place the %player% variable in the "console-command:" parameter, attempt to purchase an item, and the command error message will appear.

### Screenshots / Videos

Error due to incorrect command usage in the console : https://i.goopics.net/pps9ts.png

### "/ae plinfo" link

https://paste.md-5.net/ubedijuqiz

### Filled out form correct and using latest version

I confirm
