### ISSUE TITLE
Functioning issue type: REPEATING

### ISSUE THREAD

**Issue by TopicflyOffi** [GC-spigot/AdvancedEnchantments#4760]
### Describe the bug

Currently using the "REPEATING" setting every minute. Occasionally, for an unclear reason, it activates randomly instead of after one minute. I have the impression that it happens when the "HASTE" enchantment is on another item, but why?

• Here is the current configuration of the enchantment:
```
investisseur:
  display: '%group-color%Investisseur'
  description: |-
    &8&l« &7Toutes les minutes, vous gagnez de l'argent
    (Incompatible avec les autres enchantements) &8&l»
  applies-to: Casque
  group: ORDINAIRE
  type: REPEATING
  settings:
    not-applyable-with:
      - arrowdeflect
      - implants
      - clarte
      - auratoxique
      - aquatic
      - glowing
      - evasion
      - voodoo
      - smokebomb
      - intellectuel
  applies:
  - ALL_HELMET
  levels:
    '1':
      chance: 100
      time: 60
      conditions:
        - '%player world% = SuperiorWorld && %player essentials_afk% = no && %player player_online% = yes : %allow%'
      effects:
      - CONSOLE_COMMAND:eco give %player_name% <random number>30-90</random number>
      - "MESSAGE: DEBUG n°1 : %player server_time_dd/MM/yyyy HH:mm:ss%"
```

### How to reproduce

I can't quite figure out how to reproduce the bug, but from what I see, as soon as I hold an item with the "HASTE" enchantment, the issue occurs!

### Screenshots / Videos

• Here are the screenshots of the console and some kind of debug: 
      - In-game message: https://i.goopics.net/f8oh7l.png ; 
      - Console message: https://i.goopics.net/kjeocu.png

### "/ae plinfo" link

https://paste.md-5.net/mefetezoga

### Filled out form correct and using latest version

I confirm
