### ISSUE TITLE
Effect Durability limit 

### ISSUE THREAD

**Issue by DarkLionQc** [GC-spigot/AdvancedEnchantments#4768]
### Describe the bug

I'm using the Nexo plugin (an alternative to Oraxen) with higher durability than the base item (Netherite_pickaxe). The only problem is that when I apply a custom enchant effect to the pickaxe, once the Minecraft item's durability is used up, the effect no longer works.

### How to reproduce

1. create the item (it's a netherite pickaxe with a custom_model_data,new texture and new durability):

```yml
fire_hammer:
  itemname: <gradient:#F06966:#FAD6A6>Hammer LVL 5
  material: NETHERITE_PICKAXE
  lore:
  - <#6f737d>» <#D5D6D8>Break 5x5x7 blocks
  - <#6f737d>» <#D5D6D8>Instantly smelt ores
  Pack:
    generate_model: true
    parent_model: item/handheld
    textures:
    - default/fire_hammer.png
    custom_model_data: 1006
  Components:
    durability: 8000
```
    

2.  create the enchantement :

```yml
hammer:
  display: '%group-color%Savoir des mines'
  description: |
    Break blocks in a radius with a mining tool.
    &5Enchantement créé par DarkLionQc.
  applies-to: Tools
  type: MINING
  group: HEROIC
  applies:
  - ALL_PICKAXE
  levels:
    '1':
      radius: 3
      depth: 1
      chance: 100
      cooldown: 0
      effects:
      - BREAK_BLOCK @Trench{radiuscustom=3x3x1}
    '2':
      radius: 3
      depth: 3
      chance: 100
      cooldown: 0
      effects:
      - BREAK_BLOCK @Trench{radiuscustom=3x3x3}
    '3':
      radius: 3
      depth: 5
      chance: 100
      cooldown: 0
      effects:
      - BREAK_BLOCK @Trench{radiuscustom=3x3x5}
    '4':
      radius: 5
      depth: 5
      chance: 100
      cooldown: 0
      effects:
      - BREAK_BLOCK @Trench{radiuscustom=5x5x5}
    '5':
      radius: 5
      depth: 7
      chance: 100
      cooldown: 0
      effects:
      - BREAK_BLOCK @Trench{radiuscustom=5x5x7}
```
      
      
      
      
   
Finally, just put the enchantement on the pickaxe, start mine until the effect stop working

### Screenshots / Videos

video of the problem :
[https://youtu.be/QwF6l1CVC9s](url)

### "/ae plinfo" link

https://paste.md-5.net/gorujazogo

### Filled out form correct and using latest version

I confirm
