### ISSUE TITLE
NearestPlayer target

### ISSUE THREAD

**Issue by SirJben** [GC-spigot/AdvancedEnchantments#4795]
### Describe the bug

It activates only for oneself, not for other players.

### How to reproduce

```
explosion:
  display: '%group-color%Swords'
  description: Allows you to swing your tools faster.
  applies-to: Swords
  type: RIGHT_CLICK
  group: FABLED
  applies:
    - ALL_SWORD
    - BOW
  levels:
    '1':
      effects:
        - EXPLODE:4:true:true @NearestPlayer{radius=5}
```

### "/ae plinfo" link

https://paste.md-5.net/ozobacaqew

### Filled out form correct and using latest version

I confirm
