### ISSUE TITLE
problems/ incompatibilities with mcmmo, AE telepathy, vanilla fortune

### ISSUE THREAD

**Issue by leon37921** [GC-spigot/AdvancedEnchantments#4797]
### Describe the bug

hey,
players reported, that the Telepathy enchantment is not working as intended in combination with mcmmo or with the vanilla fortune enchantment.

you get significantly fewer drops with Telepathy or with Telepathy + Fortune III
than without Telepathy.

### How to reproduce

Plant carrots and harvest them at full age with a tool enchanted with Telepathy.
Repeat with a tool without Telepathy.

Additional information:
I tested it with a pickaxe. My users with a hoe.
Herbalism-skill is at lvl 1000.
Double checked AE and mcmmo versions. Both on latest version.
enchantment configuration:
```
telepathy:
  display: '%group-color%Telepathy'
  description: |-
    Automatically places blocks broken
    by tools in your inventory.
  applies-to: Tools
  type: MINING
  group: UNIQUE
  applies:
    - ALL_TOOLS
  levels:
    '1':
      chance: 40
      effects:
        - TP_DROPS @Block
    '2':
      chance: 60
      effects:
        - TP_DROPS @Block
    '3':
      chance: 80
      effects:
        - TP_DROPS @Block
    '4':
      effects:
        - TP_DROPS @Block
```

### Screenshots / Videos

![Image](https://github.com/user-attachments/assets/6ff9dde7-86a1-4e6d-bd76-614cbbfe03ae)

### "/ae plinfo" link

https://paste.md-5.net/yijiwobuyo

### Filled out form correct and using latest version

I confirm
