### ISSUE TITLE
Repeating does not work

### ISSUE THREAD

**Issue by noaskers** [GC-spigot/AdvancedEnchantments#4804]
### Describe the bug

[18:59:21 INFO]: Current Purpur Version: 1.21.1-2301-a43711d (MC: 1.21.1)*
* You are 28 version(s) behind
Download the new version at: https://purpurmc.org/downloads

[18:59:31 INFO]: AdvancedEnchantments version 9.15.2

```
implants:
  display: '%group-color%Implants'
  description: Chance to restore food every few seconds.
  applies-to: Armor
  type: REPEATING
  time: 5
  group: EPIC
  applies:
  - ALL_ARMOR
  levels:
    '1':
      chance: 30
      time: 5
      effects:
      - ADD_HEALTH:1
    '2':
      chance: 50
      time: 5
      effects:
      - ADD_FOOD:1
    '3':
      chance: 30
      time: 1
      effects:
      - ADD_FOOD:1
```

### How to reproduce

Add the enchant to an amour piece it does not work
Tried putting chance on 100%
Chancing the time and alot more does not work

### "/ae plinfo" link

https://paste.md-5.net/nilolehibe

### Filled out form correct and using latest version

I confirm
