### ISSUE TITLE
lore-display for "items" not allowing new line.

### ISSUE THREAD

**Issue by TomLewis** [GC-spigot/AdvancedEnchantments#4823]
### Describe the bug

I simple need a new line in my lore for lore-dispaly on all of my "items", ideally each line would be a new line in the lore, to match `lore:` just above it.
Ive tried;
```
  stattrak:
    type: MAGMA_CREAM
    id: 0
    custom-model-data: 0
    force-glow: false
    name: '&eStatTrak Creator'
    lore:
    - '&7Track how many kills you have with a weapon'
    - '&7Drag ontop of another item to apply it'
    messages:
      success:
      - '&7You successfully applied &eStatTrak Creator'
    settings:
      lore-display: 
      - '&f&lSTAT TRACKING'
      - '&c▌ Kills: &f%stats%'
 ```
Which makes it look like its just spitting out an array;
![Image](https://github.com/user-attachments/assets/902cae52-8d4a-4bb6-9f58-3f368d529e7a)

I also tried with new line `\n` but that too does not work

![Image](https://github.com/user-attachments/assets/7b57e85b-d916-41c7-aa45-058943df381e)

### How to reproduce

try and add a new line

### "/ae plinfo" link

Too invasive for a public bug report

### Server Log

n/a

### Filled out form correct and using latest version

I confirm

**Comment by GC-spigot** [comment]
It's not meant to have a list, and will very likely break the counting of kills, because it's designed to find the lore **line** and replace it. But if you want to try it out, do this instead:
`text: "First Line\nSecond Line"`
Use double commas `"` and `\n` symbol.

**Comment by TomLewis** [comment]
Then seperate the lore, with prefix and suffix so you can still find the specific Kill: 2 Counter line.

Theres a few ways this could be done, one simple way would be;
```
    settings:
      lore-prefix-display: 
      - ''
      - '&c▌How to obtain'
      lore-kill-display: '&c▌ Kills: &f%stats%'
      lore-suffix-display: 
      - ''
```

Then you filter easily as you know what text is coming before it.
Alternativly just have a prefix option, Im fine with the Kills beign shown at the bottom, but it needs to be explained to the player and fit in with all the existing lore/patterns of ALL of our custom items on the server, we have a specific template all lore follows on the server, and without being able to simple add a header/cusotmise its going to ruin this.

https://piratemc.com/guides/treasure/
