### ISSUE TITLE
The CONSOLE_COMMAND effect only works in the normal world; it does not function in any other worlds.

### ISSUE THREAD

**Issue by slyleight** [GC-spigot/AdvancedEnchantments#4824]
### Describe the bug

We've encountered an issue over the past few updates when using the CONSOLE_COMMAND effect to create advanced enchantments. Players have reported that the enchantment fails to work in any world other than the normal (vanilla) world—this includes PVP, DUNGEON, NETHER, END and others.

Initially, I suspected the problem might be due to our server settings, so I reviewed all related configurations such as settings, region flags, etc. However, the issue persists even on a vanilla Minecraft server; the CONSOLE_COMMAND effect only functions correctly in the normal world.

It's also worth noting that when I run /ae debug enable, it indicates that the effect is active, yet executing multiple console commands confirms that it simply does not trigger in non-normal worlds.

The following enchantment works as expected, creating a cobweb on the player in the normal world, but it does not produce the same effect in any other world (e.g., Nether, End, etc.).

```
spidersveil:
  display: "%group-color%Spider's Veil"
  description: |- 
  Your attacks against enemy players wrap around their bodies and trap them in a Spider Web. It requires 75 ☠ souls to work.
  applies-to: Swords, Axes, Trident
  type: ATTACK
  group: HEROIC
  settings:
    showActionBar: true
  applies:
  - ALL_SWORD
  - ALL_AXE
  - TRIDENT
  levels:
    '1':
      conditions:
      - '%souls on item% < 75 : %stop%'
      chance: 3.75
      cooldown: 12
      effects:
      - REMOVE_SOULS:75 @Self
      - SET_VARIABLE:%attacker name%_hx:%victim x%
      - SET_VARIABLE:%attacker name%_hy:%victim y%
      - SET_VARIABLE:%attacker name%_hz:%victim z%
      - CONSOLE_COMMAND:setblock %custom_%attacker name%_hx% %custom_%attacker name%_hy% %custom_%attacker name%_hz% minecraft:cobweb keep
      - WAIT:60
      - CONSOLE_COMMAND:execute if block %custom_%attacker name%_hx% %custom_%attacker name%_hy% %custom_%attacker name%_hz% minecraft:cobweb run setblock %custom_%attacker name%_hx% %custom_%attacker name%_hy% %custom_%attacker name%_hz% minecraft:air
```

### How to reproduce

Create a custom enchantment with the CONSOLE_COMMAND effect and test it in various worlds, noting that it only functions in the Vanilla world.

### "/ae plinfo" link

https://paste.md-5.net/gasujixowu

### Filled out form correct and using latest version

I confirm
