### ISSUE TITLE
Phoenix enchantment activates without wearing the armor

### ISSUE THREAD

**Issue by k4han** [GC-spigot/AdvancedEnchantments#4831]
### Describe the bug

I found a bug with the Phoenix enchantment in AdvancedEnchantments. When applying this enchantment to armor, its effect still works even if the player is only carrying the armor in their inventory without wearing it.

### How to reproduce

1. Apply the Phoenix enchantment to a piece of armor.
2. Keep the enchanted armor in your inventory (do not equip it).
3. Die and observe that the enchantment still activates.

### "/ae plinfo" link

https://paste.md-5.net/heqopefeci

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
Should be fixed in the next update. This is the new config 

```yaml
phoenix:
  display: '%group-color%Phoenix'
  description: Chance to revive yourself when killed.
  applies-to: Chestplates
  type: DEATH
  group: FABLED
  applies:
    - ALL_CHESTPLATE
  levels:
    '1':
      chance: 5
      cooldown: 20
      conditions:
        - "%victim has enchantment in CHESTPLATE of phoenix% = true : %allow%"
      effects:
        - REVIVE @Victim
    '2':
      chance: 7
      cooldown: 20
      conditions:
        - "%victim has enchantment in CHESTPLATE of phoenix% = true : %allow%"
      effects:
        - REVIVE @Victim
    '3':
      chance: 9
      cooldown: 20
      conditions:
        - "%victim has enchantment in CHESTPLATE of phoenix% = true : %allow%"
      effects:
        - REVIVE @Victim
```

Thanks for reporting
