### ISSUE TITLE
Bad effect or enchant KEEP_ON_DEATH [LATEST]

### ISSUE THREAD

**Issue by GG-MD** [GC-spigot/AdvancedEnchantments#4872]
### Describe the bug

Hey bro, if I use this to apply the highest level of enchantments to a bow, the item sometimes just disappears instead of dropping or being saved. Using AuxProtect (a CoreProtect alternative), I can't even see the bow before death, even though it was actually there. I was only able to reproduce this issue once; after that, everything worked fine. Please look into the problem.
It’s not about the cooldown, for God’s sake!
It’s about the fact that with this enchant, the item disappears when you die for the first time. It’s not even in the CoreProtect logs, but we can see that it really existed before the death.

Although we are using the highest level, Level 3, with a 100% chance to save such items, the issue still occurs.
We managed to reproduce it once (on new players). I tested it on a bow, and it just disappeared.

The player reported:

From vanilla enchants: Power 5, Mending, Unbreaking 3, Flame.
From donor enchants, I can’t name them all since there were many: Sharpshooter 5, Bow Mastery 5, Deadly Shot 5, Trap 3, Soulbound 3, Poison, and Striker (I don’t remember the level). I probably didn’t name them all, but these are the ones I remember.

We took his bow, which we found in the old logs, and managed to reproduce this bug.
So, this can be reproduced, but only once. After that, everything works correctly as it should. (Possibly due to some delay), I’m not sure.
I can provide you with all my configs so you can reproduce this. I can also give you the item used for testing.
Or I can just record a video instead!

**I’d like to draw attention to the fact that this cannot be reproduced more than once. When I tried to apply this enchantment to another item, it couldn’t be repeated. It’s a complicated situation, I understand.**

Enchant:
```
soulbound:
  display: '%group-color%Привязанный к душе'
  description: Шанс сохранить предмет при смерти
  applies-to: Оружие и инструменты
  type: DEATH;PASSIVE_DEATH
  group: LEGENDARY
  applies:
    - ALL_TOOLS
    - ALL_SWORD
    - BOW
    - CROSSBOW
  levels:
    '1':
      chance: 35
      cooldown: 300
      effects:
        - KEEP_ON_DEATH
    '2':
      chance: 65
      cooldown: 300
      effects:
        - KEEP_ON_DEATH
    '3':
      chance: 100
      cooldown: 300
      effects:
        - KEEP_ON_DEATH
```

### How to reproduce

ㅤ

### "/ae plinfo" link

ㅤ

### Server Log

ㅤ

### Filled out form correct and using latest version

I confirm
