### ISSUE TITLE
Alchemist doesn't accept trades when menu is 9 slots

### ISSUE THREAD

**Issue by Jbacot** [GC-spigot/AdvancedEnchantments#4875]
### Describe the bug

I changed the /alchem menu to be 9 slots. When trying to trade, it says "The alchemist doesn't accept this item". When I change it back to default, those same items work just fine.

### How to reproduce

Copy my config, restart, try to make a trade.

To make sure it works prior, try to make same trade before changing.

```
# General settings related to alchemist inventory system.
general:
  settings:
    # The alchemist should accept books.
    # If false, the alchemist will not accept books.
    combine-books: true
    # The alchemist should accept dust.
    # If false, the alchemist will not accept dusts.
    combine-dust: true
    books:
      # This method adds chances together and splits by 2 (x+y/2)
      add-up-chances: true
      pre-set-chances:
        enabled: false
        success: 50
        destroy: 50
    dusts:
      # This method just adds up chances together
      add-up: true
    price:
      economy: EXP # MONEY, EXP, LEVEL
      # If true the plugin will calculate the price.
      let-plugin-count: true
      # Your custom price here.
      # Only works if let-plugin-count is false.
      custom-price: 250
    other-items-slot:
      first-item-slot: 2
      second-item-slot: 3

# Options for customization of alchemist inventory.
inventory:
  # Set to "none' to disable
  # the sound when opening the inventory.
  open-sound: "BLOCK_CHEST_OPEN"

  # The title of the inventory.
  name: "&bAlchemist"

  # The size of the inventory.
  # Must be a multiple of 9. (9, 18, 27, 36, 45, 54)
  size: 9

  items:
    preview-item:
      type: LIGHT_BLUE_STAINED_GLASS_PANE
      damage: 9
      custom-model-data: 0
      slot: 6
      name: "&f&lItem Preview"
      lore:
        - "&7A preview of item you will receive"
        - "&7from the Alchemist if accepted"
    explanation-item:
      type: BOOK
      damage: 14
      custom-model-data: 0
      slot: 0
      name: "&f&lInformation"
      lore:
        - "&7The Alchemist will Exchange..."
        - ""
        - "&b&l* &f2X Enchantment Books"
        - "&7(of the same type and level)"
        - "&d= &f1X Enchantment Book"
        - "&7(of higher level)"
        - ""
        - "&b&l* &f2X Magic Dust"
        - "&7(of the same rarity)"
        - "&d= &f1X Magic Dust"
        - "&7(of higher chance)"
    confirm-item:
      type: LIME_STAINED_GLASS_PANE
      damage: 5
      custom-model-data: 0
      slot: 8
      name: "&f&lAccept"
      lore:
        - "&7Cost: &b%price% EXP"
        - ""
        - '{#357DBD}(Click to Confirm)'
    filler-item:
      # Enable or disable the filler item.
      enabled: true
      type: BLACK_STAINED_GLASS_PANE
      damage: 15
      name: " "
      lore: [ ]

```

### Screenshots / Videos

![Image](https://github.com/user-attachments/assets/f35e2d57-02eb-4261-9532-85a31d0b11bb)

### "/ae plinfo" link

https://paste.md-5.net/hafisamonu

### Filled out form correct and using latest version

confirm
