### ISSUE TITLE
Bug with WAIT AND RIGHT_CLICK x Decorated Pot

### ISSUE THREAD

**Issue by SirJben** [GC-spigot/AdvancedEnchantments#4880]
### Describe the bug

Bug with WAIT AND RIGHT_CLICK trigger in Decorated Pot

### How to reproduce

```
testing:
  display: '%group-color%dupe'
  description: |-
    dupe
  applies-to: dupe
  type: RIGHT_CLICK
  group: LEGENDARY
  applies:
    - ALL_TOOLS
    - ALL_SWORD
    - BOW
    - CROSSBOW
    - TRIDENT
  levels:
    '1':
      effects:
        - WAIT:1
        - REPAIR
```
Same with 20 ticks, you need to wait for a sec and it will reappear the item after RIGHT_CLICK with decorated pot
```
testing:
  display: '%group-color%dupe'
  description: |-
    dupe
  applies-to: dupe
  type: RIGHT_CLICK
  group: LEGENDARY
  applies:
    - ALL_TOOLS
    - ALL_SWORD
    - BOW
    - CROSSBOW
    - TRIDENT
  levels:
    '1':
      effects:
        - WAIT:20
        - REPAIR```

Right-click the enchanted item in the decorated pot, and it will reappear in the inventory slot. The pot will also retain the same item inside, which duplicates when the pot is destroyed.

### Screenshots / Videos

_No response_

### "/ae plinfo" link

https://paste.md-5.net/eqapidetew

### Server Log

_No response_

### Filled out form correct and using latest version

I confirm
