### ISSUE TITLE
Enchants Will Not Upgrade After 1 Stage In The Anvil

### ISSUE THREAD

**Issue by PunOfUs** [GC-spigot/AdvancedEnchantments#4927]
### Describe the bug

Advanced Enchants: Version 9.18.5

Issue:
I have a few enchants set up like the one below. I'm having issues with enchants upgrading after the first "stage".

Example: I have Hasten on my pickaxe, I work it up to Hasten III and can successfully apply Haste I. However, when I attempt to upgrade Haste I to Haste II in the anvil it fails to upgrade the equipment. Similarly I can go Lifespring V to Lifesteal I but cannot upgrade Lifesteal I to lifesteal II.

More Information:
- If I take a Hasten I book and a Hasten I book I can combine them into Hasten II on the anvil.
- If I take a pickaxe with Hasten I and add a Hasten I to it in the anvil it will upgrade to Hasten II.
- If I take a Haste I book and a Haste I book I can combine them into Haste II on the anvil.
- If I take a pickaxe with Haste I and another pickaxe with Haste I they will not combine into Haste II on the anvil.

### How to reproduce

Use the following enchant setups:

```
hasten:
  display: '%group-color%Hasten'
  description: Chance to gain Haste when breaking blocks.
  applies-to: Tools
  type: MINING
  group: ELITE
  applies:
  - ALL_PICKAXE
  - ALL_SPADE
  - ALL_AXE
  levels:
    '1':
      chance: 15
      cooldown: 3
      effects:
      - POTION:FAST_DIGGING:0:40
    '2':
      chance: 25
      cooldown: 3
      effects:
      - POTION:FAST_DIGGING:1:60
    '3':
      chance: 45
      cooldown: 3
      effects:
      - POTION:FAST_DIGGING:2:80
```
```
haste:
  display: '%group-color%Haste'
  description: |-
    Permanent Haste.
    &4Requires Hasten III.
  applies-to: Tools
  type: HELD
  group: ARTIFACT
  applies:
  - ALL_PICKAXE
  - ALL_SPADE
  - ALL_AXE
  settings:
    required-enchants:
    - hasten:3
    removed-enchants:
    - hasten
    removeable: true
  levels:
    '1':
      effects:
      - POTION:FAST_DIGGING:0
    '2':
      effects:
      - POTION:FAST_DIGGING:1
```

### Screenshots / Videos

https://i.gyazo.com/1f3fae4d01c49095c5f9aad326b12970.png
https://i.gyazo.com/117b3a3757ccca10980215cde0afb73e.png
https://i.gyazo.com/7ee839391e9533628c3712a7b46afb8e.png
https://i.gyazo.com/594269622c1bb6f662435eaa458c4349.png

### "/ae plinfo" link

https://paste.md-5.net/anegeriwis

### Filled out form correct and using latest version

I confirm
