### ISSUE TITLE
Set Bonus + Overload

### ISSUE THREAD

**Issue by groovyloopylou** [GC-spigot/AdvancedEnchantments#4941]
### Describe the bug

We have an armour set (detailed below). If you put overload on the set you loose the extra hearts when you switch worlds.
Have confirmed it only happens with the this set specifically

```
name: '&9&lPaladin Armor'
material: NETHERITE
settings:
  equipped:
  - '&a&l(!) &aYou have activated the Paladin Armor Set Bonus!'
  unequipped:
  - '&c&l(!) &cYou have deactivated the Paladin Armor Set Bonus!'
items:
  helmet:
    name: '&9&lPaladin Helmet'
    # Custom Model Data (for 1.13+ servers with custom item packs)
    # Set custom model data integer
    customModelData: 40
    lore:
    - ''
    - '&9&l&oPaladin Collection'
    - ''
    - '&9&lPaladin SET BONUS'
    - '&aPermanent 50% &7damage reduction.'
    - '&c-10% &7damage dealt.'
    - '&cPermanent slowness.'
    - '&7&o(Requires all four paladin armor items)'
    enchants: # Supports AdvancedEnchantments CE
      - protection:6
      - unbreaking:6
      - blastprotection:5
      - fireprotection:3
      - projectileprotection:4
  chestplate:
    name: '&9&lPaladin Chestplate'
    # Custom Model Data (for 1.13+ servers with custom item packs)
    # Set custom model data integer
    customModelData: 40
    lore:
    - ''
    - '&9&l&oPaladin Collection'
    - ''
    - '&9&lPaladin SET BONUS'
    - '&aPermanent 50% &7damage reduction.'
    - '&c-10% &7damage dealt.'
    - '&cPermanent slowness.'
    - '&7&o(Requires all four paladin armor items)'
    enchants: # Supports AdvancedEnchantments CE
      - protection:6
      - unbreaking:6
      - blastprotection:5
      - fireprotection:3
      - projectileprotection:4
  leggings:
    name: '&9&lPaladin Leggings'
    # Custom Model Data (for 1.13+ servers with custom item packs)
    # Set custom model data integer
    customModelData: 40
    lore:
    - ''
    - '&9&l&oPaladin Collection'
    - ''
    - '&9&lPaladin SET BONUS'
    - '&aPermanent 50% &7damage reduction.'
    - '&c-10% &7damage dealt.'
    - '&cPermanent slowness.'
    - '&7&o(Requires all four paladin armor items)'
    enchants: # Supports AdvancedEnchantments CE
      - protection:6
      - unbreaking:6
      - blastprotection:5
      - fireprotection:3
      - projectileprotection:4
  boots:
    name: '&9&lPaladin Boots'
    # Custom Model Data (for 1.13+ servers with custom item packs)
    # Set custom model data integer
    customModelData: 40
    lore:
    - ''
    - '&9&l&oPaladin Collection'
    - ''
    - '&9&lPaladin SET BONUS'
    - '&aPermanent 50% &7damage reduction.'
    - '&c-10% &7damage dealt.'
    - '&cPermanent slowness.'
    - '&7&o(Requires all four paladin armor items)'
    enchants: # Supports AdvancedEnchantments CE
      - protection:6
      - unbreaking:6
      - blastprotection:5
      - fireprotection:3
      - projectileprotection:4
```

### How to reproduce

overload on the set outlined above
switch worlds and loose hearts

### Screenshots / Videos

https://medal.tv/games/minecraft/clips/kwfTUaBKFUarQA4du?invite=cr-MSxxZHosNDEyNTM1MzMz

### "/ae plinfo" link

Could not create debug link! Error: Server returned HTTP response code: 500 for URL: https://paste.md-5.net/documents -   running 9.19.3 jar

### Server Log

https://mcpaste.io/028e756a587bfec2

### Filled out form correct and using latest version

I confirm
