### ISSUE TITLE
Cannot get mcmmo skills to work.

### ISSUE THREAD

**Issue by Kbryst** [GC-spigot/AdvancedEnchantments#526]
I can't seem to get mcmmo skills to work correctly. 
Paper 1.14.2, AE 5.7, mcmmo official 2.1.82

They just aren't giving any bonus exp, I've tried the following:

```
miningbonus:
  display: '%group-color%Mining Bonus'
  description: "Chance to gain bonus exp for Mining levels (mcMMO)"
  applies-to: 'Pickaxes'
  type: 'MINING'
  group: 'TOOLS'
  applies:
  - ALL_PICKAXE
  levels:
    1:
      chance: 40
      effects:
      - 'ADD_EXP_MCMMO:Mining:<random number>200-555</random number>'
    2:
      chance: 60
      cooldown: 3
      effects:
      - 'ADD_EXP_MCMMO:Mining:<random number>200-555</random number>'
    3:
      effects:
      - 'ADD_EXP_MCMMO:MINING:800'
diggingbonus:
  display: '%group-color%Digging Bonus'
  description: "Chance to gain bonus exp for Excavation levels (mcMMO)"
  applies-to: 'Shovels'
  type: 'MINING'
  group: 'TOOLS'
  applies:
  - ALL_SPADE
  levels:
    1:
      chance: 40
      effects:
      - 'ADD_EXP_MCMMO:EXCAVATION:<random number>200-555</random number>'
    2:
      chance: 60
      cooldown: 3
      effects:
      - 'ADD_EXP_MCMMO:EXCAVATION:<random number>200-555</random number>'
    3:
      effects:
      - 'ADD_EXP_MCMMO:EXCAVATION:800'
```
