### ISSUE TITLE
Custom price for alchemist not working (follow up for #533)

### ISSUE THREAD

**Issue by markusew** [GC-spigot/AdvancedEnchantments#538]
I am not sure what you changed but I am now unable to set a custom price for alchemist without having this bug.

Perhaps I am configuring it wrong but I feel like I've tested all possibilities. I want to be able to set the cost for any book combining to $1000. Right now it's $2000 x lvl of books.

If I change the setting: "let-plugin-count:" to false I am able to change the price but then the bug I reported still exists.

Any help with this issue would be greatly appreciated. Thanks in advance.

Link to old issue: https://github.com/GC-spigot/AdvancedEnchantments/issues/533

**Comment by GC-spigot** [comment]
Try in new version, will keep this open until you confirm this is fixed

**Comment by markusew** [comment]
This is with 5.7.5

**Comment by GC-spigot** [comment]
New version as in update coming today*

**Comment by markusew** [comment]
I still seem to be unable to set a custom cost for alchemist with 5.7.6.

Again, what I am trying to achieve is to set a cost of $1000 for any book combining. But I am also unsure what 2 settings in the config does so perhaps I am configuring it wrong. (let-plugin-decide & let-plugin-count)

What would you say are the correct settings to achieve what I want?
```  
  price:
    # if false, money economy will be used instead
    exp: false
    let-plugin-count: true
    pre-set-pricing:
      enabled: true
      price: 1000
    let-plugin-decide: true
```
