### ISSUE TITLE
Custom price for alchemist has upgrade bug (follow up for #538)

### ISSUE THREAD

**Issue by markusew** [GC-spigot/AdvancedEnchantments#554]
Hey, the bug I reported in https://github.com/GC-spigot/AdvancedEnchantments/issues/533 still exists if you set 'let-plugin-count' to false. 

Tested with 5.8.0 on 1.13.2

Here's my config just in case
```
  price:
    exp: false
    let-plugin-count: false
    pre-set-pricing:
      enabled: true
      price: 1000
    let-plugin-decide: true
```

Link to old issue: https://github.com/GC-spigot/AdvancedEnchantments/issues/538
