### ISSUE TITLE
Applied Enchantments Sound & Particle Issue

### ISSUE THREAD

**Issue by xxJinxedxx** [GC-spigot/AdvancedEnchantments#567]
AE: 5.8.4
Server: PaperSpigot 1.8.8-R0.1

Applying an enchantment book to an item, either successful or not the sound and the particles are the same. It always executes "failed".
No error.
```
applying:
  cosmetics:
    applied:
      particle: 'HAPPY_VILLAGER'
      sound: 'LEVEL_UP'
    failed:
      particle: 'LAVA_POP'
      sound: 'ANVIL_BREAK'
```

**Comment by xxJinxedxx** [comment]
EDIT: From what i tested, i think this is the part that is messing with the "destroy" mechanics kicking-in even tho the 'enchantment is successful'.

```
destroy:
  enabled: true
  destroy-item: true
  message:
  - '&cThe enchantment unsuccessful.'
  sound:
    enabled: true
    play: ANVIL_BREAK
  particles:
    enabled: true
    type: FLAME
chances:
  random: true
  success: 92
  destroy: 8
  destroy-if-fail:
    enabled: true
    message:
    - '&cYour book failed but item wasn''t destroyed!'
```
