### ISSUE TITLE
[Feature] Advanced Tinkerer Calc Formula

### ISSUE THREAD

**Issue by xxJinxedxx** [GC-spigot/AdvancedEnchantments#580]
If by any means possible it would be great feature to have a more advanced calculation formula for selling enchantments and books.
```
prices:
  # Exp or money (exp/money)
  type: exp
  # Define how much of currency should be paid for items per enchantment number (3 enchantments = x3 the amount, and so on)
  amount: 26
```

- Example
```
prices:
  # Exp or money (exp/money)
  type: exp
  # Define how much of currency should be paid for items per enchantment number (3 enchantments = x3 the amount, and so on)
  amount: 26
  use_formula: true/false
   formula: 'e*a+b^l'
```
**Where:**
```
e = enchantments amount on the given item
* = multiply
a = amount exp per enchantment
+ = addition
b = bonus exp points if someone wants to give per enchantment
^ = exponent
l = enchantment level
```
So, we have : "enchantments amount on the item **x** amount EXP per item **+** bonus **^** enchantment level of each enchantment"

Or we can even have -    formula: '(e*a+b^l)*g'
Where "g" is = group of the enchantment _(simple, unique, etc...)_

Or even extended for durability - '((e*a+b^l)*g)/d'
Where "/" is = division and "d" is = durability.
