### ISSUE TITLE
fishing enchant broken

### ISSUE THREAD

**Issue by osnapitzjamie** [GC-spigot/AdvancedEnchantments#659]
this doesnt work even though chance is 100

```
book:
  display: '%group-color%Book Finder'
  description: Chance to find enchantment books when fishing
  applies-to: Fishing Rod
  type: FISHING
  group: DIVINE
  applies:
  - FISHING_ROD
  levels:
    '1':
      chance: 100
      cooldown: 4
      effects:
      - CONSOLE_COMMAND:say test
```
