### ISSUE TITLE
Required-enchants bug?

### ISSUE THREAD

**Issue by TasmanianNoob** [GC-spigot/AdvancedEnchantments#751]
I was trying to make it so that you had to have a certain level of an enchant to put a higher-level one. Basically, you can add an enchantment up to level 3 but then you have to add the books level 4 then level 5 or get the max level of that enchantment, the config below almost works but if you have test_2 on a chest plate you can apply test_4 which I don't think should be happening, explanation probably sucked so a video is at the bottom showing the bug.

```
test_2:
  display: '%group-color%Test'
  description: 'test enchantment'
  applies-to: 'Armor'
  type: 'EFFECT_STATIC'
  group: 'TEST'
  applies:
  - ALL_ARMOR
  levels:
    '1':
      effects:
      - POTION:HEALTH_BOOST:0
test_3:
  display: '%group-color%Test'
  description: 'test enchantment'
  applies-to: 'Armor'
  type: 'EFFECT_STATIC'
  group: 'TEST'
  settings:
    required-enchants:
    - 'test_2'
    removed-enchants:
    - 'test_2'
  applies:
  - ALL_ARMOR
  levels:
    '2':
      effects:
      - POTION:HEALTH_BOOST:1
test_4:
  display: '%group-color%Test'
  description: 'test enchantment'
  applies-to: 'Armor'
  type: 'EFFECT_STATIC'
  group: 'TEST'
  settings:
    required-enchants:
    - 'test_3'
    removed-enchants:
    - 'test_3'
  applies:
  - ALL_ARMOR
  levels:
    '3':
      effects:
      - POTION:HEALTH_BOOST:2
```

video: https://www.youtube.com/watch?v=CaZRH9Lyogs
